---
title: "Bylaws: Definitions, Committees, Committees Charters, Elections, Substitutes, Vacancies"
description: "These Bylaws describe the Definitions, Rules and Functions of Committees, Committee Charters, Rules for Elections, How to Assign Substitutes, How to Address Vacancies"
toc: true
toc-location: right
toc-depth: 3
---

## 1. - Definitions {#definitions .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Faculty, defined as all members of Unit 3 in the current Collective Bargaining Agreement (CBA). Within the broader category of Faculty, the Senate identifies the following distinct subcategories: 

    1. Tenured and Probationary Faculty, defined as those that hold tenured or probationary AY, 10-month, or 12-month full-time faculty appointments as professors, librarians, or student services professionals academic-related (SSP-AR). They may be department chairs or school directors, but cannot hold a full- or part-time MPP (Management Personnel Plan) appointment. 
    2.	Contingent Faculty, defined as those holding temporary appointments to a full- or part-time lecturer, librarian, or SSP-AR position. 
    3.	Coaching Faculty, defined as those who hold full- or part-time coaching appointments and are members of Unit 3 according to the CBA. 
    4.	Faculty on FERP appointments and all other members of Unit 3 who are not included in 1.1.1, 1.1.2, or 1.1.3 above. 

2. Staff. Within the broader category of Staff, the Senate identifies the following distinct subcategories: 
    1.	Non–Management Personnel Plan (non-MPP) staff. These are staff employed by SDSU who do not occupy a position classified under the CSU Management Personnel Plan. 
    2.	Auxiliary organization staff. These are staff affiliated with SDSU but not employed by SDSU. They work for SDSU auxiliary organizations (Associated Students, Aztec Shops, Campanile Foundation, or Research Foundation). Managers as defined in Bylaws 1.3 and student employees are excluded. 

3.  Managers. Within the broader category of Managers, the Senate identifies the following distinct subcategories: 
    1.	SDSU employees that hold a full or part time position as Management Personnel Plan (MPP) employee. This excludes Department Chairs and School Directors. 
    2.	Management and Fair Labor Standard Act exempt supervisory personnel of auxiliary organizations.

4.	Major Academic Unit. Unless otherwise stipulated, “major academic unit” shall refer to each college, the Library, University Services (which includes Counseling and Psychological Services, Test Office, Educational Opportunity Program, and Health Services), and SDSU Imperial Valley.

5.	Ex officio members of the Senate. The following shall be ex officio members of the Senate:
    
    1.	Voting:
        1.	President of the University or designee, Provost and Senior Vice President, Vice President for Research and Innovation, Vice President of Student Affairs and Campus Diversity, Associate Vice President for Faculty Advancement and Student Success, Dean of the College of Graduate Studies, and Dean of Global Campus.
        2.	Seven students chosen by Associated Students:
            1.	Five students from the San Diego Campus, two of the five being graduate students. Associated Students may consult the Dean of Graduate Studies when necessary according to the Bylaws of Associated Students in San Diego.
            2.	Two students from the Imperial Valley Campus chosen by Associated Students at SDSU Imperial Valley. 
        3.	A professor emeritus chosen by procedures specified in the Bylaws of the San Diego State University Retirement Association.
        4.	A member of the Department of Athletics appointed by the Athletics Director.  
        5.	The above ex officio members of the Senate have full voting rights, with the provision that they shall not vote in the elections where the Constitution specifies that only the Elected members may vote (examples: election of Senate Officers or faculty members to the Senate Executive Committee).
    
    2.	Non-Voting: 
        1.	Vice President of Business and Financial Affairs;
        2.	Vice President for University Relations and Development;
        3.	Vice President of Information Technology
        4.	Vice Provost for Academic Affairs; 
        5.	Associate Vice President for Curriculum, Assessment and Accreditation;
        6.	President or designee of each of the collective bargaining agents on campus.
        7.	The Immediate Past Chair of the Senate may serve as a non-voting ex officio member of the Senate for one year, if qualified to serve in the Senate and not otherwise serving.
        8.	Two individuals who are current members of the SDSU Alumni Association shall be chosen by the SDSU Alumni Association. These individuals shall be non-voting ex officio members of the Senate.
    
    3.	Excessive absences (as defined in Bylaws 4.0) of ex-officio senators (voting and nonvoting) shall be addressed by the Chair of the Senate.
:::


## 2. - Committees {#committees .unnumbered}

### 2.1 - Types of Committees {#types-of-committees .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Senate Committee. A Senate Committee has certain functions to perform that are essential or useful for shared governance.

1. Senate Core Committee. Senate Core Committees are deemed to be critical to shared governance within the university. The work of Senate Core committees helps to form, shape, and direct most of the policies, recommendations, and resolutions emanating from the Senate. The chairs of Senate Core Committees shall serve as members of the Senate Executive Committee. MPP-classified members on any Senate Core Committee cannot exceed 25% of the total listed membership of the committee. Senate Core Committee charters are maintained in the bylaws.

1. Senate Executive Committee. The Senate Executive Committee comprises the chairs of all the Senate Core Committees, as well as additional elected and ex officio members. The role of the committee board is to manage and organize the work of the Senate. It can also act on behalf of the Senate if needed. The Senate Executive Committee charter is maintained in the bylaws.

1. Senate-affiliated Campus Committee. A Senate-affiliated Campus committee is a non-Senate committee with Senate representation. It is established by and reports to a non-Senate office. The Senate, and the Senate policies governing election and appointment of members, are involved in appointing a subset of members and its charter is included in the Senate policy file. A Senate-affiliated Campus Committee must have a charter that is approved by the Senate.

1. Senate Ad Hoc Committee. A Senate Ad Hoc Committee is established by a majority vote in the Senate. An Ad Hoc Committee performs a specific task and is dissolved when the task is completed and the final report is given, typically within the same academic year.

:::

### 2.2 - Subcommittees and Working Groups {#subcommittees-and-working-groups .unnumbered}

::: {.policy-numbering .policy-start-1}

1. A subcommittee or working group is established to help with the charge of the committee outside regular committee meetings.

    1. If a Senate Committee establishes a subcommittee, this shall be documented in the committee’s charter, which shall be amended to describe the membership and function of it.

    1. If a Senate Committee forms a working group to complete a specific task, it shall be dissolved when the task is completed.

1. Subcommittees and working groups report to the parent committee, unless otherwise specified in the subcommittee charter.

1. Subcommittees and working groups may include nonmembers, however, at least one of its members shall be a member of the parent committee.

:::

### 2.3 - Committee Charters {#committee-charters .unnumbered}

::: {.policy-numbering .policy-start-1}

1. All Senate and Senate-affiliated Campus Committees must establish and maintain a committee charter.

    1. Senate Committee charters, as well as any subsequent revisions of these charters, shall be approved by the Senate.

    1. Senate-affiliated Campus committees must have a charter, as well as any subsequent revisions, approved by the Senate.

    1. It is the responsibility of the respective Committee Chairs to ensure their committee’s charter in the University Senate Policy File is accurate.

1. A committee charter shall outline the following:

    - Background: provides context as to the original purpose of the committee (e.g., required for accreditation).

    - Membership: a list of all appointed, elected, and ex officio members. All members shall be considered voting members unless otherwise specified. The membership section of the charter may include specific term lengths or limits on consecutive terms, if applicable.

    - Senate Committees shall have a minimum of at least three (3) members.

    - Senate Committees shall have at least two (2) appointed senators.

    - Quorum: define how quorum will work for the committee.

    - Subcommittees (if applicable): a charter, including membership rosters and a function for the subcommittee.

1. Committee charters shall be maintained in the University Senate Policy File.

    1. Charters for Senate Core Committees, and the Senate Executive Committee, shall be maintained in the Bylaws of the University Senate Policy File.

    1. Charters for regular Senate Committees shall be maintained in the “UNIVERSITY POLICIES: Committees – Regular Senate Committees and Councils” section of the University Senate Policy File.

    1. Charters for Senate-affiliated Campus Committees shall be maintained in the “UNIVERSITY POLICIES: Committees – Campus Committees with Senate-Appointed Members” section of the University Senate Policy File.

:::

### 2.4  Appointments {#appointments .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Unless otherwise stipulated, authorities for nomination to Senate and Senate Ad-Hoc Committees, as well as Senate-appointed members of Senate-affiliated Campus Committees, shall be as follows: (a) faculty by the Senate Committee on Committees and Elections, (b) administrators by the university administration, (c) staff by the Staff Affairs Committee, and (d) students by the Associated Students, who shall verify that nominated students are in good academic standing.

1. The Senate shall approve all nominees

    1. The Senate Committee on Committees and Elections shall see that committees reflect overall an unbiased and reasonable representation of the faculty.

    1. If the Committee on Committees and Elections is unable to fill verified vacancies for a committee, the Senate Chair shall have the authority to organize and present nominations for the committee and present them as an action item to the Senate. The Senate Chair shall make reasonable attempts to consult with the nominating authority.

1. All elected senators listed in Constitution 4.0 shall serve on a Senate or Senate appointed university committee.

1. In filling vacancies, the Committee on Committees and Elections shall observe the following rules:

    1. Senator committee appointments shall take priority over appointments of non-Senators.

    1. Committee members are not required to be senators.

    1. Faculty in the Faculty Early Retirement Program (FERP) may only occupy designated "faculty" seats during active employment.

1. No member can occupy two seats on the same committee at the same time, including substitutes.

:::

### 2.5 - Times of Nomination and Appointment {#times-of-nomination-and-appointment .unnumbered}

::: {.policy-numbering .policy-start-1}

1. The Committee on Committees and Elections shall be constituted for the upcoming academic year at the final regularly scheduled Senate meeting of the previous academic year. The committee shall have presented a full slate of nominees to Senate and Senate-appointed committees by the last Senate meeting of each academic year.

    1. All terms of office begin June 1, or at the time of appointment, and conclude May 31 in the final year of the term.

:::

### 2.6 - Referrals {#referrals .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Items shall be referred to committees by the Senate Chair, in consultation with the other Senate officers, by the Executive Committee, or by the Senate. An item referred to a committee by the Executive Committee shall be referred to another committee only through the Executive Committee.

1. Items shall be referred to existing committees whenever possible.

1. The Senate Chair’s additional communications to committees regarding referred items shall be reported at the next Executive Committee meeting.

1. A committee may use subcommittees or may invite non-voting members to participate in its work.

:::

### 2.7  Records and Reports {#records-and-reports .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Each committee chair shall transmit records and pertinent information to the incoming chair.

1. Each Senate and Senate-appointed committees shall submit a summary report of its activities annually by May 1.

:::

### 2.8 - Committee Operation {#committee-operation .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Rules: Senate rules shall apply to the operation of Senate or Senate appointed university committees. Exceptions to these rules may be noted in sec. 25 of Robert’s Rules of Order Newly Revised. Specific stipulations for a given committee regarding authority, tenure, duration, scope, and objectives shall be available in the Senate office.

1. Committee Chairs

    1. Election: Unless otherwise specified, committees shall elect a chair annually by April 1 for the upcoming academic year. The current chair will oversee the election. The voting members of the committee shall elect the chair. The Chair of the Committee on Committees and Elections and the Secretary of the Senate shall be notified and included in the committee's annual report, or when any change in committee leadership occurs.

    1. An ex-officio member shall not be named chair unless otherwise specified by the committee’s charter.

    1. If no member of the committee is willing to serve as chair, the Chair of the Committee on Committees and Elections or the Chair of the Senate may appoint a new chair. This appointment may result in a member being replaced by a chair from outside the committee.

    1. A chair can be vacated by a majority vote of the entire voting membership of the committee.

    1. When the chair is vacated before the expiration of a term, the remaining committee members elect a new chair.

1. Meetings and Quorum: Meetings shall be called by the chair, who shall preside over the meeting. Should the chair fail or decline to call meetings with sufficient frequency to accomplish committee objectives, two members may call a meeting, provided that all members including the chair are given at least three working days' notice. A majority of the members shall constitute a quorum of a committee.

1. Hearings and Deliberations: A committee should, where time permits, hear all testimony relevant to its assignment. All meetings shall be open to the university community unless called into executive session by the chair for purposes in concert with current statutory requirements for open meetings. The chair’s decision to call an executive session shall be subject to challenge and may be overruled by a majority of the committee members present.

1. Record of Proceedings: The chair of the committee shall keep records of all actions of the committee or shall ensure that they be kept by a committee secretary. The agenda for each committee meeting should be made available in the Senate office at least three working days in advance of the meeting. Persons wishing to be heard on an item should notify the chair of the committee.

1. Reporting: All Senate and Senate-appointed committees shall report to the Senate. Committees that do not report directly to the Senate may be invited to the Senate to discuss or clarify their activities. The type of report will depend on the status of the committee or body and the nature of its task.

    1. If the report contains information only, no action by the Senate is required, but may be moved to the floor for action by a majority vote.

    1. If the report contains statements of policy or opinion, these should be stated at the end of the report, and the proper motion is to accept the report. If accepted, the policies or opinions shall become those of the Senate.

    1. If the report contains resolutions or recommendations wherein the Senate has power to act, these should be stated at the end of the report, and the proper motion is to adopt the report. If adopted, the resolutions or recommendations shall become policy pending approval or lack of denial by the President of the university.

1. Dissolution: Senate committees shall be dissolved by amending the Bylaws. Senate-approved university committees shall be dissolved by Senate action. Ad hoc or pro tempore committees shall be dissolved when they rise and report or at the end of the academic year in which they were appointed, whichever comes first, unless specifically extended by action of the Senate Chair, in consultation with the other Senate officers.

1. Terms of Service on Senate and Senate-Appointed University Committees

    1. Unless otherwise specified, committee members shall serve three-year terms. A committee member may be reappointed. During a committee’s initial three years, or as needed to ensure term staggering that is healthy for the continuity of the committee, the Committee on Committees and Elections shall specify members with one-, two-, and three-year seats.

    1. Removal: The Committee on Committees and Elections may recommend the removal of a committee member. Accordingly, the committee member shall be told of the reasons for the proposed removal and shall be given at least two weeks in which to respond. If the Committee on Committees and Elections then determines that removal of the member is in the best interests of the affected committee and of the Senate, it shall recommend to the Senate the name of a replacement member. Appointment of the new nominee by the Senate shall constitute removal of the previous member.

    1. Leave: As soon as a committee member is certain of being granted leave from duties at the university, that member shall in writing, so inform the chair of that committee, who in turn shall immediately inform the Secretary of the Senate and the Chair of the Committee on Committees and Elections. If the leave is one semester, the Committee on Committees and Elections, in consultation with the committee chair, shall recommend to the Senate a temporary replacement. If the leave is longer than one semester, the Committee on Committees and Elections shall recommend to the Senate a permanent replacement selected according to normal criteria and procedure.

:::

## 3. - Senate Core Committees: Charters {#senate-executive-committee-and-senate-core-committees-charters .unnumbered}

### 3.1 - Senate Executive Committee {#senate-executive-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (24): The Senate Executive Committee shall consist of 21 ex officio members and three elected members.

    1. Ex officio (voting): Chair of the Senate (who shall be the Chair of the Senate Executive Committee); Senate Vice Chair; Secretary of the Senate (who shall be the Secretary of the Executive Committee); Treasurer of the Senate; the Chairs of all Senate Core Committees: (a) Academic Policy and Planning, (b) University Resources and Planning, (c) Faculty Affairs, (d) Committees and Elections, (e) Constitution and Bylaws, (f) Undergraduate Curriculum, (g) Diversity, Equity, and Inclusion, (h) Undergraduate Council, (i) Graduate Council, (j) Lecturer Affairs, (k) Staff Affairs, and (l) Sustainability; an ASCSU Senator chosen from and by the CSU Academic Senators; Provost and Senior Vice President; and the President of the Associated Students.

    1. Ex officio (non-voting): President of the university’s chapter of the faculty unit’s collective bargaining agreement; the Immediate Past Chair of the Senate.

    1. Elected (voting): Three faculty senators elected from and by the elected members of the Senate, with no more than one from a college or equivalent academic unit.

    1. The Senate Parliamentarian, the Senate Analyst and Instructional Technology Services staff support the function of the committee, and as such may attend regular and confidential meetings; however they are not active members of the committee. They may not vote or make motions, and may only address the body by invitation of the Senate Chair.

1. Functions

    1. The Senate Executive Committee may consider all matters within the purview of the Senate.

    1. The Senate Executive Committee may formulate recommendations and opinions on Senate matters and shall report them to the Senate or refer them to the appropriate committees.

    1. The Senate Executive Committee shall be empowered to act for a committee in lieu of referral; such action shall be reported at the next regular meeting of the Senate.

    1. The Senate Executive Committee shall act for the Senate on all matters that call for immediate action or attention. Such action shall require an absolute two-thirds majority vote of the entire membership of the Executive Committee and shall be reported to the Senate as a specific agenda item at its next meeting.

1. Meetings

    1. The Senate Executive Committee shall meet at least one week preceding each regular meeting of the Senate. The Committee shall meet at other times as necessary at the call of the Chair of the Senate or at the request of the President of the university.

    1. The Senate Executive Committee may meet with the President of the university, at the initiative of the Committee or the President, to consider problems or issues of the university.

1. Senate Agendas

    1. At the second fall meeting of the Senate, the Senate Executive Committee shall present an annual agenda for the Senate. This agenda shall address major concerns and outline problems for Senate attention during the academic year.

    1. The Senate Executive Committee shall provide the Secretary with the regular agenda to be distributed to the Senate and instruct the Secretary to request the presence of such personnel as may be needed to facilitate the business of the Senate.

    1. Challenge and Censure. A senator may challenge an action taken by the Senate Executive Committee on behalf of the Senate. The matter shall be immediately submitted to a vote. A simple majority vote of the Senate shall uphold the action of the Senate Executive Committee.

    1. The Senate Executive Committee shall be censured for its actions by a two-thirds majority vote of the Senate present and voting.
:::

### 3.2 - Committee on Academic Policy and Planning {#committee-on-academic-policy-and-planning .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (18)

    1. Ex officio: the Provost and Senior Vice President or designee, the Associate Vice President for Faculty Advancement and Student Success, the Senate Chair (or designee), and the Dean of Graduate Studies (or designee).

    1. Appointed: eleven faculty members, one from each academic college, the Library, and SDSU Imperial Valley, at least two of whom shall be elected senators, and two open faculty seats, one of whom shall be a contingent faculty member; one staff member; and two students.

1. Functions: The Committee shall consider and make recommendations to the Senate and, within policy guidelines established by the Senate, to appropriate administrative officers concerning the following: (a) issues of academic philosophy, standards, and conduct; appropriateness of present and proposed programs, degrees, majors, options, and concentrations; (b) faculty-student relations; (c) the governance of the university; and (d) other matters of academic policy. All such recommendations made to administrative officers without prior Senate approval shall be submitted to the next meeting of the Senate for its consideration.

:::

### 3.3 - Committee on University Resources and Planning {#committee-on-university-resources-and-planning .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (17)

    1. Ex officio (5) : Vice President for Academic Affairs, or designee; Vice President for Business and Financial Affairs, or designee; Vice President for Student Affairs and Campus Diversity, or designee; Vice President for Research and Innovation, or designee; and the University Senate Treasurer.

    1. Appointed (12): nine faculty members, one from each college, the Library, and SDSU Imperial Valley, nominated by the Committee on Committees and Elections and appointed by the Senate, at least two of whom shall be elected senators; one staff member selected by the Staff Affairs Committee in consultation with the staff senators and confirmed by the Senate, and two students appointed in accordance with procedures established by the Associated Students.

1. Function

    1. The Committee shall make recommendations to the Senate and, within the policy guidelines established by the Senate, to appropriate administrative officers concerning the allocation of university resources;

    1. The Committee shall act as the deliberative body of the Senate on all issues pertaining to, but not limited to, university budgets, allocation of facilities and positions, and allocation of special funds;

    1. The Committee shall review and recommend budget allocations, shall review patterns of previous expenditures and propose changes as they may affect instructional programs, and shall make general policy recommendations regarding present and future resource decisions.

    1. The Chair of the Committee shall concurrently send to the Senate Chair all of its written communications sent to or received from administrative officers.

    1. All recommendations made to administrative officers without prior Senate approval shall be submitted to the next meeting of the Senate following the recommendation for the consideration of the Senate. The Committee shall inform faculty and students about resource issues by providing information reports to the Senate.
:::

### 3.4 - Committee on Faculty Affairs {#committee-on-faculty-affairs .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (15):

    1. Ex officio (non-voting): Associate Vice President for Faculty Advancement and Student Success or designee, Associate Vice President for Student Affairs and Campus Diversity-Faculty/Staff or designee, and the Director of the Center for Teaching and Learning or designee.

    1. Appointed: nine tenured or probationary faculty, one from each college, the Library, and SDSU Imperial Valley; one Lecturer; one tenured and probationary or contingent Student Services Professional Academic-Related (SSP-AR) faculty member; and one contingent faculty (Lecturer, Assistant Librarian, or SSP-AR) or coaching faculty member. All shall be nominated by the Committee on Committees and Elections and appointed by the Senate for three year terms; at least three shall be elected senators.

1. Functions: In conformance with the Unit 3 faculty Collective Bargaining Agreement (CBA), the Committee shall consider matters that involve particularly the individual or collective relationship of faculty to the university. Among its considerations shall be policies concerning the selection and evaluation of faculty, e.g., academic tenure, promotions, sabbaticals, academic privilege, and separation from the university.

:::

### 3.5 - Committee on Committees and Elections {#committee-on-committees-and-elections .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (16):

    1. Appointed (12): nine faculty senators, one from each academic college, SDSU Imperial Valley, and the Library; three additional faculty, one each from the College of Arts and Letters, the College of Professional Studies and Fine Arts, and the College of Sciences[^fn1], all selected by their respective college senators.. These members shall be affirmed by vote of the Senate.

    1. Ex-officio (4): The Senate Secretary, or designee; the President of Associated Students, or designee; the chair of the Staff Affairs Committee; and the Chair of the Lecturer Affairs Committee.

    1. The term of office shall be for one year and begins at the last regular spring meeting of the Senate; it may be extended.

    1. The first meeting of each term shall occur immediately following the last spring meeting of the Senate and the outgoing chair shall chair it. The business of the first meeting shall be to elect a successor to the outgoing chair.

1. Functions: The Committee on Committees and Elections shall submit for confirmation by the Senate its nominees for members and chairs of Senate and Senate-appointed university committees as openings arise. It shall make nominations as needed for ad hoc and pro tempore committees established by the Senate, shall fill vacancies that may occur in committees, and may inquire into the activities of committees to determine their continued usefulness. The Committee shall observe the following in nominating or appointing members for Senate or Senate-appointed university committees:

    1. The Committee on Committees and Elections shall operate as a committee of the whole.

    1. Committees shall consist of at least three members.

    1. Each elected senator shall serve on at least one Senate or Senate-appointed committee.

    1. Administrative officers of the university may be named as members of Senate or university committees or councils.

    1. An ex officio member shall not be named chair of any committee, unless otherwise provided.

    1. No faculty member shall be nominated or appointed to membership on more than one Senate committee except for members of the Senate Executive Committee who may be appointed or elected to one other committee.

    1. The entire personnel of a committee shall not be changed from one year to the next; terms shall be staggered.

    1. The chair of a committee shall normally be chosen from the committee membership of the preceding year. Whenever possible, the chair shall be an elected senator.

    1. The chair of a committee may request the Committee on Committees and Elections to replace a committee member for cause. The committee member shall be sent a copy of the request.

1. Duties

    1. The Committee on Committees and Elections shall devise procedures for and shall supervise and administer all elections of members of the Senate.

    1. The Committee shall devise procedures for and shall supervise and administer all elections within the Senate, including elected officers and elected members of committees, except for the Committee on Committees and Elections.

    1. The Committee shall certify vacancies in the Senate and in Senate and Senate- appointed university committees.

    1. The Committee shall supervise and administer the elections of Academic senators and of members to boards and selection committees, and it shall supervise and administer the elections or appointments of others to various positions as directed by the Senate or by the Senate Executive Committee.

    1. Members of the Committee shall, when requested, act as tellers when votes are cast by ballot.

    1. The Committee shall decide in cases of doubt the eligibility for election or membership in the electorate.

    1. The Committee shall conduct all referenda to amend the Constitution.

:::

### 3.6 - Committee on Constitution and Bylaws {#committee-on-constitution-and-bylaws .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (10):

    1. Ex officio (voting): Secretary of the Senate, Professor Emeritus Senator.

        Appointed (8): six faculty members, including at least one contingent faculty member, one non-MPP staff member, and one student appointed in accordance with procedures established by Associated Students. Members with previous or current senate experience are preferred. At least two of the appointed members shall be senators.

1. The parliamentarian, while not a member of the committee, shall be invited to the meeting in an advisory capacity.

1. Functions

    1. The Committee shall review periodically the Constitution and Bylaws of the Senate and university policies, and it shall recommend to the Senate such changes as desirable. It shall report to the Senate its recommendations with respect to proposed amendments to the Constitution or Bylaws that have been submitted in writing, signed by the originator(s), and referred to the Committee by the Senate or by the Senate Executive Committee.

    1. Questions concerning interpretations of the text of a Senate-approved document shall be referred to the Committee.

    1. Interpretations by the Committee shall be reported in writing to the Senate and shall be considered binding unless reversed or altered by action of the Senate.

    1. The Committee shall consider each year, as may be necessary, revision of the list of Senate and Senate-appointed university committees and of the membership and functions of each committee. It shall present its recommendations to the Senate in the first Senate meeting held after April 1.

:::

### 3.7 - Undergraduate Curriculum Committee {#undergraduate-curriculum-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (13): Provost and Senior Vice President or designee, Associate Vice President for Curriculum, Assessment and Accreditation or designee, one representative from each college, the Library, and SDSU Imperial Valley selected by the Committee on Committees and Elections, and two students named in accordance with procedures approved by the Associated Students.

1. Functions

    1. The Committee shall review all undergraduate curricula proposals to include additions, deletions, and changes in curricula, with special consideration to items of an interdepartmental or university-wide interest. The Committee shall report all changes to the Senate.

    1. Undergraduate curriculum proposals reviewed by the deans, and by the Undergraduate Council when appropriate, shall be forwarded by the Office of the Provost to the Committee.

    1. Except for approval of the use of courses in the graduate program, approval by the Committee shall be the final step required for including an undergraduate curriculum proposal in the General Catalog. Proposals for new programs and deletion of programs shall be forwarded to the Senate as action items. At the request of four members of the Committee, a proposal shall be placed on the Senate agenda for final action.

    1. A person, department, dean, or college curriculum committee may request the Committee to review a decision on a curriculum proposal. The Committee may agree to review the matter and inform all interested parties of the decision to review and of the date set for the review, or the Committee may decide not to review and promptly inform the appellant of its decision.

:::

### 3.8 - Committee on Diversity, Equity, and Inclusion {#committee-on-diversity-equity-and-inclusion .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (23):

    1. Ex officio (11): Chair of the Senate, or designee; Provost and Senior Vice President, or designee; Vice President for Student Affairs and Campus Diversity (Chief Diversity Officer), or designee; Senior Associate Vice President for Campus Diversity, or designee; Associate Vice President for Faculty Advancement and Student Success, or designee; Associate Vice President for Enrollment, or designee; Director/Title IX Coordinator - Center for Prevention of Harassment and Discrimination, or designee; Tribal Liaison, or designee; Associate Chief Diversity Officer for HSI and Regional Affairs; Director of the Center for Human Resources, or designee; and the Director of Student Ability Success Center, or designee.

    1. Appointed (12): nine faculty members, one of whom shall chair, including one from each college, the Library, and SDSU Imperial Valley, at least one of whom shall be a Senator nominated by the Committee for Committees and Elections (CCE) and appointed by the Senate; one staff member selected by the Staff Affairs Committee in consultation with the staff senators and confirmed by the Senate; and two students, including a representative from the Associated Students appointed in accordance with procedures established by the Associated Students.

    1. Appointed faculty members shall serve three-year, staggered terms.

    1. Membership on the committee shall include representation from diverse campus groups.

    1. The chair of the Committee, in consultation with the President, may request the service and advice of educational and community leaders.

1. Reporting: The Committee shall report to the Senate and advise the President.

1. Functions

    1. The Committee shall review university-wide programs for the recruitment and retention of faculty, staff, and students.

    1. Subject to the approval of the President, the Committee shall advise the university administration regarding prohibited discrimination, equal opportunity, outreach, and related matters.

    1. Additional duties of the Committee shall be: (a) to advise the President regarding the university’s conformity or potential lack thereof with California State University policies and with legislation on nondiscrimination and equal opportunity in admissions and employment, (b) to recommend policies and procedures to recruit students for matriculation and to retain students for graduation, (c) to work with Enrollment Services, diverse student organizations, and interested community persons and groups to coordinate activities to enhance the recruitment of diverse students, (d) to review and assist in coordination of programs for advising and mentoring diverse students, (e) to assist departments in reviewing and modifying their curricula in order to incorporate multicultural materials, (f) to promote faculty and staff involvement in addressing the educational needs of diverse students, (g) to disseminate information concerning funding for equity programs within the university, (h) to advise the Office of Employee Relations and Compliance and the Chief Diversity Officer regarding policies, procedures, and outcomes of the university’s diversity programs.
:::

### 3.9 - Graduate Council {#graduate-council .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Representing the interests of the university in graduate studies, the Graduate Council shall be responsible to the university administration, the Dean of the College of Graduate Studies, the Senate, academic units, faculty members, and students. The university-wide jurisdiction of the Council shall derive from the President, the Senate, and the faculty.

1. Membership (30): Voting members include fifteen tenured and probationary faculty, two from each of the seven academic colleges and one from SDSU Imperial Valley; Dean of the College of Graduate Studies or designee, who shall chair; Provost and Senior Vice President for Academic Affairs, Dean of the Library (or designee), and two classified graduate students in good standing. Non-voting members include Associate and Assistant Deans of the College of Graduate Studies; Vice President for Research and Innovation; Director of Graduate Life and Diversity; two Enrollment Services representatives (Graduate Admissions Lead and Associate Director); and four additional representatives from the College of Graduate Studies, appointed by the Dean of the College of Graduate Studies.

    1. Faculty members shall be active in graduate programs of their colleges and schools or departments. They shall serve staggered three-year terms and may immediately succeed themselves for one term. Nominations shall originate in colleges, and the Committee on Committees and Elections shall consult with the Dean of the College of Graduate Studies before recommending nominees to the Senate.

    1. Student members shall be appointed for a one-year term (renewable for one year) by the Associated Students in consultation with the Dean of the College of Graduate Studies. The Dean of the College of Graduate Studies shall submit nominations from graduate advisers to the Associated Students, who shall appoint two graduate students (one to represent a doctoral program and one to represent a master’s program).

1. Functions. The Council shall be responsible for the development of policy on (a) graduate programs, (b) graduate student affairs, (c) graduate research and scholarship, and (d) faculty participation in graduate programs. Duties also include the review and approval of new and modified graduate courses and graduate program proposals.

    1. Graduate Programs

        1. The Council shall encourage colleges, schools, and departments to develop criteria and procedures to ensure the quality of their programs and to provide guidance and oversight in developing new programs.

        1. The Council shall review these criteria and procedures, approve new graduate programs, review and approve new graduate curricula and changes in existing curricula, and review existing graduate programs.

        1. Both the Council and the Undergraduate Curriculum Committee shall review courses that will become available to both undergraduate and graduate programs.

        1. The Council shall distribute its minutes concerning curricula and programs simultaneously to members of the Senate and the Council.

        1. The Council shall follow the procedures as outlined in the “University Policies” section titled “Curriculum Changes, Undergraduate, and Graduate.”

    1. Graduate Student Affairs

        1. The Council shall recommend university-wide academic policies and standards for the admission and retention of graduate students and for assistantship, scholarship, and fellowship programs.

        1. The Council shall develop policy to assist schools and departments in ensuring an equitable resolution of differences and issues that may arise between graduate students and the faculty.

        1. The Council shall ensure opportunities for participation by graduate students in the development of policy concerning graduate student issues by providing for such membership on its pertinent standing committees.

    1. Faculty: The Council shall encourage departments, schools, and programs to develop criteria and standards for participation in their graduate programs. It shall ensure that department, school, and program standards accord with university policy.

    1. Policy Management:

        1. The Chair shall develop agenda items and coordinate the activities of the Council.

        1. The Council shall consult with all relevant stakeholders (e.g. students, faculty, administration, college deans, school directors and department chairs) before bringing policy to the Senate.

        1. The Council shall route all new policy and policy changes through the Senate for approval.

        1. The Council shall ensure that all stakeholders are informed of policy changes in a timely manner and publish policies online in collaboration with the College of Graduate Studies, Curriculum Services, the University Senate and others as appropriate.

:::

### 3.10 - Undergraduate Council {#undergraduate-council .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (17): nine faculty, including one from each academic college, the Library and SDSU Imperial Valley; Associate Vice President for Faculty Advancement and Student Success or designee, who shall chair; Associate Dean (FASS); Assistant Dean of Undergraduate Studies (FASS); Assistant Dean of Student Success (FASS); Vice President of Student Affairs and Campus Diversity, or designee; Associate Vice President for Enrollment; and two undergraduate students.

1. Functions: The Council shall:

    1. Oversee an integrated approach to undergraduate excellence at San Diego State University,

    1. Recommend policy for the Office of Faculty Advancement and Student Success,

    1. Propose changes in policy for undergraduate programs

    1. Forward to the Senate the annual report on retention and graduation in the fall of each academic year.

    1. Supervise specific university-wide undergraduate programs such as, but not limited to, the General Education Curriculum Committee and the Graduation and Retention Subcommittee.

1. Subcommittees of Undergraduate Council:

    1. The Graduation and Retention Subcommittee

        1. The Graduation and Retention Subcommittee shall be a permanent subcommittee of the Undergraduate Council.

        1. Membership (22)**:** all members of the Undergraduate Council; the Associate Vice President for Student Life and Dean of Students or designee; the Assistant Vice President of Analytic Studies and Institutional Research or designee; the Director of Institutional Research or designee; the Director of Testing, Assessment, and Research; and two additional, at-large faculty members appointed by the Senate.

        1. Functions: The Subcommittee

            1. Shall oversee a systematic approach to the retention and timely graduation of undergraduates;

            1. Shall recommend to the Undergraduate Council policy changes that promote the timely progress of undergraduate students to graduation;

            1. Shall produce an annual report on retention and graduation during the fall semester.

    1. Special Topics Subcommittee

        1. The Special Topics Subcommittee shall be a permanent subcommittee of the Undergraduate Curriculum Committee.

        1. Membership (5): three faculty who are members of the Undergraduate Curriculum Committee, one of whom shall chair; the Associate Vice President for Curriculum, Assessment and Accreditation and the Associate Vice President for Enrollment or designee.

        1. Function

            1. The Subcommittee shall review course proposals identified as 296, 496, 580, and 596, and General Studies 250, 350, and 550. Courses numbered 550, 580, and 596 shall be forwarded to the Graduate Council for an additional review. Although the Subcommittee may apply different criteria to these, it shall retain the same standards of regular courses.

            1. The Subcommittee shall encourage experimental and interdisciplinary courses.
:::

### 3.11 - Lecturer Affairs Committee {#lecturer-affairs-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (13-20):

    1. Ex Officio (13): All Contingent Faculty serving on the SDSU University Senate, including the elected ASCSU Lecturer representative.

    1. Appointed (0-7): Up to seven additional at-large Contingent Faculty members from across the university, including Librarian and Student Services Professionals - Academic Related (SSP-AR) faculty members.

    1. Members must have a minimum one-year appointment, or have a reasonable expectation that they will be appointed to work during both the fall and spring semesters.

    1. Terms for all members shall be three year renewable terms.

    1. Quorum requires the presence of at least seven (7) members.

    1. No college or unit may have more than 25% of members on the committee at any one time.

    1. A chair shall be elected by members in March of each year to serve for the next academic year.

1. Functions. The committee shall:

    1. Serve as the nominating authority for Contingent Faculty seats to the Senate, Senate Core Committees, Senate Committees, Senate-affiliated Campus Committees, and any other Senate-related appointments designated specifically for Contingent Faculty. Vacancies will be filled in accordance with the policies outlined in the Senate policy file, under Bylaws, section 6.0: Vacancies.

    1. Meet a minimum of four times per semester to identify, discuss and organize around campus issues that impact the Contingent Faculty constituency.

    1. Develop new policy or make recommendations for revisions to existing policy related to Contingent Faculty affairs.

    1. Advocate for the inclusion of the Contingent Faculty constituency as part of the decision making and governance on campus, including identifying and recommending Contingent Faculty for placement on senate and other campus committees.

    1. Organize the Senate caucus for Contingent Faculty senators.

    1. Engage regularly with the Contingent Faculty constituency.

    1. Perform other functions that may be required in service of the Contingent Faculty constituency.

    1. Known topics that impact the Contingent Faculty constituency include, but are not limited to:

        - Service and work completed outside of the scope of contracted teaching. Inclusion in department meetings, collaborations, and decision-making processes.

        - Training.

        - Contingent Faculty planning and hiring at the university and departmental levels.

        - Collecting Contingent Faculty feedback (e.g. surveys) for collaborative decision making, etc.

        - Perform a periodic assessment of Contingent Faculty seats on Senate committees to ensure Contingent Faculty interests are represented on key groups and regarding key issues.

        - Make recommendations to the Committee on Committees and Elections (CCE) and/or Senate leadership regarding Contingent Faculty participation on Senate committees.

1. The Chair (or designee) shall report the business of the committee to the Senate.

:::

### 3.12 - Staff Affairs Committee {#staff-affairs-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership sixteen (16): Fourteen (14) open seats for permanent Non–Management Personnel Plan (non-MPP) staff from across the institution, one (1) open seat for an auxiliary organization Staff Senator as defined in Bylaws 1.0, and one (1) non-voting ex officio staff emeritus appointed by SDSU Retirement Association.

    1. The quorum for meetings shall be a simple majority of filled positions.

    1. At least four (4) members of the committee shall be current Staff Senators.

    1. Membership shall serve staggered three-year terms and may immediately succeed themselves for one term. Nominations shall originate as open calls to all permanent non-MPP staff.

    1. A chair shall be elected by members in March each year to serve for the next academic year. When possible, the chair shall be a current or former Senator. The chair may be re-elected for a total of three consecutive terms.

    1. The chair (or designee) shall serve as ex officio voting member of the Senate Executive Committee and report committee business to the Senate Executive Committee and the University Senate.

    1. Staff representatives on Senate Core Committees, Senate Committees, Senate-affiliated Campus Committees and staff senators are invited to present relevant committee information at the Staff Affairs Committee.

1. Function: The committee shall:

    1. Be the nominating authority for staff representation on committees. As such, the committee will nominate staff to fill vacancies to Senate Core Committees, Senate Committees, and Senate-affiliated Campus Committees by campuswide announcement for nominations and simple majority vote of the committee.

    1. Meet regularly during the academic year to identify, discuss, and organize around university issues that impact the staff constituency.

    1. Develop new policy or make recommendations for revisions to existing policy-related to staff affairs.

    1. Engage regularly with the staff constituency and advocate for the inclusion of the staff constituency as part of the decision-making and shared governance on campus.

    1. Organize the Senate caucus for staff senators.

    1. Nominate emeritus staff to the Senate Executive Committee and the University Senate in accordance with the University Policies: Emeritus Employees.

1. Elect staff seats on ad hoc committees.

    1. Search Committees: The Staff Affairs Committee shall coordinate filling any search committee vacancy with the Senate Committee on Committees and Elections. The announcement shall explain the duties of the Search Committee and ask for nominations for each vacancy. All permanent non-MPP staff employees within the unit or division (e.g., individual colleges, Academic Affairs, Business and Financial Affairs, Research and Innovation, Information Technology, Student Affairs and Campus Diversity, University Relations and Development, etc.) in which the search is conducted shall be eligible to serve; only non-MPP staff from within the unit or division shall be eligible to nominate and vote. When nominating someone other than oneself, agreement to serve must be obtained from the nominee prior to the nomination. Each nomination shall include contact information, department, and position name, and a statement of qualifications and interest. The nomination period shall be at least five (5) business days. Once nominations are closed, a second voting announcement shall be made with the list of nominees (including their statements). Voting shall be open for five (5) business days. Selection shall be determined by the plurality of received votes.

    1. Administrator Review Panels: The Staff Affairs Committee shall coordinate filling any Search committee vacancy with the Senate Committee on Committees and Elections. The announcement shall explain the duties of the Administrator Review Panel and ask for nominations for each vacancy. All permanent non-MPP staff employees within the unit or division (e.g., individual colleges, Academic Affairs, Business and Financial Affairs, Research and Innovation, Information Technology, Student Affairs and Campus Diversity, University Relations and Development, etc.) in which the search is conducted shall be eligible to serve; only non-MPP staff from within the unit or division shall be eligible to nominate and vote. When nominating someone other than oneself, agreement to serve must be obtained from the nominee prior to the nomination. Each nomination shall include contact information, department and position name, and a statement of qualifications and interest. The nomination period shall be at least five (5) business days. Once nominations are closed, a second voting announcement shall be made with the list of nominees (including their statements). Voting shall be open for five (5) business days. Selection shall be determined by the plurality of received votes.

    1. Auxiliary Review Panels: The Staff Affairs Committee shall coordinate filling any review panel vacancy with the Senate Committee on Committees and Elections. The announcement shall explain the duties of the Auxiliary Review Panel and ask for nominations for each vacancy. All permanent non-MPP staff employees within the unit or division (e.g., individual colleges, Academic Affairs, Business and Financial Affairs, Research and Innovation, Information Technology, Student Affairs and Campus Diversity, University Relations and Development, etc.) in which the search is conducted shall be eligible to serve; only non-MPP staff from within the unit or division shall be eligible to nominate and vote. When nominating someone other than oneself, agreement to serve must be obtained from the nominee prior to the nomination. Each nomination shall include contact information, department and position name, and a statement of qualifications and interest. The nomination period shall be at least five (5) business days. Once nominations are closed, a second voting announcement shall be made with the list of nominees (including their statements). Voting shall be open for five (5) business days. Selection shall be determined by the plurality of received votes.

    1. Subcommittees {subcommittees .policy-toc-heading}

        1. Staff Honors and Awards Subcommittee

            1. Membership twelve (12): eight (8) permanent staff members selected from bargaining units 1, 2, 4, 5, 6, 7, 8, 9, and one (1) confidential staff; one student selected by Associated Students, one (1) Administrator I or II (staff MPP classification), and one (1) Auxiliary organization staff as defined in Bylaws 1.0. In the event that the subcommittee cannot meet these requirements the subcommittee chair may fill vacancies as best as possible. The subcommittee chair shall be a member of the Staff Affairs Committee. The remaining staff members shall be from as many areas of campus (including Imperial Valley) as possible.

            1. The subcommittee chair shall be identified during the fall semester from among existing Staff Affairs Committee members by majority vote.

            1. Membership shall be a one-time term from December through August when the awards are announced. Members may be re-elected for a total of three consecutive terms.

            1. The Staff Affairs Committee shall coordinate filling the subcommittee with the Senate Committee on Committees and Elections. The announcement shall explain the duties of the Staff Honors and Awards Subcommittee and ask for nominations for each vacancy outside of the subcommittee chair (e.g., if the chair is in unit 7 then the announcement will go out to the other membership groups in 3.12.4.1.1.). All permanent non-MPP staff employees, the Administrator I or II, and the Auxiliary staff in which the search is conducted shall be eligible to serve; only the eligible nominee pool shall be eligible to nominate and vote. When nominating someone other than oneself, agreement to serve must be obtained from the nominee prior to the nomination. Each nomination shall include contact information, department, and position name, and a statement of qualifications and interest. The nomination period shall be at least five (5) business days. Once nominations are closed, a second voting announcement shall be made with the list of nominees (including their statements). Voting shall be open for five (5) business days. Selection shall be determined by the plurality of received votes.

            1. Functions: The committee shall provide recommendations to the University President regarding the Staff Excellence Awards program as defined in University Policies: Staff Awards 1.0.

:::

### 3.13 - Sustainability Committee {#sustainability-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Background/Purpose: Sustainability refers to practices designed to meet the needs of the present without compromising the ability of future generations to meet their own needs. It encompasses teaching, research, and practice in a variety of areas including but not limited to policy development, building design and construction, waste management and recycling, energy production and use, water use, and transportation.

1. Membership (21**):** ten faculty members, including one from each academic college, the SDSU Library, SDSU Imperial Valley and one contingent faculty member; one staff member; Vice President for Student Affairs and Campus Diversity, or designee; Associate Vice President for Curriculum, Assessment and Accreditation, or designee; Director of Energy and Sustainability, or designee; Associate Vice President for Real Estate, Planning and Development, or designee; Associate Vice President for Business Operations, or designee; SDSU Research Foundation Director of Facilities, or designee; KPBS General Manager, or designee; CEO of Aztec Shops, or designee; two students.

1. Functions. The Committee shall:

    1. Study, track and review sustainability issues related to the campus and make recommendations to improve sustainable practices.

    1. Coordinate with campus units and the community to ensure that sustainability is taken into consideration.

    1. Communicate with the Committee on Environment and Safety and the Campus Development Committee to ensure that sustainability is taken into consideration in the deliberations of those bodies.

    1. Receive copies of Executive Orders or other instructions to the campus dealing with sustainability and report on them to the Senate.

    1. Serve as a resource to faculty, staff and students wishing to undertake research, or propose curricular changes, or pursue sustainable practices.

    1. Communicate these activities and outcomes to the Senate, campus, and the broader community.

:::

[^fn1]: CAL, SCI, and PSFA have historically held the largest FTEF and are thus accorded an additional member to assist with committee staffing. This is consistent with the CSU Academic Senate, which allots two senators to each campus, and three senators to the largest of the campuses.


## 4. - Elections {#elections .unnumbered}

::: {.policy-numbering .policy-start-1}

1. General Procedures

    1. All nominations and elections for which the Committee on Committees and Elections is responsible shall be by secret ballot.

    1. The chair of the Committee on Committees and Elections shall maintain a record of each election. The results of each election by numerical count of votes received by each candidate shall be posted in the Senate office by the chair of the Committee on Committees and Elections as soon as the count has been completed and verified. The chair of the Committee on Committees and Elections shall retain for 30 days all ballots, or electronic records of ballots, cast during an election. If the results of the election are formally protested during that time, the ballots shall be retained until the protest is resolved. The results of each election by numerical count of the votes shall be kept on file in the Senate office for three years.

    1. The period of time for casting ballots shall be five working days with the deadline at noon on the last day. The poll closing time shall be clearly stated on the ballot. Only ballots received via the online polling site by the poll closing time shall be counted.

1. Elections to the Senate

    1. The regular annual elections to the Senate shall occur during the spring. There shall be no elections to the Senate during the summer. Elections to fill uncompleted terms shall be conducted as directed in Sections 6.1, 6.22, and 6.32.

    1. For purposes of determining the number of college senators, faculty positions per major academic unit shall be the total Tenured and Probationary Faculty positions filled by the college.

    1. The number of senators to be elected by a major academic unit as authorized in Sec. 4.0 of the Constitution shall be determined once each year immediately before the regular annual elections.

    1. A faculty member shall not serve as a representative to the CSU Academic Senate (ASCSU) while serving as a faculty representative in the SDSU University Senate.

    1. The election of senators shall be conducted in three steps as indicated below unless the election is terminated earlier as provided. Throughout this section, fractional numbers of candidates shall be considered as the next larger integer.

        1. The availability of Senate seats shall be publicized to the university community. Electronic means of publicizing shall be acceptable, as long as all members of the various electorates are reached in this fashion. The election call shall request nominations to be submitted to the Senate office. Electronic submission shall be accepted. Self-nominations are acceptable. Those nominated shall have their names placed on the ballot for the next step of the election, unless the nominee requests that his or her name be withdrawn or the Committee on Committees and Elections determines that the nominee does not meet the criteria to be elected.

        1. The second step shall provide the electorate with a ballot that lists all candidates nominated in accord with sec. 4.2.5.1. The candidates’ names shall be listed in random sequence as determined by lot. To allow faculty and staff to vote for candidates not duly nominated, the ballot shall also include a number of spaces for write-in nominees equal to the total number of vacant seats. On this and successive ballots, write-in nominees, without regard to their accumulated votes, shall be considered candidates of standing equal to those nominated in accord with sec. 4.2.5.1. The electorate may vote for as many candidates as there are vacant seats, but it shall vote for no more candidates than vacant seats. Ballots containing more votes than the number of vacant seats shall be voided. Candidates shall be elected to fill vacant seats in a descending order of votes cast until all vacant seats are filled.

        1. Successive ballots shall be cast to eliminate ties for remaining vacant seats. Each ballot shall include only those candidates who have tied for the last vacant seat on an immediately preceding ballot.

        1. Whenever feasible, staggered terms shall be arranged so that only one-third of the senators of each major academic unit are elected to a three-year term in the spring. When the election involves terms of different lengths, the candidates who receive the greatest number of votes on the ballot resulting in their being elected shall receive the longest term available. Ties shall be broken by lot. Service for a short term shall be considered a partial term; therefore, the person elected remains eligible to serve two additional consecutive full terms.

        1. Vacant seats resulting from the application of Sections 4.2.5.1.–2.5.4. above shall be conducted as directed in Sections 6.1, 6.2.2., 6.3.2.

    1. The Senate seat of an elected member shall become vacant when the individual (a) resigns from the Senate, (b) becomes an ex officio member of the Senate, (c) is elected as a member of the Senate representing another employee group, (d) is absent and unrepresented for more than two regular Senate meetings during the academic year, (e) is absent with or without representation for more than four regular Senate meetings during the academic year, (f) has not served on a Senate or Senate-affiliated Campus committee for over a year, (g) becomes ineligible due to change in classification or job status, (h) separates from the university.

    1. Members that fail to meet the eligibility criteria due to a change in job status (e.g. a tenured and probationary faculty member becoming a member of MPP or entering FERP) may finish serving the current year of their term in the Senate, but if they hold a position of officer, they shall relinquish that position immediately. Likewise, those who are no longer eligible to serve in a Senate Committee due to a change in job status can finish the current year of their term, but if they hold the position of a committee chair, they shall relinquish that position immediately.

1. Filling Temporary Vacancies: The Secretary of the Senate shall report leaves and extended absences of senators to the Committee for Committees and Elections, which shall certify the existence of a vacancy and proceed to fill it as prescribed in Sec. 4.2.5.

1. Elections within the Senate

    1. The annual election of the Chair, the Vice Chair, the Secretary, and the Treasurer of the Senate, and of the elected members of the Senate Executive Committee shall be conducted at a Senate meeting during the spring semester following the regular annual election of members to the University Senate, including those elected to the Academic Senate of The California State University (ASCSU). Eligible electors shall consist of the members of the Senate for the ensuing Senate year.

        1. The Committee on Committees and Elections shall conduct the elections in the following order: (a) Chair, (b) Vice Chair, (c) Secretary, (d) Treasurer, (e) three Executive Committee members.

        1. Officers and elected Senate Executive Committee members shall serve for the following Senate year.

        1. A nominating caucus held prior to the election shall submit at least one nominee for each position to be elected. Attendance at the caucus shall be open to all outgoing and incoming Senators.

        1. Elections shall be conducted during a regular Senate meeting. In addition to those nominated by the caucus, nominations may be made from the floor prior to each election. A majority of votes cast shall be required for election on the first ballot. If a majority is not obtained for each position, a runoff election shall be held among the n + 1 candidates receiving the most votes where n is the remaining number of positions to be filled.

        1. The numerical results of all ballots shall be available to senators through the chair of the Committee on Committees and Elections.

1. Elections to the Academic Senate of The California State University (ASCSU)

    1. The Committee on Committees and Elections (CCE) shall devise procedures for and shall supervise and administer all elections of representatives from San Diego State University to the Academic Senate of The California State University (ASCSU). Elections shall be held each spring by April 15 for ASCSU senators with terms to start the upcoming academic year.

    1. Eligibility to serve as an elected member in the ASCSU is defined in Constitution 4.0.

    1. The electorate is defined in Constitution 4.0.

    1. The CCE shall resolve any dubious or disputed eligibility for election to the Academic Senate or membership in the electorate.

    1. The election shall be conducted in a manner similar to the provisions of Sec. 4.2.

    1. The two runners-up from the last regular yearly election of ASCSU senators are considered “Alternates,” and are qualified to serve as a substitute for an ASCSU Senator. If an “Alternate” is not available to serve as substitute, the Chair of the Senate shall appoint a substitute. Any appointed substitute must meet the eligibility requirements in 4.5.2.

    1. In the event that an elected member will be absent for one semester or longer a replacement shall be elected by all faculty for the duration of the absence or the end of the term. Any elected replacement must meet the eligibility requirements in 4.5.2.

1. Nomination of Faculty Trustee

    1. A tenured and probationary faculty member with no administrative position other than department chair or equivalent may stand to be submitted as a candidate for the position of Faculty Trustee. Nomination shall require the signed concurrence of at least 10 percent of the tenured and probationary faculty or 50 such faculty members, whichever number is smaller.

    1. At a regularly scheduled meeting, the Senate may nominate candidates to serve as a Faculty Trustee. The nominees shall have previously agreed to serve and to submit all required materials. Nominations from the Senate floor shall require a three-fourths affirmative vote of the senators present at the meeting.

1. Nomination of Faculty to Advisory Committee to the Trustees Committee for the Selection of the President (ACTCSP)

    1. The Committee on Committees and Elections shall provide notice to the faculty of the formation of the search Committee and shall invite nominations to the ACTCSP of tenured or probationary faculty.

    1. Nominations shall be made by interested faculty submitting a request, endorsed by 10 faculty members, at least five of whom are tenured or tenure-track, for placement on the ACTCSP selection ballot. Eligible nominees are tenured and probationary faculty as defined by these Bylaws, in Sec. 1.2. The period for submitting these requests shall be not less than two or more than five weeks.

    1. At the next regular Senate meeting following the close of the initial nominating period, additional nominations (with the consent of the nominee) shall be added to the ballot by a simple majority vote of the senators present.

    1. To conduct the election, the Committee on Committees and Elections shall prepare a ballot with the names of all nominees, in an order determined by lot. The electorate shall include all faculty, as defined by Bylaws 1.0. The two faculty members with the highest vote counts shall have been elected, provided that no more than one shall serve from any college.

    1. The sitting Senate Chair shall serve as an ex officio member of the ACTCSP.

1. Nomination of non-MPP Staff to the Advisory Committee to the Trustees Committee for the Selection of the President

    1. The Committee on Committees and Elections shall provide notice to the staff of the formation of the search committee and shall invite nominations to the ACTCSP of non-MPP staff.

    1. Nominations shall be made by petition endorsed by 10 staff for placement on the selection ballot. The period for submitting these requests shall be not less than two nor more than five weeks.

    1. To conduct the election, the Committee on Committees and Elections shall prepare a ballot with the names of all nominees in an order determined by lot. The electorate shall include all non-MPP staff, including probationary staff. The staff member with the highest vote count shall be elected.
:::

## 5. - Substitutes {#substitutes .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Senators and members of Senate and Senate-appointed committees may appoint a substitute if they cannot attend a meeting, unless specified otherwise. {#policy .policy-heading}

    1. A substitute serves for a single meeting.

    2. The substitute may attend the meeting and shall have the same speaking and voting privileges as the member.

1. Eligibility 

    1. General eligibility

        1. Appointed and elected members may appoint someone from their same constituency, unless otherwise stated in the policy file.

        1. Ex officio members may appoint someone from their same administrative area, unless otherwise stated in the policy file.

    1. Senate Executive Committee: Ex officio members that chair a Senate standing committee may only appoint as substitute a committee member that is eligible to chair that committee.

    1. Senate Officer: Substitutes shall only be allowed for Senate Officers while serving as ex officio on Senate or Senate-appointed committees. An officer may appoint another officer as a substitute.

    1. ASCSU: The two runners-up from the last regular yearly election of the ASCSU Senator are considered “Alternates,” and are qualified to serve as a substitute for an ASCSU Senator. If an “Alternate” is not available to serve as substitute, the Chair of the Senate shall appoint a substitute. Any appointed substitute must meet the eligibility requirements in Bylaws 4.5.2.

1. Notification 

    1. Senators appointing substitutes for a Senate meeting shall notify the Senate Officers in writing via established procedure as soon as is reasonably possible.

    1. Committee members appointing substitutes for a committee meeting shall notify the committee chair in writing as soon as is reasonably possible.

    1. ASCSU Academic Senators appointing “Alternates” shall notify the appropriate member of the Academic Senate. ASCSU Academic Senators appointing a substitute for a Senate Executive Committee or Senate meeting shall notify the Senate Officers in writing via established procedure as soon as is reasonably possible.
:::

## 6. - Vacancies {#vacancies .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Determination

    1. Vacancies for elected SDSU Senators, including ASCSU Academic Senators, occur when the member meets the criteria in Bylaws 4.0.

    1. Vacancies for SDSU Senate and Senate-appointed committee members occur when the member meets the criteria in Bylaws 2.0.

1. Replacement of Elected Senators

    1. CSU Academic Senators. The Committee on Committees and Elections shall hold an election as soon as is possible to elect a replacement for the duration of the absence or the end of the term as outlined under 4.0 of these Bylaws.

    1. All other elected SDSU Senators

        1. The temporary replacement shall be chosen from nominees receiving the next highest number of votes in the latest election for the constituency where the vacancy occurs. In the event of a tie number of votes, the Committee on Committees and Elections shall select the alternate filling the vacancy by lot.

        1. If there are no other nominees or the nominee is not interested in serving any longer, the chair of the Committee on Committees and Elections, in consultation with current senators from the impacted constituency, shall nominate the temporary replacement.

        1. In nominating replacements for Contingent Faculty, the Lecturer Affairs Committee shall be consulted. A preference for units without existing representation shall be applied.

        1. In nominating replacements for Staff Senators, the Staff Affairs Committee shall be consulted.

    1. If the vacating member’s term extends beyond the date an election will occur, the member appointed to that seat shall be considered a permanent replacement and shall complete the vacating member’s term before they are electable for their own term. Per Bylaws 4.0 , completion of a partial term as a replacement does not does not impact on the member’s eligibility to serve full terms of their own.

1. Replacement of Committee Members

    1. Replacements shall meet all eligibility requirements as set forth in the committee’s charter.

    1. To replace a Senator-at-large in the Senate Executive Committee an election will be hold as soon as a vacancy is reported.

    1. In all other cases, the Committee on Committees and Elections in collaboration with impacted committees and constituencies as appropriate, shall nominate a candidate.

        1. Contingent Faculty seats: The Lecturer Affairs Committee shall be consulted in identifying a replacement.

        1. Staff seats: The Staff Affairs Committee shall be consulted in identifying a replacement.

    1. Elected Senators without a committee assignment shall be prioritized in identifying a replacement.

    1. CCE shall present all nominated replacement committee members to the Senate for confirmation.

    1. If the member replaced was a committee chair the impacted committee shall elect a new chair per Bylaws 2.0.

    1. In instances where replacements are appointed to service on committees, Bylaws 4.0. shall apply. Completion of a partial term as a replacement does not impact the member’s eligibility to serve full terms of their own.

1. Replacement of Senate Officers

    1. Should the Chair be unable to serve the full term, the Vice Chair shall become the Chair and an election shall be held to choose a replacement Vice Chair.

    1. Should the Vice Chair, Secretary or Treasurer of the Senate be unable to serve the full term, an election shall be held to choose a replacement.
:::

## 7. - Meetings {#meetings .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Meetings of the Senate

    1. The Senate shall serve and meet as necessary during the summer.

    1. The dates and time of the regular meetings of the Senate shall be set by the Senate far enough in advance to facilitate members’ scheduling of classes.

    1. Special meetings of the Senate shall be called by the Chair either at the Chair’s discretion or upon receiving a written petition of 10 percent of the Senate membership or of 10 percent of the electorate.

    1. Written notice of each special meeting and its agenda shall be distributed to the members of the Senate by the Secretary at least three days before the meeting unless the Chair or Vice Chair, with the concurrence of a majority of the Executive Committee, decides that the urgency of the occasion will not permit the usual three day notice. In a meeting called under this provision, notice shall be given as far in advance as possible, and action shall require an absolute majority of the membership of the Senate.

    1. The meetings shall be open to all, but only members of the Senate shall participate in the debate. Others may provide information or explain a point of view on matters before the Senate by invitation of the Chair, or the Senate.

    1. A faculty session of the Senate shall comprise only Tenured and Probationary Faculty senators, as defined by the Constitution. Its function shall be to express the collective voice of the faculty. It may make determinations regarding any issue. Any member of the university community may attend a faculty session; however, only Tenured and Probationary Faculty senators may speak and vote.

        1. A faculty session shall be convened upon a majority vote of the sitting Senate or by a majority vote of the Senate Executive Committee.

        1. A faculty session shall be terminated by a two-thirds majority vote of the convened session or by an advance stipulation.

        1. When the faculty session has concluded its business or when the session has been terminated by advance stipulation, its actions shall be reported to the full Senate. The Secretary of the Senate shall include all actions of the faculty session in the minutes of the Senate.

1. Meetings of the Faculty

    1. For a meeting of the faculty, those eligible to participate shall be defined as persons who hold a permanent, multiple year, or temporary appointment and are members of Unit 3 as defined in the current Collective Bargaining Agreement. For the purposes of this section, temporary appointees of Unit 3 shall become members of the general faculty on their dates of appointment.

    1. The quorum for faculty meetings shall be a simple majority, that is, 50 percent plus one of the faculty.

    1. Meetings of the faculty may be called under these conditions: (a) upon the call of the President of the university, at which time the President shall preside; (b) upon the call of the Senate, at which time the Senate Chair shall preside; and (c) upon the call of the Senate Chair, for review of an action of the Senate.

    1. The Senate Chair or Vice Chair shall obtain the consent of a majority of the members of the Senate Executive Committee prior to establishing the agenda for a meeting of the faculty that is called by the Senate or by the Senate Chair.

1. The conduct, frequency, and agendas of Senate committees shall be determined by those committees.

1. Senate business shall have priority over class scheduling. Senators’ class schedules shall permit their attendance at Senate meetings from 2:00 to 5:30 PM on Tuesdays and Thursdays.

:::

## 8. - Order of Business {#order-of-business .unnumbered}
::: {.policy-numbering .policy-start-1}
1.  The regular order of business of the Senate shall be the agenda prepared by the Senate Executive Committee.

2.	Any member of the Senate may present to the Secretary of the Senate items for the agenda. Resolutions, if not forwarded by a committee, have to be endorsed by at least 5 voting senators (endorsees to be listed at the end of the text). The Secretary shall deliver all such items to the Executive Committee, which shall place them on the agenda for the next regular Senate meeting or refer them to a specific committee. Disposition of such items shall be indicated in the minutes of the Senate Executive Committee.

3.	The	senate agenda as approved by the Senate Executive Committee shall be made available in writing no later than four working days before a University Senate meeting. 

4.	Any	senator may bring an information item on the approved agenda of the University Senate to the floor for debate. To move it to action a simple majority vote is needed.

5.	Any	member of the Senate may present an action item on the senate floor. A  two-thirds majority vote is needed to place it on the agenda.
:::

## 9. - University Policy File {#university-policy-file .unnumbered}

::: {.policy-numbering .policy-start-1}
1. The Senate shall establish and maintain a University Policy File, containing the policies and regulations adopted by the Senate and approved by the President, and various references to executive orders and legislative codes.

2.	The Secretary of the Senate shall review such additions and changes as are adopted by the Senate and approved by the President for the Policy File and shall reword or reorganize, without substantive change, such portions as are necessary to conform to the standard format of the Policy File. The Secretary of the Senate, with advice from the Committee on Constitution and Bylaws, shall ensure the accuracy of the Policy File.

3.	Printed copies of the Policy File shall be distributed upon request to the Secretary of the Senate. A full copy of the Policy File shall be maintained on the Senate Website.

4.	The language of the Policy File shall clearly and concisely describe or narrate prescriptive or prohibitive policies and procedures. It may include the purposes for policies or procedures but shall avoid histories, contexts, and motivations. ``Shall” or “shall not” shall indicate prescription or prohibition; “may” shall indicate option or ability; “should” shall indicate advice or suggestion.
:::

## 10. - Parliamentary Procedure {#parliamentary-procedure .unnumbered}

::: {.policy-numbering .policy-start-1}

1.	All questions of parliamentary procedure not covered by these Bylaws shall be decided according to the latest edition of Robert’s Rules of Order Newly Revised.
2.	Unless objections are raised immediately following a Senate vote, the terms “unanimous” or “without dissent” may be used in the minutes when all votes are affirmative and in spite of abstentions.

:::

## 11. - Presidential Approval of Senate Actions {#presidential-approval-of-senate-actions .unnumbered}

::: {.policy-numbering .policy-start-1}

1.  Draft minutes of Senate meetings where any official Senate action is taken shall be delivered to the President within fourteen (14) calendar days of the conclusion of the Senate meeting. 

2.	Within thirty (30) calendar days of receiving the Senate Minutes, the President shall respond in writing to indicate approval, rejection, or postpone a decision on an action item. This written response is referred to as a Presidential Action Memo. 

    1.	If any action item is postponed, the President shall include a rationale for postponement. The President shall have until the first Senate Executive Committee meeting of the next academic year to either approve or reject postponed items. 
    
    2.	If any action item is rejected, the President shall include a rationale. 
    
    3.	If an action item passed by the Senate is not approved by the President, and hence does not become policy, the Senate Chair, or designee, shall notify the Senate.
    
    4.	Approved actions shall be implemented as soon as is practical, which may precede their appearance in the university policy file.
    
    5.	Senate Resolutions do not require approval or rejection of the President. The President shall note receipt of a Senate resolution, and may choose to indicate what, if any, follow-up steps they plan to make based on specific resolved clauses in the resolution. 

3.	The Senate Chair, or their designee, shall forward a copy of the President’s Action-Memo to all Vice Presidents, Human Resources Director (for emeritus status processing), Vice Chair of the Senate (for referrals updates), Secretary of the Senate (for policy file updates), SEC members, Senate Chairs, as well as to any other person/department/unit whose work may be impacted by the Senate action. 

4.  The Senate Chair, or designee, shall ensure that the President is informed promptly by suitable means of Senate actions that would require implementation in fewer than 30 days after Senate action, in order that such legislation not be unduly delayed.

:::

## 12. - Interpretation of Senate Actions {#interpretation-of-senate-actions .unnumbered}

Interpretations made by the Committee on Constitution and Bylaws shall be reported in writing to the Senate and shall be considered binding unless reversed or altered by action of the Senate. Such interpretations shall be considered binding on the university only after they have been approved by the President.


## 13. - Availability of Documents and Records {#availability-of-documents-and-records .unnumbered}

::: {.policy-numbering .policy-start-1}

1. All agendas, minutes, resolutions, annual Senate University Policy Files versions, and presidential action memos of all regular and special Senate and Senate Executive Committee meetings shall be posted on the Senate website for a minimum of two years. 

2.	If a Senate meeting or any Senate-related event is recorded in whole or in part, the recording shall be available in a manner consistent with the California Public Records Act.  

3.	Confidential material shall be redacted or omitted from posted materials, but the agenda item in which confidential material is addressed shall be included in the table of contents and minutes.

4.	Special Collections and University Archives will archive Senate agendas, minutes, resolutions, annual university policy file versions, and presidential action memos over two years old. These materials are publicly available in Special Collections & University Archives.  

5.	The current Senate University Policy File shall be made available on the senate website.

:::

## 14. - Amendments {#amendments .unnumbered}

Amendments to these Bylaws may be adopted at a regular business meeting of the Senate by a two-thirds vote of those present, provided the amendments have been presented at the previous meeting.
