---
title: "Senate Executive Committee and Senate Core Committees: Charters"
description: "The charters of the Core Senate Committees."
toc: true
---

## 3. Senate Executive Committee and Senate Core Committees: Charters {#senate-executive-committee-and-senate-core-committees-charters .unnumbered}

### 3.1  Senate Executive Committee {#senate-executive-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (24): The Senate Executive Committee shall consist of 21 ex officio members and three elected members.

    1. Ex officio (voting): Chair of the Senate (who shall be the Chair of the Senate Executive Committee); Senate Vice Chair; Secretary of the Senate (who shall be the Secretary of the Executive Committee); Treasurer of the Senate; the Chairs of all Senate Core Committees: (a) Academic Policy and Planning, (b) University Resources and Planning, (c) Faculty Affairs, (d) Committees and Elections, (e) Constitution and Bylaws, (f) Undergraduate Curriculum, (g) Diversity, Equity, and Inclusion, (h) Undergraduate Council, (i) Graduate Council, (j) Lecturer Affairs, (k) Staff Affairs, and (l) Sustainability; an ASCSU Senator chosen from and by the CSU Academic Senators; Provost and Senior Vice President; and the President of the Associated Students.

    1. Ex officio (non-voting): President of the university’s chapter of the faculty unit’s collective bargaining agreement; the Immediate Past Chair of the Senate.

    1. Elected (voting): Three faculty senators elected from and by the elected members of the Senate, with no more than one from a college or equivalent academic unit.

    1. The Senate Parliamentarian, the Senate Analyst and Instructional Technology Services staff support the function of the committee, and as such may attend regular and confidential meetings; however they are not active members of the committee. They may not vote or make motions, and may only address the body by invitation of the Senate Chair.

1. Functions

    1. The Senate Executive Committee may consider all matters within the purview of the Senate.

    1. The Senate Executive Committee may formulate recommendations and opinions on Senate matters and shall report them to the Senate or refer them to the appropriate committees.

    1. The Senate Executive Committee shall be empowered to act for a committee in lieu of referral; such action shall be reported at the next regular meeting of the Senate.

    1. The Senate Executive Committee shall act for the Senate on all matters that call for immediate action or attention. Such action shall require an absolute two-thirds majority vote of the entire membership of the Executive Committee and shall be reported to the Senate as a specific agenda item at its next meeting.

1. Meetings

    1. The Senate Executive Committee shall meet at least one week preceding each regular meeting of the Senate. The Committee shall meet at other times as necessary at the call of the Chair of the Senate or at the request of the President of the university.

    1. The Senate Executive Committee may meet with the President of the university, at the initiative of the Committee or the President, to consider problems or issues of the university.

1. Senate Agendas

    1. At the second fall meeting of the Senate, the Senate Executive Committee shall present an annual agenda for the Senate. This agenda shall address major concerns and outline problems for Senate attention during the academic year.

    1. The Senate Executive Committee shall provide the Secretary with the regular agenda to be distributed to the Senate and instruct the Secretary to request the presence of such personnel as may be needed to facilitate the business of the Senate.

    1. Challenge and Censure. A senator may challenge an action taken by the Senate Executive Committee on behalf of the Senate. The matter shall be immediately submitted to a vote. A simple majority vote of the Senate shall uphold the action of the Senate Executive Committee.

    1. The Senate Executive Committee shall be censured for its actions by a two-thirds majority vote of the Senate present and voting.

:::

### 3.2  Committee on Academic Policy and Planning {#committee-on-academic-policy-and-planning .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (18)

    1. Ex officio: the Provost and Senior Vice President or designee, the Associate Vice President for Faculty Advancement and Student Success, the Senate Chair (or designee), and the Dean of Graduate Studies (or designee).

    1. Appointed: eleven faculty members, one from each academic college, the Library, and SDSU Imperial Valley, at least two of whom shall be elected senators, and two open faculty seats, one of whom shall be a contingent faculty member; one staff member; and two students.

1. Functions: The Committee shall consider and make recommendations to the Senate and, within policy guidelines established by the Senate, to appropriate administrative officers concerning the following: (a) issues of academic philosophy, standards, and conduct; appropriateness of present and proposed programs, degrees, majors, options, and concentrations; (b) faculty-student relations; (c) the governance of the university; and (d) other matters of academic policy. All such recommendations made to administrative officers without prior Senate approval shall be submitted to the next meeting of the Senate for its consideration.

:::

### 3.3 Committee on University Resources and Planning {#committee-on-university-resources-and-planning .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (17)

    1. Ex officio (5) : Vice President for Academic Affairs, or designee; Vice President for Business and Financial Affairs, or designee; Vice President for Student Affairs and Campus Diversity, or designee; Vice President for Research and Innovation, or designee; and the University Senate Treasurer.

    1. Appointed (12): nine faculty members, one from each college, the Library, and SDSU Imperial Valley, nominated by the Committee on Committees and Elections and appointed by the Senate, at least two of whom shall be elected senators; one staff member selected by the Staff Affairs Committee in consultation with the staff senators and confirmed by the Senate, and two students appointed in accordance with procedures established by the Associated Students.

1. Function

    1. The Committee shall make recommendations to the Senate and, within the policy guidelines established by the Senate, to appropriate administrative officers concerning the allocation of university resources;

    1. The Committee shall act as the deliberative body of the Senate on all issues pertaining to, but not limited to, university budgets, allocation of facilities and positions, and allocation of special funds;

    1. The Committee shall review and recommend budget allocations, shall review patterns of previous expenditures and propose changes as they may affect instructional programs, and shall make general policy recommendations regarding present and future resource decisions.

    1. The Chair of the Committee shall concurrently send to the Senate Chair all of its written communications sent to or received from administrative officers.

    1. All recommendations made to administrative officers without prior Senate approval shall be submitted to the next meeting of the Senate following the recommendation for the consideration of the Senate. The Committee shall inform faculty and students about resource issues by providing information reports to the Senate.

:::

### 3.4  Committee on Faculty Affairs {#committee-on-faculty-affairs .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (15):

    1. Ex officio (non-voting): Associate Vice President for Faculty Advancement and Student Success or designee, Associate Vice President for Student Affairs and Campus Diversity-Faculty/Staff or designee, and the Director of the Center for Teaching and Learning or designee.

    1. Appointed: nine tenured or probationary faculty, one from each college, the Library, and SDSU Imperial Valley; one Lecturer; one tenured and probationary or contingent Student Services Professional Academic-Related (SSP-AR) faculty member; and one contingent faculty (Lecturer, Assistant Librarian, or SSP-AR) or coaching faculty member. All shall be nominated by the Committee on Committees and Elections and appointed by the Senate for three year terms; at least three shall be elected senators.

1. Functions: In conformance with the Unit 3 faculty Collective Bargaining Agreement (CBA), the Committee shall consider matters that involve particularly the individual or collective relationship of faculty to the university. Among its considerations shall be policies concerning the selection and evaluation of faculty, e.g., academic tenure, promotions, sabbaticals, academic privilege, and separation from the university.

:::

### 3.5 Committee on Committees and Elections {#committee-on-committees-and-elections .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (16):

    1. Appointed (12): nine faculty senators, one from each academic college, SDSU Imperial Valley, and the Library; three additional faculty, one each from the College of Arts and Letters, the College of Professional Studies and Fine Arts, and the College of Sciences[^fn1], all selected by their respective college senators.. These members shall be affirmed by vote of the Senate.

    1. Ex-officio (4): The Senate Secretary, or designee; the President of Associated Students, or designee; the chair of the Staff Affairs Committee; and the Chair of the Lecturer Affairs Committee.

    1. The term of office shall be for one year and begins at the last regular spring meeting of the Senate; it may be extended.

    1. The first meeting of each term shall occur immediately following the last spring meeting of the Senate and the outgoing chair shall chair it. The business of the first meeting shall be to elect a successor to the outgoing chair.

1. Functions: The Committee on Committees and Elections shall submit for confirmation by the Senate its nominees for members and chairs of Senate and Senate-appointed university committees as openings arise. It shall make nominations as needed for ad hoc and pro tempore committees established by the Senate, shall fill vacancies that may occur in committees, and may inquire into the activities of committees to determine their continued usefulness. The Committee shall observe the following in nominating or appointing members for Senate or Senate-appointed university committees:

    1. The Committee on Committees and Elections shall operate as a committee of the whole.

    1. Committees shall consist of at least three members.

    1. Each elected senator shall serve on at least one Senate or Senate-appointed committee.

    1. Administrative officers of the university may be named as members of Senate or university committees or councils.

    1. An ex officio member shall not be named chair of any committee, unless otherwise provided.

    1. No faculty member shall be nominated or appointed to membership on more than one Senate committee except for members of the Senate Executive Committee who may be appointed or elected to one other committee.

    1. The entire personnel of a committee shall not be changed from one year to the next; terms shall be staggered.

    1. The chair of a committee shall normally be chosen from the committee membership of the preceding year. Whenever possible, the chair shall be an elected senator.

    1. The chair of a committee may request the Committee on Committees and Elections to replace a committee member for cause. The committee member shall be sent a copy of the request.

1. Duties

    1. The Committee on Committees and Elections shall devise procedures for and shall supervise and administer all elections of members of the Senate.

    1. The Committee shall devise procedures for and shall supervise and administer all elections within the Senate, including elected officers and elected members of committees, except for the Committee on Committees and Elections.

    1. The Committee shall certify vacancies in the Senate and in Senate and Senate- appointed university committees.

    1. The Committee shall supervise and administer the elections of Academic senators and of members to boards and selection committees, and it shall supervise and administer the elections or appointments of others to various positions as directed by the Senate or by the Senate Executive Committee.

    1. Members of the Committee shall, when requested, act as tellers when votes are cast by ballot.

    1. The Committee shall decide in cases of doubt the eligibility for election or membership in the electorate.

    1. The Committee shall conduct all referenda to amend the Constitution.

:::

### 3.6  Committee on Constitution and Bylaws {#committee-on-constitution-and-bylaws .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (10):

    1. Ex officio (voting): Secretary of the Senate, Professor Emeritus Senator.

        Appointed (8): six faculty members, including at least one contingent faculty member, one non-MPP staff member, and one student appointed in accordance with procedures established by Associated Students. Members with previous or current senate experience are preferred. At least two of the appointed members shall be senators.

1. The parliamentarian, while not a member of the committee, shall be invited to the meeting in an advisory capacity.

1. Functions

    1. The Committee shall review periodically the Constitution and Bylaws of the Senate and university policies, and it shall recommend to the Senate such changes as desirable. It shall report to the Senate its recommendations with respect to proposed amendments to the Constitution or Bylaws that have been submitted in writing, signed by the originator(s), and referred to the Committee by the Senate or by the Senate Executive Committee.

    1. Questions concerning interpretations of the text of a Senate-approved document shall be referred to the Committee.

    1. Interpretations by the Committee shall be reported in writing to the Senate and shall be considered binding unless reversed or altered by action of the Senate.

    1. The Committee shall consider each year, as may be necessary, revision of the list of Senate and Senate-appointed university committees and of the membership and functions of each committee. It shall present its recommendations to the Senate in the first Senate meeting held after April 1.

:::

### 3.7 Undergraduate Curriculum Committee {#undergraduate-curriculum-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (13): Provost and Senior Vice President or designee, Associate Vice President for Curriculum, Assessment and Accreditation or designee, one representative from each college, the Library, and SDSU Imperial Valley selected by the Committee on Committees and Elections, and two students named in accordance with procedures approved by the Associated Students.

1. Functions

    1. The Committee shall review all undergraduate curricula proposals to include additions, deletions, and changes in curricula, with special consideration to items of an interdepartmental or university-wide interest. The Committee shall report all changes to the Senate.

    1. Undergraduate curriculum proposals reviewed by the deans, and by the Undergraduate Council when appropriate, shall be forwarded by the Office of the Provost to the Committee.

    1. Except for approval of the use of courses in the graduate program, approval by the Committee shall be the final step required for including an undergraduate curriculum proposal in the General Catalog. Proposals for new programs and deletion of programs shall be forwarded to the Senate as action items. At the request of four members of the Committee, a proposal shall be placed on the Senate agenda for final action.

    1. A person, department, dean, or college curriculum committee may request the Committee to review a decision on a curriculum proposal. The Committee may agree to review the matter and inform all interested parties of the decision to review and of the date set for the review, or the Committee may decide not to review and promptly inform the appellant of its decision.

:::

### 3.8  Committee on Diversity, Equity, and Inclusion {#committee-on-diversity-equity-and-inclusion .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (23):

    1. Ex officio (11): Chair of the Senate, or designee; Provost and Senior Vice President, or designee; Vice President for Student Affairs and Campus Diversity (Chief Diversity Officer), or designee; Senior Associate Vice President for Campus Diversity, or designee; Associate Vice President for Faculty Advancement and Student Success, or designee; Associate Vice President for Enrollment, or designee; Director/Title IX Coordinator - Center for Prevention of Harassment and Discrimination, or designee; Tribal Liaison, or designee; Associate Chief Diversity Officer for HSI and Regional Affairs; Director of the Center for Human Resources, or designee; and the Director of Student Ability Success Center, or designee.

    1. Appointed (12): nine faculty members, one of whom shall chair, including one from each college, the Library, and SDSU Imperial Valley, at least one of whom shall be a Senator nominated by the Committee for Committees and Elections (CCE) and appointed by the Senate; one staff member selected by the Staff Affairs Committee in consultation with the staff senators and confirmed by the Senate; and two students, including a representative from the Associated Students appointed in accordance with procedures established by the Associated Students.

    1. Appointed faculty members shall serve three-year, staggered terms.

    1. Membership on the committee shall include representation from diverse campus groups.

    1. The chair of the Committee, in consultation with the President, may request the service and advice of educational and community leaders.

1. Reporting: The Committee shall report to the Senate and advise the President.

1. Functions

    1. The Committee shall review university-wide programs for the recruitment and retention of faculty, staff, and students.

    1. Subject to the approval of the President, the Committee shall advise the university administration regarding prohibited discrimination, equal opportunity, outreach, and related matters.

    1. Additional duties of the Committee shall be: (a) to advise the President regarding the university’s conformity or potential lack thereof with California State University policies and with legislation on nondiscrimination and equal opportunity in admissions and employment, (b) to recommend policies and procedures to recruit students for matriculation and to retain students for graduation, (c) to work with Enrollment Services, diverse student organizations, and interested community persons and groups to coordinate activities to enhance the recruitment of diverse students, (d) to review and assist in coordination of programs for advising and mentoring diverse students, (e) to assist departments in reviewing and modifying their curricula in order to incorporate multicultural materials, (f) to promote faculty and staff involvement in addressing the educational needs of diverse students, (g) to disseminate information concerning funding for equity programs within the university, (h) to advise the Office of Employee Relations and Compliance and the Chief Diversity Officer regarding policies, procedures, and outcomes of the university’s diversity programs.

:::

### 3.9  Graduate Council {#graduate-council .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Representing the interests of the university in graduate studies, the Graduate Council shall be responsible to the university administration, the Dean of the College of Graduate Studies, the Senate, academic units, faculty members, and students. The university-wide jurisdiction of the Council shall derive from the President, the Senate, and the faculty.

1. Membership (30): Voting members include fifteen tenured and probationary faculty, two from each of the seven academic colleges and one from SDSU Imperial Valley; Dean of the College of Graduate Studies or designee, who shall chair; Provost and Senior Vice President for Academic Affairs, Dean of the Library (or designee), and two classified graduate students in good standing. Non-voting members include Associate and Assistant Deans of the College of Graduate Studies; Vice President for Research and Innovation; Director of Graduate Life and Diversity; two Enrollment Services representatives (Graduate Admissions Lead and Associate Director); and four additional representatives from the College of Graduate Studies, appointed by the Dean of the College of Graduate Studies.

    1. Faculty members shall be active in graduate programs of their colleges and schools or departments. They shall serve staggered three-year terms and may immediately succeed themselves for one term. Nominations shall originate in colleges, and the Committee on Committees and Elections shall consult with the Dean of the College of Graduate Studies before recommending nominees to the Senate.

    1. Student members shall be appointed for a one-year term (renewable for one year) by the Associated Students in consultation with the Dean of the College of Graduate Studies. The Dean of the College of Graduate Studies shall submit nominations from graduate advisers to the Associated Students, who shall appoint two graduate students (one to represent a doctoral program and one to represent a master’s program).

1. Functions. The Council shall be responsible for the development of policy on (a) graduate programs, (b) graduate student affairs, (c) graduate research and scholarship, and (d) faculty participation in graduate programs. Duties also include the review and approval of new and modified graduate courses and graduate program proposals.

    1. Graduate Programs

        1. The Council shall encourage colleges, schools, and departments to develop criteria and procedures to ensure the quality of their programs and to provide guidance and oversight in developing new programs.

        1. The Council shall review these criteria and procedures, approve new graduate programs, review and approve new graduate curricula and changes in existing curricula, and review existing graduate programs.

        1. Both the Council and the Undergraduate Curriculum Committee shall review courses that will become available to both undergraduate and graduate programs.

        1. The Council shall distribute its minutes concerning curricula and programs simultaneously to members of the Senate and the Council.

        1. The Council shall follow the procedures as outlined in the “University Policies” section titled “Curriculum Changes, Undergraduate, and Graduate.”

    1. Graduate Student Affairs

        1. The Council shall recommend university-wide academic policies and standards for the admission and retention of graduate students and for assistantship, scholarship, and fellowship programs.

        1. The Council shall develop policy to assist schools and departments in ensuring an equitable resolution of differences and issues that may arise between graduate students and the faculty.

        1. The Council shall ensure opportunities for participation by graduate students in the development of policy concerning graduate student issues by providing for such membership on its pertinent standing committees.

    1. Faculty: The Council shall encourage departments, schools, and programs to develop criteria and standards for participation in their graduate programs. It shall ensure that department, school, and program standards accord with university policy.

    1. Policy Management:

        1. The Chair shall develop agenda items and coordinate the activities of the Council.

        1. The Council shall consult with all relevant stakeholders (e.g. students, faculty, administration, college deans, school directors and department chairs) before bringing policy to the Senate.

        1. The Council shall route all new policy and policy changes through the Senate for approval.

        1. The Council shall ensure that all stakeholders are informed of policy changes in a timely manner and publish policies online in collaboration with the College of Graduate Studies, Curriculum Services, the University Senate and others as appropriate.

:::

### 3.10  Undergraduate Council {#undergraduate-council .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (17): nine faculty, including one from each academic college, the Library and SDSU Imperial Valley; Associate Vice President for Faculty Advancement and Student Success or designee, who shall chair; Associate Dean (FASS); Assistant Dean of Undergraduate Studies (FASS); Assistant Dean of Student Success (FASS); Vice President of Student Affairs and Campus Diversity, or designee; Associate Vice President for Enrollment; and two undergraduate students.

1. Functions: The Council shall:

    1. Oversee an integrated approach to undergraduate excellence at San Diego State University,

    1. Recommend policy for the Office of Faculty Advancement and Student Success,

    1. Propose changes in policy for undergraduate programs

    1. Forward to the Senate the annual report on retention and graduation in the fall of each academic year.

    1. Supervise specific university-wide undergraduate programs such as, but not limited to, the General Education Curriculum Committee and the Graduation and Retention Subcommittee.

1. Subcommittees of Undergraduate Council:

    1. The Graduation and Retention Subcommittee

        1. The Graduation and Retention Subcommittee shall be a permanent subcommittee of the Undergraduate Council.

        1. Membership (22)**:** all members of the Undergraduate Council; the Associate Vice President for Student Life and Dean of Students or designee; the Assistant Vice President of Analytic Studies and Institutional Research or designee; the Director of Institutional Research or designee; the Director of Testing, Assessment, and Research; and two additional, at-large faculty members appointed by the Senate.

        1. Functions: The Subcommittee

            1. Shall oversee a systematic approach to the retention and timely graduation of undergraduates;

            1. Shall recommend to the Undergraduate Council policy changes that promote the timely progress of undergraduate students to graduation;

            1. Shall produce an annual report on retention and graduation during the fall semester.

    1. Special Topics Subcommittee

        1. The Special Topics Subcommittee shall be a permanent subcommittee of the Undergraduate Curriculum Committee.

        1. Membership (5): three faculty who are members of the Undergraduate Curriculum Committee, one of whom shall chair; the Associate Vice President for Curriculum, Assessment and Accreditation and the Associate Vice President for Enrollment or designee.

        1. Function

            1. The Subcommittee shall review course proposals identified as 296, 496, 580, and 596, and General Studies 250, 350, and 550. Courses numbered 550, 580, and 596 shall be forwarded to the Graduate Council for an additional review. Although the Subcommittee may apply different criteria to these, it shall retain the same standards of regular courses.

            1. The Subcommittee shall encourage experimental and interdisciplinary courses.

:::

### 3.11  Lecturer Affairs Committee {#lecturer-affairs-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (13-20):

    1. Ex Officio (13): All Contingent Faculty serving on the SDSU University Senate, including the elected ASCSU Lecturer representative.

    1. Appointed (0-7): Up to seven additional at-large Contingent Faculty members from across the university, including Librarian and Student Services Professionals - Academic Related (SSP-AR) faculty members.

    1. Members must have a minimum one-year appointment, or have a reasonable expectation that they will be appointed to work during both the fall and spring semesters.

    1. Terms for all members shall be three year renewable terms.

    1. Quorum requires the presence of at least seven (7) members.

    1. No college or unit may have more than 25% of members on the committee at any one time.

    1. A chair shall be elected by members in March of each year to serve for the next academic year.

1. Functions. The committee shall:

    1. Serve as the nominating authority for Contingent Faculty seats to the Senate, Senate Core Committees, Senate Committees, Senate-affiliated Campus Committees, and any other Senate-related appointments designated specifically for Contingent Faculty. Vacancies will be filled in accordance with the policies outlined in the Senate policy file, under Bylaws, section 6.0: Vacancies.

    1. Meet a minimum of four times per semester to identify, discuss and organize around campus issues that impact the Contingent Faculty constituency.

    1. Develop new policy or make recommendations for revisions to existing policy related to Contingent Faculty affairs.

    1. Advocate for the inclusion of the Contingent Faculty constituency as part of the decision making and governance on campus, including identifying and recommending Contingent Faculty for placement on senate and other campus committees.

    1. Organize the Senate caucus for Contingent Faculty senators.

    1. Engage regularly with the Contingent Faculty constituency.

    1. Perform other functions that may be required in service of the Contingent Faculty constituency.

    1. Known topics that impact the Contingent Faculty constituency include, but are not limited to:

        - Service and work completed outside of the scope of contracted teaching. Inclusion in department meetings, collaborations, and decision-making processes.

        - Training.

        - Contingent Faculty planning and hiring at the university and departmental levels.

        - Collecting Contingent Faculty feedback (e.g. surveys) for collaborative decision making, etc.

        - Perform a periodic assessment of Contingent Faculty seats on Senate committees to ensure Contingent Faculty interests are represented on key groups and regarding key issues.

        - Make recommendations to the Committee on Committees and Elections (CCE) and/or Senate leadership regarding Contingent Faculty participation on Senate committees.

1. The Chair (or designee) shall report the business of the committee to the Senate.

:::

### 3.12 Staff Affairs Committee {#staff-affairs-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership sixteen (16): Fourteen (14) open seats for permanent Non–Management Personnel Plan (non-MPP) staff from across the institution, one (1) open seat for an auxiliary organization Staff Senator as defined in Bylaws 1.0, and one (1) non-voting ex officio staff emeritus appointed by SDSU Retirement Association.

    1. The quorum for meetings shall be a simple majority of filled positions.

    1. At least four (4) members of the committee shall be current Staff Senators.

    1. Membership shall serve staggered three-year terms and may immediately succeed themselves for one term. Nominations shall originate as open calls to all permanent non-MPP staff.

    1. A chair shall be elected by members in March each year to serve for the next academic year. When possible, the chair shall be a current or former Senator. The chair may be re-elected for a total of three consecutive terms.

    1. The chair (or designee) shall serve as ex officio voting member of the Senate Executive Committee and report committee business to the Senate Executive Committee and the University Senate.

    1. Staff representatives on Senate Core Committees, Senate Committees, Senate-affiliated Campus Committees and staff senators are invited to present relevant committee information at the Staff Affairs Committee.

1. Function: The committee shall:

    1. Be the nominating authority for staff representation on committees. As such, the committee will nominate staff to fill vacancies to Senate Core Committees, Senate Committees, and Senate-affiliated Campus Committees by campuswide announcement for nominations and simple majority vote of the committee.

    1. Meet regularly during the academic year to identify, discuss, and organize around university issues that impact the staff constituency.

    1. Develop new policy or make recommendations for revisions to existing policy-related to staff affairs.

    1. Engage regularly with the staff constituency and advocate for the inclusion of the staff constituency as part of the decision-making and shared governance on campus.

    1. Organize the Senate caucus for staff senators.

    1. Nominate emeritus staff to the Senate Executive Committee and the University Senate in accordance with the University Policies: Emeritus Employees.

1. Elect staff seats on ad hoc committees.

    1. Search Committees: The Staff Affairs Committee shall coordinate filling any search committee vacancy with the Senate Committee on Committees and Elections. The announcement shall explain the duties of the Search Committee and ask for nominations for each vacancy. All permanent non-MPP staff employees within the unit or division (e.g., individual colleges, Academic Affairs, Business and Financial Affairs, Research and Innovation, Information Technology, Student Affairs and Campus Diversity, University Relations and Development, etc.) in which the search is conducted shall be eligible to serve; only non-MPP staff from within the unit or division shall be eligible to nominate and vote. When nominating someone other than oneself, agreement to serve must be obtained from the nominee prior to the nomination. Each nomination shall include contact information, department, and position name, and a statement of qualifications and interest. The nomination period shall be at least five (5) business days. Once nominations are closed, a second voting announcement shall be made with the list of nominees (including their statements). Voting shall be open for five (5) business days. Selection shall be determined by the plurality of received votes.

    1. Administrator Review Panels: The Staff Affairs Committee shall coordinate filling any Search committee vacancy with the Senate Committee on Committees and Elections. The announcement shall explain the duties of the Administrator Review Panel and ask for nominations for each vacancy. All permanent non-MPP staff employees within the unit or division (e.g., individual colleges, Academic Affairs, Business and Financial Affairs, Research and Innovation, Information Technology, Student Affairs and Campus Diversity, University Relations and Development, etc.) in which the search is conducted shall be eligible to serve; only non-MPP staff from within the unit or division shall be eligible to nominate and vote. When nominating someone other than oneself, agreement to serve must be obtained from the nominee prior to the nomination. Each nomination shall include contact information, department and position name, and a statement of qualifications and interest. The nomination period shall be at least five (5) business days. Once nominations are closed, a second voting announcement shall be made with the list of nominees (including their statements). Voting shall be open for five (5) business days. Selection shall be determined by the plurality of received votes.

    1. Auxiliary Review Panels: The Staff Affairs Committee shall coordinate filling any review panel vacancy with the Senate Committee on Committees and Elections. The announcement shall explain the duties of the Auxiliary Review Panel and ask for nominations for each vacancy. All permanent non-MPP staff employees within the unit or division (e.g., individual colleges, Academic Affairs, Business and Financial Affairs, Research and Innovation, Information Technology, Student Affairs and Campus Diversity, University Relations and Development, etc.) in which the search is conducted shall be eligible to serve; only non-MPP staff from within the unit or division shall be eligible to nominate and vote. When nominating someone other than oneself, agreement to serve must be obtained from the nominee prior to the nomination. Each nomination shall include contact information, department and position name, and a statement of qualifications and interest. The nomination period shall be at least five (5) business days. Once nominations are closed, a second voting announcement shall be made with the list of nominees (including their statements). Voting shall be open for five (5) business days. Selection shall be determined by the plurality of received votes.

    1. Subcommittees {subcommittees .policy-toc-heading}

        1. Staff Honors and Awards Subcommittee

            1. Membership twelve (12): eight (8) permanent staff members selected from bargaining units 1, 2, 4, 5, 6, 7, 8, 9, and one (1) confidential staff; one student selected by Associated Students, one (1) Administrator I or II (staff MPP classification), and one (1) Auxiliary organization staff as defined in Bylaws 1.0. In the event that the subcommittee cannot meet these requirements the subcommittee chair may fill vacancies as best as possible. The subcommittee chair shall be a member of the Staff Affairs Committee. The remaining staff members shall be from as many areas of campus (including Imperial Valley) as possible.

            1. The subcommittee chair shall be identified during the fall semester from among existing Staff Affairs Committee members by majority vote.

            1. Membership shall be a one-time term from December through August when the awards are announced. Members may be re-elected for a total of three consecutive terms.

            1. The Staff Affairs Committee shall coordinate filling the subcommittee with the Senate Committee on Committees and Elections. The announcement shall explain the duties of the Staff Honors and Awards Subcommittee and ask for nominations for each vacancy outside of the subcommittee chair (e.g., if the chair is in unit 7 then the announcement will go out to the other membership groups in 3.12.4.1.1.). All permanent non-MPP staff employees, the Administrator I or II, and the Auxiliary staff in which the search is conducted shall be eligible to serve; only the eligible nominee pool shall be eligible to nominate and vote. When nominating someone other than oneself, agreement to serve must be obtained from the nominee prior to the nomination. Each nomination shall include contact information, department, and position name, and a statement of qualifications and interest. The nomination period shall be at least five (5) business days. Once nominations are closed, a second voting announcement shall be made with the list of nominees (including their statements). Voting shall be open for five (5) business days. Selection shall be determined by the plurality of received votes.

            1. Functions: The committee shall provide recommendations to the University President regarding the Staff Excellence Awards program as defined in University Policies: Staff Awards 1.0.

:::

### 3.13  Sustainability Committee {#sustainability-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Background/Purpose: Sustainability refers to practices designed to meet the needs of the present without compromising the ability of future generations to meet their own needs. It encompasses teaching, research, and practice in a variety of areas including but not limited to policy development, building design and construction, waste management and recycling, energy production and use, water use, and transportation.

1. Membership (21**):** ten faculty members, including one from each academic college, the SDSU Library, SDSU Imperial Valley and one contingent faculty member; one staff member; Vice President for Student Affairs and Campus Diversity, or designee; Associate Vice President for Curriculum, Assessment and Accreditation, or designee; Director of Energy and Sustainability, or designee; Associate Vice President for Real Estate, Planning and Development, or designee; Associate Vice President for Business Operations, or designee; SDSU Research Foundation Director of Facilities, or designee; KPBS General Manager, or designee; CEO of Aztec Shops, or designee; two students.

1. Functions. The Committee shall:

    1. Study, track and review sustainability issues related to the campus and make recommendations to improve sustainable practices.

    1. Coordinate with campus units and the community to ensure that sustainability is taken into consideration.

    1. Communicate with the Committee on Environment and Safety and the Campus Development Committee to ensure that sustainability is taken into consideration in the deliberations of those bodies.

    1. Receive copies of Executive Orders or other instructions to the campus dealing with sustainability and report on them to the Senate.

    1. Serve as a resource to faculty, staff and students wishing to undertake research, or propose curricular changes, or pursue sustainable practices.

    1. Communicate these activities and outcomes to the Senate, campus, and the broader community.

:::

[^fn1]: CAL, SCI, and PSFA have historically held the largest FTEF and are thus accorded an additional member to assist with committee staffing. This is consistent with the CSU Academic Senate, which allots two senators to each campus, and three senators to the largest of the campuses.


