---
title: "Committees"
description: "The policies and procedures for the committees of the University Senate."
toc: false
---

::: {.policy-numbering .policy-start-2}

2. Committees

    1. Types of Committees

        1. Senate Committee. A Senate Committee has certain functions to perform that are essential or useful for shared governance.

        1. Senate Core Committee. Senate Core Committees are deemed to be critical to shared governance within the university. The work of Senate Core committees helps to form, shape, and direct most of the policies, recommendations, and resolutions emanating from the Senate. The chairs of Senate Core Committees shall serve as members of the Senate Executive Committee. MPP-classified members on any Senate Core Committee cannot exceed 25% of the total listed membership of the committee. Senate Core Committee charters are maintained in the bylaws.

        1. Senate Executive Committee. The Senate Executive Committee comprises the chairs of all the Senate Core Committees, as well as additional elected and ex officio members. The role of the committee board is to manage and organize the work of the Senate. It can also act on behalf of the Senate if needed. The Senate Executive Committee charter is maintained in the bylaws.

        1. Senate-affiliated Campus Committee. A Senate-affiliated Campus committee is a non-Senate committee with Senate representation. It is established by and reports to a non-Senate office. The Senate, and the Senate policies governing election and appointment of members, are involved in appointing a subset of members and its charter is included in the Senate policy file. A Senate-affiliated Campus Committee must have a charter that is approved by the Senate.

        1. Senate Ad Hoc Committee. A Senate Ad Hoc Committee is established by a majority vote in the Senate. An Ad Hoc Committee performs a specific task and is dissolved when the task is completed and the final report is given, typically within the same academic year.

    1. Subcommittees and Working Groups

        1. A subcommittee or working group is established to help with the charge of the committee outside regular committee meetings.

            1. If a Senate Committee establishes a subcommittee, this shall be documented in the committee’s charter, which shall be amended to describe the membership and function of it.

            1. If a Senate Committee forms a working group to complete a specific task, it shall be dissolved when the task is completed.

        1. Subcommittees and working groups report to the parent committee, unless otherwise specified in the subcommittee charter.

        1. Subcommittees and working groups may include nonmembers, however, at least one of its members shall be a member of the parent committee.

    1. Committee Charters

        1. All Senate and Senate-affiliated Campus Committees must establish and maintain a committee charter.

            1. Senate Committee charters, as well as any subsequent revisions of these charters, shall be approved by the Senate.

            1. Senate-affiliated Campus committees must have a charter, as well as any subsequent revisions, approved by the Senate.

            1. It is the responsibility of the respective Committee Chairs to ensure their committee’s charter in the University Senate Policy File is accurate.

        1. A committee charter shall outline the following:

            - Background: provides context as to the original purpose of the committee (e.g., required for accreditation).

            - Membership: a list of all appointed, elected, and ex officio members. All members shall be considered voting members unless otherwise specified. The membership section of the charter may include specific term lengths or limits on consecutive terms, if applicable.

            - Senate Committees shall have a minimum of at least three (3) members.

            - Senate Committees shall have at least two (2) appointed senators.

            - Quorum: define how quorum will work for the committee.

            - Subcommittees (if applicable): a charter, including membership rosters and a function for the subcommittee.

        1. Committee charters shall be maintained in the University Senate Policy File.

            1. Charters for Senate Core Committees, and the Senate Executive Committee, shall be maintained in the Bylaws of the University Senate Policy File.

            1. Charters for regular Senate Committees shall be maintained in the “UNIVERSITY POLICIES: Committees – Regular Senate Committees and Councils” section of the University Senate Policy File.

            1. Charters for Senate-affiliated Campus Committees shall be maintained in the “UNIVERSITY POLICIES: Committees – Campus Committees with Senate-Appointed Members” section of the University Senate Policy File.

    1. Appointments

        1. Unless otherwise stipulated, authorities for nomination to Senate and Senate Ad-Hoc Committees, as well as Senate-appointed members of Senate-affiliated Campus Committees, shall be as follows: (a) faculty by the Senate Committee on Committees and Elections, (b) administrators by the university administration, (c) staff by the Staff Affairs Committee, and (d) students by the Associated Students, who shall verify that nominated students are in good academic standing.

        1. The Senate shall approve all nominees

            1. The Senate Committee on Committees and Elections shall see that committees reflect overall an unbiased and reasonable representation of the faculty.

            1. If the Committee on Committees and Elections is unable to fill verified vacancies for a committee, the Senate Chair shall have the authority to organize and present nominations for the committee and present them as an action item to the Senate. The Senate Chair shall make reasonable attempts to consult with the nominating authority.

        1. All elected senators listed in Constitution 4.0 shall serve on a Senate or Senate appointed university committee.

        1. In filling vacancies, the Committee on Committees and Elections shall observe the following rules:

            1. Senator committee appointments shall take priority over appointments of non-Senators.

            1. Committee members are not required to be senators.

            1. Faculty in the Faculty Early Retirement Program (FERP) may only occupy designated "faculty" seats during active employment.

        1. No member can occupy two seats on the same committee at the same time, including substitutes.

    1. Times of Nomination and Appointment.

        1. The Committee on Committees and Elections shall be constituted for the upcoming academic year at the final regularly scheduled Senate meeting of the previous academic year. The committee shall have presented a full slate of nominees to Senate and Senate-appointed committees by the last Senate meeting of each academic year.

            1. All terms of office begin June 1, or at the time of appointment, and conclude May 31 in the final year of the term.

    1. Referrals

        1. Items shall be referred to committees by the Senate Chair, in consultation with the other Senate officers, by the Executive Committee, or by the Senate. An item referred to a committee by the Executive Committee shall be referred to another committee only through the Executive Committee.

        1. Items shall be referred to existing committees whenever possible.

        1. The Senate Chair’s additional communications to committees regarding referred items shall be reported at the next Executive Committee meeting.

        1. A committee may use subcommittees or may invite non-voting members to participate in its work.

    1. Records and Reports

        1. Each committee chair shall transmit records and pertinent information to the incoming chair.

        1. Each Senate and Senate-appointed committees shall submit a summary report of its activities annually by May 1.

    1. Committee Operation

        1. Rules: Senate rules shall apply to the operation of Senate or Senate appointed university committees. Exceptions to these rules may be noted in sec. 25 of Robert’s Rules of Order Newly Revised. Specific stipulations for a given committee regarding authority, tenure, duration, scope, and objectives shall be available in the Senate office.

        1. Committee Chairs

            1. Election: Unless otherwise specified, committees shall elect a chair annually by April 1 for the upcoming academic year. The current chair will oversee the election. The voting members of the committee shall elect the chair. The Chair of the Committee on Committees and Elections and the Secretary of the Senate shall be notified and included in the committee's annual report, or when any change in committee leadership occurs.

            1. An ex-officio member shall not be named chair unless otherwise specified by the committee’s charter.

            1. If no member of the committee is willing to serve as chair, the Chair of the Committee on Committees and Elections or the Chair of the Senate may appoint a new chair. This appointment may result in a member being replaced by a chair from outside the committee.

            1. A chair can be vacated by a majority vote of the entire voting membership of the committee.

            1. When the chair is vacated before the expiration of a term, the remaining committee members elect a new chair.

        1. Meetings and Quorum: Meetings shall be called by the chair, who shall preside over the meeting. Should the chair fail or decline to call meetings with sufficient frequency to accomplish committee objectives, two members may call a meeting, provided that all members including the chair are given at least three working days' notice. A majority of the members shall constitute a quorum of a committee.

        1. Hearings and Deliberations: A committee should, where time permits, hear all testimony relevant to its assignment. All meetings shall be open to the university community unless called into executive session by the chair for purposes in concert with current statutory requirements for open meetings. The chair’s decision to call an executive session shall be subject to challenge and may be overruled by a majority of the committee members present.

        1. Record of Proceedings: The chair of the committee shall keep records of all actions of the committee or shall ensure that they be kept by a committee secretary. The agenda for each committee meeting should be made available in the Senate office at least three working days in advance of the meeting. Persons wishing to be heard on an item should notify the chair of the committee.

        1. Reporting: All Senate and Senate-appointed committees shall report to the Senate. Committees that do not report directly to the Senate may be invited to the Senate to discuss or clarify their activities. The type of report will depend on the status of the committee or body and the nature of its task.

            1. If the report contains information only, no action by the Senate is required, but may be moved to the floor for action by a majority vote.

            1. If the report contains statements of policy or opinion, these should be stated at the end of the report, and the proper motion is to accept the report. If accepted, the policies or opinions shall become those of the Senate.

            1. If the report contains resolutions or recommendations wherein the Senate has power to act, these should be stated at the end of the report, and the proper motion is to adopt the report. If adopted, the resolutions or recommendations shall become policy pending approval or lack of denial by the President of the university.

        1. Dissolution: Senate committees shall be dissolved by amending the Bylaws. Senate-approved university committees shall be dissolved by Senate action. Ad hoc or pro tempore committees shall be dissolved when they rise and report or at the end of the academic year in which they were appointed, whichever comes first, unless specifically extended by action of the Senate Chair, in consultation with the other Senate officers.

        1. Terms of Service on Senate and Senate-Appointed University Committees

            1. Unless otherwise specified, committee members shall serve three-year terms. A committee member may be reappointed. During a committee’s initial three years, or as needed to ensure term staggering that is healthy for the continuity of the committee, the Committee on Committees and Elections shall specify members with one-, two-, and three-year seats.

            1. Removal: The Committee on Committees and Elections may recommend the removal of a committee member. Accordingly, the committee member shall be told of the reasons for the proposed removal and shall be given at least two weeks in which to respond. If the Committee on Committees and Elections then determines that removal of the member is in the best interests of the affected committee and of the Senate, it shall recommend to the Senate the name of a replacement member. Appointment of the new nominee by the Senate shall constitute removal of the previous member.

            1. Leave: As soon as a committee member is certain of being granted leave from duties at the university, that member shall in writing, so inform the chair of that committee, who in turn shall immediately inform the Secretary of the Senate and the Chair of the Committee on Committees and Elections. If the leave is one semester, the Committee on Committees and Elections, in consultation with the committee chair, shall recommend to the Senate a temporary replacement. If the leave is longer than one semester, the Committee on Committees and Elections shall recommend to the Senate a permanent replacement selected according to normal criteria and procedure.

:::
