---
title: "7. Meetings"
description: "The policies and procedures for meetings of the University Senate."
toc: false
---

::: {.policy-numbering .policy-start-1}
1. Meetings of the Senate

    1. The Senate shall serve and meet as necessary during the summer.

    1. The dates and time of the regular meetings of the Senate shall be set by the Senate far enough in advance to facilitate members’ scheduling of classes.

    1. Special meetings of the Senate shall be called by the Chair either at the Chair’s discretion or upon receiving a written petition of 10 percent of the Senate membership or of 10 percent of the electorate.

    1. Written notice of each special meeting and its agenda shall be distributed to the members of the Senate by the Secretary at least three days before the meeting unless the Chair or Vice Chair, with the concurrence of a majority of the Executive Committee, decides that the urgency of the occasion will not permit the usual three day notice. In a meeting called under this provision, notice shall be given as far in advance as possible, and action shall require an absolute majority of the membership of the Senate.

    1. The meetings shall be open to all, but only members of the Senate shall participate in the debate. Others may provide information or explain a point of view on matters before the Senate by invitation of the Chair, or the Senate.

    1. A faculty session of the Senate shall comprise only Tenured and Probationary Faculty senators, as defined by the Constitution. Its function shall be to express the collective voice of the faculty. It may make determinations regarding any issue. Any member of the university community may attend a faculty session; however, only Tenured and Probationary Faculty senators may speak and vote.

        1. A faculty session shall be convened upon a majority vote of the sitting Senate or by a majority vote of the Senate Executive Committee.

        1. A faculty session shall be terminated by a two-thirds majority vote of the convened session or by an advance stipulation.

        1. When the faculty session has concluded its business or when the session has been terminated by advance stipulation, its actions shall be reported to the full Senate. The Secretary of the Senate shall include all actions of the faculty session in the minutes of the Senate.

1. Meetings of the Faculty

    1. For a meeting of the faculty, those eligible to participate shall be defined as persons who hold a permanent, multiple year, or temporary appointment and are members of Unit 3 as defined in the current Collective Bargaining Agreement. For the purposes of this section, temporary appointees of Unit 3 shall become members of the general faculty on their dates of appointment.

    1. The quorum for faculty meetings shall be a simple majority, that is, 50 percent plus one of the faculty.

    1. Meetings of the faculty may be called under these conditions: (a) upon the call of the President of the university, at which time the President shall preside; (b) upon the call of the Senate, at which time the Senate Chair shall preside; and (c) upon the call of the Senate Chair, for review of an action of the Senate.

    1. The Senate Chair or Vice Chair shall obtain the consent of a majority of the members of the Senate Executive Committee prior to establishing the agenda for a meeting of the faculty that is called by the Senate or by the Senate Chair.

1. The conduct, frequency, and agendas of Senate committees shall be determined by those committees.

1. Senate business shall have priority over class scheduling. Senators’ class schedules shall permit their attendance at Senate meetings from 2:00 to 5:30 PM on Tuesdays and Thursdays.

:::
