---
title: "8. Order of Business"
description: "The policies and procedures for the order of business of the University Senate."
toc: false
---

::: {.policy-numbering .policy-start-1}
1.  The regular order of business of the Senate shall be the agenda prepared by the Senate Executive Committee.

2.	Any member of the Senate may present to the Secretary of the Senate items for the agenda. Resolutions, if not forwarded by a committee, have to be endorsed by at least 5 voting senators (endorsees to be listed at the end of the text). The Secretary shall deliver all such items to the Executive Committee, which shall place them on the agenda for the next regular Senate meeting or refer them to a specific committee. Disposition of such items shall be indicated in the minutes of the Senate Executive Committee.

3.	The	senate agenda as approved by the Senate Executive Committee shall be made available in writing no later than four working days before a University Senate meeting. 

4.	Any	senator may bring an information item on the approved agenda of the University Senate to the floor for debate. To move it to action a simple majority vote is needed.

5.	Any	member of the Senate may present an action item on the senate floor. A  two-thirds majority vote is needed to place it on the agenda.

:::
