---
title: "Presidential Approval of Senate Actions"
description: "The policies and procedures for presidential approval of Senate actions."
toc: false
---

::: {.policy-numbering .policy-start-11}

11. Presidential Approval of Senate Actions

    1.  Draft minutes of Senate meetings where any official Senate action is taken shall be delivered to the President within fourteen (14) calendar days of the conclusion of the Senate meeting. 

    2.	Within thirty (30) calendar days of receiving the Senate Minutes, the President shall respond in writing to indicate approval, rejection, or postpone a decision on an action item. This written response is referred to as a Presidential Action Memo. 

        1.	If any action item is postponed, the President shall include a rationale for postponement. The President shall have until the first Senate Executive Committee meeting of the next academic year to either approve or reject postponed items. 
        
        2.	If any action item is rejected, the President shall include a rationale. 
        
        3.	If an action item passed by the Senate is not approved by the President, and hence does not become policy, the Senate Chair, or designee, shall notify the Senate.
        
        4.	Approved actions shall be implemented as soon as is practical, which may precede their appearance in the university policy file.
        
        5.	Senate Resolutions do not require approval or rejection of the President. The President shall note receipt of a Senate resolution, and may choose to indicate what, if any, follow-up steps they plan to make based on specific resolved clauses in the resolution. 
    
    3.	The Senate Chair, or their designee, shall forward a copy of the President’s Action-Memo to all Vice Presidents, Human Resources Director (for emeritus status processing), Vice Chair of the Senate (for referrals updates), Secretary of the Senate (for policy file updates), SEC members, Senate Chairs, as well as to any other person/department/unit whose work may be impacted by the Senate action. 
    
    4.  The Senate Chair, or designee, shall ensure that the President is informed promptly by suitable means of Senate actions that would require implementation in fewer than 30 days after Senate action, in order that such legislation not be unduly delayed.

:::
