---
title: "6. Vacancies"
description: "How vacancies are defined and addressed in the Bylaws."
toc: false
---

::: {.policy-numbering .policy-start-1}
1. Determination

    1. Vacancies for elected SDSU Senators, including ASCSU Academic Senators, occur when the member meets the criteria in Bylaws 4.0.

    1. Vacancies for SDSU Senate and Senate-appointed committee members occur when the member meets the criteria in Bylaws 2.0.

1. Replacement of Elected Senators

    1. CSU Academic Senators. The Committee on Committees and Elections shall hold an election as soon as is possible to elect a replacement for the duration of the absence or the end of the term as outlined under 4.0 of these Bylaws.

    1. All other elected SDSU Senators

        1. The temporary replacement shall be chosen from nominees receiving the next highest number of votes in the latest election for the constituency where the vacancy occurs. In the event of a tie number of votes, the Committee on Committees and Elections shall select the alternate filling the vacancy by lot.

        1. If there are no other nominees or the nominee is not interested in serving any longer, the chair of the Committee on Committees and Elections, in consultation with current senators from the impacted constituency, shall nominate the temporary replacement.

        1. In nominating replacements for Contingent Faculty, the Lecturer Affairs Committee shall be consulted. A preference for units without existing representation shall be applied.

        1. In nominating replacements for Staff Senators, the Staff Affairs Committee shall be consulted.

    1. If the vacating member’s term extends beyond the date an election will occur, the member appointed to that seat shall be considered a permanent replacement and shall complete the vacating member’s term before they are electable for their own term. Per Bylaws 4.0 , completion of a partial term as a replacement does not does not impact on the member’s eligibility to serve full terms of their own.

1. Replacement of Committee Members

    1. Replacements shall meet all eligibility requirements as set forth in the committee’s charter.

    1. To replace a Senator-at-large in the Senate Executive Committee an election will be hold as soon as a vacancy is reported.

    1. In all other cases, the Committee on Committees and Elections in collaboration with impacted committees and constituencies as appropriate, shall nominate a candidate.

        1. Contingent Faculty seats: The Lecturer Affairs Committee shall be consulted in identifying a replacement.

        1. Staff seats: The Staff Affairs Committee shall be consulted in identifying a replacement.

    1. Elected Senators without a committee assignment shall be prioritized in identifying a replacement.

    1. CCE shall present all nominated replacement committee members to the Senate for confirmation.

    1. If the member replaced was a committee chair the impacted committee shall elect a new chair per Bylaws 2.0.

    1. In instances where replacements are appointed to service on committees, Bylaws 4.0. shall apply. Completion of a partial term as a replacement does not impact the member’s eligibility to serve full terms of their own.

1. Replacement of Senate Officers

    1. Should the Chair be unable to serve the full term, the Vice Chair shall become the Chair and an election shall be held to choose a replacement Vice Chair.

    1. Should the Vice Chair, Secretary or Treasurer of the Senate be unable to serve the full term, an election shall be held to choose a replacement.

:::
