---
title: "Constitution"
description: "The Constitution of the San Diego State University Senate"
toc: true
toc-location: right
toc-depth: 3

format:
  html:
    body-classes: "policy-hybrid policy-start-1"
---

## Preamble {#preamble .unnumbered}

San Diego State University shall perform its educational mission guided by the principles of shared governance. Granted, therefore, that the Board of Trustees of The California State University invests responsibility for the operation of San Diego State University in the President of the university, the President shall be committed to formal consultation through shared governance: Accordingly, committees and councils shall advise the President either directly or through the University Senate, also called the Senate, a deliberative body that shall represent university faculty, administration, students, and staff.

## Purpose {#purpose .policy-heading}

The San Diego State University Senate shall be the university’s delegate assembly. Through this assembly the faculty in concert with the administration, staff, and students shall normally exercise its powers. The Senate shall have the power to act for the faculty on matters within the scope of the faculty when the action is approved by a majority vote of the members present after a quorum has been constituted.

## Duties {#duties .policy-heading}

1. The Senate shall consider policies with respect to the general welfare of the university. It shall review established policies, consider new policies, and study matters of concern to the students or faculty members.

2. It shall formulate educational policy, including admissions, curricula, and criteria for the granting of degrees. It shall analyze established and proposed policies of instruction and consider variations in policy in exceptional cases.

3. It shall advise the President in the selection of administrative personnel.

4. It shall maintain adequate communication within the university community. Any member of the university community may request a member of the Senate to transmit to the Senate for discussion and possible action topics coming under the jurisdiction of the Senate.

5. It shall appoint Senate and Senate-appointed university committees. It shall establish rules and procedures for Senate committees and shall establish procedures for the Senate.

6. The ultimate authority to recommend approval of candidates for graduation shall reside with the tenured and probationary faculty. Following formal advice of the tenured and probationary faculty, only the members of the Senate who are elected as tenured and probationary faculty shall vote in the matter of approving the list of candidates for graduation.

## Calendar {#calendar .policy-heading}

The Senate year shall begin on the day following the last day of the spring semester.

## Membership and Electorate {#membership-and-electorate .policy-heading}

1.  Elected Members 

    1.  Tenured and Probationary Faculty
        
        1.  The electorate shall consist of all tenured and probationary members of the faculty, as defined in Bylaws 1.0, representing each of the following constituencies: College of Arts and Letters, Fowler College of Business, College of Education, College of Engineering, College of Health and Human Services, College of Professional Studies and Fine Arts, College of Sciences, Imperial Valley Campus, Library, and Student Service Professionals-Academic Related (SSP-AR). 
        
        2.  Each of the constituencies outlined above shall elect the number of senators equivalent to nine percent (9%), rounded up to the nearest integer, of its tenured and probationary full time equivalent faculty positions. This method of apportionment shall always yield at least one elected senator for each constituency.
        
        3.  The term of office for Tenured and Probationary Faculty senators shall be three senate calendar years. A Tenured and Probationary Faculty senator shall serve no more than two consecutive complete terms. Service for a partial term and for terms served on the Academic Senate of The California State University (ASCSU) shall not be included in this calculation. So far as feasible, senate terms shall be arranged so that only one-third of the membership is elected annually in the spring.

    2.  Contingent Faculty (12).  There shall be twelve elected Contingent Faculty senators, including one Lecturer from each of the following nine academic colleges/units: College of Arts & Letters, College of Education, College of Engineering, College of Health & Human, College of Professional Studies and Fine Arts, College of Sciences, Faculty Advancement & Student Success, Fowler College of Business and Imperial Valley; and three additional Contingent Faculty from any classification.
        
        1.  No more than one shall be a contingent Student Services Professionals-Academic Related (SSP-AR) faculty and no more than one shall be an assistant librarian.
        
        2.  The electorate shall consist of all contingent faculty members as defined in Bylaws 1.0.  
        
        3.  The term of office for Contingent Faculty senators shall be three senate calendar years. A Contingent Faculty senator shall serve no more than two consecutive complete terms. Service for a partial term and for terms served on the Academic Senate of The California State University (ASCSU) shall not be included in this calculation. So far as feasible, senate terms shall be arranged so that only one-third of the membership is elected annually in the spring. 

    3.  Faculty elected to serve the Academic Senate of the California State University (ASCSU) (4). 
        
        1.  ASCSU Senators: Three (3) faculty as defined in Bylaws 1.0 shall be elected to serve in the ASCSU. Electorate shall be all faculty as defined in Bylaws 1.0. 
        
        2.  ASCSU Lecturer Electorate: One (1) Contingent Faculty shall be elected as ASCSU Lecturer representative and shall serve as a member of the Lecturer electorate for the ASCSU (one Contingent Faculty from each of the 23 campuses of the CSU). Electorate for this elected ASCSU Lecturer representative shall be all Contingent Faculty. 
        
        3.  Faculty serving as ACSU Senators or in the Lecturer Electorate shall have a minimum one-year appointment and faculty time base entitlement of at least 0.6. 
        
        4.  Delegates from this university to the ASCSU, whether as an ASCSU Senator or as a member of the ASCSU Lecturer Electorate, shall be considered elected members of the senate.  
        
        5.  The term of office for faculty elected to serve in the ASCSU is three years. If the SDSU ASCSU Lecturer representative is elected to be one of three ASCSU Lecturer Senators, at any time during their three-year term, their term within the SDSU Senate shall be revised to align with their term as a senator of the ASCSU. 

    4.  Staff. (8)
        
        1. There shall be six non–Management Personnel Plan (MPP) staff senators as defined in Bylaws 1.2.1. One position shall be reserved for an SDSU Imperial Valley staff member. Only permanent staff are eligible to serve. The electorate shall consist of permanent and temporary non-MPP staff, including probationary staff.
        
        2. There shall be two SDSU Auxiliary organization staff as defined in Bylaws 1.2.2.
    
    5.  Managers.  There shall be two Managers. Only those in classes 1 and 2 of the Management Personnel Plan (MPP) are eligible. The electorate shall consist of all those eligible to serve.

2.  Ex officio Members. The Senate may include ex officio, voting or non-voting, representatives as members. The ex officio members of the Senate shall be designated in the Bylaws.

3.  Vacancies.  Vacancies in Senate membership shall be filled in a manner prescribed by the Bylaws.

## Officers and Parliamentarian {#officers-and-parliamentarian .policy-heading}

1. The Chair of the Senate, who shall be the Chair of the Faculty, shall be an elected senator. The Chair shall be annually elected to office by the majority of the elected senators. The Chair shall preside at all meetings of the Senate and may call special meetings of the Senate.

2. The Vice Chair of the Senate shall be an elected senator. The Vice Chair shall be annually elected to office by the majority of the elected senators. The Vice Chair of the Senate shall preside as the Chair of  the Senate should the Chair be unable to fulfill the duties of the office.

3. The Secretary of the Senate shall be an elected senator. The Secretary shall be annually elected to office by the majority of the elected senators. The Secretary (a) shall prepare the agenda for all Senate meetings and notify all senators of these meetings; (b) shall keep roll and report in a manner prescribed by the Bylaws when, in accordance with Senate policy, a seat has become vacant through repeated absence; (c) shall maintain a complete record of Senate meetings and prepare summaries of Senate minutes; (d) shall supervise the distribution of copies of Senate resolutions and decisions to appropriate persons; (e) and shall annually compile and publish an index of Senate actions.

4. The Treasurer of the Senate shall be an elected senator. The Treasurer shall be annually elected to the office by the majority of the elected senators. The Treasurer (a) shall administer the Senate annual operating budget and oversee the financial affairs of the Senate, which includes drafting an annual budget for approval by the Senate Executive Committee and final proposed budget shall be presented to the Senate for approval by the end of the Spring semester; (b) report the state of the Senate budget at Senate and Senate Executive Committee meetings; and (c) shall act on the behalf of the Senate in meetings and serve on Senate committees that may require financial advice and oversight related to the Senate’s annual budget.

5. The Parliamentarian, who need not be a member of the Senate, shall be appointed annually and shall advise the presiding officer on parliamentary issues.

## Meetings and Quorum {#meetings-and-quorum .policy-heading}

1. Regular Meetings. The Senate shall regularly meet at least seven times during the academic year, and each academic year at least one regular Senate meeting shall be held at one of the SDSU Imperial Valley campuses.

    1. A regular meeting shall be a scheduled meeting and may continue beyond one day.
    2. The agenda of each regular meeting shall be distributed to the members of the Senate at least four working days before the meeting. 
    3. A senator present for a portion of a meeting shall be recorded as present for the entire meeting.

2. Special Meetings. Special meetings of the Senate may be called in a manner prescribed by the Bylaws.

3. Records. The minutes of both regular and special meetings shall be made available to the university community. Complete copies of the minutes of the Senate shall be available to members of the Senate, and copies shall be distributed on request. A summary of the contents of the Senate minutes and of actions taken shall be available to all faculty members and to other CSU senates or councils. These records may be made available in electronic form and need not be stored in paper form.

4. Quorum. Two-thirds of the voting Senate membership shall constitute a quorum. Seats that are not filled are considered “vacant” and do not count for quorum.  The members present at a duly called or held meeting at which a quorum is present may continue to conduct business until the time stated for adjournment in the call of the meeting, notwithstanding the withdrawal of enough members to leave less than a quorum. If a senator is unable to attend, they may in accordance with the Bylaws appoint a substitute with the power to vote. 

5. Meetings of the Faculty. Meetings of the faculty may be held in a manner prescribed by the Bylaws.

6. Faculty Review of Senate Actions. Any action of the Senate may be reviewed at a meeting of the faculty upon a written request signed by 10 percent of the tenured and probationary faculty and submitted to the Senate Chair. Such a meeting of the faculty shall be called by the Chair within two weeks of the request.

## Committees of the Senate {#committees-of-the-senate .policy-heading}

1. The Senate shall establish standing and other ad hoc or pro tempore committees as specified in the Bylaws.
2. Other committees and councils that report to or through the Senate shall be designated Senate-appointed university committees.

## Bylaws {#bylaws .policy-heading}

The Senate shall be responsible for constructing its own rules of operating procedure known as the Senate Bylaws.

## Amendments {#amendments .policy-heading}

Amendments to this Constitution shall be initiated by a majority vote of the Senate after having been presented at the previous meeting. Proposed amendments shall be submitted in writing to the tenured and probationary faculty electorate (as defined in the Bylaws 1.0) . The Senate shall conduct a ballot vote (via the web) on all proposed amendments. An amendment shall be adopted by an affirmative vote of a majority of those voting.
