---
title: ""
---
## Duties

::: {.policy-numbering .policy-start-2}

1. Duties

    1. The Senate shall consider policies with respect to the general welfare of the university. It shall review established policies, consider new policies, and study matters of concern to the students or faculty members.
    
    1. It shall formulate educational policy, including admissions, curricula, and criteria for the granting of degrees. It shall analyze established and proposed policies of instruction and consider variations in policy in exceptional cases.
    
    1. It shall advise the President in the selection of administrative personnel.
    
    1. It shall maintain adequate communication within the university community. Any member of the university community may request a member of the Senate to transmit to the Senate for discussion and possible action topics coming under the jurisdiction of the Senate.
    
    1. It shall appoint Senate and Senate-appointed university committees. It shall establish rules and procedures for Senate committees and shall establish procedures for the Senate.
    
    1. The ultimate authority to recommend approval of candidates for graduation shall reside with the tenured and probationary faculty. Following formal advice of the tenured and probationary faculty, only the members of the Senate who are elected as tenured and probationary faculty shall vote in the matter of approving the list of candidates for graduation.

:::
