project:
  type: website  

website:
  title: "University Policy File"
  search:
    location: navbar
    type: overlay
    limit: 50
    collapse-after: 5
    show-item-context: tree
    copy-button: true
    keyboard-shortcut: ["/", "s", "f"]
  
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: Home
        href: index.qmd
      - text: "University Senate Constitution"
        href: ./University_Senate_Constitution/constitution.qmd
      - text: "Bylaws"
        href: ./Bylaws/bylaws.qmd
      - text: "Resolutions"
        href: ./Resolutions/resolutions.qmd
      - section: "University Policies"
        contents:
        - text: "Academics"
          href: ./University_Policies/academics.qmd
        - text: "Administration"
          href: ./University_Policies/administration.qmd
        - text: "Budget"
          href: ./University_Policies/budget.qmd
        - text: "Codes"
          href: ./University_Policies/codes.qmd
        - text: "Committees - Regular Senate Committees and Councils"
          href: ./University_Policies/committees_regular_senate.qmd
        - text: "Committees - Senate-affiliated Campus Committees"
          href: ./University_Policies/committees_senate_affiliated.qmd
        - text: "Facilities"
          href: ./University_Policies/facilities.qmd
        - text: "Faculty"
          href: ./University_Policies/faculty.qmd
        - text: "Organization"
          href: ./University_Policies/organization.qmd
        - text: "Staff"
          href: ./University_Policies/staff.qmd
        - text: "Students"
          href: ./University_Policies/students.qmd
        - text: "Emeritus Employees"
          href: ./University_Policies/emeritus_employees.qmd

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true
    toc-depth: 4
    number-sections: false

language:
  search-text-placeholder: "Search the University Policy File"


