---
title: "University Policies: Academics"
---

## Absence from Class, Student {#absence-from-class-student .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Absence from First Class Meeting**

    If a student who is enrolled in a course does not attend the first class meeting of the semester or session and is not present at the start of the second meeting, the course instructor may request an administrative drop for nonattendance with the approval of the College Dean or designee(s). Instructors must be able to provide attendance records.

1. **Absence for Official University Events and Activities**

    Official university events and activities such as inter collegiate athletics, fine arts performances, forensics, and other academic competitions supported by the university require participation by students as official members of groups. Responsibilities shall be as follows:

    1. Sponsoring Departments or Programs: A sponsor of an official university event or activity shall provide each student participant with a memorandum regarding specific absences from classes. The memorandum shall be given to the student’s instructors within the first two weeks of classes. If scheduling changes occur, the sponsor shall provide the student with a revised memorandum to be given to instructors.

    1. Student Participants: Within the first two weeks of classes, a student who expects to be part of an official university event or activity shall notify the instructors of affected courses. At that time, the student shall request accommodation for any missed examinations or other assignments. If scheduling changes occur, the student shall immediately notify the instructors.

    1. Instructors**:** When possible, the instructor shall reasonably accommodate the student’s required absence from class. An instructor who believes that the anticipated absences would preclude successful completion of the course or would seriously affect the student’s grade shall inform the student by the end of the second week of classes.

1. **Absence for Religious Observances**

    1. The university is committed to supporting students who wish to practice their religious beliefs.[^fn3] Students anticipating an absence or missed coursework due to religious observances should provide reasonable advance notice to their instructor for the purposes of identifying and developing an appropriate accommodation.[^fn4]

    1. Instructors shall reasonably accommodate students who notify them in advance of planned absences for religious observances.

[^fn3]: Language copied from Cornell University: [https://scl.cornell.edu/religiousaccommodations](https://scl.cornell.edu/religiousaccommodations)

[^fn4]: Language copied and adapted from University of Nebraska Omaha: [https://www.unomaha.edu/campuspolicies/religious-observances.php](https://www.unomaha.edu/campuspolicies/religious-observances.php)

:::

## Advising, Undergraduate Academic {#advising-undergraduate-academic .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Mission and Purpose**

    Academic advising engages students in a dynamic relationship to support their growth and development as they seek to earn their degree. SDSU academic advisors help students:

    - Identify and mobilize a community of support (including faculty, staff, students, and family);

    - Envision a positive future and make a four-year plan to reach that vision;

    - Grow in their capacity to navigate the University and the challenges of college life;

    - Become well-informed about campus processes, policies, resources, and requirements.

1. **Coordination**

    1. The Associate Vice President for Faculty Advancement and Student Success shall lead in consultation with the Associate Vice President and Dean of Students and the Associate Vice President for Enrollment Services a coordinated campus approach to advising, including:

        a. Dissemination of information (e.g., General Education requirements, academic deadlines),

        a. Preparation and updating of written statements (e.g., Catalog and Class Schedule) describing those academic requirements, regulations, and policies applicable to all students,

        a. Identification of academic policy matters and their referral to the Undergraduate Council for consideration, and to prepare action for The Senate,

        a. Systematic consultation with Student Affairs regarding implementation of,

        a. Assessment of campus advising activities for the purpose of program development, change, and improvement, including general navigational and developmental advising essential to student sin transition or in special populations,

        a. Support of technological innovation to support advising services,

        a. Recognition of outstanding academic advisers, and

        a. Advising-related training and support.

    1. Academic advising shall take place in three major venues:

        a. First-year and specific population (including, for example, EOP, Athletics, Health Professions) coordinated care advising to be provided by assigned advisors as determined by the Associate Vice President for Faculty Advancement and Student Success and the Dean of Students;

        a. College and department or school academic advising for students in the relevant major fields involving assistant deans, faculty and staff advisors, and informal contacts with faculty members in the major department or school, with Faculty Advancement and Student Success providing support for undeclared students;

        a. Office of Evaluations advising for students seeking assistance with technical questions relevant to transfer credit, evaluation and for undergraduate students seeking to qualify for graduation.

1. **Academic Advising Council**

    An Academic Advising Council will be formed and directed by the designee of the Associate Vice President for Faculty Advancement and Student Success, to promote best practices and ensure campus coordination and alignment for undergraduate academic advising initiatives. This council will consist of one representative from each academic college, and one representative from other advising departments (e.g. Office of Evaluations, Athletics, Global Campus, Imperial Valley Campus, and each advising unit in Student Affairs and Campus Diversity). Members will help provide feedback and support for campus advising initiatives and monitor advisor training compliance and assessment of advising outcomes.

1. **Undergraduate Advisers**

    Colleges shall develop academic advising structures to support majors and minors. Academic unit-based advisors (a) shall provide clear, current, and accurate course and program information, including department or school policies and procedures and specific graduation requirements for the major and minor, (b) shall assist with course selection, (c) shall suggest career options and opportunities for further study, and (d) refer to other campus offices for specialty support including the Career Services Center, the Office of Financial Aid and Scholarships, Student Ability Success Center, Counseling & Psychological Services, etc. The adviser shall also make judgments on petitions for adjustment of academic requirements in the major or minor and shall maintain liaison with the Office of Evaluations and the evaluators assigned to the major. Credential or certificate programs may bring additional advising responsibilities. Other faculty members throughout the university may assist in advising through individual student conferences on educationally related concerns.

1. Student Affairs offices may provide various aspects of academic advising. Student Affairs advisors and counselors, therefore, may provide services related to employment, financial aid, disability-related accommodations, careers, personal, and related nonacademic concerns. These offices shall cooperate with the Associate Vice President for Faculty Advancement and Student Success, Enrollment Services, and department or school advisers throughout the university to ensure that information is current and accurate.

:::

## Assessment {#assessment .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Faculty shall be responsible to their students, colleagues, and the community for providing competent and ever improving instruction and programmatic quality. The purpose of assessing Degree Learning Outcomes shall be to identify opportunities to improve teaching, learning, and academic advising at the individual, course, programmatic, and institutional level.

1. In order to assess the extent to which students are achieving their Degree Learning Outcomes, San Diego State University shall be committed to systematic evaluation of instructional programs. Such evaluation shall extend both to broad interdisciplinary programs such as General Education and to degree-related programs within specific disciplines and departments or schools. The university shall encourage department and school faculties to engage in assessment research related to teaching and learning, and to disseminate such efforts through scholarly peer-reviewed venues.

1. Evidence of student achievement with respect to assessment shall not be used to evaluate individual faculty members or to publicly compare departments, schools, or institutions. Where assessment evidence is presented within lecturer evaluations or faculty retention, tenure, and promotion process, the evaluative focus shall be on the approach that the instructor has taken to demonstrate where students are with respect to desired outcomes and the evidence-based pedagogical and curricular actions undertaken to improve student achievement.

1. Assessment of student learning shall:

    a. Be used directly by disciplinary faculty to (a) articulate educational outcomes, (b) develop assessment methodologies to evaluate student achievement with regard to these outcomes, (c) undertake curricular planning, revision, and improvement;

    a. Be characterized by an approach that embraces multiple methods in order to provide valid information for improving academic programs;

    a. Be driven by the faculty, who shall have the primary responsibility for deciding how to assess, that is, how to design, select, and administer assessment methods, to interpret the results, and determine how the data shall be used to improve programs;

    a. Be part of strategic planning efforts that include consideration of sufficient resources to carry out the plan;

    a. Facilitate discussion of and agreement upon common principles across disciplines in programs such as General Education and identify or develop assessment mechanisms to evaluate student performance;

    a. Articulate programmatic and instructional goals and expectations and make these public to students and the general public;

    a. Open new areas of discussion with community colleges for coordinated assessment and curricular planning to improve student access and retention;

    a. Be reported within the established university-wide relational database (i.e., WEAVE Online);

    a. Be an integral component of the Academic Program Review process for departments, schools, and programs.

1. In addition to its primary roles of improving program effectiveness and promoting student achievement, data collected for academic assessment purposes may also be published or otherwise publicly disseminated as the scholarship of teaching and learning. If the data obtained in an assessment process are intended for eventual public dissemination, for example—in the form of journal publications or conference presentations—then the data protocol shall have received prior approval through San Diego State University’s Human Research Protection Program. Interested faculty should consult with their college representative on the Student Learning Outcomes and Program Assessment Committee and the Human Research Protection Program staff for more information.

1. **Student Support Services:** Student outcomes assessment of co curricular activities, which are integral to student learning, shall be necessary for a complete picture of students’ campus experience. These activities may involve the library, academic advising, counseling and career planning, housing, financial aid services, extracurricular activities, health services, and campus climate.

:::

## Calendar {#calendar .unnumbered}

::: {.policy-numbering .policy-start-1}

Each Fall (or earlier, if possible), the Associate Vice President for Faculty Advancement and Student Success (in consultation with appropriate campus officers) shall prepare the Academic Calendar for the following year, referencing a) guidelines established by the State of California and b) an approved set of rules, principles, and algorithms to create it; the Calendar shall then be presented to the Senate as an Information item.

However, the Calendar shall be presented for review to the Committee on Academic Policy and Planning for any year in which there are special circumstances that call for deviation from the approved rules, principles and algorithms; the Committee's report shall then be forwarded to the Senate for approval and recommendation to the President.

:::

## Cheating and Plagiarism {#cheating-and-plagiarism .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Institutions of higher education are founded to impart knowledge, seek truth, and encourage one’s development for the good of society. University students shall thus be intellectually and morally obliged to pursue their course of studies with honesty and integrity. Therefore, in preparing and submitting materials for academic courses and in taking examinations, a student shall not yield to cheating or plagiarism, which violate both academic and student disciplinary standards.

1. **Definitions**

    1. Cheating shall be defined as the act of obtaining or attempting to obtain credit for academic work by the use of dishonest, deceptive, or fraudulent means. Examples of cheating include, but are not limited to (a) copying, in part or in whole, from another’s test or other examination; (b) discussing answers or ideas relating to the answers on a test or other examination without the permission of the instructor; (c) obtaining copies of a test, an examination, or other course material without the permission of the instructor; (d) using notes, cheat sheets, or other devices considered inappropriate under the prescribed testing condition; (e) collaborating with another or others in work to be presented without the permission of the instructor; (f) falsifying records, laboratory work, or other course data; (g) submitting work previously presented in another course, if contrary to the rules of the course; (h) altering or interfering with the grading procedures; (i) plagiarizing, as defined; and (j) knowingly and intentionally assisting another student in any of the above.

    1. Plagiarism shall be defined as the act of incorporating ideas, words, or specific substance of another, whether purchased, borrowed, or otherwise obtained, and submitting same to the university as one’s own work to fulfill academic requirements without giving credit to the appropriate source. Plagiarism shall include but not be limited to (a) submitting work, either in part or in whole, completed by another; (b) omitting footnotes for ideas, statements, facts, or conclusions that belong to another; (c) omitting quotation marks when quoting directly from another, whether it be a paragraph, sentence, or part thereof; (d) close and lengthy paraphrasing of the writings of another; (e) submitting another person’s artistic works, such as musical compositions, photographs, paintings, drawings, or sculptures; (f) submitting as one’s own work papers purchased from research companies; and (g) representing work produced by generative artificial intelligence (AI) as one’s own.

1. **Academic and Disciplinary Sanctions**

    Cheating and plagiarism in connection with the academic program at the university may warrant two separate and distinct courses of disciplinary action that may be applied concurrently in response to a violation of this policy: (a) academic sanctions, such as grade modifications; and (b) disciplinary sanctions, such as probation, suspension, or expulsion. Academic sanctions are concerned with the student’s grades and are the responsibility of the instructor involved. Disciplinary sanctions are concerned with the student’s records and status on campus and shall be the responsibility of the university President or designated representative. The Coordinator of Judiciary Procedures shall be the President’s representative in matters of student discipline

1. **Due Process in Review of Alleged Violations**

    1. Disciplinary Sanctions: Only the university President or designated representative shall be authorized to exercise disciplinary authority over students and in so doing shall be mandated to accord students all the elements of “due process.” The steps set forth in the Executive Order 1098-Revised (2015) related to student conduct procedures shall be followed in the delineation of these matters.

    1. Academic Sanctions

        1. The instructor involved shall be expected to determine the type of academic sanction for cheating or plagiarism. Usually, “grade modification” shall be used; however, grade modification shall not be considered punishment and shall be used only if the instructor is satisfied that cheating or plagiarism did occur. The grade modification shall be left to the discretion of the instructor. Grade modification may include (a) a zero or F on the paper, project, or examination, (b) a reduction in one letter grade (e.g., C to D in the course), or (c) an F in the course. In addition to grade modification, certain departments or schools may have policies that state that cheating can show unsuitability for the program or profession. Students should be made aware of the penalties for cheating and of their appeal rights.

        1. Furthermore, before applying grade modification, the instructor should advise the student of the alleged violation and should have reasonable evidence to sustain that allegation. Reasonable evidence, such as documentary evidence or personal observation or both, shall be necessary for the allegation to be upheld.

    1. When a student is accused of cheating or plagiarism, the instructor should arrange an informal office conference with the student and at that time advise the student of the allegation as well as the evidence supporting it. The purpose of the office conference shall be to bring together the persons involved to discuss the situation informally and to decide upon an appropriate solution. If more than one student is involved in the incident, the instructor may call the students together to confer as a group if the students so desire. All notes and discussions between the student and instructor shall be confidential, except as may be relevant in subsequent campus disciplinary proceedings or subsequent legal action.

1. **Disciplinary Record**

    In order to coordinate information so as to permit appropriate disciplinary action for first-time and repeat offenders, instructors shall contact the Center for Student Rights and Responsibilities [(http://csrr.sdsu.edu/) ](http://csrr.sdsu.edu/))to submit the required reports. Instructors should describe violations of this policy according to the requirements stated in Executive Order 1098- Revised (2015) related to student conduct procedures.

1. For additional discussion of professional responsibilities of faculty with respect to plagiarism, see University Policies: Faculty, Professional Responsibilities.

:::

## Competency and Proficiency in Written English and Mathematics {#competency-and-proficiency-in-written-english-and-mathematics .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Competency in standard written English and in basic mathematics is essential to successful university study. Before enrolling in baccalaureate-level writing, mathematics, and other specified courses, students pursuing a baccalaureate degree shall satisfy the following requirements:

    a. CSU English Placement Test (EPT)

    a. CSU Entry Level Mathematics Examination (ELM)

    1. All new freshmen shall fulfill within one year of enrollment the two competency requirements, namely: CSU English Placement Test, CSU Entry Level Mathematics Examination.

        1. Students shall fulfill the California State University (CSU) English Placement Test requirement by one of the following:

            a. Completion of the CSU English Placement Test (EPT) at San Diego State University or at another CSU campus

            a. Completion before matriculation at San Diego State University of an acceptable college transfer course in English composition of three semester units or four quarter units with a grade of C or better

            a. Satisfactory score on the Verbal section of the Scholastic Aptitude Test (SAT) or Scholastic Assessment Test (SAT I)

            a. Satisfactory score on the English Usage section of the American College Test (ACT)

            a. Satisfactory score on the CSU English Equivalency Examination

            a. Satisfactory score on either the Language and Composition or the Composition and Literature Examination of The College Board Advanced Placement Program

            a. Satisfactory score on The College Board Achievement Test in English Composition with Essay.

        1. Students shall fulfill the CSU Entry-Level Mathematics Examination (ELM) requirement by one of the following:

            a. Satisfactory score on the CSU Entry-Level Mathematics Examination at SDSU or at another CSU campus

            a. Completion of an approved General Education mathematics transfer course of three semester units or four quarter units that satisfies the General Education Breadth quantitative reasoning requirement with a grade of C or better

            a. Satisfactory score on the Mathematics section of the Scholastic Aptitude Test (SAT) or Scholastic Assessment Test (SAT I)

            a. Satisfactory score on the Mathematics section of the American College Test (ACT)

            a. Satisfactory score on The College Board Advanced Placement Test in Mathematics, Level AB or BC

            a. Satisfactory score on The College Board Mathematics Achievement Test, Level 1, or College Board Mathematics Subject Test, Level 1

            a. Satisfactory score on The College Board Mathematics Achievement Test, Level 2, or College Board Mathematics Subject Test, Level 2C.

1. **Proficiency in Writing****[^fn5]**

    1. San Diego State University students shall demonstrate proficiency in writing skills as a requirement for graduation. Such skills shall incorporate basic rules of good writing, subject to the argument, format, logical development, demonstration of evidence, and style appropriate to various disciplines. Furthermore, departments and schools should insist upon effective expression in their courses and should stress the need for improving substandard writing.

    1. Certification of Upper Division Writing Proficiency: Students shall enroll in one intensive upper division writing course (W) or two disciplinary writing courses (DW).

        a. Completion of an approved writing course(s) with a minimum grade of C or Cr shall mean the student has met the Certification of Upper Division Writing Proficiency.

[^fn5]: On June 23, 2022, the SEC passed, on behalf of the Senate, the following update exception: The following 6 General Education (GE) classes (2 from each explorations category) shall be designated as 3-unit Upper Division Writing for AY 22-23 with the expectation that the appropriate Senate curriculum and writing committees approve permanent policy for beyond AY 22-23: Social Sciences - History 404 - Hist of Human Rights, BRAZ 325 - Brazilian Democracy and Society; Humanities - ENGL 301 - Psychological Novel, ENGL 305 - Literature and Environment; Natural Sciences - ENV S 301 - Energy and the Environment, MATH 303 - History of Mathematics. Students in majors that will exceed the 120 unit cap and are graduating in AY 22-23 can request a waiver to the Upper Division Writing requirement.

:::

## Course Prerequisites {#course-prerequisites .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Prerequisites for each course shall be stated in the Catalog course description. Students shall complete a course prerequisite or its equivalent before registering for the course. Only those prerequisites listed in the course catalog shall be enforced. Instructors may not add additional course prerequisites or require entrance examinations for course admission.

1. Each department or school shall review its courses and submit proposals to reaffirm, modify, or delete existing prerequisites or to add new prerequisites according to the following guidelines:

    1. Departments and schools shall clarify upon what basis the consent of the instructor is to be given if such consent is a course prerequisite.

    1. Departments and schools shall be aware that upper division and senior standing are determined solely on the total number of units completed. Such standing shall not guarantee that prior coursework has been completed in the discipline.

    1. Departments and schools shall devise systems for monitoring the enforcement of their own prerequisites, such as requiring students to sign a statement indicating where and when prerequisites were completed and what grade was received.

    1. Departments and schools may use “strongly recommended” or “recommended” instead of “prerequisite.”

    1. Students with a continuous enrollment record shall retain catalog rights with respect to prerequisites. Prerequisites added to a course in subsequent catalog years shall not be imposed on students with prior catalog rights.

1. Faculty may request to drop a student from a class if the student fails to meet listed prerequisite requirements. Faculty-initiated drops have to be verified by the College Dean or designee(s) before students are dropped.

:::

## Courses, Credit/No Credit Undergraduate {#courses-credit-no-credit-undergraduate .unnumbered}

::: {.policy-numbering .policy-start-1}

Only those courses designated in the General Catalog as being offered only for credit/no credit shall be approved for implementation.

:::

## Courses, Cross-Listed {#courses-cross-listed .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Cross listed courses are defined as courses that are offered two or more academic units, have identical course elements (title, description, units, mode of instruction; prerequisites and number, unless one of the academic units has already used that number for another course then the next closest number should be used) except the course prefix which reflects the academic department or program; are interchangeable for degree requirements; cannot be repeated for degree credit under separate prefixes; may be scheduled with the same instructor, room, and meeting pattern; may be scheduled with all, some, or one of the course prefixes.

1. Process for approving a cross-listed course: If the course is an approved course in the catalog and additional department(s) want to cross-list the course, use a "Course Modification" form and get signatures from all participating department chairs and college deans. Forward the signed Course Modification form to the Curriculum Committee as an information item and to the Office of Enrollment Services.

    If the course has never been taught, approval for a new cross-listed course shall follow the campus curriculum guidelines associated with a new course proposal.

1. **Criteria**

    1. A cross-listed course shall have the same title, number, unless one of the academic units has already used that number for another course, prerequisites, description, unit value, and grading method in its description as listed in every unit.

    1. Catalog and course schedule listings shall indicate that the course is cross-listed. Materials presented to students, such as syllabi and course descriptions, shall also indicate that the course is cross-listed.

    1. The academic units shall agree that students may take the course under any of its listings to fulfill an academic unit’s requirements.

:::

## Courses, Experimental and Interdisciplinary Limited-Duration {#courses-experimental-and-interdisciplinary-limited-duration .unnumbered}

::: {.policy-numbering .policy-start-1}

(Numbered 296, 496, 580, and 596, and General Studies 250, 350, 550)

1. The 496 number shall designate defined, selected topics not specifically treated in regular Catalog courses. It may thus be used either as an experimental precursor to a new course proposal or as a vehicle to explore current interests through a standard course format, including syllabus, texts of bibliography, explicit procedure or methodology, and an appropriate student population. Unlike the 499 Special Studies course, the topics course should be subjected to a reasonable department or school review for need, relevance, and substance before being included in the Class Schedule.

1. **Residence Courses**: Proposals for experimental and interdisciplinary limited-duration courses shall follow an expedited curriculum review process as follows:

    1. Experimental and interdisciplinary limited duration courses (initiated in the curriculum management system) shall be approved by the proposing department and college curriculum committees using the College’s internal curriculum approval process and then sent to the College Dean (or designee) for approval. Proposals approved by the College Dean (or designee) will be sent simultaneously to the Senate Executive Committee, Undergraduate Curriculum Committee, Undergraduate Council, Graduate Council (for 500-level courses) and the Associate Vice President for Enrollment or designee as an information item. Unless objections arise, curriculum proposals will then be included in the Senate report as an information item. Courses that span multiple departments and/or colleges must be approved by all relevant departmental and college committees. If consensus cannot be achieved among these committees, the proposal shall undergo the full review process for new course proposals.

    1. Proposals shall not be constrained by General Catalog and committee deadlines for regular course proposals; they shall be dealt with on demand and shall be completely processed during one semester for implementation the next semester.

    1. Assessment of an experimental and limited duration course shall be included as one component of the rationale for proposing the permanent version of the course. Proposals for these permanent courses shall undergo the full review process for new course proposals.

1. **Extension Courses:** Proposals for experimental and interdisciplinary limited-duration courses offered for academic credit by Global Campus shall follow the same process described in 2.1.

:::

## Courses: Hours and Preparation {#courses-hours-and-preparation .unnumbered}

::: {.policy-numbering .policy-start-1}

1. A course shall meet for the required number of hours and shall offer an opportunity to prepare, to study, and to cogitate for the required hours, as stated in the General Catalog.

1. A unit credit hour shall represent 50 minutes of lecture or recitation combined with two hours of preparation per week throughout one semester of 15 weeks. Two credit hours of activity (e.g., in Exercise and Nutritional Sciences) or three credit hours of laboratory (e.g., in Physics) shall be conside red equivalent to one credit hour of lecture.

1. A course offered in a term of less than 15 weeks shall contain the same contact hours, preparation time, content, and requirements as the same course offered over a 15-week semester.

1. The approval of the department, school, or program and of the college dean shall be required to schedule all short-term or weekend courses.

1. One-unit courses scheduled on consecutive days shall not be scheduled for less than four consecutive calendar days.

:::

## Courses Not Offered in Two Years, Undergraduate {#courses-not-offered-in-two-years-undergraduate .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Each year the Associate Vice President for Enrollment or designee (or other administrative officer who shall coordinate the curricular process) shall identify the courses not offered during the past two years and shall inform each department or school that failure to offer the courses within the next academic year shall subject the courses to deletion from the Catalog. A course not offered during that third year shall be deleted by the Office of Curriculum, Assessment, and Accreditation.

1. **Reinstatement of Deleted Courses:** For up to three years after the deletion of an undergraduate course by the Undergraduate Curriculum Committee the course (same number, title, credit, units, prerequisites, Catalog description) may be reinstated.

    1. The academic department, school, or program shall forward to the dean of the college a completed Course Reinstatement form.

    1. If the dean approves the request, the form shall be forwarded to the Office of the Provost for inclusion in the next General Catalog; however, a reinstated course may be listed in the Class Schedule and taught prior to the publication of that catalog.

    1. The department, school, or program shall teach the reinstated course within two semesters of the submission of the Course Reinstatement form. Failure to do so shall result in a second deletion of the course from the curriculum; courses thus deleted shall be restored to the curriculum only through the process to approve new courses.

:::

## Courses Rejected by the Curriculum Committee {#courses-rejected-by-the-curriculum-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

Courses rejected by the Curriculum Committee shall not be offered under special topics numbers or otherwise included in the schedule of classes unless specifically authorized by the Provost, who shall report such action to the Undergraduate Curriculum Committee.

:::

## Courses, Special Study {#courses-special-study .unnumbered}

::: {.policy-numbering .policy-start-1}

1. A course numbered 299, 499, or 599 signifies a well-defined, one-of-a-kind, special study usually on a topic or in an area not covered by a regular, titled Catalog course. It may be offered only with the consent of the instructor and is intended only for a student who has demonstrated ability to work independently and who is clearly qualified to work at an advanced level in the discipline. The instructor shall meet with the student regularly and by schedule to plan, monitor, and direct progress. Standard grading procedures shall apply as in all other university courses. The maximum credit for 299, 499, and 599 courses applicable toward a bachelor’s degree shall be nine units.

1. A 499 number shall not be used (a) to offer lower division coursework, (b) to extend internships, (c) to award academic credit in place of pay, (d) for work experience, (e) for class-sized groups.

:::

## Courses, Undergraduate Collaborative {#courses-undergraduate-collaborative .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Collaborative courses shall be developed collaboratively under two or more rubrics by two or more academic units responsible for course development (typically departments, schools, or interdisciplinary programs). Collaborative courses shall be listed among the courses of each collaborative unit.

1. Approval for collaborative courses at the 100- through 500-level shall rest with the Undergraduate Curriculum Committee. Approval for a collaborative course shall be considered only after the course itself, whether new or revised, has been approved for content in the normal process as presented on a New Course Proposal form. Approval as a collaborative course requires that the collaborative process be described under which the course was developed and that all units participating in the collaboration agree to the conditions of the collaboration. In addition, the units shall agree that, if the course is not team taught, the instructor shall be knowledgeable in all of the content areas.

1. **Conditions of Collaboration**

    1. Each collaborative unit shall agree to any change in course title, number, prerequisites, description, unit value, content, or grading method. If a collaborative unit disagrees to a proposed change, no change shall be made. If a unit withdraws from a collaboration, the course shall be deleted, and each unit shall formally reapply by the new course proposal process to teach that material, even if the unit taught that material before the collaboration.

    1. If a collaborative course is acceptable for General Education, the following General Education policies apply:

        a. A student shall not receive more than 12 units of GE credit from an academic unit, including collaborative courses offered therein.

        a. A student shall not receive more than seven units of GE credit in GE sections II, III, and IV from an academic unit, including collaborative courses offered therein. Courses in a student’s major unit or collaborative courses listed therein shall not be used in section IV (Explorations).

1. **Criteria**

    1. A collaborative course shall have the same title, number, prerequisites, description, unit value, and grading method in its description as listed in every collaborative unit.

    1. Experimental topics courses, General Studies 250 and 350, and variable title and variable unit courses shall not be collaborative courses.

    1. Catalog and course schedule listings shall indicate that the course is collaborative. Materials presented to students, such as syllabi and course descriptions, shall also indicate that the course is collaborative.

    1. The collaborating units shall jointly maintain responsibility for course content.

    1. The collaborative units shall agree to the special conditions above. If the course is offered for General Education credit, the collaborative units shall agree to the special conditions on collaborative General Education courses above.

    1. The collaborative units shall agree that students may take the course under any of its listings to fulfill an academic unit’s requirements.

:::

## Credit by Examination {#credit-by-examination .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Credit by examination shall be restricted to students who are regularly enrolled (matriculated), not on probation, and enrolled in at least one regular course. Credit/no credit shall be applied only to regular undergraduate courses and shall be limited to 30 units. Credit by examination obtained through credit/no credit shall be limited by the usual restrictions on credit/no credit grading to 15 total units. Credit by examination shall not be treated as part of the student’s study load, but the student shall pay for additional units if costs exceed fees already paid.

1. **To obtain credit by examination:**

    1. The student shall register during the change-of-program period in an actual course for which credit by examination is being requested. Credit by examination units shall not be counted toward full- time enrollment. The student shall be registered in at least one other course.

    1. Before taking an examination, the student shall obtain on the appropriate special form, available through the Office of the Registrar or the department or school office, the permission of the chair or director of the department or school offering the examination and of the dean of the appropriate college to enroll in the course and to take it for credit by examination as the grading option.

    1. After department or school approval has been obtained, the Office of the Registrar shall verify the student’s enrollment and probation status and shall add the course to the student’s record. The grading option of credit by examination shall be so indicated on the system at that time and shall be reflected in reports such as enrollment confirmations, class lists, and grade sheets.

    1. The student shall take the examination and be evaluated by the department or school. The grade may be submitted by the department or school to the Office of the Registrar either immediately or on the regular grade sheet for the course at the end of the semester or session

1. **Department or school policies shall be subject to the following:**

    1. A department or school may exclude any of its courses from credit by examination, or it may prevent a student from obtaining credit by examination in a course that is a prerequisite to a course the student has taken or is currently taking.

    1. In a course a department or school may require credit/no credit grading only for credit by examination.

    1. If a student takes an examination, a grade, if only “no credit,” shall be entered on the student’s transcript.

    1. A department or school may develop its own procedures regarding a student who signs up for credit by examination and then either elects not to take the examination or fails the examination; however, the department or school shall inform the student of its policy.

:::

## Credits Earned by High School Students {#credits-earned-by-high-school-students .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Upon recommendation by their counselor, principal, or the coordinator of a gifted students program, students who have completed their junior year of high school and are of exceptional academic ability and achievement may apply for admission to the SDSU Summer Session program. Credits earned during the summer shall be placed on a permanent record by the Office of the Registrar and may be applied toward a degree at San Diego State University. Registration in a particular course shall be subject to the approval of the instructor.

1. International Baccalaureate Program: Students who have completed the requirements for the International Baccalaureate Diploma may be admitted to San Diego State University. Course credit for specified courses or advanced placement for specified test scores may be awarded at the discretion of appropriate departments or schools.

:::

## Credit for Academically Related Work Experience {#credit-for-academically-related-work-experience .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Academic credit may be granted for academically related work experience supervised and evaluated by a faculty member in accordance with university policies and standards.

1. Academically related work experience shall be defined as practical experience, paid or unpaid, that the sponsoring faculty member considers likely to contribute directly to a student’s academic and professional growth. Outside the structure of courses specifically designed to facilitate such experience, academic credit related to work experience shall be awarded only for satisfactory completion of clearly articulated academic requirements agreed upon in advance by the student and the sponsoring professor and duly approved and recorded in compliance with department or school policy.

:::

## Curriculum Changes, Undergraduate and Graduate {#curriculum-changes-undergraduate-and-graduate .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Initiation:** Proposals for changes in the curriculum may originate from faculty, departments or schools, deans, college curriculum committees, or the Undergraduate Curriculum Committee.

    1. The Office of Curriculum, Assessment, and Accreditation shall provide assistance in the preparation of proposals.

    1. A schedule of deadlines for submission of curricular proposals from the colleges to the Office of Curriculum, Assessment, and Accreditation shall be established and published annually in the Curriculum Guide. Colleges may establish internal deadlines if they so desire.

1. **The Office of Curriculum, Assessment, and Accreditation Review (CAA):** Proposals shall be reviewed for proper format, content, and elements that might conflict with existing policy, regulations, administrative code, or with other agencies within the university. The Office of Curriculum, Assessment, and Accreditation shall also be responsible for ensuring external review of proposals are done in a timely manner. This includes review by the CSU Board of Trustees, WSCUC, and the CSU Chancellor’s Office as appropriate.

1. **College Review:** Each college shall develop and file in the Office of the Provost procedures for review of curricular proposals, including department or school-level review. Every proposal should be reviewed by the College Curriculum Committee following the procedures outlined by the College. Review should be concerned with the academic merit of the proposal and its relationship to the academic program of other departments or schools and the college as a whole.

1. **Approval by the dean of the College:** In general, every curricular proposal shall be submitted to the dean of the college concerned for approval or disapproval. The dean should announce a decision within 10 academic workdays. The dean’s approval shall be based on the determination that the proposal is consistent with plans for the long-run development of the college, that all budget needs of the proposal (teaching positions, space, equipment, supplies, staff, etc.) have been considered carefully, and that the dean is prepared to give the needs of the program high priority in the college’s budget.

1. When the final form is acceptable to the college, dean, and the department or school, the curriculum proposal, depending on the type of proposal, shall be forwarded by Curriculum Services using the following workflow:

    1. **New Undergraduate Degree Proposals**

        1. After Intent forms have been submitted and approved by the Board of Trustees as appropriate (for new programs only), requests for new degree programs, new minors, emphases, options, basic certificates, and concentrations not in the Academic Master Plan shall be sent concurrently to the Committee on Academic Policy and Planning to be considered for inclusion in the Academic Master Plan and to the Committee on Academic University Resources and Planning to be evaluated for resource implications.

        1. Proposals approved by APP and URP shall be routed to the Undergraduate Curriculum Committee for approval.

        1. Proposals approved by the Undergraduate Curriculum Committee shall be sent to the Senate as an action item and to the AA-AVPs, Academic Deans Council, Undergraduate Council, and Associated Students as information items. Proposals approved by the Senate shall be sent to the President for final approval. Once approved, the Office of Curriculum, Assessment, and Accreditation will work with the Chancellor’s Office, CAL State Apply, and the Registrar’s Office to prepare the programs for admissions.

        1. New Undergraduate Degree Proposals Flow Chart:

    1. **New Undergraduate Courses, Changes in Existing Programs and Courses, and Major Modifications to Existing****[^fn7]** **Courses**

        1. Curriculum proposals for new classes, major changes in existing classes, or programs shall be sent concurrently to the General Education (GE) Committee if changes involve the University’s GE program and the Graduate Curriculum Sub-Committee (GCC) for undergraduate proposals that involve classes open to graduate students, for approval.[^fn8]

        1. Proposals approved by GE and /or GCC shall be sent to the Undergraduate Curriculum Committee (UCC). Proposals that do not require review by GE or GCC shall skip step 5.2.1 and go directly to UCC. Proposals for minor modifications to existing undergraduate courses can skip 5.2.2 and go directly to the Senate as information items.

        1. Proposals approved by the UCC shall be reported to the Senate, to the AA-AVPs, Academic Deans Council, Undergraduate Council, and Associated Students as information items.

        1. New Undergraduate Courses and Changes in Existing Programs and Courses Flow Chart:

    1. **New Graduate Degree Proposals**

        1. After Intent forms have been submitted and approved by the Board of Trustees as appropriate (for new programs only), requests for new degree programs, emphases, options, advanced certificates, and concentrations not in the Academic Master Plan shall be sent concurrently to the Committee on Academic Policy and Planning to be considered for inclusion in the Academic Master Plan and to the Committee on University Resources and Planning to be evaluated for resource implications.

        1. Approved proposals shall be sent to the Graduate Curriculum Sub-Committee/Graduate Council for approval.

        1. Approved proposals shall be sent to the Senate as an action item and to the AA-AVPs, Academic Deans Council, and Associated Students as information items. Proposals approved by the Senate shall be sent to the President for final approval. Once approved, the Office of Curriculum, Assessment, and Accreditation will work with the Chancellor’s Office, CAL State Apply, and the Registrar’s Office to prepare the programs for admissions.

        1. New Graduate Degree Proposals Flow Chart:

    1. **New Graduate Courses and Emphases, and Changes in Existing Courses (Major), Emphases, Advanced Certificates, and Requirements****[^fn9]**

        1. Curriculum proposals shall be sent to the Graduate Curriculum Sub-Committee for approval.

        1. Curriculum proposals approved by the Graduate Curriculum Committee shall be reported to the Senate, AA-AVPs, Graduate Council, Associated Students, and Academic Deans Council as information items.

        1. New Graduate Courses and Emphases, and Changes in Existing Courses, Emphases, Advanced Certificates, and Requirements Flow Chart:

    1. **Discontinuance of Undergraduate and Graduate Degree Proposals**

        1. Requests to discontinue Undergraduate Degree Programs, which will include a teachout process, shall follow the same workflow as that for new programs outlined in 5.1. Following approval by the College Curriculum Committee and College Dean and review for accuracy by CAA, the proposal shall be forwarded to AP&P and URP, and, upon approval, move to the Undergraduate Curriculum Committee for approval. Undergraduate Degree Proposals to discontinue existing degrees approved by Undergraduate Curriculum Committee will be routed to the Senate as an action item and to the AA-AVPs, Academic Deans Council, Undergraduate Council, and Associated Students as information items. Proposals approved by the Senate shall be sent to the President for final approval. Once finalized, the Office of Curriculum, Assessment, and Accreditation will notify the Chancellor’s Office and other external bodies.

        1. Requests to discontinue Graduate Degree Programs, which will include a teach-out process, shall follow the same workflow as that for new programs outlined in 5.3. Following approval by the College Curriculum Committee and College Dean and review for accuracy by CAA, the proposal shall be forwarded to AP&P and URP, and, upon approval, move to the Graduate Curriculum Sub-Committee/Graduate Council for approval. Graduate Degree Proposals to discontinue existing degrees approved by the Graduate Curriculum Sub-Committee/Graduate Council be routed to the Senate as an action item and to the AA-AVPs, Academic Deans Council, Graduate Council, and Associated Students as information items. Proposals approved by the Senate shall be sent to the President for final approval. Once finalized, the Office of Curriculum, Assessment, and Accreditation will notify the Chancellor’s Office and other external bodies.

[^fn7]: See Curriculum Guide for current list of course modifications requiring additional review and approval.

[^fn8]: Current Area E courses undergoing reconsideration of GE status will be evaluated by the department and college curriculum committees and if approved, forwarded to the Dean. If the Dean approves the new GE designation, the proposal will be forwarded to the University GE committee for review. If approved by the GE committee, the proposal will be presented to the Senate as an action item. Expedited GE consideration is only available to current Area E classes and only for the 24/25 AY.

[^fn9]: See Curriculum Guide for current list of course modifications requiring additional review and approval.

:::

## Dean's List {#dean-s-list .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Computation for the Dean's List shall be based on a minimum of 12 units of credit, each carrying a letter grade. Students shall be placed on the Dean's List if they receive a grade point average of 3.50 or above for the given semester. The computation of the grade point averages for the semester shall be made within six weeks after the end of the semester to permit students to convert incomplete (I) grades to letter grades in time to be included in the computations.

1. "Dean" shall refer to the dean of each line college. The Associate Vice President for Faculty Advancement and Student Success shall recognize undeclared majors and special majors; the Dean of the College of Education shall recognize Liberal Studies majors.

1. A student's transcript shall indicate each inclusion on the Dean's List.

:::

## Degree Program Discontinuation {#degree-program-discontinuation .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Procedures**

    1. Proposals for the discontinuation of degree programs may be initiated by departments or schools, faculty members, college or university committees, or administrative officers of the University. Proposals shall specify mechanisms to protect the interests of students enrolled in such programs and, if possible, to allow the students to complete their degrees in a reasonable time. Proposals shall include a declaration of intent to effect (a) a degree program discontinuation or (b) the discontinuation of degree program with department or school dissolution. Proposals shall address employment options, informed by the applicable Collective Bargaining Agreement (CBA), for the affected tenured and probationary faculty and for permanent staff.

    1. Proposals shall be reviewed by designated department or school and college curriculum committees, and the dean of the college.

    1. Proposals approved by the college dean shall be forwarded to the office of the Provost for university-wide distribution.

    1. Undergraduate Proposals

        1. Undergraduate proposals shall be reviewed for approval by the Committee on Academic Policy and Planning, which shall seek broad consultations with groups or persons likely to be affected by the degree program discontinuation, including enrolled students in the affected degree program.

        1. Proposals shall be additionally reviewed by the Undergraduate Curriculum Committee, with recommendations forwarded to the Senate.

        1. Approved proposals shall be forwarded to the Senate as action items.

        1. Approved proposals shall be forwarded to the President for final action.

    1. Graduate Proposals

        1. Graduate proposals shall be reviewed for approval by the Graduate Council, which shall seek broad consultation with groups or persons likely to be affected by the degree program discontinuation, including enrolled students in the degree programs affected.

        1. Proposals shall be further reviewed by the Committee on Academic Policy and Planning, with recommendations forwarded to the Senate.

        1. Approved proposals shall be forwarded to the Senate as action items.

        1. Approved proposals shall be forwarded to the President for final action.

1. **Dissolution of a Department or School:** If a proposal for degree program discontinuation implies the dissolution of a department or school, this procedure shall be followed:

    1. Proposals for the discontinuation of degree programs may be initiated by departments or schools, faculty members, college and university committees, or administrative officers of the university. Proposals shall specify means to protect the interests of students enrolled in the programs and, if possible, to allow those students to complete their degrees in a reasonable time. Proposals for degree program discontinuation shall include a declaration of intent to effect (a) a degree program discontinuation or (b) the discontinuation of degree program with department dissolution. Proposals shall address employment options, informed by the applicable Collective Bargaining Agreement (CBA), for the affected tenured and probationary faculty and for permanent staff.

    1. Proposals shall be reviewed by designated department or school and college curriculum committees.

    1. Proposals shall be reviewed by the dean or deans of the colleges. If the dean or deans determine that the proposal has no merit, this recommendation together with the original proposal shall be forwarded to the Provost. If the dean or deans determine that the proposal does have merit, the dean or deans shall form a special ad hoc committee to give the matter full and serious consideration. The ad hoc committee shall have at least five members, at least two of whom shall be department chairs or school directors with one chair or director drawn from an uninvolved college.

    1. The ad hoc committee shall report its recommendations to the dean and the executive committee (or equivalent) of the colleges involved, and the dean shall subsequently transmit final recommendations to the Provost who shall in turn convey the recommendations with comments to the Committee on Academic Policy and Planning.

    1. The Committee on Academic Policy and Planning shall seek broad consultation with groups or persons likely to be affected by the degree program discontinuation, including enrolled students in the affected degree program. The Committee shall forward its recommendations regarding deletions or transfer of programs to the Undergraduate Curriculum Committee for review. The Committee on Academic Policy and Planning shall present its recommendation regarding dissolution of a department or school to the Senate as an action item concurrent with the Undergraduate Curriculum Committee report on the deletion or transfer of programs.

    1. The Undergraduate Curriculum Committee shall present its recommendations regarding the deletion or transfer of programs to the Senate as an action item.

    1. Approved proposals shall be forwarded to the President for final action.

:::

## Degree Revocation {#degree-revocation .unnumbered}

::: {.policy-numbering .policy-start-1}

1. The University’s award of academic credit and Degrees constitutes its formal certification of student achievement.However, a Degree may be awarded to a Student in error, or as a result of fraud, misrepresentation, or other intentional or unintentional actions. In order to preserve the integrity and academic standards of Degrees granted, San Diego State University (hereafter the University) may exercise the right to revoke a previously conferred Degree as set forth in the following procedure. The authority to revoke a Degree resides with the President. The President hereby delegates that authority to the Provost.

1. **Definitions**

    1. *Advisor*: An Advisor is someone who may accompany the Student at the Degree revocation hearing. The Advisor’s role is limited to consulting and providing support, and may not speak for, or on behalf of, the Student. The Advisor may not be an attorney.

    1. *Clear and convincing evidence*: Evidence of such convincing force that it demonstrates, in contrast to the opposing evidence, a high probability of the truth of the fact(s) for which it is offered as proof. Such evidence requires a higher standard of proof than proof “by a preponderance of the evidence” but a lower standard than required for proof “beyond a reasonable doubt.”

    1. *Degree*: Degree includes any form of academic Degree, credential, certificate, or professional designation or other award (e.g., Honors designation) conferred by the University, or any of its colleges, departments or units, including Global Campus.

    1. *Registrar*: Registrar refers to the management personnel in the Office of the Registrar at the University.

    1. *Notice of Intent to Revoke Degree*: Notice of Intent to Revoke Degree is the written notice issued to a Student possessing a Degree the University intends to revoke under the terms of this policy.

    1. *Student*: The term Student may refer to any current or former student, including those enrolled through Global Campus.

    1. *Hearing Officer*: The Hearing Officer referred to herein shall be a person selected by the Provost in consultation with the Associate Vice President for Administration. The Hearing Officer shall be a University faculty member or administrator who has relevant experience, or who shall have received appropriate training, regarding this policy and procedure as well as the standards associated with the granting of the Degree at issue in the proceedings. Student conduct administrators and their subordinates, persons with a conflict of interest in the matter, and perceived witnesses giving rise to the matter are ineligible to serve as Hearing Officers. If a conflict of interest or other cause prevents the selection of a Hearing Officer employed by the University, a Hearing Officer who is a faculty member or administrator at another CSU campus shall be asked to serve as a Hearing Officer.

    1. *Timelines*: The University may, but is not required to, extend timelines set forth herein. Extensions shall be determined by the Provost or designee. The Provost or designee shall promptly and in writing notify the Student and any University administrators involved of any revised timeline.

1. **Basis for Revocation**

    1. A Degree may be revoked by the University if: 1) upon examination of a Student’s record, it is determined that the requirements for the Degree awarded as established by the California Code of Regulations, Title 5, were not met; or 2) information comes to light that, if known at the time the Degree was awarded, would have resulted in a determination that the Degree should not be conferred. The bases for a Degree revocation include, but are not limited to, the following:

    1. Academic misconduct by Students, faculty, staff, or administrators, including fabrication, falsification, plagiarism, or fraud.

    1. Unauthorized altering of information on a Student record (including in an official University student information system).

    1. Error(s) by administrators, faculty, staff, or Students that resulted in the awarding of the Degree that would not have been awarded otherwise.

    1. Other violations of the University’s Student Conduct Code that are of such a nature that had the misconduct been discovered prior to the issuance of the Degree, it would have resulted in the suspension or expulsion of the Student from the University.

1. **Investigation**

    1. When information comes to light that places into question the validity of a previously conferred Degree, it shall be referred to the Provost through the Dean of the college from which the Degree in question was granted.

    1. Upon receipt of such information, the Provost or designee shall conduct an initial review of the information and determine whether such information is credible and whether, if established as true, the evidence would justify the revocation of a Degree.

    1. If the Provost determines that the information is credible and, if established, would justify the revocation of a Degree, the Provost shall select an investigation committee of faculty and/or administrators. Members of the investigation committee shall be selected according to expertise as it pertains to the details of the case. The investigation shall be completed within sixty (60) calendar days, and the investigation committee shall present a report of findings with regards to the information examined and a recommendation as to whether the investigation establishes by clear and convincing evidence that the Degree should be revoked.

    1. The Provost shall review the report and, if appropriate, may ask the General Counsel and/or other University personnel to investigate any other information relevant to whether the Degree should be revoked. If the Provost determines that there is sufficient information to make a determination as to whether to issue a “Notice of Intent to Revoke Degree” (“Notice”), the Provost or designee shall issue the Notice to the Student possessing the Degree in question. If the Provost determines that there is insufficient evidence to justify a revocation, no further action shall be taken and the Degree shall stand.

1. **Process When Notice of Intent to Revoke Degree is Issued**

    1. The Notice shall advise the Student that the University has clear and convincing evidence that justifies the revocation of the Student’s Degree pursuant to this policy. The Notice shall identify the Degree and year it was awarded and describe the evidence upon which the Notice is based in sufficient detail to allow the Student to respond to the Notice. A copy of this policy shall also accompany the Notice. The Notice shall state that if the Student decides to contest the revocation, the Student shall, within thirty (30) calendar days of receipt of the Notice, make a written request to the Provost for a hearing. The Notice shall also state that if the Student requests a hearing, the Student shall prepare a written response to the Notice (“Response”) stating whether the Student disputes the information set forth in the Notice and/or the University’s conclusion that the Degree should be revoked, as well as the specific evidence and reasons upon which the Student bases such dispute or conclusion.

    1. The Notice shall be sent by certified mail, personal or overnight delivery, to the last known mailing or contact address for the Student. If possible, the Notice shall also be sent concurrently via email. The Student’s written request for a hearing and Response shall be sent to the Provost via certified mail within the thirty (30) day period set forth in Paragraph 5.1. Absent good cause to be determined by the University, the failure to timely request a hearing and submit a Response shall result in the University revoking the Degree as set forth in Paragraph 5.4.

    1. The thirty (30) calendar day period within which the Student may request a hearing shall commence as of the date of receipt by the Student as reflected on the written confirmation received by the University that the Student received the Notice. This confirmation can be a document signed by the person who delivered the Notice indicating that the Student was given the Notice; a receipt signed by the Student acknowledging receipt of the Notice by certified mail; a signed acknowledgement by the Student acknowledging receipt of the overnight mail containing the Notice; or other proof of actual receipt by the Student, such as email delivery confirmation.

    1. If the University receives confirmation pursuant to Paragraph 5.3 and the Student does not request a hearing, the University may revoke the Degree without further proceedings. If the University does not obtain appropriate confirmation, it may nevertheless proceed with revocation in accordance with Paragraph 5.11 of this policy.

    1. If the Student requests a hearing, the Provost or designee shall use reasonable efforts to schedule such hearing no sooner than thirty (30) and no later than sixty (60) calendar days after the Student notifies the University of the request for a hearing. The Student shall be provided with a written notice of the scheduled hearing date and location no later than fourteen (14) days prior to the hearing.

    1. The Student shall be entitled to review the evidence that supports the University’s Notice and may request a copy of such evidence at a cost not to exceed that provided under the California Information Practices Act (Civil Code section 1798 et. seq.). The Student and the Provost, or a designee, shall exchange a list of witnesses to be called at the hearing no later than fourteen (14) calendar days prior to the hearing. At the Student’s written request, the University shall send a “notice to appear” to any University employee-witness at her or his University-assigned email address. If, after this deadline, the Student and/or the University wish to supplement their witness list, they shall request permission from the Hearing Officer to do so.

    1. The Student may be accompanied at the hearing by an Advisor, who may neither speak for, nor on behalf of, the Student. The Advisor may not be an attorney.

    1. The hearing shall take place before a Hearing Officer selected by the Provost in consultation with General Counsel. The Provost or designee shall represent the University.

    1. Subject to Paragraph 5.6 of this policy, the Student and the University shall be allowed to introduce evidence and call witnesses to testify at the hearing. The formal rules of evidence applied in courtroom proceedings do not apply in the hearing. All information that responsible persons are accustomed to rely upon in the conduct of serious affairs is considered, although unduly repetitive information may be excluded. The Hearing Officer controls the proceedings.

    1. If, after requesting a hearing, the Student fails to appear at the hearing without good cause, the hearing shall proceed and the Hearing Officer shall render a decision based on the evidence submitted by the University and the Student’s written response. The Hearing Officer shall weigh the evidence presented and shall draw no inferences from the Student’s absence from the hearing.

    1. If, despite its own due diligence, the University receives no confirmation that the Student received the Notice, or is unable to locate the Student to provide the Notice, the University may nonetheless seek revocation of the Degree. The University shall schedule a hearing within sixty (60) calendar days of the date of the Notice that shall proceed in the absence of the Student. The Hearing Officer shall consider the evidence presented by the University at the hearing and shall determine whether there is sufficient evidence to revoke the Student’s Degree pursuant to this policy. The Hearing Officer shall draw no inferences from the Student’s absence from the hearing.

    1. The Hearing Officer shall consider and weigh the evidence and shall prepare written findings concerning whether there is clear and convincing evidence to revoke the Degree. If the Hearing Officer finds that the evidence establishes that the Degree should be revoked, the Hearing Officer shall also consider whether the Student should be permitted to complete the requirements for the revoked Degree after some sanction (if appropriate) is applied. Sanctions may include, but are not limited to, a ban from enrollment for some period of time or a loss of catalog year rights. The Hearing Officer shall submit such written findings and any appropriate recommendations to the Provost no later than thirty (30) calendar days after the hearing.

    1. The Hearing Officer may consider and recommend alternative remedies to revocation.

    1. The Provost shall prepare a decision letter that accepts the Hearing Officer’s recommendation, adopts a different result, or refers the matter back to the Hearing Officer for further findings on enumerated issues. The decision letter shall be issued within fifteen (15) calendar days of the Hearing Officer’s recommendation. Any decision letter that refers the matter back to the Hearing Officer shall include timelines for the Hearing Officer’s supplemental findings/recommendations as well as the subsequent supplemental decision letter.

    1. If a Degree is revoked in accordance with Paragraph 5.11 (University unable to locate Student), a Student who later learns of the revocation and wishes to contest it may request a rehearing of the matter in writing. The Student shall provide clear and convincing evidence to the Provost that the Student did not receive any advance notice (either in writing or verbally) of the University’s intent to revoke the Student’s Degree through no fault of the Student. The decision to grant or deny a rehearing shall be made by the Provost and shall be final. The decision shall be made within sixty (60) calendar days of receipt of the request and provided to the Student in writing. If a rehearing is granted by the Provost, a new Hearing Officer shall be assigned to hear the matter.

    1. The Provost or designee may direct the Registrar to place an administrative hold on the issuance of any official transcript for a student to whom a Notice of Intent to Revoke Degree has been sent. The student will be able to request and access unofficial transcripts under the same conditions as any other student.

    1. Nothing in this policy shall be construed to prevent the Provost from agreeing to an informal resolution of the matter with a Student in lieu of, or after, a hearing.

1. **Post-Revocation Steps**

    1. If a Degree is revoked pursuant to Paragraph 5.4 (Student does not request a hearing), 5.11 (University unable to locate Student), or 5.12 (after hearing), then the following actions shall take place:

        1. The Registrar shall ensure that all relevant records of the University relating to the Student are promptly amended to reflect the Degree revocation;

        1. The Registrar shall note the effective date of the revocation on the Student’s transcript and use reasonable efforts to transmit a copy of the official (revised) transcript to the Student; and

        1. The Provost or designee shall use reasonable efforts to notify the Student that the Student is no longer entitled to represent to any person that he or she is the recipient of the revoked Degree and that the Student should take appropriate steps to notify all former and current employers, relevant educational institutions, professional registration bodies or associations, or others as applicable that the Degree has been revoked. If, despite its own due diligence, the University is unable to provide this notice to the Student due to an inability to contact or locate the Student, the University shall place a hold on the Student’s records until such time as it is able to provide such notice. If at the time of the revocation the Student is enrolled at the University, the Provost or designee shall promptly notify the Vice President for Student Affairs and Campus Diversity of the revocation so that the Vice President of Student Affairs and Campus Diversity can consider whether to take any steps pursuant to Executive Order 1073 (2012) and any other applicable policies.

:::

## Enrollment Management and Impaction {#enrollment-management-and-impaction .unnumbered}

::: {.policy-numbering .policy-start-1}

1. As part of The California State University, San Diego State University shall be committed to providing qualified students with the greatest possible access to excellent higher education and lifelong learning. Accordingly, the university shall continue to search for innovative ways to provide access with available funding.

1. Selection criteria shall allow the university to enhance, not compromise, the diversity reflected by our enrollment. Diversity shall remain an important concern of the University.

1. Enrollment management strategies shall evolve with the consultation of various constituencies, so that the use of selection criteria or other techniques shall not distort the current array and balance of programs.

1. Changes in the proportions among lower division, upper division, and graduate division students as well as among majors and professional programs shall be a fundamental policy question. Changes in the relative growth of these populations shall be deliberative, consultative policy decisions.

1. Enrollment management shall take into account and increase where appropriate the impact on the ratio of tenured and probationary faculty to lecturers insofar as it affects faculty responsibilities in teaching, advising, professional growth, shared governance, and curriculum development. Decisions regarding changes in this ratio for the university, colleges, schools, departments, and programs shall occur through consultation.

1. The University shall recognize its commitment to the greater San Diego region, including Imperial County, and in the admissions process shall consider its responsibilities to the region.

    1. The University shall admit all CSU-eligible, upper division place-bound students who reside within its regional service area. Place-bound admission may be determined by

        a. a low-income designation using a measure such as eligibility for application fee waiver, or

        a. an essay addressing place-bound status.

    1. The University shall admit all first-time freshmen who are CSU-eligible with no remedial needs and who reside within its regional service area. This policy shall provide greater access to local students and shall support the Trustees’ policy to reduce the need for remedial coursework.

    1. The University shall admit all first-time freshmen within its regional service area who are CSU- eligible and who graduate from high schools where educational opportunities are limited by economic circumstances.

1. The Committee on Academic Policy and Planning shall annually review the previous year’s outcomes as well as any enrollment management changes proposed by the administration, and it shall annually report to the Senate. This review shall include consultation with, among others,

    a. the Associated Students,

    a. the college councils of chairs, and

    a. administrative divisions, including staff, particularly in units that act as liaisons with the San Diego community and the public schools.

1. The University shall solicit the concerns of external constituencies and shall advise them of anticipated changes in the University’s selection criteria for admission.

:::

## Enrollment Management Strategy {#enrollment-management-strategy .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Preamble: To manage its enrollment effectively, SDSU shall implement a comprehensive admissions process. This process shall support increased access for local high school graduates and community college transfers, respond to a commitment to diversity, and enhance student success while bringing greater fairness in decision-making across the region.

1. **A Comprehensive Model for Admissions:** SDSU shall pursue a comprehensive admissions model yielding students who are more diverse and academically prepared. The guiding principles for this model shall be:

    1. Access for the Local Region – SDSU is committed to serving the larger public with a strong commitment to students from San Diego and Imperial counties.

    1. Access for Diverse Communities – SDSU is committed to providing access to students who have been historically underrepresented and underserved in education.

    1. Enhancing Student Success - SDSU has the responsibility to ensure students who are admitted have the necessary preparation to succeed both at the institution and in their major.

    1. Fairness in Decision-Making – SDSU is committed to admissions practices that foster equitable access to the university, in general, and more specifically for students across K-12 and community college districts in our service area.

    1. Additional considerations that guide the enrollment management process include:

        1. Enrollment targets: Specific target setting discussions should begin at the college level, with participation and engagement from faculty and college leadership.

        1. Fiscal impact: Maintaining or changing the balance of resident to out-of-state students has significant and long-term fiscal implications for the university, which should be considered as part of the target-setting process.

        1. Information sharing: SDSU is committed to providing robust access to information with our K-12 and community college partners.

    1. These Enrollment Management Strategies shall be reviewed annually as part of the systematic review of Impaction and Enrollment Management policies by the Senate Committee on Academic Policy and Planning, as outlined in University Policies: Academics: Enrollment Management and Impaction, 7.0.

1. **Freshman Admissions:** SDSU shall use as a basic foundation for its freshman admissions a comprehensive set of indicators, that may include: but not be limited to:

    1. Grade Point Average (GPA) - GPA is calculated based on the college preparatory courses completed in meeting the California A-G standards. Based on the specific major cluster, differential weights may be used for determining ranked GPA in each A-G area.

    1. SAT/ACT Scores - Academic performance is also assessed based on an applicants’ score on the Scholastic Assessment Test (SAT) or the American College Test (ACT). In cases of multiple re-examinations, the highest overall score is used. The ACT employs the composite score, which does not include the writing section.

    1. College Preparatory Coursework - College Preparatory Coursework may include the total number of math, English, and science courses taken, grades earned in math, English and science courses, as well as participation and grades in Advanced Placement, International Baccalaureate, and dual enrollment coursework.

    1. Local Area - Local area enrollment refers to students who have completed high school in a school or district within SDSU’s service area.

    1. Ability to Thrive in a Diverse Environment - The ability to contribute to and thrive in a diverse environment is an essential component of a healthy campus climate and shall be assessed based on a multitude of factors, such as: progressive involvement in community service and work experiences, educational experiences (e.g., clubs, service, coursework beyond A-G), and biliteracy or multilingual competence (e.g., fluency, candidate for Seal of Biliteracy, AP test scores).

    1. Contextual Factors - Environmental contextual factors shall refer to attendance at public high schools that have high proportions of students who are underrepresented minorities, foster youth, receive free and reduced lunch, and/or are English language learners. In a similar manner, neighborhood characteristics (e.g., median family income, homeownership rates ) may also be employed. In addition, SDSU shall consider special circumstances, such as whether students were in foster care, wards of the court, emancipated minors, homeless, or other factors that may have previously inhibited academic success in high school.

    1. College Preparatory Programs - Participation in approved college-readiness programs supported by educational and/or nonprofit organizations is essential to student success. Programs are approved and assessed for continued partnership by Enrollment Services in collaboration with the Division of Student Affairs and Campus Diversity.

    1. Tribal Affiliation - Tribal affiliation is based on whether prospective students identify as being enrolled members or the dependent of an enrolled member of a Federally Recognized Tribe.

1. Transfer Admissions: SDSU shall use as a basic foundation for its transfer admissions a comprehensive set of indicators, that may include: but not be limited to:

    1. Local Area - Local area enrollment refers to students who have completed community college in a district within SDSU’s service area.

    1. College Transition Programs - Participation in approved college success and transition programs may include existing community college programs such as: Umoja Community, Hermanos-Unidos Brothers United (HUBU), Puente Project, CalWorks, and Extended Opportunity Programs and Services (EOP). Programs are approved and assessed for continued partnership by Enrollment Services in collaboration with the Division of Student Affairs and Campus Diversity.

    1. Deferred Admission - A Local Freshmen Deferred Admission (LFDA) priority may be provided to community college students in SDSU’s service area who were denied admission but graduated from a local high school and were CSU-eligible and are transferring from a local community college. In addition to attending a local community college, students will need to complete the following requirements by spring or fall admission:

        - Complete CSU "Golden Four" course requirements with C- grade or higher

        - Complete a minimum of 60 transferable semester units

        - Complete 30 units of General Education courses (includes CSU Golden Four courses)

        - Complete major preparation courses and meet required GPA for the major

        - Complete the above requirements within three years of their initial application

            Audition and portfolio majors (such as Music, Dance, and Theatre Arts: Performance) or direct admit majors (e.g., Nursing) are excluded from the deferred admission program.

:::

## Examinations and Projects {#examinations-and-projects .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Final Examinations and Projects**

    1. Because of many valid methods of instruction, not all courses may require the standard, comprehensive final examination. When, however, an instructor does conclude a course with a major, comprehensive final examination, that examination shall be given at the place and time scheduled during the final examination week. Other tests such as an hour exam or quiz may be given during the final week of classes. No examinations shall be given on “study and consultation” days.

    1. Although university policy does not demand the administration of a final, comprehensive examination on the day, time, and place specified in the Class Schedule, the days designated for Final Examinations shall be counted among the academic workdays constituting the legally defined semester or session. Every instructor, therefore, shall conduct some class business with students on the day and at the time officially scheduled for the final examination for each course. The instructor may use the scheduled final examination period to review examinations or projects with the class.

    1. Should an instructor determine that final course assignments can be called neither “major, comprehensive final examinations” nor “hour exams” nor even “projects,” the instructor shall exercise professional expertise and responsibility, common sense, and good will to translate the letter and spirit of this policy.

1. **Examinations for Disabled Students**

    Instructors shall give students with certified disabilities time and opportunity to complete examinations without undue disadvantage.

1. **Saturday Examinations**

    1. By the end of the third week of classes, students shall notify instructors of conflict with Saturday examinations for religious observance.

    1. Instructors shall reasonably accommodate students who notify them of conflict with Saturday examinations for religious observance.

1. **Group Examinations**

    1. No department or school shall be assured of more than a single examination period in which to hold common examinations for multiple section courses.

    1. Group examination periods shall be allotted in available spaces according to the number of students.

    1. Requests for special time periods shall be granted only if received in the Office of the Provost in time for announcement in the Class Schedule.

    1. Group midterm examinations requiring the use of hours outside the regular class schedule shall be permitted for multiple section courses that require a common midterm examination. Specific regulations are as follows:

        1. The dates and times of group midterm examinations shall be announced in the Class Schedule.

        1. Regularly scheduled class meetings should be reduced to compensate for the time used to test in-group midterm examinations.

        1. Midterm examinations outside of regularly scheduled class meeting times shall be prohibited for single-section courses (i.e., courses taught in one section during a term).

        1. Sections not participating in a group examination for a multiple section course may hold any midterm examinations during regularly scheduled class periods.

        1. Group midterm examinations shall be scheduled after 4:00 p.m. on Mondays through Fridays. All midterm examinations for a given course shall be scheduled for the same day of the week.

        1. Rooms for group midterm examinations shall be assigned according to available spaces at the times requested and according to the number of students served. Priority in room assignments shall be given to regularly scheduled classes.

:::

## Global Campus {#global-campus .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Degree Programs through Special Sessions

    1. Degree programs providing residence credit may be offered through Global Campus. Students enrolling in these programs shall meet all San Diego State University and California State University entrance requirements. Existing degree programs may be offered through Global Campus if not enough General Funds are available to meet student demand or to serve the needs of those not served by the university.

    1. These degrees shall be offered with the approval of an academic department or school and college and of the Provost in consultation with either the Dean of the College of Graduate Studies or the Associate Vice President for Faculty Advancement and Student Success With the approval of the academic units, the university administration, the Chancellor’s office, and the Postsecondary Education Commission, a degree not already being offered by San Diego State University may be developed and run for self-support through Global Campus.

1. Concurrent Enrollment of Global Campus Students

    1. Non-matriculated students may take regular university courses through concurrent enrollment (Open University) in Global Campus.

    1. Departments or schools and colleges shall have complete autonomy in designating the undergraduate courses in the regular program in which concurrent enrollment students are permitted to register.

    1. Concurrent enrollment in a course shall require the approval of the course instructor.

    1. Concurrent enrollment shall not take place before registration.

    1. Concurrent enrollment shall be permitted in classes that have reached maximum size with regular enrollments only at the request of the instructor of the class.

    1. Concurrent enrollment shall not be the basis for the addition of a new section or the continuation of an under-enrolled section. When enough students enroll to form a separate concurrent enrollment class and if a qualified instructor and adequate facilities are available, a concurrent enrollment section may be established.

    1. Concurrent enrollment students shall meet the same course prerequisites as regular students.

    1. Records shall be kept of registrations through concurrent enrollment for purposes of research and department or school allocation.

    1. There shall be no additional compensation for instructors who accept concurrent enrollment students in regular classes.

    1. Concurrent enrollments shall not accrue as FTEs to departments or schools for budget support purposes.

    1. The net revenue collected from concurrent enrollments in regular classes shall be deposited in the Professional and Continuing Education (PaCE) Fund, one-half of which shall be made available for department or school support.

    1. Concurrent enrollment shall earn resident credit and shall be subject to limitations.

    1. Course requirements and grading procedures shall be the same for concurrently enrolled students as they are for the matriculated students.

1. Certificate Programs and Global Campus Courses

    1. The Undergraduate Curriculum Committee shall periodically review proposed and continuing credit certificate programs.

    1. Courses numbered X-0l through X-79, X-397, and X-997 shall be Extension professional advancement units offered only through Global Campus to meet specific academic needs of community groups. Courses numbered X-01 through X-79, X-397, and X-997 shall not be acceptable for degree programs. All courses numbered X-01 through X-79, X-397, and X-997 shall be processed according to the procedures established for the review and approval of new courses through Global Campus.

:::

## Freedom of Expression {#freedom-of-expression .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Principles: Recognizing that the principles established in the First Amendment of the United States Constitution, Article 1, Section 2 of the Constitution of the State of California, and the California Education Code (sec. 66301) apply to all faculty, staff, and/or students, San Diego State University (SDSU) affirms the following principles of the free expression of ideas:

    1. Freedom of expression is a tenet of higher education; is integral to the mission of the University and to its students, staff, and faculty; is a central and inviolate freedom to learn and teach; necessary for an educated populace; is a requisite to a free society; is incompatible with the suppression of opinions; is incompatible with prior restraint; encompasses forms of expression other than speech; and defends the expression we abhor as well as the expression we support.

1. **Scope**

    1. SDSU supports and promotes freedom of expression and assembly by students, faculty, staff, and the general public. Reasonable regulations may be designed to avoid disruption of the mission of the university, particularly academic instruction, research and creative activity or to protect campus safety and security. See the SDSU Mission and Goals Statement for a more complete explanation of these aspects of the university’s mission.

    1. The intent of this policy is to guide the development of specific regulations regarding the exercise of free expression rights on campus. In developing these regulations, the intent of this policy is to provide as much opportunity for freedom of expression, as is consistent with the limits of the law and section 2.1 hereof.

    1. This policy should in no way be regarded as placing prohibitions beyond those prescribed by law or section 2.1 hereof on the right to express political, religious, philosophical, ideological, or academic viewpoints by any individual on the SDSU campuses. In addition, it is not the intent of this policy to conflict with provisions of collective bargaining agreements that may be in force at SDSU, and those agreements shall control in the event of any conflict.

    1. SDSU does not support cooperation with agencies that unlawfully investigate, surreptitiously monitor or harass persons due to the legitimate exercise of their constitutionally protected prerogatives of free speech and assembly.

1. **Time, place, and manner**

    1. SDSU campuses shall be open to noncommercial speech and expressive activities, subject to appropriate time, place, and manner regulations. Regulations may be created to ensure that the university’s mission of instruction, research, and creative activity is not disrupted and that campus safety and security are not compromised. In drafting these regulations the intention and effect should be to maximize opportunities, in terms of time, place, and manner, for free expression. Regulation of noncommercial free speech and free expression activities shall be content neutral. All legal speech, even offensive speech is permitted. Noncommercial speech and expressive activities by students, faculty, staff and the general public may include but are not limited to: picketing, demonstrating and other forms of peaceful assembly, petitioning, leafleting, postering, the display of signs, tabling, chalking, music, dance, audio-visual and theatrical performances.

    1. Regulations may be created to assure that campus grounds and facilities are available in a fair and equitable manner that has the effect of encouraging opportunities for the expression of diverse points of view. Regulations may be created to avoid competition for resources required for such expression.

    1. Noncommercial speech and expression activities may occur on campus, either indoors or outdoors, where they will not disrupt the university’s mission of instruction, research, or creative activity or threaten safety and security. Regulations may provide for the voluntary reservation of various outdoor and indoor locations on campus, although SDSU is under no obligation to provide or otherwise make available indoor locations or facilities. Individuals and groups who have made such reservations for a given date and time should be granted priority over those who have not. In allocating space and facilities that may be reserved, recognized student, faculty and/or staff organizations may be granted priority over individual members of the university community. Members of the university community may similarly have priority for use of space and facilities over the general public. However, regulations should be designed so that reasonable access to the campus for noncommercial speech and expressive activities is available to all, including those who may not have made a reservation in advance, are not a member of a recognized campus organization, or are not members of the university community.

    1. Additional regulations and reasonable restrictions, such as limits on amplification or decibel levels of sound, may also be established.

    1. Commercial expression, defined as activities designed primarily to sell goods and services or to promote the sale of goods and services, may be regulated by the President in accordance with Trustee policy to a greater extent than noncommercial speech and expressive activities.

1. **Oversight**

    1. Noncommercial Speech and Expressive Activities. The President, in consultation with the Vice Presidents, shall designate a coordinator for events where noncommercial speech and expressive activities are expected to occur. Groups planning such events should be encouraged to work with the coordinator to ensure that these events do not materially disrupt instruction, research, or creative activity or endanger campus safety and security. Prior notification of noncommercial speech and expressive activities shall be voluntary except where advance notice is reasonably required to permit consideration of public safety, disruption to education or similar concerns.

    1. Commercial expression. The President shall designate a coordinator for commercial events held on campus and at SDSU facilities. The coordinator shall be responsible for working with the vendors to ensure that the event is held in accordance with university regulations.

    1. Compliance. Issues regarding compliance with this policy and complaints regarding enforcement of regulations shall be directed to the Committee on Freedom of Expression.

:::

## General Education {#general-education .unnumbered}

::: {.policy-numbering .policy-start-1}

1. General Education courses shall be taught at least once every two years at a San Diego State University campus. A course not taught during this time shall be removed from the General Education program.

1. Courses offered for General Education credit, whether in state-funded semesters or sessions or via the College of Global Campus, shall meet all the standards set forth in the Curriculum Guide regardless of the length of time allotted for the course.

1. The Committee on General Education and its subcommittees shall oversee the General Education program and its curriculum.

1. **Waivers for Engineering**

    1. Engineering majors are exempt from completing a 3-unit course in the “Explorations in Social and Behavioral Sciences” area (CSU GE Area D explorations).

    1. Engineering majors are exempt from completing a 3-unit course in the “Lifelong Learning and Self-Development” area (CSU GE Area E).

:::

## Grades {#grades .unnumbered}

::: {.policy-numbering .policy-start-1}

1. In order that the assignment of grades truly reflects the student’s achievement in courses, the integrity of the academic program, and the integrity of departments or schools and instructors, grades shall genuinely distinguish between high and low levels of achievement. Although no formula for a curve shall be appropriate to all courses offered at the university, instructors shall use all grades from A through F to distinguish among levels of academic accomplishment. The grade for satisfactory performance in a course by an undergraduate student shall be C; the grade for satisfactory performance in a course by a graduate student shall be B.

    1. Undergraduate grades shall be: A, outstanding achievement; B, praiseworthy performance; C, satisfactory performance; D, minimally passing; and F, failing. Graduate grades shall be: A, superior performance; B, satisfactory performance; C, minimally passing; D, unacceptable for graduate degree credit; and F, failing.

    1. Faculty may assign plus and minus grades with the exception of A+, F+, and F-. .

1. **Variations:** Some courses naturally call for varied application of the policy above. Courses graded credit/no credit do not produce the distribution of grades indicated in the grade descriptions above. Courses in which the differential quality of performance is difficult or impossible to assess may be graded other than A through F when authorized by the same officers, agencies, and procedures required for changes in the curriculum. When requested by a department, school, or program, experimental departures from regular grading practices may be authorized in undergraduate courses by the Undergraduate Council.

    Competency-based courses shall normally be graded credit/no credit. Upper division work, including specialized work, shall not be a normal exception to the general grading policy. Although students are prepared to do higher level work than in lower division courses, higher levels of achievement shall be demanded therein for higher grades.

1. **Administration of Policy**

    1. To facilitate common understanding of grading policy, each department, school, and program shall have a grading policy based on University policy and elaborating all general and special applications of the policy acceptable to the relevant college academic policy and planning committee and on file in the college dean’s office. Departments, schools, and programs are encouraged to consider whether and to what extent generative AI tools may be used to assist faculty in the grading process.

    1. Every member of the faculty shall assign grades in his or her classes in conformity with the policies set forth above. To facilitate common understanding between the instructor and students, the specific coordination of course requirements and University grading policy shall be presented to the students at the beginning of a course.

        1. Faculty are responsible and accountable for the grades they assign. Instructors of record shall disclose to their students any use of generative AI tools in grading.

        1. Faculty are responsible for setting grading expectations and criteria for their graders and TAs, including the use, if any, of generative AI tools in grading. TAs and graders shall not deviate from these criteria.

    1. Responsibility for maintaining department, school, or program integrity in grading practices shall rest with the department or program chair or school director. Every semester or session the chair or director shall receive data on grades awarded in courses offered in the department, school, or program. The chair or director shall compute and distribute the department, school, or program grading data according to internal procedures. The department, school, or program shall maintain grading integrity chiefly through discussions of grading practices and peer pressure. An instructor who provides a professionally defensible explanation for marked or persistent departure from predictable grading patterns shall be in conformity with policy.

    1. Late Grade Submission: Every instructor shall report grades to the Office of the Registrar by the published due date corresponding to that semester. Not turning in grades on time shall constitute failure to perform the responsibilities of the position (cf. California Education Code, sec. 89535(f) and CSU Executive Order 1037). Grade submission duties include submitting a grade change form to convert an Incomplete (I) into a final grade (A-F), and conversion of a Report in Progress (RP) to Credit or No Credit. Additional responsibilities for timely resolution of I and RP grades are described in 4.5 and 4.6 below. Failure to comply with this policy (for reasons other than illness, emergency, or incapacitation) shall result in progressive discipline, including written warnings, reprimands, and, in the case of repeated incidents, disciplinary action as stated in the Collective Bargaining Agreement. If grades have not been submitted fifteen days past the published due date, the department chair or school director may submit grades in the instructor’s stead.

    1. The instructor is responsible for notifying their department chair or school director if they cannot meet the responsibilities described in 4.5.4 and 4.6.4 for any reason. If grades have not been submitted fifteen working days past the semester’s due date for any reason, the department chair or school director may shall submit grades in the instructor’s stead. The chair or director shall identify a qualified faculty designee to evaluate student work and develop final grades for submission by the department or school. Transition of grade submission responsibilities shall include grade change forms for expiring I and RP agreements. The fifteenday grade submission grace period may not be extended for faculty illness, emergency, incapacitation, or other extenuating factors.

1. **Options, Computation, and Registration of Grades**

    1. Registration of Grades: At the end of each semester or session in which a student is enrolled, a report of courses taken, showing units used in reporting shall be as follows: Grade of A (outstanding achievement), 4 points; B (praiseworthy performance), 3 points; C (average), 2 points; D (minimally passing), 1 point; F (failing), 0 points; the Plus (+) notation adds 0.3 grade points per unit; the Minus (-) notation subtracts 0.3 grade points per unit; I (incomplete), counted as units attempted after one year, 0 points; SP (satisfactory progress, used through summer 2002), not counted in the grade point average; RP (report in progress, introduced in fall 2002), not counted in the grade point average; W (withdrawal), not counted in the grade point average; Audit, no credit earned and not counted in the grade point average; Cr (credit), signifying units earned but not counted in the grade point average; NC (no credit), no credit earned and not counted in the grade point average; U (unofficial withdrawal, used through summer 2002), counted as F for grade point average and progress point computation; WU (withdrawal unauthorized, introduced fall 2002), counted as F for grade point average and progress point computation.

    1. Undergraduate Student Options on Grading[^fn10]

        1. Credit/No Credit: An undergraduate student may elect to be graded credit/no credit (Cr/NC) in particular courses subject to the following conditions: (a) election of this option shall not be used as a criterion for denying admission to a course; and (b) students electing Cr/NC grading shall be held accountable to the same academic requirements and standards as students taking a course for a letter grade.

        1. Courses graded Cr/NC, whether taken at this or at another institution, shall not be used to satisfy requirements in the major or upper division courses in the minor except for those courses identified in the course listing as graded Cr/NC.

        1. No more than 15 units graded Cr/NC shall be offered in satisfaction of the total units required in a bachelor’s degree program, except that all units accepted as transfer credit from another institution at the time of the student’s admission may be used. If 15 or more units graded Cr/NC are transferred, the student shall offer no additional courses graded Cr/NC to satisfy total units required for a bachelor’s degree. Exceptions to this rule may be made if a student is required to take a San Diego State University course for credit/no credit.

            1. If for a reason such as change of major or minor or transfer from another institution courses graded Cr/NC are offered to satisfy requirements in the major or upper division course requirements in the minor, the student may be required by the department or school to pass competency examinations at an acceptable level or to take prescribed alternate courses before continuing in the major.

            1. Selection of the grading basis (A through F or Cr/NC) shall be made at the time of registration for the course. Change of grading basis may be made on or before the last day of the schedule adjustment period.

            1. A grade of Credit shall be awarded for work equivalent to A, B, or C. No Credit shall be awarded to work equivalent to C–, D, or F.

            1. A grade of C- or better is required in each CSU or transfer course in English composition (Area 1A), critical thinking (Area 1B), oral communication (Area 1C) and mathematical concepts and quantitative reasoning (Area 2). (Title 5 Sections 40803, 40804, 40804.1). As such, the Cr/NC option at SDSU shall not be used for courses in these areas of the CSU General Education (GE) Requirements. The election of the Cr/NC option shall be solely at the discretion of the student.

    1. Graduate Student Options on Grading:

        1. Credit/No Credit: Courses with a letter grade option may not be applied to a graduate degree if the earned grade is Credit, rather than a letter grade. Only courses 500 and above may be applied to graduate degree requirements. No undergraduate courses graded credit/no credit shall be assigned to the deficiencies or foreign language option(s) of a master’s degree program.

        1. At least 70 percent of the units used to fulfill the minimum requirements on a master’s degree program shall be letter graded.

    1. Grade Point Average (GPA): To compute the grade point average, one shall divide the total number of grade points earned by the number of units attempted. Units earned with a Cr (credit) shall not be included in the computation nor shall an I (incomplete) until it has been converted to Incomplete Charged (IC). The minimum cumulative GPA requirements shall be the same for Good Academic Standing, avoiding Academic Disqualification, and awarding a degree.

    1. Incomplete Grade

        1. An incomplete shall signify that a portion of required course work has not been completed and evaluated in the prescribed time period due to unforeseen, but fully justified, reasons and that there is still a possibility of earning credit. An Incomplete shall not be assigned if the only way the student could make up the work would be to attend a major portion of the class when it is next offered. It shall be the student’s responsibility to bring pertinent information to the instructor and to reach agreement on the means by which the remaining course requirements shall be satisfied.

        1. The maximum time to resolve an incomplete shall be one year, defined as follows. For an incomplete from the Fall term, the instructor shall submit a grade change no later than the next Fall term’s grade reporting deadline. For an incomplete from the Spring term, the instructor shall submit a grade change no later than the next Spring term’s grade reporting deadline. For an incomplete from the Summer term, the instructor shall submit a grade change no later than the next Summer term’s grade reporting deadline. This one-year limitation shall prevail whether or not the student maintains continuous enrollment.

        1. The instructor shall assign a deadline for the student to complete their work that is appropriate for the extenuating circumstances and the nature of the outstanding assignments. The student’s work completion deadline shall account for time that the instructor will need to evaluate the submission, and meet the grade submission deadline described in 4.5.2.

        1. The instructor shall evaluate the student’s submission in a timely manner. A grade change form shall be submitted by the earlier of 1) six weeks after receiving the student’s work, or 2) the deadlines outlined in 4.5.2 (assuming that the student has met the work completion deadline that they were assigned). An instructor who is unable to meet their instructional responsibility for any reason is obligated to inform the department chair or school director, who shall assume grade submission responsibilities described in 3.5. Failure to report a grade change by the deadlines outlined in 4.5.2 shall result in the incomplete being replaced with Incomplete Charged (IC) on the transcripts, which is counted as equivalent to an F for grade point average and progress point computation.

        1. A candidate for graduation with the baccalaureate degree whose record carries a grade of incomplete shall not be graduated until the incomplete is resolved or changed to Incomplete Charged (IC). No grade changes shall be made after the degree has been granted.

        1. A candidate for graduation with a post-baccalaurate degree (to include advanced certificates) whose record carries a grade of Incomplete (I) will not have their graduation canceled if 1) the course is not required for the degree, 2) all degree requirements have been met, and 3) conversion of the I to Incomplete Charged (IC) would not result in loss of Graduate Academic Good Standing. Grades of I are converted to IC at the time of graduation. Students who do not wish to graduate with a grade of IC on their permanent transcripts must formally cancel their application for graduation. No grade changes shall be made after the degree has been granted

        1. Extension of time limit for I shall receive prior authorization by the corresponding academic college Dean (for undergraduate courses) or the Dean of the College of Graduate Studies (for graduate courses), or their designees.

    1. Report in Progress Grade (RP)

        1. RP shall be used for courses that extend beyond one academic term. It shall indicate that work is in progress and has been evaluated and found to be satisfactory to date but that assignment of a precise grade awaits completion of additional work. Instructor responsibilities related to RP grades shall be the same as those associated with I grades, as described in section 4.5. Cumulative enrollment in units attempted shall not exceed the total number applicable to the student’s educational objective. Extension of time limit shall receive prior authorization by the Associate Vice President for Faculty Advancement and Student Success (for undergraduate courses) or the Dean of the College of Graduate Studies (for graduate courses).

        1. For all courses except graduate research (797), thesis (799A) and doctoral dissertation (899), the maximum time to resolve a report in progress shall be one year, as described in section 4.5.2. For 797, work shall be completed within two years. For 799A and 899, work shall be completed within the overall time limit for completion of all degree requirements.

        1. The instructor shall assign a deadline for the student to complete their work using the guidelines described in section 4.5.3.

        1. The instructor shall evaluate the student’s submission in a timely manner using the guidelines described in section 4.5.4. Failure to report a grade change by the required deadlines shall result in the report in progress being replaced with No Credit (NC) on the transcripts.

        1. A candidate for graduation with the baccalaureate degree whose record carries a grade of report in progress shall not be graduated until the report in progress is resolved or changed to No Credit (NC). No grade changes shall be made after the degree has been granted.

        1. A candidate for graduation with a post-baccalaureate degree (to include advanced certificates) whose record carries a grade of No Credit (NC) will not have their graduation canceled if 1) the course is not required for the degree, and 2) all degree requirements have been met. Grades of RP are converted to NC at the time of graduation. Students who do not wish to graduate with a grade of NC on their permanent transcripts must formally cancel their application for graduation. No grade changes shall be made after the degree has been granted.

        1. Extension of time limit for RP shall receive prior authorization by the corresponding academic college Dean (for undergraduate courses) or the Dean of the College of Graduate Studies (for graduate courses), or their designees.

    1. Uncompleted Theses

        1. Students shall be registered in 799A or 799B when their thesis is submitted to the publishing unit for formatting review.

        1. A student who registers for course 799A (Thesis), but does not submit the thesis for formatting review by the end of the semester or session, shall be assigned a grade of RP (report in progress). This grade symbol shall remain on the student’s record until the thesis is approved by all parties and published by the university. If at the end of two years the thesis is not completed, the grade NC (no credit) shall be recorded unless an extension of time for completion due to extenuating circumstances has been recommended in advance by the thesis committee chair and the graduate advisor, and is approved by the Dean of the College of Graduate Studies. A second registration in course 799A, Thesis, shall be expressly prohibited.

        1. A student who has been assigned the RP for Thesis shall be required to register for course 799B (0 units, Cr/NC) in a semester or session in which the student expects to use the facilities and resources of the university.

1. **Challenges and Revocations**

    1. The instructor’s grading practices shall meet the highest professional standards of objectivity, fairness, and accuracy. Testing procedures shall be designed reasonably to measure the attainments of students in the subject matter covered by the course.

    1. Student grievance procedures shall offer the student a means of redress if an instructor has abused university grading policy. They also shall offer the instructor redress if falsely charged with abuse of University grading policy.

    1. Except as authorized by policies and procedures approved by the Senate, no grade for a course shall be assigned or changed except by the instructor responsible for the course.

    1. If a student receives a lower grade than earned in a course due to a mistake by the instructor, the instructor shall direct the Office of the Registrar to raise the grade by completing the required form. If the grade is to be lowered, the change shall have the approval of the dean of the appropriate academic unit. The student shall be notified by the registrar when a change becomes an official part of the student’s record.

    1. The instructor is expected to administer examinations or other exercises measuring the level of student attainment in a manner reasonably calculated to minimize the possibility of dishonesty by the student. When plagiarism or other dishonesty does occur, normal grade expectations are altered.

1. **Good Academic Standing**

    1. Undergraduate Academic Good Standing: Academic standing for undergraduate students shall be determined by the grade point average earned in university courses. At the undergraduate level, good academic standing shall mean that the student has an overall cumulative GPA and an SDSU cumulative GPA of 2.0 or better.

    1. Graduate Academic Good Standing

        1. Graduate students are considered to be in Good Standing with the College of Graduate Studies if they:

1. maintain good academic standing with the university (based on cumulative GPA),

1. are in good judicial standing (as defined by the Center for Student Rights and Responsibilities),

1. make continued good progress toward the degree each semester (as defined by the graduate program),

1. maintain matriculation (enroll in classes or file Leave of Absence, each Fall and Spring semester).

        1. Appeals may be submitted in writing to the Graduate Dean to reinstate Good Standing with the College of Graduate Studies. The consequences for loss of Good Standing may also be appealed in writing to the Graduate Dean.

1. **Undergraduate Disqualification and Reinstatement**

    1. Academic Notice and Disqualification

        1. An undergraduate student whose grade point average falls below a C average (2.0) for either all baccalaureate-level college work attempted or all work attempted at San Diego State University shall be placed on academic notice at the end of the semester. Provided a student earns a C average or better in San Diego State University work during the semester while on academic notice, academic notice may be continued up to a maximum of three semesters. Academic notice shall be lifted when the student has attained a C average or better on all baccalaureate-level college work attempted and on all work attempted at San Diego State University.

        1. An undergraduate student on academic notice shall be disqualified at the end of the fall or spring semesters if the student’s GPA in all units attempted or in all units attempted at SDSU falls below the following as a freshman (up to 30 units earned), 1.5; as a sophomore (30-59 units earned), 1.7; as a junior (60-89 units earned), 1.85; as a senior (90+ units earned), 1.95. Undergraduate students who are on academic notice shall be subject to disqualification at the end of the semester in which their academic record first falls to or below the disqualification level as defined in Title 5 of the California Code of Regulations, sec. 41300, and Executive Order 1038 (2008).

    1. Reinstatement Principles

        1. First Consideration

            1. Except under exceptional circumstances, a disqualified student may not be reinstated earlier than the third semester after disqualification. Disqualified students seeking reinstatement shall petition for readmission or reinstatement during the normal admission application periods established by the university. Under exceptional circumstances, the Director of the Student Ability Success Center (SASC) or an Assistant Dean for Student Affairs may initiate a petition on behalf of a student for reinstatement before the third semester. Such petitions shall be reviewed in the same manner as other reinstatement petitions.

            1. Criteria for the adjudication of an application include either or both of the following: (a) removal of the conditions that caused the initial poor academic performance that led to disqualification and (b) evidence of baccalaureate coursework applicable to the student’s degree program at San Diego State University. The coursework shall be at a level clearly indicating progress to degree completion.

            1. The dean or designees of the college of the applicant’s proposed major shall make decisions on reinstatement.

            1. Previously disqualified students shall be readmitted with probationary status.

        1. Second Consideration: Normally, students who have been disqualified twice from San Diego State University shall not be considered for reinstatement.

1. **Unofficial Withdrawal (WU)**

    The symbol WU shall indicate that an enrolled student did not withdraw from the course but failed to complete course requirements. It shall be used when, in the opinion of the instructor, completed assignments or course activities or both were insufficient to make normal evaluation of academic performance possible. For purposes of grade point average and progress point computation, this symbol shall be equivalent to an F. The U shall be awarded to a student who has not completed any graded work in the class.

1. **Official Withdrawal (W)**

    After the Schedule Adjustment Deadline, a student may withdraw from a course(s) under conditions outlined below. For late withdrawals processed from the Schedule Adjustment Deadline through Census, all notation of the course shall be deleted from the student’s record; for late withdrawals processed after Census, the symbol W shall replace an assigned grade. Summer Session deadlines may vary.

    1. Late Schedule Adjustment

        1. Withdrawing from a course(s) after the Schedule Adjustment Deadline and before the last 20% of instruction shall be permitted only for unforeseen serious and compelling reasons. All such requests shall be accompanied by appropriate verification. Undergraduate students may withdraw from no more than 18 semester-units attempted at SDSU. Permission to withdraw from a course(s) during this period shall be granted only with the approval of the instructor, the approval of the College dean or designee (Graduate Dean or designee in the case of graduate students). Permission to withdraw from all courses in the current term shall be granted with approval of the College dean or designee (Graduate Dean or designee in the case of graduate students). Catastrophic Withdrawals (see 9.1.2.) during Late Schedule Adjustment do not count toward the unit maximum.

        1. Catastrophic Withdrawal: Students shall not be permitted to withdraw from a course(s) during the final 20% of instruction except in cases, such as accident or serious illness where the cause of the withdrawal is due to circumstances clearly beyond the student’s control and the assignment of an incomplete is not practical. All such requests shall be accompanied by appropriate verification. Such withdrawals will not count against unit maximums in 9.1.1. Permission to withdraw from a course during this period shall be granted only with the approval of the instructor, the College dean or designee (Graduate Dean or designee in the case of graduate students), and an Academic Affairs administrator appointed by the president. Permission to withdraw from all courses in the current term shall be granted with approval of the College dean or designee (Graduate Dean or designee in the case of graduate students) and the Academic Affairs Administrator or designee. For graduate students,withdrawal from one or more courses during the final 20% of instruction shall require the written acknowledgment of each instructor, who shall indicate the student’s grade in the class, and approval of the Graduate Dean or designee.

    1. Retroactive Withdrawal

        1. After the last day of the semester or session, an undergraduate student who wishes to change assigned grades to W grades may request to withdraw from either individual courses, or the full semester’s or session’s work. Graduate students must petition for retroactive withdrawal from all courses in a prior semester; exceptions for partial retroactive withdrawal based on unusual circumstances may be approved by the Graduate Dean or designee. Retroactive withdrawal may be granted only in cases such as accident or serious illness where the cause for substandard performance was beyond the student’s control. All requests shall be accompanied by appropriate verification. Only those retroactive changes from an assigned grade to a W shall be made that are approved by the dean or designee (including assistant deans) of the college of the student’s major (Graduate Dean or designee in the case of graduate students) and the Academic Affairs Administrator or designee.

        1. For graduate students, each retroactive change from an assigned grade to a W shall require written acknowledgment from the instructor who assigned the original grade except that (a) the Graduate Dean or designee may authorize the change of U or WU to W and (b) department chairs or school directors shall act on behalf of instructors no longer affiliated with the university or absent from the university for a length of time that would unduly delay processing the withdrawal request.

        1. For graduate students, retroactive withdrawal must be filed within two years after grades are posted. Approval beyond that time may be granted by the Graduate Dean or designee in highly unusual circumstances, unless a degree has been awarded and the transcripts are sealed.

1. **Repeated Courses and Grade Forgiveness for Undergraduate Students**

    1. A student who receives a grade of C– or lower (fewer than 2.0 grade points per unit) may request that the course repeat policy for grade forgiveness be applied to that course. Students may request up to a limit of 16 units for course forgiveness. The course repeat policy shall be applied to courses taken at San Diego State University, except where enrollment is restricted or the student no longer qualifies for admission to a course.

    1. A course may be repeated once for grade forgiveness. Although the original grade(s) shall remain on the transcript, only the latest grade shall be used in calculating grade point averages. Courses taken in summer term and courses taken through Open University shall be counted for grade forgiveness.

    1. If a student repeats a course in which a grade of C or better was received, only the original grade and units earned shall be used for calculation of grade point average and units needed for the degree. In addition, the only courses that may be repeated with a credit/no credit option are those in which the student previously received a grade of no credit; if a course taken for a grade is repeated credit/no credit, the original grade shall continue to be used in computing grade point average.

    1. The repeat policy for grade forgiveness for a specific course shall be applied automatically unless the student notifies the Office of the Registrar before the end of the change of program period.

        The grade earned in that course that semester or session shall be used to calculate grade point averages. In cases where a student exceeds the allowed number of grade forgivenesses, he or she shall have the right to define which courses receive grade forgiveness.

    1. A course shall not be repeated for grade forgiveness by a student found by the Office of Student Rights and Responsibilities to be guilty of academic dishonesty in that course.

    1. Enrollment in a repeated course shall not be allowed if the student has already cumulatively repeated 34 units of coursework.

[^fn10]: For courses taken during the Fall 2020 semester, a change in grading basis may be made on or before Friday, December 10 by 11:59 p.m. via Petition for Credit/No Credit from the Registrar's office.” 2. All courses shall be made available to students as Credit/No Credit for the Fall 2020 semester. All students shall be allowed to request to change any course they are currently enrolled in to Credit/No Credit grading for the Fall 2020 semester. To request a change in grading basis for a Fall 2020 class, students must email a completed Late Schedule Adjustment Petition to the Registrar's Office on or before 11:59 PM Pacific Daylight Time on Friday, December 10, 2020. Students shall consult with appropriate academic and financial aid advisors before changing their grading bases in any class. Deans shall work with their Chairs, Directors, and Faculty to provide students with guidance in making decisions about changing grading status. These recommendations should balance the following salient concerns: A. The need to ensure that students remain in good standing in their programs. B. The need to ensure that students can make progress towards their degrees/certificates and within the constraints imposed by accreditation and certification, as well as student specific restrictions such as those on student veterans, student athletes, international students, and those on specific types of financial aid. C. The need to offer students reprieve in the form of a Credit/No Credit option in the context of the COVID-19 pandemic. D. The understanding that under EO 1037, students will not be able to repeat a C / NC course for a letter grade at a later date. E. SDSU will waive the 15-unit maximum policy in Fall 2020 and any COVID-impacted semester. 3. College Deans and appropriate faculty committees are asked to review blanket exceptions established during Spring 2020 allowing Cr grades to count for graduation requirements (impaction, major prep, major) and notify the Office of Advising and Evaluation no later than November 30, 2020 if they wish to extend these through Fall 2020, bearing in mind the need to ensure that students can make progress towards their degrees/certificates and within the constraints imposed by accreditation and certification, as well as student specific restrictions such as those on student veterans, student athletes, international students, and those on specific types of financial aid. (Passed Senate meeting November 10, 2020, extended indefinitely for all COVID-19 impacted semesters).

:::

## Graduation {#graduation .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Approval of Candidates for Graduation**

    1. Each semester, lists of candidates for graduation shall be made available to faculty by Enrollment Services. Lists shall be distributed as follows: (a) Senate office, one copy of all lists; (b) Office of the Provost, one copy of all lists; and (c) For each major, one copy of candidates for graduation will be distributed to the corresponding academic department, school or equivalent unit.

        Faculty shall be notified of the distribution. At the final Senate meeting of each academic term, the Senate will be presented a report which contains the number of candidates for graduation (aggregated by college and major), comparative information, and details on how Enrollment Services will be evaluating each candidate to ensure that all degree requirements have been met. The report will also specify how late graduation candidates will be managed and evaluated in accordance with CSU and SDSU policies.

    1. Faculty objecting to the appearance of any candidate’s name on any of the graduation lists may register such objections through the department chair or school director or the Senate office. The objections shall be forwarded to the Provost, who shall investigate the objections and report to a closed session of the Senate Executive Committee. The Provost shall make necessary adjustments in the graduation list.

1. **Summer Graduation:** The faculties of the summer session shall be expressly delegated the authority by the faculty of the university to act for the faculty of the university in the matter of recommending all candidates for graduation at the end of the summer session.

1. **Required Scholarship for Graduation**

    1. Time Limit on Completion of Requirements for the Major: As authorized by Title 5 of the California Code of Regulations, sec. 40401, departments or schools may require that specific baccalaureate degree requirements be met within as few as seven years of the date of the degree. The requirements shall consist of advanced courses and examinations in areas of knowledge changing so rapidly that information may be obsolete after seven years. Proposals to identify degree requirements subject to the seven-year restriction shall be approved by the department or school, college, and university. The requirements shall be identified in the General Catalog, and departments or schools shall keep evaluators informed how students may certify recency of subject matter. When a student is required to repeat a course taken more than seven years before, only the last grade shall be used in computation of the grade point average.

    1. Scholarship required by Title 5 reads:

        “40402. Required Scholarship. Each undergraduate student shall complete with a grade point average of 2.0 (grade C) or better:

        a. All units applicable toward a degree, including those accepted by transfer from another institution;

        a. All units in the major; and

        a. All units attempted at the college granting the degree except that only those courses in which a letter grade (A, B, C, D, F) is assigned shall be used in computing grade point average.”

            Proposals to interpret the work “applicable” in 40402(a) as excluding from the calculation of the GPA all courses for which a failing grade have been recorded shall be improper and unacceptable.”

1. **Graduation with Honors**

    1. Graduation with honors shall be granted to those undergraduate students in each graduating class who achieve high grade point averages. Excellence shall be recognized at three levels: cum laude (3.50–3.64), magna cum laude (3.65–3.79), and summa cum laude (3.80–4.00).

    1. For determination of eligibility, two grade point averages are computed; both shall satisfy the minimum grade point average for the appropriate honors designation: (a) the GPA calculated on all units taken at this institution (a minimum of 24 graded units), and (b) the overall (cumulative) grade point average (including both San Diego State University and transfer units).

    1. Grades for the final semester’s or session’s work shall be included in calculation of eligibility for graduation with honors. Students shall be tentatively designated as eligible for graduation with honors if the GPA meets required standards at the beginning of the fall semester for mid-year graduates, and at the end of the fall semester for May and summer session graduates. Notation of cum laude, magna cum laude, or summa cum laude on transcripts and diplomas shall be based on achievement when all courses for graduation are completed. Grades for removal of incompletes and all other grade changes shall be received in the Office of the Registrar no later than the end of the fifth week of the semester in which the student plans to graduate, and the student shall file an application for graduation before the published deadline.

    1. Upon recommendation of the major department or school, a student doing superior work in his or her major field may be graduated with distinction in that field.

    1. Honors lists shall be distributed to the Senate Executive Committee, rather than to the entire faculty.

1. **Outstanding Graduates/Outstanding Graduates**

    1. At Commencement each college and the Office of Faculty Advancement and Student Success shall select an Outstanding Graduate who shall receive a bachelor’s diploma on behalf of the graduating class.

    1. To be eligible for Outstanding Graduate, a student shall complete the college course in not over 10 semesters (excluding summer sessions) and shall have not fewer than 54 units in residence at San Diego State University. Three quarters shall equal two semesters.

:::

## Honorary Degrees {#honorary-degrees .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Nominations of persons to receive honorary degrees shall be encouraged from any member of the San Diego State University community, including Trustees, the Chancellor, presidents, faculty, students, staff, alumni, Campus Advisory Board members, and other friends of the university. Nominations originating in any of the campus communities shall be submitted to the President of the University.

1. The Advisory Committee on Honorary Degrees shall review all nominations and submit recommendations to the President.

:::

## Honors Societies, Student {#honors-societies-student .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Academic Honor Societies: An academic honor society shall be a campus organization that values and reinforces the high academic standards of the university and selects its members, at least in part, based on superior academic performance.

1. Honor societies shall receive academic sanction by the university through the appointment of a faculty adviser subject to approval by the Provost.

1. Honor societies shall be required to obtain on-campus status through the Office of Vice President for Student Affairs and Campus Diversity. Campus wide multidisciplinary honor societies shall be required to obtain approval from the Provost.

1. Honor societies with on-campus status shall be represented by the Honors Council.

:::

## Hybrid, Online and Intercampus Classes: Definitions and Scheduling {#hybrid-online-and-intercampus-classes-definitions-and-scheduling .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Hybrid, online, and intercampus classes involve a formal educational process in which student and instructor are not necessarily in the same physical location, but interact in a synchronous or asynchronous manner through technology. Classes in which 20% to 50% of the scheduled sessions are conducted through this process are defined as hybrid. Classes in which greater than 50% of the scheduled sessions are conducted through this process are defined as online. Classes in which the instructor is located on one SDSU campus and interacts with students on another SDSU campus shall be defined as intercampus; such intercampus classes shall be arranged through consultations between the instructor and the appropriate personnel on each campus. For all three class modes, any required synchronous interactions (e.g. weekly sessions, aperiodic examinations, capstone presentations) shall be clearly established in the official schedule of classes with respect to specific dates, days, times, and locations as appropriate.

1. **The following guidelines shall apply to new hybrid and online classes.**

    1. The initial offering of a given course by a given instructor in hybrid and online modality shall be established through consultations between the instructor of record, the department chair, the college curriculum committee, and the associate dean of the college. An example “Initial Offering of Hybrid or Online Class” form to facilitate such consultations may be found in the Curriculum Guide. Each college shall establish and disseminate specific policies, expectations, and timelines for the submission and approval of such hybrid/online courses and instructors. Proposed hybrid/online course-instructors pairings that have not been previously approved through the college’s established process may be removed from the schedule of classes by the Dean’s office.

    1. Hybrid online classes shall be so identified in the official schedule of classes, which shall notify students of any required participation in synchronous class activities beyond those session times indicated in the schedule of classes.

    1. The schedule of classes shall notify students of any software and hardware required for participation in class meetings taking place when the student and instructor will not be in the same physical location.

    1. Ownership of materials, faculty compensation, copyright issues and the use of revenue derived from the creation and production of hybrid and online classes, including software, or other media products shall be in accordance with the policy on Intellectual Property.

    1. Regardless of the modality in which they are offered, classes should be consistent in terms of purpose, scope, quality, assessment and expected learning outcomes with other classes bearing the same department code, number, and course title. Courses shall meet all the standards set forth in the Curriculum Guide regardless of their modality.

    1. Students enrolled in hybrid and online classes shall not be denied access to advising, grievances, or other key academic rights and services, nor shall they be excused from the academic responsibilities expected of all students.

:::

## SDSU Imperial Valley: Curriculum and Academic Policy {#sdsu-imperial-valley-curriculum-and-academic-policy .unnumbered}

::: {.policy-numbering .policy-start-1}

1. An SDSU Imperial Valley Admissions Board shall have authority to apply principles acceptable to the San Diego State Enrollment Services Board in admitting special applicants, especially in regard to Title 5, sec. 50801 (Adult Special Students).

1. All curricular activities and academic programs of IV Imperial Valley shall maintain and reflect the traditions and standards of San Diego State University. All graduates from SDSU Imperial Valley shall be awarded San Diego State University degrees.

1. Curricular Procedures: Curricular proposals for new courses, new minors, new emphases, topics courses, and changes in courses, programs, and degrees offered at SDSU Imperial Valley shall be initiated either by the IVC or by academic departments or schools of the San Diego campus; however, in either case such initiations shall be approved both by SDSU Imperial Valley and by the relevant San Diego campus department or school and college before University review and approval.

    1. Furthermore, San Diego campus departments or schools and their colleges shall by committees and periodic reviews share with the SDSU Imperial Valley the responsibility for the quality of IVC programs and courses.

    1. With consultative approval of the relevant academic departments or schools and the Chairs of the Curriculum Committee and Graduate Council of the San Diego campus, SDSU Imperial Valley may make minor substitutions in approved programs to fit local needs and faculty availability.

    1. Requests to implement an undergraduate degree already offered at the San Diego campus shall be routed as follows: SDSU Imperial Valley faculty, SDSU Imperial Valley Dean, San Diego campus department or school, San Diego campus college and dean housing the mirrored degree, Senate, the President (or designee).

:::

## Intellectual Property {#intellectual-property .unnumbered}

::: {.policy-numbering .policy-start-1}

1. The intellectual property policies of the university shall consist of two components: (a) the SDSU Patents policy and (b) the SDSU Copyrights, Trademarks, and Trade Secrets policy. Intellectual property shall include works of authorship, inventions, and discoveries that may be subject to protection by copyrights, trademarks, patents, and trade secrets. (See also Copyrights, Trademarks, and Trade Secrets; and Patents.)

1. These intellectual property policies shall foster and encourage the development of creative works and further to protect the rights of all parties involved, namely: San Diego State University, the San Diego State University Research Foundation, San Diego State University faculty, staff, and students, and external sponsors and contractors. Furthermore, these policies shall serve to educate the university community in the proper use of intellectual property and the application of intellectual property law.

1. Members of the university community shall become familiar with the provisions of these policies before engaging in activities covered by these policies. It may be necessary to disclose the creation of intellectual property and to sign a written agreement regarding this work. Inquiries concerning these policies shall be addressed to the Vice President of Research and Innovation.

:::

## Major {#major .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Declaration of Pre-major and Major**

    1. Newly admitted freshmen shall be admitted to a pre-major or as undeclared. Newly admitted transfer students shall be admitted to a major or pre-major.

    1. A lower division student may request a change from one pre-major to another pre-major at any time; similarly, a lower division student may change from undeclared to a pre-major at any time.

    1. Every upper division student shall have a declared major or pre-major.

    1. A student may major in two departments or schools. All requirements for both majors shall be satisfied; units for courses that could satisfy requirements in both majors shall be counted only once.

    1. A student may earn two majors in one department or school only where specific combinations of majors are authorized in the Catalog. All requirements for both majors shall be satisfied; units or courses that could satisfy requirements in both majors shall be counted only once. Students pursuing two majors in one department or school shall be required to file with the Office of Evaluations a master plan approved by the major department or school.

1. **Changes in Undergraduate Major**

    1. An upper division student may request a change from one major to another major at any time. Upper division students wishing to change majors into any subject area that has limited admission quotas may do so only with written permission from the department, school, or program. Such transfers shall be counted toward the quota established for each academic subject area concerned.

    1. The catalog in effect at the time of a change in major shall govern the requirements for that major, unless the student elects to meet the requirements in effect at the time of graduation.

:::

## Matriculation by Faculty Members {#matriculation-by-faculty-members .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Members of the faculty of San Diego State University may be candidates for degrees on this campus.

1. Faculty may not seek degrees or register for courses within their own departments, programs, or schools and retain faculty status in that unit.

:::

## Minor {#minor .unnumbered}

::: {.policy-numbering .policy-start-1}

1. The minor shall provide the opportunity to develop a degree of competence in a field beyond the area of major course of study. Like the major, the minor shall offer an integrated and coherent pattern of coursework organized around the principal areas of interest or subfields of academic disciplines and interdisciplinary areas. It shall combine lower and upper division coursework in proportions appropriate to the various disciplines.

1. **Units**

    1. The minor shall consist of 15–24 units, the specific number to be determined by the academic departments, schools, and programs and approved through the normal university curricular process. Minors that require considerable lower division preparation for upper division work shall tend to include more units than others.

    1. Normally, 12 units of coursework in the minor shall be upper division. A minimum of six upper division units shall be completed at San Diego State University. In minors where the number of prerequisite lower division units precludes taking 12 upper division units without exceeding a total of 22 to 24 units, the required upper division coursework may be reduced to six units with the approval of the Undergraduate Curriculum Committee.

1. **Subject Areas**

    1. Departments, schools, and programs offering minors shall indicate the specific subject areas to which individual courses relate rather than permit a merely random selection of courses from a department, school, or program.

    1. The subject areas in which programs in the minor are offered should be such that the limited number of units required in a minor is sufficient to enable a student to achieve a reasonable degree of competence in the area. The degree of competence achieved shall be considerably less than that required by a major but should nevertheless constitute a worthwhile educational objective.

1. Courses taken in satisfaction of a minor may be used to meet requirements in General Education. In addition, courses taken to satisfy the preparation for the major requirements may be used as a part of a minor. However, no course shall be used to satisfy the requirements for both a major and a minor.

1. The minimum grade point average for awarding a minor at the time of graduation shall be 2.0 or better in all units applicable toward that minor, including those accepted by transfer from another institution.

:::

## Mission and Goals {#mission-and-goals .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Mission:** The mission of San Diego State University shall be to provide well balanced, high quality education for undergraduate and graduate students and to contribute to knowledge and the solution of problems through excellence and distinction in teaching, research, and service. The university shall impart an appreciation and broad understanding of human experience throughout the world and the ages. This education shall extend to:

    a. Diverse cultural legacies,

    a. Accomplishments in many areas, such as the arts and technology,

    a. The advancement of human thought, including philosophy and science,

    a. The development of economic, political, and social institutions, and

    a. The physical and biological evolution of humans and their environment.

        The university shall accomplish this through its many and diverse departments and interdisciplinary programs in the creative and performing arts, the humanities, the natural and mathematical sciences, and the social and behavioral sciences. Through the President’s Shared Vision, students, parents, faculty, staff, administrators, and the community have identified the following five challenges:

    1. To extend and enhance the university’s deep and abiding commitment to academic excellence expressed through superior teaching, research, creative activity, and public service;

    1. To nurture a learning centered university that supports the growth and development of the whole person;

    1. To create a community proud of its diversity and committed to furthering social justice on and off campus;

    1. To promote the growth, development, and wise use of our human and fiscal resources; and

    1. To create a global university.

1. **Academic Goals:** Responding to these and other challenges, the university shall pursue the following academic goals to sustain and strengthen our position as a leading university:

    1. To encourage the intellectual and creative development of a diverse group of students by helping them learn about themselves and others, their own and other cultural and social heritages, and their environment;

    1. To foster development of critical thinking, writing, reading, oral communication, and quantitative and qualitative analysis as well as a commitment to lifelong learning and international perspectives needed to contribute to communities and fields of endeavor;

    1. To provide the basis for informed citizenship in a democracy;

    1. To offer advanced undergraduate and graduate students professional training and preparation for further study in a broad range of disciplines, with special emphasis on the preparation of teachers;

    1. To support faculty in developing specialized contributions to knowledge, including innovative curriculum and pedagogy responsive to intellectual and professional needs of undergraduate, master’s, and doctoral students;

    1. To support faculty in their professionally related community activities and informed exchanges with diverse professional and lay communities that strengthen the university’s courses and scholarship;

    1. To encourage scholarship, including the creative and performing arts, by students, faculty, and administrators from all areas of the university; and

    1. To continue our commitment to research, including the expansion of externally funded projects and doctoral programs where appropriate.

1. **The Faculty:** Given these challenges and academic goals, we hope to create

    1. A Faculty of Teacher Scholars: Every faculty member shall demonstrate excellence as a teacher scholar. The faculty shall adopt and evaluate innovative teaching methods and shall incorporate active scholarship into teaching. The university’s research orientation, distinctive within The California State University, shall afford graduate and undergraduate students the opportunity to become involved in research as well as interact with active research faculty.

    1. A Faculty That Meets the Needs of Departments, School, and Programs to Provide Quality Degree Programs: Proud of our accomplishments in many areas, we shall continue to build upon the excellence of our academic offerings.

    1. A Faculty That Is Diverse: Because academic discourse is informed and enriched by diverse ideas, the university shall diversify its faculty to meet the academic need for various perspectives and experiences, to address our student demographics, and to prepare students for the world in which they will live and work.

    1. A Faculty That Provides International Perspectives: In our increasingly global society, we shall recruit faculty who can bring international perspectives to their work, who are committed to internationalization in their teaching and scholarship and in advising students, and some of whom are bilingual or multicultural.

    1. A Faculty with Community Based Interests: To strengthen the university’s courses and scholarship and to bring university expertise to the community, the faculty shall address the needs of the region through teaching, research, and service, which may include community-based activities such as applied research, training grants, and service learning.

    1. A Faculty That Provides Interdisciplinary Perspectives. Because societal issues are multidimensional and transcend traditional academic disciplines, the faculty shall be expert in its disciplines and shall collaborate across disciplines to encourage students to work in groups and to provide an integrated educational perspective.

1. **Diversity:** Diversity shall be an essential consideration in all university policies and decisions, and shall be guided by the following statements that shall be published in staff and faculty handbooks, in the University Policy File, in the University General Catalog, the Graduate Bulletin, the IVC Bulletin, and linked from the Mission and Goals section on the main University web homepage.

    1. San Diego State University is a community diverse in race, ethnicity, language, culture, social class, national origin, religious and political belief, age, ability, gender, gender identity, and expression, and sexual orientation. As a university committed to learning in all its forms, San Diego State University recognizes the need to attract and retain a critical mass of diverse persons who will advance its goals and ideals. This fundamental commitment to diversity 1) enriches the institution and provides an atmosphere in which all human potential is valued, 2) promotes learning through interactions among people of different backgrounds and many perspectives, and 3) better enables the university to prepare all members of its community to promote social responsibility, equity, freedom, and productive citizenship in a global society.

    1. Diversity means not only the opportunity for all groups to be represented among faculty, student, staff, and administration but also the support for these persons as they seek the highest achievements. Attitudes, actions, programs, and policies that foster diversity engender the vigorous exchange of ideas, enhance respect and consideration for individuals and groups, strengthen the understanding of our mutual dependence, and form the core of the university. Diversity promotes enriched learning and produces positive educational outcomes for all.

    1. Vigorous efforts to increase the diversity of the faculty, staff, administration, and students shall continue as a high priority, and as access increases, the university will create changes in its environment that enhance the opportunities for the success of all members of the campus community.

    1. The university shall cultivate a campus climate that promotes human dignity, civility, and mutual appreciation for the uniqueness of each member of our community. Because the university’s educational goals are founded on the values of intellectual honesty, appreciation for diversity, and mutual respect, it is critical that our academic and co-curricular programs, scholarships, courses, workshops, lectures, and other aspects of campus life reflect diverse perspectives. Freedom from discrimination, harassment, and violence against persons or property is a basic right and is requisite for learning. Freedom of speech shall be protected. By the same token, the campus community shall denounce and confront acts of intolerance, abusive behaviors, and the beliefs and past events that have separated us as a people.

:::

## Records {#records .unnumbered}

::: {.policy-numbering .policy-start-1}

1. In compliance with federal and state law, San Diego State University has adopted a Student Records policy designed to protect the confidentiality of student records. The policy shall be maintained in the Office of the Provost and shall be the governing document in this matter.

    1. Only such records as are demonstrably and substantially relevant to the educational or related purposes of the university, its divisions, departments or schools, or agents shall be generated or maintained.

    1. No student shall be required to furnish, but may do so voluntarily, information as to the student’s race, color, religion, sex, handicap, marital status, age, national origin, or political affiliation or preferences, except as specifically required by state statute, federal law, or valid federal or state rules or orders.

1. **Student Rights**

    1. The federal Family Education Rights and Privacy Act of 1974 (20 U.S.C. 12329) and regulations adopted there under (45 C.F.R. 99), and the California Education Code, secs. 22509–22509.18, require the university to provide students access to their official education records and an opportunity to challenge such records when their accuracy or appropriateness is in question. Further, the laws generally prohibit the disclosure of personally identifiable information from a student’s education records without the prior consent of the student.

    1. Privacy

        1. Students shall have the right to protection from improper disclosure of personally identifiable information from their education records.

        1. Without the prior written consent of the student, disclosure of personally identifiable information from the student’s education record is prohibited, except for the following: (a) release of such information to a specified list of officials with a legitimate educational interest in the record; (b) release of such information in response to a court order, health or safety emergency, or approved research project; or (c) release of public Directory Information not previously restricted by the student.

    1. Access

        1. Students shall have the right to inspect and review with an appropriate university official or employee of the academic or administrative unit that maintains the records, the education records or pertinent portion thereof.

        1. The right to inspect and review education records shall include (a) the right to an explanation or interpretation of the record, where appropriate, by a qualified university official or employee and (b) the right to obtain copies of the record, unless otherwise provided by this policy, where failure to provide copies would effectively curtail the right of access.

        1. Access to inspect and review such records shall be granted no later than 15 working days following receipt of the request for access.

    1. Disclosure of Personally Identifiable Information

        1. Personally identifiable information from the education records of students, except Directory Information not previously restricted by the student, is considered confidential and may not be disclosed to any party for any purpose without the prior written consent of the student.

        1. Exceptions to this general policy, as provided by state and federal law, shall be as follows:

            a. Officials and employees of The California State University who have been determined by the Associate Vice President for Enrollment to have a legitimate educational interest in the educational record;

            a. Officials and employees of another education institution in which the student seeks or intends to enroll;

            a. A court of law, pursuant to the receipt of a court order, process, or subpoena that specifically seeks access to the education records of a named student, and then only by consent of the Associate Vice President for Enrollment;

            a. A health or safety emergency, and then only by consent of the Associate Vice President for Enrollment;

            a. A research project within the university, and then only by consent of the Associate Vice President for Enrollment;

            a. In connection with financial aid for which a student has applied or which a student has received;

            a. Organizations conducting studies for, or on behalf of, the university, education agencies, or institutions for the purpose of developing, validating, or administering predictive tests, administering student aid programs, improving instruction, and for accreditation purposes; or

            a. The Comptroller General of the United States, the Secretary or Assistant Secretary of the U.S. Department of Health and Human Services, the U.S. Commissioner of Education, the Director of the National Institute of Education, and state educational authorities.

    1. Challenge

        1. Students may challenge the content of their education records and request that a specific record be amended on the grounds that the record is (a) inaccurate, (b) misleading, (c) an unsubstantiated personal conclusion of the observer, (d) a conclusion or inference outside of the observer’s area of competence, (e) not based upon the personal observation of a named person within the time and place of the observation noted, or (f) otherwise in violation of their privacy or other rights.

        1. Rights afforded to students in Section 2.5.1. shall not be interpreted as permission to contest the assignment of grades.

1. **Records and Retention**

    1. Class Roster

        1. The class roster contains the names of all students enrolled in each class.

        1. The class roster shall be retained on the server for a minimum of seven years.

    1. Grade and Attendance Records

        1. Grade records shall contain notations related to a student’s progress in a class but may also reflect class attendance and office visits.

        1. Records shall be retained by the instructor or the department or school for seven years after the conclusion of the class.

        1. Instructors, upon leaving the employment of the university, shall surrender their records to the department chair or school director.

        1. Graduate teaching assistants and Contingent Faculty shall turn in all class records to the department chair or school director at the end of each semester or session.

        1. Instructors, upon leaving the employment of the university or upon taking leave from the University, shall surrender their incomplete grade contracts to the department chair or school director.

    1. Examinations and Course Papers: Examination papers, reports, and other course papers may be retained by the instructor only if the instructor communicates to the student at the time of assigning such materials the instructor’s intention to retain them.

        1. Instructors who retain examinations or graded work, hard copy or electronic, shall provide reasonable access to them.

        1. Instructors shall dispose of examinations, reports, and other graded work no later than the day after the last day of the semester (excluding summer session) after the semester during which the student was enrolled provided that no grievance has been filed with the Student Grievance Committee.

        1. Examinations, reports, and course papers shall be returned to the students in accord with each student’s right to confidentiality, which, however, shall not apply to dissertations or comprehensive examinations at the master’s or doctoral level.

:::

## Registration {#registration .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Priority** **Registration**

    1. Definitions and Principles

        1. “Priority registration” shall be defined as the opportunity to enter the registration process earlier than the normally scheduled registration time in order to adjust a class schedule to sanctioned time constraints. Student groups that were granted priority registration prior to Fall 2025 will continue to be granted registration appointments at the start of the registration period unless otherwise specified. Beginning Fall 2025, newly-added priority registration groups will be permitted to register prior to all other students within their class unless federal, state, or CSU requirements mandate that they register prior to all other students.

        1. Every effort shall be made to protect the value of each student’s regular registration time. Priority registration is intended to be used rarely and for students who could not otherwise achieve their academic goals within a reasonable period of time due to time constraints outside of their control and other extraordinary circumstances.

        1. Priority registration may be used to accommodate students of those groups whose services to the university and special circumstances require early registration. “Special circumstances” shall not include self-imposed time constraints. Additionally, priority registration will be granted to all student groups in accordance with federal, state, and CSU requirements.

        1. Priority registration shall not be used as a reward or perquisite for any student or group of students.

    1. Procedures for adding or removing groups

        1. Proposals to add or delete a group shall be evaluated by the Provost or designee in consultation with the Vice President for Student Affairs and Campus Diversity or designee.

        1. The Provost or designee shall forward each proposal with recommendations and justifications to the Committee on Academic Policy and Planning, which shall present as information to the Senate recommendations along with the current list of groups receiving priority registration.

1. **Registration Sequence**

    1. The University recognizes that new students are best prepared for successful matriculation if they are familiarized through orientation with the array of academic and student services available to support their studies.

    1. All new students are invited to attend a New Student Orientation as part of their successful transition to the University. Once a new student has attended their scheduled orientation, they shall receive priority to register for classes.

    1. Registration for a group below shall not begin before registration for an earlier group has received an opportunity. The registration sequence shall be as follows:

        1. Fall and spring semesters

            a. Members of Priority Registration groups (continuing students)

            a. Spring admits

            a. Graduate students

            a. Seniors (90 units and above)

            a. Juniors (60-89 units)

            a. Sophomores (30-59 units)

            a. Other freshmen (in third and subsequent semesters before sophomore status)

            a. New graduate students and undergraduate students with priority registration

            a. New undergraduate students (new first-year and transfers) based on their orientation dates and registration appointments

    1. Loss of Registration Opportunity

        1. A newly admitted student who (1) does not attend and (2) withdraws from school after registration but before the end of the refund period shall lose priority order and shall apply for admission to the university as a returning student.

        1. A continuing student shall be permitted up to four semesters of approved leave during matriculation at San Diego State University by taking the following action:

            Before the end of the schedule adjustment (drop/add) period for each semester of intended leave, the student shall submit a Leave of Absence Request through the SDSU WebPortal. A continuing student who fails to submit a Leave of Absence Request by this deadline may be subject to consequences that range from losing registration priority order to being required to apply for admission to the university as a returning student.

:::

## Review of Departments, Schools, or Programs {#review-of-departments-schools-or-programs .unnumbered}

::: {.policy-numbering .policy-start-1}

1. An academic review (a) shall assist a department, school, or program in improving its instructional, research, and professional programs, (b) shall review how the faculty have used their resources, (c) shall evaluate the quality of degree programs, (d) shall chart the direction of growth, (e) shall elucidate need for further support, and (f) shall examine the academic health of the unit. The review shall assist in department, school, or program planning and in requests for new degrees and programs. The contents and format of the academic review shall be aligned with those for academic plans.

1. **Review Panel**

    1. Normally each department, school, or program shall be reviewed periodically by an appropriate panel. The faculty of the unit shall be consulted by their dean in selecting the panel members. The panel shall comprise faculty from other appropriate universities and institutions and from related departments or schools at San Diego State University. Panel members shall be acceptable to the unit.

    1. The review may be coordinated and integrated with an accreditation; if, however, an accreditation visit has occurred within about a year, the academic review panel may choose to accept or augment the accreditation report. The academic review shall involve the cooperative efforts of the department, the college dean, the Associate Vice President for Curriculum, Assessment, and Accreditation, Dean of the College of Graduate Studies. The Provost shall assign the responsibility to coordinate an academic review to the Dean of the College of Graduate Studies, to the Associate Vice President for Curriculum, Assessment, and Accreditation or to another administrative officer.

1. **Self-Study**

    1. After a panel has been constituted, the department, school, or program shall be notified and arrangements shall be made for a visit at a mutually agreeable time. The deans shall see that the administration and faculty provide a self-study following guidelines distributed by the office of the Provost. The self-study may include other relevant information as members of the panel may request. Student participation in the review shall be provided by interviews, surveys, class visitations, or other appropriate means.

    1. At least two weeks before the panel convenes on campus, such data shall be provided to the panel, the Provost, the Dean of the College of Graduate Studies, the Associate Vice President for Curriculum, Assessment, and Accreditation, the dean of the college, and appropriate members of their staff.

1. Agendas shall be established by appropriate administrators.

1. **Report**

    1. The panel shall be requested to submit a report or reports to an appropriate administrator.

    1. All reports connected with the review shall be confidential and shall not be released without permission of the department, school, or program. Excerpts or summaries of the review documents shall be released by the college dean or the Dean of the College of Graduate Studies or the Associate Vice President for Curriculum, Assessment, and Accreditation only after consultation with the department, school, or program for use by curriculum committees or as required by the Chancellor’s Office or state officials.

1. The department, school, or program shall be given an opportunity to respond to the panel’s report, after which the administration and faculty shall meet to discuss the report.

1. **SDSU Imperial Valley**

    1. An overall review of SDSU Imperial Valley programs, facilities, and Master Plan shall be conducted approximately every five years. The review panel shall include members of the San Diego campus Committee on Academic Policy and Planning, other appropriate members of the San Diego campus, and persons external to the University.

    1. Within two years of the completion of the overall review, each academic degree (major, minor, and graduate) on SDSU Imperial Valley shall be reviewed by a panel of faculty members from relevant academic areas on the San Diego campus and members external to San Diego State University from institutions with similar demographic features and academic programs. This review shall assure that program content and quality are as similar as possible.

    1. Academic reviews of San Diego campus degree programs shall include in the self-study systematic written descriptions of the same degree programs at SDSU Imperial Valley. In addition, faculty members and students from SDSU Imperial Valley shall be invited to the San Diego campus for participation in the reviews.

    1. Reviews described in sec. 7.2 shall be held periodically to assure comparability between the academic degree programs of the two campuses.

:::

## Transfer Students {#transfer-students .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **General Education**

    1. Transfer with Certification

        1. San Diego State University shall honor certification by California community colleges for General Education requirements to a maximum of 39 state-mandated General Education units as outlined in Title 5 of the California Code of Regulations.

        1. Transfer students who have been certified for 39 units shall be required to complete an additional nine units of approved General Education courses at San Diego State University to comply with the Title 5 provision that at least nine units shall be earned at the campus granting the degree.

    1. Transfer without Certification: Transfer students not receiving a 39-unit certification may receive General Education credit for baccalaureate courses taken at other institutions in two ways:

        1. The transfer course shall appear on approved General Education course lists submitted to the CSU Chancellor and shall have been taken while included on the approved course list. This list shall include courses within Communication and Analytical Reasoning, Foundations, and Explorations in the San Diego State University General Education program.

        1. The transfer course shall clearly satisfy the criteria for General Education courses as defined by Title 5 of the California Code of Regulations, Executive Order 1100-Revised (2017), and the appropriate section of the San Diego State University Curriculum Guide. Such determination shall be made by the Associate Vice President for Curriculum, Assessment and Accreditation. in consultation with the Committee on General Education.

1. **California Articulation Number System**

    Departments or schools may choose to participate with one or more courses in the California Articulation Number (CAN) system. Transfer courses bearing published CAN numbers the same as those published in the San Diego State University General Catalog shall be acceptable for all purposes in lieu of the SDSU courses, provided that the transfer courses be taken (a) after publication of the CAN number in the San Diego State University General Catalog and (b) before publication of the San Diego State University General Catalog deleting CAN numbers for courses that SDSU departments or schools have withdrawn from the CAN system.

1. **Choice of Catalog**

    Students may select the General Education requirements in effect during the academic catalog year in which they entered San Diego State University, another campus in the system, or a California community college, even if they declare or change their major in a later year. All other requirements (including GE, pre-major and impaction criteria, course prerequisites, and accepted articulation arrangements) shall continue to be governed by the catalog in effect in the academic year in which students declare or change their major, or in the academic year in which they graduate. This option shall apply only to students who maintain continuous enrollment either (a) solely at San Diego State University or (b) at San Diego State University and a California Community College or another CSU campus.

:::

## Unit Limits {#unit-limits .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Academic Year Unit Limits: During initial registration, undergraduate students can enroll in a maximum of 18 units. One week before the start of each semester, the credit limit will be raised to 21 credits. All undergraduates wishing to register for more than 21 credits will be required to have the approval of the academic department that houses their first major, or a delegated advisor, Assistant Dean or department designee.

1. Summer Unit Limits: Students may enroll in no more than 18 units in total during summer. Students will be permitted to enroll in no more than 9 units in each Summer Session (S1 and S2), and up to 18 units in the 13-week session T1 (if they are not taking classes during Sessions 1 and 2). Any exceptions to these maximums will require approval by an academic advisor and administrator in Enrollment Services.

1. Students should expect to spend in class and study a total of three hours per week for each unit of college work attempted.

:::

## Universal Access to Information Technology Resources and Services {#universal-access-to-information-technology-resources-and-services .unnumbered}

::: {.policy-numbering .policy-start-1}

1. San Diego State University is committed to providing an educational environment that assures comparable access to electronic and information technology for individuals with disabilities.

1. The University affirms the Academic Senate Resolution AS-2700-05/FA on Student Access to Academic Information Technology.

1. Implementation

    1. Electronic and information technology services developed by or for an official unit of the university, or its auxiliary organizations, shall be designed to be compatible with and accessible through commonly used assistive technology. This includes websites developed by individual employees on University servers and used in support of university services, programs, and courses available to the campus community.

    1. Existing websites (legacy sites) shall be brought into compliance with minimum web accessibility standards.

    1. To the extent possible, the University shall provide course material that is accessible to all persons regardless of disability.

    1. The University shall make every effort to assure that vendor-supplied electronic and information technology products and services comply with this accessibility policy.

    1. The Vice President for Information Technology/Chief Information Officer, working in conjunction with appropriate committees, shall establish an implementation plan with appropriate timelines and milestones for assuring compliance with executive orders and state and federal laws. The implementation plan shall include definitions of minimal accessibility standards and be clearly posted on the University’s website.

1. **Enforcement**

    1. The Vice President for Information Technology/Chief Information Officer shall be responsible for web accessibility compliance and training, including the development of a communication plan to educate the campus about the policy.

    1. Assessment plans and progress reports shall be provided on a regular basis.

    1. Appropriate sanctions shall be developed, up to and including the shutting down of inaccessible websites. No sanctions shall be imposed until notice has been given to the individual or unit responsible for the website, and shall proceed in accordance with due process.

:::
