---
title: "University Policies: Administration"
---

## Academic Administrators {#academic-administrators .unnumbered}

::: {.policy-numbering .policy-start-1}

1. “Academic administrator” shall refer to personnel holding full-time administrative positions in the division of Academic Affairs.

1. Tenure for Academic Administrators: When an individual is being considered for appointment to a full-time academic administrative position, the President shall request and consider the recommendations of the relevant department(s) or school(s) from which the person has requested a tenured position. In arriving at these recommendations, the unit(s) shall consider appropriate rank and tenure status, were that person to be considered at that time for appointment as a faculty member in the unit(s).

:::

## Annual Review of Academic Administrators {#annual-review-of-academic-administrators .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Annual Review:** The Provost or designee shall conduct an annual review of all academic administrators, including Associate and Assistant Vice Presidents, Deans, and Associate Deans. Chairs and Directors shall undergo periodic review as specified in section 4.0 of University Policies: Organization: Chairs of Departments or Programs and Directors of Schools.

    1. The Provost shall consult with appropriate representatives of the college, to include the department and program chairs, school directors, and Senators of the college.

    1. A faculty or staff member may provide information through a representative as defined in sec. 1.1.

    1. The conclusions of the recommendations of the Provost shall be reported to the President.

1. **Five-Year Review of Academic Administrators**

    1. The review shall be a cooperative effort by the administration, faculty, students, and administrative office under review (a) to appraise the administrator and the administrative office in meeting the leadership and management objectives, (b) to report to the President the results of the review, and (c) to recommend action to be taken to improve the effectiveness of the administrator and office. The President shall carefully weigh the results in the continuing evaluation of the administrator and office. The review shall be collegial and shall effect a periodic renewal of understanding among the administrator’s several constituencies about the goals and responsibilities of the office, and it shall provide the occasion to consider educational philosophies, interpretations of goals, and expectations for leadership and management within the office; at the same time, it shall require examining the conditions in which the administrator and the office must operate. The report shall focus on issues that have been resolved and are yet to be resolved by the administrator and the faculty. In summary: (a) the review panel shall be both representative of and acceptable to all parties (faculty, staff, administration, students, and the administrative office); (b) the review process shall ensure the full participation of these parties; (c) the report shall be timely, respectful of persons, but specific in its recommendations; (d) and a report shall follow on the implementation of specific recommendations.

    1. Initiation: The periodic review process shall occur in the fifth year of the administrator’s tenure in the office and every five years thereafter unless the review is initiated earlier by special request. The special request to advance the review may be initiated by the administrative office to be reviewed, the faculty, or the administration. Circumstances warranting such a request shall be unusual but compelling from the point of view of the constituency requesting the review. The scheduling of reviews shall be the responsibility of the Provost or the President.

    1. Composition of Review Panels

        1. For deans of the Colleges of Arts and Letters, Education, Engineering, Fowler College of Business, Health and Human Services, Professional Studies and Fine Arts, Sciences, the SDSU Imperial Valley Dean, the Dean of the Library, and their offices:

            a. Internal faculty (six): For college deans the department and program chairs and school directors shall arrange for the nomination and election of 12 nominees by the faculty; six of the 12 nominees shall be selected by the Provost in agreement with the dean being reviewed and the college faculty committee determined by the college. Nominees to and members of the review panel should be perceived by the college’s constituencies as objective, discreet, and representative of the diverse educational philosophies within the college. For the dean of SDSU Imperial Valley and for the Dean of the Library, three faculty members shall be selected from a pool of six nominated respectively by the tenured and probationary faculty of SDSU Imperial Valley or of the Library. Faculty, as defined by Bylaw 1.1, are eligible to serve. Chairs and directors from the college in question are eligible to serve on the review panel.

            a. External faculty (one): For college deans the Senate Executive Committee shall determine the Senate procedures whereby a pool of up to 14 faculty members, with at least one from each college and the library, can be established annually (in years when a review is expected to occur) in the early fall to be on call to serve as external members of review panels; the external member of the panel shall be selected from the pool by the Provost in agreement with the dean being reviewed and the college’s appropriate faculty committee. For the Dean of SDSU Imperial Valley and the Dean of the Library, two external members shall be selected for the review panel from the Senate pool.

            a. Students: for college deans, two (usually one undergraduate and one graduate). The college’s student organization(s) shall nominate four students (usually two undergraduates and two graduates); two (usually one undergraduate and one graduate) shall be selected by the Provost in agreement with the dean being reviewed and the college’s appropriate faculty committee. For the Dean of SDSU Imperial Valley there shall be one student member on the panel, to be selected as above from two nominees. For the Dean of the Library the Associated Students shall nominate two students, one of whom shall be selected by the Provost in agreement with the Dean of the Library and with Library members of the reviewing panel.

            a. Administrators: for college deans and the Dean of the Library, one dean from the San Diego State University Academic Deans’ Council and one administrator from another university with similar responsibilities. The member of the Academic Deans’ Council shall be selected by the Provost in agreement with the dean being reviewed and the college’s appropriate faculty committee. The external administrator shall be selected by the Provost in agreement with the administrator being reviewed and the college’s appropriate faculty committee. For the Dean of SDSU Imperial Valley, the panel shall include one member of the Academic Deans’ Council, to be selected as above. Associate and Assistant Deans from the same college are ineligible to serve.

            a. Internal staff member: For college deans, the Dean of SDSU Imperial Valley, and the Dean of the Library, an election among staff shall determine four nominees from whom one shall be selected by the Provost in agreement with the dean being reviewed and the college’s appropriate faculty committee. Nominees to and the member of the review panel should be perceived by the college’s constituencies as objective, discreet, and representative of the diverse educational philosophies within the college.

            a. Community member outside the university: for college deans and the Dean of SDSU Imperial Valley, one community member outside the university shall be selected by the Provost in agreement with the dean and the appropriate faculty committee within the college as determined by that unit.

        1. Dean of Global Campus, and their offices.

            a. Faculty (six): The faculty of each college and SDSU Imperial Valley shall nominate two faculty members; six of the nominees shall be selected by the Provost in consultation with the President and in consultation with the Dean of Global Campus and the Chair of the Senate. To ensure sufficient time for election, the Provost shall give at least one month’s notice of the deadline for submitting the names of those elected.

            a. Administrators (two): one member of the San Diego State University Academic Deans’ Council and one administrator with similar responsibilities from another university. Both shall be selected by the Provost in agreement with the administrator being reviewed and the Chair of the Senate.

            a. Students (two): one undergraduate and one graduate both with recent experience in Global Campus. Four nominees shall be chosen by the Associated Students; two shall be selected from the nominees by the Provost in agreement with the administrator being reviewed and the Chair of the Senate.

            a. Staff members (two): An election among staff shall determine four nominees (usually two represented and two non-represented) from which two (one represented and one non-represented) shall be selected by the Provost in agreement with the Dean of Global Campus and the Chair of the Senate.

        1. Dean of Graduate Studies

            a. Faculty (six): The faculty of each college and SDSU Imperial Valley shall nominate two faculty members; six of the nominees shall be selected by the Provost in consultation with the President and in consultation with the Dean of Graduate Studies and the Chair of the Senate. Procedures for the nominations shall be determined by the faculty of each college. To ensure sufficient time for election, the Provost shall give as much notice as possible, but no less than one month’s notice, of the deadline for submitting the names of those elected.

            a. Administrators (two): one member of the San Diego State University Academic Deans’ Council and one administrator with similar responsibilities from another university. They shall be selected by the Provost in consultation with the President, the Dean of Graduate Studies, and the Chair of the Senate.

            a. Students (two): one master’s student and one doctoral student. Four nominees shall be chosen by the Associated Students; two of the nominees shall be selected by the Provost in consultation with the Dean of Graduate Studies and the Chair of the Senate.

            a. Staff member: An election among staff shall determine four nominees from whom one shall be selected by the President of the university in agreement with the Provost and the Chair of the Senate.

        1. Provost and the Academic Affairs Office

            a. Faculty (eight): The faculty of the Colleges of Arts and Letters, Professional Studies and Fine Arts, and Sciences shall nominate and elect three nominees from each of these units; the faculty of the Colleges of Business Administration, Education, and Health and Human Services shall elect two nominees from each of these units; and the faculty of the College of Engineering, the Library, and SDSU Imperial Valley shall nominate and elect one nominee from each of these units. Eight of the nominees shall be chosen by the President of the university in agreement with the Provost and the Chair of the Senate. The faculty members shall be broadly representative. To ensure sufficient time for election, the Provost shall give at least one month’s notice of the deadline for submitting the names of those elected.

            a. Administrators (two): one member of the San Diego State University Academic Deans’ Council and one provost or vice president for academic affairs from another university. Both shall be selected by the President of the university in agreement with the Provost and Chair of the Senate.

            a. Students (two): one undergraduate and one graduate. Four nominees shall be chosen by the Associated Students. Two shall be selected by the President of the university in agreement with the Provost and the Chair of the Senate.

            a. Staff member: An election among staff shall determine four nominees from whom one shall be selected by the President of the university in agreement with the Provost and the Chair of the Senate.

1. **Procedures and Responsibilities**

    1. The review panel shall work primarily from the published job description of the administrator, from the self-study, and from "ideal" descriptions of the role of the administrator solicited from faculty members by the review panel, in combination with the data that define performance in office and the constraints within which the possibilities for performance are defined. Both written statements developing an argument and interviews shall be employed. Groups (e.g., departments, committees) as well as individuals shall be invited to participate.

    1. The review panel shall ensure access to all members of the administrative unit’s faculty, student body, and staff (a) to communicate representative views and (b) to provide the administrator with the opportunity to discuss issues and concerns, and the panel ensure the confidentiality of all communications.

    1. To promote an honest and constructive assessment, confidentiality shall be honored throughout all aspects of the review panel’s work. Raw survey data, individual comments from feedback forums or interviews, and committee deliberations shall not be shared beyond the panel. All data and feedback shall be anonymized, aggregated, and shared only in summary form with the administrator undergoing review. Per Title IX and EEOC laws and regulations, review panel members, as well as all participants in the assessment process, shall be protected from future retaliation. The Center for the Prevention of Harassment and Discrimination shall ensure compliance with anti-retaliation laws. This confidentiality policy shall be shared with all participants in the process, including committee members and those providing individual feedback about the administrator.

1. **Reporting Process**

    1. The review panel shall submit a written report to the Provost or, as appropriate, to the President. The report shall contain a description of the review process, data collected, findings, and specific recommendations for future action by the administrator and the office, the faculty, and the university.

    1. The complete report shall be made available to the administrator immediately after it is reviewed by the Provost or, as appropriate, to the President. The faculty of the unit shall receive a timely summary of the report prepared and issued by the review panel after approval by the Provost or the President. This summary shall contain major findings and specific recommendations for action.

    1. The administrator and the person to whom they report, in consultation with the appropriate faculty committee of the organizational unit, shall recommend a plan of action to respond to the recommendations of the panel.

1. **Post-review:** The administrator who has been reviewed shall in the annual report comment specifically on the progress toward the plan of action, which comments shall be made available to the faculty of the unit. The Provost or, as appropriate, the President shall discuss the report with the review panel. A further report may then be issued to the faculty by the Provost or the President.

1. **Legal Restrictions:** All aspects of the review shall be consistent with requirements of state and federal law and with university policy. The Associate Vice President for Faculty Advancement and Student Success shall provide specific instructions.

1. **Review of the Review Procedure:** Each review panel shall recommend changes in the procedure to the Committee on Academic Policy and Planning.

:::

## Search Committees for University Administrators {#search-committees-for-university-administrators .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Search for University-Wide Administrative Personnel**

    1. Faculty, staff, and students shall participate in searches for (a) Provost, (b) Vice President for Student Affairs and Campus Diversity, (c) Vice President for Business and Financial Affairs, (d) Vice President for University Relations and Development, (e) Vice President for Research and Innovation, (f) Associate Vice President for Faculty Advancement and Student Success, (g) Dean of Global Campus, (h) Dean of the Library.

        1. All vacancies shall be advertised and filled in compliance with the University’s Nondiscrimination and Equal Opportunity Policy. The Director of the Office of Employee Relations and Compliance, the Chief Diversity Officer, and the Committee on Diversity, Equity, and Inclusion may assist in the search.

        1. An ad hoc search committee shall be formed each time it is necessary to recommend a person to fill one of the positions in sec. 1.1. Faculty members shall be tenured and shall be selected in accordance with sec. 4.0. The Associated Students and Staff Affairs Committee shall respectively formulate rules for selection of students and staff members. Additional members shall be selected by the President or designee. The composition of search committees shall be as follows:

            a) Provost: six faculty members, two students, one staff member, and five additional members (of whom at least three shall be faculty)

            b) Vice President for Student Affairs and Campus Diversity: two faculty members, two representatives elected by and from the personnel of the Division of Student Affairs and Campus Diversity(of whom at least one shall be staff), two students, and one administrator designated by the President

            c) Vice President for Business and Financial Affairs: two faculty members, two staff members, and three additional members

            d) Vice President for University Relations and Development: five faculty members, three representatives from development offices across the campus, one representative from the San Diego State University Research Foundation, one staff member, one student, one representative from the Alumni Association, one member of the community at large, and one representative from the Department of Athletics

            e) Vice President for Research and Innovation: five faculty members, two classified graduate students, one staff member, and five additional members (of whom at least three shall be faculty)

            f) Associate Vice President for Faculty Advancement and Student Success: five faculty members, two undergraduate students, one staff member, and four additional members (of whom at least two shall be faculty)

            g) Dean of Global Campus: five faculty members, two students, two Global Campus staff members (one represented, one non-represented), and four additional members (of whom at least two shall be faculty);

            h) Dean of the Library: three tenured librarians elected under the rules governing elections to the Senate, three faculty members, one Library staff member elected by that group, one student, and one additional member.

        1. The procedures and duties of the search committee are as follows:

            1. The President or designee shall convene the organizational meeting of the committee and shall preside until a chair has been elected. The Chair of the Senate or designee shall attend the organizational meeting and participate without a vote. The search committee shall elect its chair from among its elected members and shall establish its own search and selection procedures, except that no member of the committee shall act unilaterally regarding committee business. The Director of the Office of Employee Relations and Compliance, the Chief Diversity Officer, or a representative from the Committee on Diversity, Equity, and Inclusion may attend committee meetings as a nonvoting member.

            1. All committee recommendations shall be by a majority vote of the voting members of the committee. Search committee procedures shall be in compliance with the University Nondiscrimination and Equal Opportunity Employment policy and with Title 5 of the California Code of Regulations, sec. 42701.

            1. The committee, before inviting any candidates to the campus, shall present to the President the list of those whom it intends to invite. If the President requests it, the committee shall add names to the list before any candidates are interviewed on campus. The President shall appoint, however, only from the final list of those recommended by the committee.

            1. For each position to be filled, the committee shall recommend the appropriate number of candidates to the President for selection.

            1. In searches for vice presidents, the Director of the Office of Employee Relations and Compliance shall have certified that all Nondiscrimination and Equal Opportunity Employment obligations and commitments have been satisfied. For the other administrators, the appropriate vice president shall have certified.

    1. Searches for Positions Not Requiring Faculty Participation (administrative positions not specifically designated in sec. 1.1 or covered by the procedures of the bylaws of auxiliary organizations).

        1. The President or designee shall decide when a search committee is appropriate. When it is not, a person may be appointed to the position by the administrator to whom that person will report; this shall occur after a full search in compliance with University Nondiscrimination and Equal Opportunity Employment procedures.

        1. When a search committee is appropriate, it shall be appointed by the President or designee to review all applications and to conduct personal interviews with the most qualified candidates. The committee shall include one or more members of the faculty. The Director of the Office of Employee Relations and Compliance, the Chief Diversity Officer, or a member of the Committee on Diversity, Equity, and Outreach may attend committee meetings as a nonvoting member.

            1. The committees shall submit a list of the appropriate number of candidates to the President or designee for review and appointment.

            1. The appropriate vice president, dean, or director shall have certified that all Nondiscrimination and Equal Employment Opportunity obligations and commitments have been satisfied.

1. Searches for Deans of Colleges and Related Positions (Including Deans of the Colleges of Arts and Letters, Fowler College of Business, Education, Engineering, Health and Human Services, Professional Studies and Fine Arts, Sciences, and of SDSU Imperial Valley).

    1. All vacancies shall be advertised and filled in compliance with the University’s Nondiscrimination and Equal Opportunity Employment policy.

    1. An ad hoc 13-member search committee shall be formed each time to recommend a person to fill one of the above positions. The committee shall comprise (a) six tenured faculty members from the college elected by the faculty of the college under the rules governing elections to the Senate, (b) one faculty member from outside the college elected by the Senate in conformance with sec. 4.0, (c) three members (of whom at least two shall be faculty) selected by the President or designee, (d) two upper division or graduate students whose majors are in that college, selected by Associated Students procedures, and (e) one member elected by and from the staff of that college. The Director of the Office of Employee Relations and Compliance or designee shall serve as a non-voting ex officio member of the committee.

    1. The procedures and duties of the search committee shall be as follows:

        1. The President or designee shall convene the organizational meeting of the committee and preside until a chair has been elected. The Chair of the Senate or designee shall attend the organizational meeting and participate without a vote. The search committee shall elect its chair from among its elected members.

        1. The committee shall establish its own search and selection procedures in writing, before any formal deliberations, and shall forward these procedures to the President. Any revision of the procedures requires reexamination of all submitted papers. Ongoing consultation with the President shall be established.

            1. Minutes of all meetings shall be in writing. Copies of the minutes of each meeting shall be sent to the President and the Director of the Office of Employee Relations and Compliance.

            1. The committee shall demonstrate its commitment to affirmative action by including the steps to be taken in the guidelines.

            1. Operational procedures shall include timelines. Changes in these timelines shall require a reopening of the search.

            1. The committee, before inviting the candidates to the campus, shall present to the President the list of those it intends to invite. If the President requests it, the committee shall add names to the list before any candidates are interviewed on the campus. The President shall appoint, however, only from the final list of those recommended by the committee.

    1. Before committee recommendations, the Provost shall have certified that all Nondiscrimination and Equal Opportunity Employment obligations and commitments have been satisfied.

        1. All committee recommendations shall be by majority vote of the voting members of the committee.

        1. If the President disagrees with the committee’s recommendations, the President shall communicate reasons to the committee. If an agreement cannot be reached between the committee and the President, the search shall be reopened.

1. Appointment of Acting Vice Presidents and Deans (including administrators identified in secs. 1.1 and 2.0)

    1. When, in accordance with Senate policies, a committee has been selected for the purpose of making recommendations concerning appointment to a position designated in secs. 1.1 and 2.0 and when the position becomes vacant before the committee has a candidate for permanent appointment, the President shall seek the advice of the committee before appointing an acting officer.

    1. When a position designated in Sections 1.1 and 2.0 above becomes vacant before a committee has been elected in accordance with Senate procedures for the purpose of recommending an appointment to the President; the President shall consult with appropriate Senate officers and committees and may then appoint an acting vice president or dean.

    1. No person appointed as an acting officer shall serve for longer than one year without the concurrence of the committee elected in accordance with Senate procedure to recommend to the President a permanent appointment to the position.

1. Procedures for the Selection of Faculty to Serve on Search Committees (other than those selected within colleges as specified in sec. 2.0)

    1. The President shall announce the vacancies or anticipated vacancies to the Chair of the Senate. The Chair of the Senate shall call for the nominations process to be completed at the next regular or special Senate meeting. The faculty and the senators shall be informed of the impending nominations by campus mail or email. The search committee shall comprise the number of faculty indicated for the position with no more than one from any college, and the faculty shall be tenured and themselves eligible for election to the Senate.

    1. Nominations shall be made by a faculty member eligible to vote in Senate elections. Nominations by petition shall be in the Senate office seven days before the regularly scheduled Senate meeting. Nominations may also be made from the floor of the Senate. Faculty shall be considered nominated upon formal recommendation by a Senator. There shall be at least one nominee for each seat to be filled by the Senate. All nominees shall have agreed to serve.

    1. Elected members of the Senate shall elect faculty representatives to the search committee by secret ballot. If the first ballot does not yield a simple majority vote for the indicated number of candidates, additional ballots shall be conducted until that number has received a majority.

1. If an administrative search needs to take place for a position of the same category as the positions listed in 1.1, but the position is not explicitly described above, and the search needs to take place before this policy is amended, then the Senate Executive Committee (SEC) shall determine the composition of an as-hoc search committee. All elections for faculty to serve on search committees shall be overseen by the Committee on Committees and Elections (CCE). Associated Students (A.S.) and the Staff Affairs Committee shall respectively formulate rules for the election or appointment of students and staff members. Appointed members shall be selected by the President or designee.

:::

## Staff Deans, Appointment of {#staff-deans-appointment-of .unnumbered}

::: {.policy-numbering .policy-start-1}

The appointment of a staff dean shall be the prerogative of the administrator in whose office the staff dean will work, and it shall not require a special faculty committee to nominate candidates.

:::

## Academic Misconduct {#academic-misconduct .unnumbered}

::: {.policy-numbering .policy-start-1}

Management Personnel Plan (MPP) Employees shall not provide students with unethical academic assistance, including but not limited to, providing or arranging for the provision of: (a) copies of a test, an examination, or other course material to any student without the permission of the instructor; (b) fraudulent academic credit or false transcripts regarding an individual’s academic record; and (c) an academic exception that results in a grade change, academic credit, or fulfillment of a graduation requirement when such an exception is not available to all students.

:::
