---
title: "University Policies: Budget"
---

## Budget Procedures {#budget-procedures .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Allocations**

    1. The Office of the Provost shall allocate the university’s instructional resources to the colleges to allow each college maximum flexibility in executing its programs and achieving its goals.

    1. These procedures shall relate to instructional equipment, although they may be extended to cover other budget categories.

1. **Equipment Budget Preparation**

    1. A formula equipment summary containing brief descriptive titles of the equipment sought, arranged in priority order along with their cost, shall be employed at budget preparation levels higher than the college.

    1. Equipment lists shall be prepared by departments and schools in the fall for the next budget year and shall be submitted to the deans of the respective colleges by December 1. The requests shall be rank ordered and sent to the Office of the Provost by January 1.

1. **Allocation of Equipment Funds**

    1. As soon as the preliminary equipment amount for the next budget year has been obtained from the Chancellor’s Office, the Provost’s office shall undertake to allocate this amount according to the needs and priorities indicated in the equipment summary lists received from the colleges. Historical relationships and new program requirements, as well as other guidelines pertinent to the problem, shall be taken into account. The final allocation to each college, however, shall be in the form of dollar amounts rather than as items with a certain dollar value.

    1. When these allocations are completed (between February 1 and February 15), the Committee on Academic Resources and Planning shall be informed of their amount and the methods by which they were determined.

    1. Upon receipt of the tentative allocation for equipment, the dean of each college shall allot these funds as dollar amounts to the departments and schools. Within sufficient time to meet Office of Business and Financial Affairs deadlines, each department and school shall return a list of the equipment items for purchase, having a total cost equal to the dollar amount of their allocation. Having received the list of equipment items from the colleges, the Office of Business and Financial Affairs shall then collate this material and compile the list required by the Chancellor’s Office.

    1. Finally, in July or as soon as the information is available, the Office of Business and Financial Affairs shall inform the Provost of the amount finally approved for equipment. If it is the same as the preliminary budget amount allocated in January, the Provost shall simply inform the deans of colleges that equipment purchasing may begin. If the final budget amount differs from the preliminary figure, the allocations previously made shall be adjusted accordingly.

1. **Augmentation Budgets**

    The need for revising these formula factors shall be demonstrated, for example, by an augmentation request using a program budgeting format.

1. **Short-Term Budget Adjustments**

    A short-range budget adjustment shall be defined as one that does not carry over into the next academic year. It shall be an expedient adjustment to carry the university through the year. This adjustment shall follow these principles:

    1. Personnel Decisions

        1. No tenured or probationary faculty shall be laid off.

        1. One-year appointments shall be honored before semester appointments

        1. Preferential retention of graduate teaching assistants over part-time faculty shall be left to the discretion of each college.

    1. Efforts shall be made to maintain FTEs as much as possible without affecting department or school programs.

    1. Although ability to pay shall be considered during the payback discussions, units responsible for the financial shortfall shall share a relatively larger burden for a payback. Payback allocations shall not be made on a solely proportional basis among the colleges.

    1. Short-term budget adjustments shall not exceed those demanded by the fiscal exigency.

    1. As far as possible, the reductions assigned to the major divisions of the university shall protect the ability of the university to maintain its academic program.

1. **Summary:** Expenditure of budgeted funds for equipment, for clerical, technical, and student assistant positions, and for instructional operating expenses shall be administered by the Office of Business and Financial Affairs. Budget procedures and allocations shall be as follows:

    1. The allocation of the instructional resources of the university, as well as the preparation of an augmentation budget, shall be centered in the Office of the Provost as part of an academic planning function.

    1. These resources shall be allocated to colleges and other administrative units under procedures and rules that permit maximum flexibility in the achievement of programs and objectives.

:::

## Payroll Checks {#payroll-checks .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Faculty and staff may arrange through the Payroll Office to have their warrants deposited directly in a financial institution.

1. Non-deposited payroll checks for faculty and staff shall be distributed by courier from the Payroll Office to colleges, schools, or departments. Checks not claimed within five working days of delivery shall be collected and returned by courier to the Payroll Office. After five working days, checks shall be available only in the Payroll Office.

:::

## Relocation Expenses {#relocation-expenses .unnumbered}

::: {.policy-numbering .policy-start-1}

1. The California State University shall allocate funds for moving and relocation expenses of newly hired and current employees including (a) teaching faculty, (b) university librarians, (c) deans, (d) vice presidents, and (e) presidents. Reimbursements of such expenses shall be payable from monies made available for such purposes by the Chancellor, campus president, or their designee.

    1. A newly hired faculty employee or administrator who has been offered a position within the CSU by the Chancellor, campus President, or designee and has accepted the appointment may receive reimbursement for actual, necessary, and reasonable moving and relocation expenses. The recipient and amount of a reimbursement shall be determined by the Chancellor, campus president, or designee.

    1. Whenever a current CSU employee is required by the Chancellor, campus president, or designee to change place of residence because of a change in assignment, promotion, or other reason related to the employee’s duties deemed to be in the best interests of the CSU, the employee shall receive reimbursement for actual, necessary, and reasonable moving and relocation expenses.

    1. Full or partial reimbursement, within budgetary constraints, may be allowed for the actual and necessary expenses incurred for packing, insurance, transportation, storage in transit (not to exceed 60 calendar days), and unpacking and installation of the employee's household goods at the new residence, when properly documented. Should employees elect to move themselves, reimbursement for such moves may not exceed the costs that would have been incurred had a commercial firm been used.

    1. An employee may be reimbursed for actual lodging expenses, supported by a voucher, plus meal and incidental expenses, in accordance with the CSU Internal Regulations Governing Travel Expenses and Allowances, sec. 105, Rates for Housing and Lodging (App. A). This allowance shall be paid for not more than 60 days unless the Chancellor or campus president has determined in advance that the search for a new residence will result in unusual and unavoidable hardship for an employee and, therefore, has granted an exception. This allowance shall terminate immediately upon establishment of a permanent residence.

    1. When an employee is required to change assignment and designated place of work that requires the sale of residence, the employee may be reimbursed for actual and necessary selling costs as determined by prevailing practices within the area of sale. Actual and necessary selling costs may include brokerage commission, title insurance, escrow fees, prepayment penalties, taxes, charges, or fees fixed by local authority required to consummate the sale of the residence. Miscellaneous seller’s costs customary to the area may be reimbursed if determined appropriate by the Chancellor or campus president. Actual and necessary selling costs shall be reimbursed for that portion of the dwelling the employee actually occupies if the employee owns and resides in a multifamily dwelling.

    1. Whenever an employee is required to change an officially designated place of work and such change requires the settlement of a lease on the employee’s former residence, the employee may receive the actual and necessary cost of settlement of the unexpired lease to a maximum of one year. Reimbursement shall not be allowed if the Chancellor or campus president determines that the employee knew or reasonably should have known that relocation was imminent before entering into a lease agreement.

1. If an employee whose moving or relocation expenses have been reimbursed does not continue employment with the CSU for a period of at least two years (unless the discontinuance of the employment was the result of death, disability, or other similar unexpected cause beyond the control of the employee as determined by the Chancellor or campus president), the employee or appropriate representative shall repay 100 percent of the amount received for reimbursement for the moving and relocation expenses if employed less than six months; 75 percent if employed at least six months but less than 12 months; 50 percent if employed at least 12 months but less than 18 months; 25 percent if employed at least 18 months but less than 24 months.

1. The university shall ensure that a copy of these regulations is given to the employee upon notice to the employee of an impending move.

1. The university shall not:

    a. Differentiate between single and married people in allocating such funds,

    a. Use this fund for paying moving or travel expenses for people brought to campus for interviews,

    a. Use this fund to pay moving or travel expenses of temporary personnel acting as replacements,

    a. Use this fund to pay moving and traveling expenses of lecturers.

:::
