---
title: "University Policies: Codes"
---

## Alcohol Abuse and Illegal Drugs {#alcohol-abuse-and-illegal-drugs .unnumbered}

::: {.policy-numbering .policy-start-1}

1. The university shall facilitate the prevention, assessment, early intervention, and treatment of problems arising from alcohol abuse and the use of illegal drugs, and it shall enforce with appropriate disciplinary actions university policy and applicable local, state, and federal law.

1. **Prohibitions and Restrictions**

    1. The unlawful possession, use, distribution, or manufacture of alcohol or illegal drugs on the campus or during university-sponsored activities shall be prohibited.

    1. Except for alcohol in student rooms where a resident is of legal drinking age, residence halls shall be free of alcohol and illegal drugs. Students who are 21 years of age or older may possess in their rooms for personal consumption a limited amount of alcoholic beverages excluding hard liquor.

    1. The university shall restrict the serving of alcohol to authorized facilities that carefully monitor and supervise the use of alcohol.

1. **Enforcement and Sanctions**

    1. Persons who violate alcohol or drug policies shall, in addition to any legal consequences, be subject to disciplinary sanctions up to and including suspension and expulsion from the university. Organizations that violate alcohol or drug policies shall be subject to loss of campus status, funding, and other forms of support up to and including suspension or permanent expulsion from the university.

    1. University offices such as Judicial Procedures, University Police, Center for Fraternity and Sorority Life, Office of Student Life and Development, Office of Student Rights and Responsibilities, and Housing and Residential Life, which are charged with the responsibility for enforcing alcohol and drug policies and imposing sanctions for violations shall, be adequately supported to carry out their responsibilities.

1. **Prevention and Treatment**

    1. The university shall provide substance-free housing options for specific programs to encourage healthy lifestyles that are free of alcohol and illegal drugs and that require residents, regardless of age, to commit to meeting community standards.

    1. The university shall develop and support effective prevention, assessment, early intervention, and treatment programs for alcohol and illegal drug use. The programs shall be available to students through Counseling and Psychological Services and Student Health Services, and to staff and faculty through programs supported by the Center for Human Resources.

    1. The university shall periodically evaluate the impact of interventions to reduce alcohol and illegal drug abuse and to mitigate the negative personal and interpersonal consequences thereof.

    1. The university shall inform students of campus policies and sanctions for the abuse of alcohol and illegal drugs through such channels and forums as the following: (a) orientation programs, (b) new member education programs, (c) residential life handbooks, (d) SDSU Website, (e) Greek Guidelines, (f) residence hall meetings, (g) recruitment activities.

    1. Within the rules of applicable state and federal laws and regulations, the university shall communicate to students and organizations instances when sanctions are invoked.

:::

## Copyrights, Trademarks, and Trade Secrets {#copyrights-trademarks-and-trade-secrets .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Introduction:** Copyrights are used to protect the rights of creators of a diverse group of products ranging from traditional literary, musical, artistic, and dramatic works to lecture notes, multimedia classroom productions, and computer software. This policy shall be flexible and adaptable.

1. **Definitions**

    a. “assignment of rights”: a transfer of rights under copyright by the owner to the university, a publisher, or any other individual, agency or corporate entity. A transfer of copyright ownership shall not be valid unless it is in writing.

    a. “author” or “creator” (synonymous): one who produces a copyrightable work and is the initial owner of the copyright in the work, except a “work made for hire.” Authors of a “joint work” shall be co-owners of the copyright in the work. Unless otherwise assigned, the author of a contribution to a “collective work” shall be the owner of the copyright in the separate contribution as distinguished from the copyright in the collective work.

    a. “auxiliary”: The official auxiliaries of San Diego State University shall be Aztec Shops, San Diego State University Research Foundation, Campanile Foundation, and the Associated Students.

    a. “auxiliary resources”: funds and material resources, regardless of the sources, that are administered under the control, responsibility, or authority of the President of San Diego State University and the boards of directors of the designated auxiliaries.

    a. “contractual agreement”: an enforceable agreement between the university and individuals or parties.

    a. “copyright”: a legal right to protect certain original works of authorship that are fixed in any tangible form of expression from unauthorized reproduction, sale or other transfer, display, performance, or preparation of a derivative work. Copyright protection shall extend to but not be limited to the following works: (1) literary works such as books, textbooks, technical articles, manuscripts and class notes; (2) musical works, including any accompanying music; (3) dramatic works, including any accompanying music; (4) pantomimes and choreographic works; (5) pictorial, graphic, and sculptural works; (6) motion pictures and other audiovisual works, including classroom videos; (7) sound recordings; and (8) computer software, CD ROM systems, and other programs fixed in a tangible medium.

    a. “copyright notice”: For visually perceptible copies, the copyright notice should contain (1) the symbol “©” or “copyright” or “copr.,” (2) the year of first publication of the work; and (3) the name of the owner of copyright in the work. The copyright notice for sound recordings should contain (1) the symbol, (2) the year of first publication of the sound recording, and (3) the name of the owner of the copyright. The notice should be affixed to copies of the work in such a manner and location as to give reasonable notice of the copyright claim. Copyright is secured automatically when the work is created. For works published on and after March 1, 1989, use of the copyright notice shall be optional, though highly recommended. Before March 1, 1989, use of the notice was mandatory on all published works, and any work first published before that date shall bear a notice or risk loss of copyright protection.

    a. “derivative work”: a work based upon one or more existing works. It is created when one modifies by annotation, editing, translating, or otherwise significantly changing the contents of a work. Only the copyright owner shall have the right to make derivative works. Anyone who creates an unauthorized derivative work, including a user who downloads a copyrighted file, may be liable if the unauthorized derivative work is reproduced, distributed, publicly performed, or publicly displayed.

    a. “duration of copyright”: term of copyright registration. For a work created on or after January 1, 1978, it shall be automatically protected from the moment of its creation and shall be terminated 70 years after the death of the author. For a joint work the term lasts for 70 years after the last surviving author’s death. For “works made for hire” and both anonymous and pseudonymous works, the duration of copyright shall be 95 years from publication or 125 years from creation, whichever is shorter.

    a. “employee”: University employees shall include full-time and part-time faculty, classified staff, student employees, appointed personnel, graduate assistants and teaching associates, persons with “no salary” appointments, and shall also include visiting faculty and academic professionals who develop intellectual property using university or auxiliary resources and facilities unless there is an agreement providing otherwise. Persons who are not such university or auxiliary employees and who come to the university as guest lecturers or to teach colloquia, seminars, or short courses shall not be considered university employees in their teaching and classroom activities unless an agreement provides otherwise.

    a. “fair use”: a use of copyrighted material permitted by law even though no express authorization is granted by the copyright owner as long as the use is for purposes such as criticism, comment, news reporting, teaching, scholarship, or research. Demonstration of such a purpose shall not by itself be sufficient to sustain a claim that the use is “fair.” Fair use shall be determined by the following statutory criteria: “(1) the purpose and character of the use; (2) the nature of the copyrighted work; (3) the amount and substantiality of the portion used in relation to the copyrighted work as a whole; and (4) the effect of the use upon the potential market for the value of the copyrighted work” (U.S. Copyright Act, 1976, sec. 107).

    a. “infringement”: except for fair use and other specifically permitted exceptions, exercise without permission of rights granted by law to the copyright owner; for example, when a material portion of a copyrighted work is copied or is commercially exploited without such permission.

    a. “institution” or “university”: San Diego State University and its auxiliaries.

    a. “institutional support”: resources associated with the creation, production, or distribution of a copyrighted work provided by either San Diego State University or its auxiliaries.

    a. “intellectual property”: ideas, products, processes, and resultant communications that can be protected by law from unauthorized exploitation. This shall encompass copyrights, patents, trademarks, trade secrets, technical data, or know-how.

    a. “license”: that which provides for a contractual relationship in which a copyright owner grants permission for use of the copyrighted material. An “exclusive license” shall provide an agreement by the licensor not to license any other person to exploit the licensed intellectual property and also that the licensor or his agents will not exploit the licensed property. A “sole license” shall reserve the right of the licensor to use or sell the licensed property. A “nonexclusive license” shall allow the licensor to grant other licenses to the intellectual property.

    a. “material”: all copyrightable works including but not limited to writings, lectures, musical or dramatic compositions, sound recordings, films, videotapes, and other pictorial reproductions, computer programs, listings, flow charts, manuals, codes, instructions, and software.

    a. “non-copyrightable works”: works not protected by copyright as follows: (1) ideas, systems, processes, procedures, concepts, or methods; (2) titles of works, names of products or services, even if they are novel or distinctive; (3) names of businesses, organizations, or groups; (4) catch words, slogans, short phrases, and familiar symbols for familiar designs; (5) lists of ingredients, contents, or as a general rule, forms; and (6) information that is in the public domain (common property and property that contains no original authorship) such as standard charts, measuring devices, tables, or lists taken from government public sources.

    a. “owner”: the party or parties who own(s) or control(s) rights to copyrightable material.

    a. “public domain”: material is said to be in the public domain if it is not protected by common law or statutory copyright and is therefore available for copying without infringement.

    a. “publication”: sale, lease, loan, giving away, or otherwise making available to the public the original or tangible copies of a work

    a. “San Diego State University resources”: funds and material resources, regardless of the source, administered under the control, responsibility or authority of both the President of the university and the State of California.

    a. “trademarks,” “trade names,” and “service marks”: A trademark shall be any word, name, symbol, or device, or combination of these, adopted and used by a manufacturer or merchant to identify its goods and to distinguish them from those manufactured or sold by others. A trade name shall be the name of a business, corporation, company, etc., that distinguishes one business entity from another. If the mark is used to identify a service, it shall be classed a service mark. In general, trademarks appear on products and service marks appear in advertising. The first user of a mark generally shall have the right to exclude subsequent users from adopting a similar mark on similar goods or services.

    a. “trade secret”: in California and defined by statute, “information, including a formula, pattern, compilation, program, device, method, technique or process, that derives independent economic value from not being generally known to the public or to other persons who can obtain economic value from its disclosure or use; and is the subject of efforts that are reasonable under the circumstances to maintain its secrecy.” A trade secret shall not be claimed on something that may be readily available by reverse engineering or disassembly. A trade secret shall be kept secret and shall give its owner a competitive advantage over those who do not have access to the secret. Other forms of intellectual property shall be protected via disclosure. Whether particular information constitutes a legally protectable “trade secret” shall be determined through litigation, and misappropriation of a “trade secret” shall be the basis for civil and criminal action.

    a. “work made for hire”: a specifically ordered or commissioned work or a work prepared by an employee within the scope of employment. In such cases, the employer shall be considered the legal author and owns all of the rights in the copyright unless otherwise expressly agreed in writing.

1. **Ownership of and Rights Related to Copyrightable Material**

    1. Those who engage in scholarship and creative activity shall have specific privileges and responsibilities associated with the products of such work. San Diego State University shall subscribe to the general principle that the results of scholarship and creative work shall be the property of those who originate them and who therefore have the right of copyright or final disposition of their work. Such property rights, however, shall be defined in relation to all of the resources contributed by persons, institutions, and agencies involved in the scholarship and development of the creative work.

    1. Institutional support shall refer to both state and auxiliary resources. In institutional support for scholarship and creative activities, auxiliary resources shall be disbursed through the San Diego State University Research Foundation. Nothing in this policy should be construed as affecting the current legal relationship between San Diego State University and its auxiliaries as set forth in the Operating Agreement Between Trustees of The California State University and San Diego State University Research Foundation.

    1. The university shall facilitate creative activities among its faculty and students and shall make its facilities available for such purposes. Where use of university resources has been made in the creation of copyrightable works, the university may exercise its right to participate in the management, protection, and marketing of such works. The assignment of property rights between the institution and its employees shall depend upon the nature and degree of institutional support devoted to the creation of the copyrightable work. Institutional support for an employee’s project yielding copyrightable results shall be classified under one of four categories: (a) commissioned or assigned works, (b) institutional works, (c) partial institutional support, and (d) no institutional support, as defined and specified below.

        1. Commissioned or Assigned Works

            1. A product shall be commissioned or assigned when there exists between the university, acting through any of its agents or auxiliaries, and the author a contractual agreement to develop that specific product.

            1. In a commission or assignment, the contractual agreement shall specify the terms applying to the relative rights and ownership of the copyright and the distribution of royalties between the author and the university or its auxiliary.

            1. In a commission or assignment by the university, the terms of the agreement shall be consistent with university policy.

        1. Institutional Works (Works Made for Hire)

            1. A product shall be an institutional work when it is created for the university or its auxiliaries within the scope of the creator’s employment rather than through a specific contract as in sec. 3.31. For instance, as defined by law, work assigned to employees such as writing a manual or computer program shall be a “work made for hire” whether or not there is an express written agreement specifying that work as a “work made for hire.” However, the parties may agree otherwise in a signed written agreement to that effect in accord with the processes outlined in section 7.4.

            1. Unless specifically commissioned or assigned by the university (sec. 3.31), traditional faculty developed academic works (e.g., class notes and syllabi, recorded or broadcast instructional activity, books and articles, works of fiction and nonfiction, poems and dramatic works, musical and choreographic works, pictorial, graphic, and sculptural works, and educational software commonly known as “courseware”) are not considered works made for hire.

            1. When such works are created independently and at the faculty member’s own initiative for traditional academic purposes, the faculty member shall retain copyright ownership of the work. This policy shall apply independently of the physical medium in which these “traditional academic works” appear, that is, on paper or in audiovisual or electronic form. However, any such works which involve the use of significant institutional resources must be disclosed to the university by the faculty member in accordance with sec. 3.33, Partial Institutional Support. When the university has invested substantial resources in the production of copyrightable material (fixed media), then the work falls under Partial Institutional Support.

            1. The university shall retain, for educational, research, and administrative purposes only, an irrevocable, royalty-free, non-transferable, non-exclusive license to use by its employees and students of any syllabus that has been authored by an SDSU employee and used as the syllabus for an SDSU course offering. The Vice President for Research or designee may waive the university's rights to such a license on a case-by-case basis.

            1. The university or a designated auxiliary shall be considered the legal author and shall own all rights in the copyright to institutional works.

        1. Partial Institutional Support

            1. A product shall be considered to have partial institutional support if the author has made use of institutional resources in the development of the product and if the resource cost to the institution is significant. In computing the total cost of the product, the author’s contribution will include all direct costs incurred by the author and a reasonable value placed on the cost of the author’s time (not all of the author’s time will necessarily be allocated to the author’s credit). Institutional support will include (a) those costs that would not have been incurred by the institution in the absence of the development of the copyrightable work and (b) those other costs associated with the significant use of institutional equipment, supplies, facilities, employee time, or other institutional resources.

            1. The author’s use of office, library, or personal computer shall not be construed to be “significant” use of institutional resources, and projects limited to such institutional support may not be disclosed to the university. Consequently, authors who produce textbooks or other noncommissioned or unassigned works and use no other university resources, shall not be considered to have made “significant” use of institutional resources, and therefore the provisions of sec.3.331 shall not apply. If, however, additional and significant use of university resources was made (e.g., additional and significant secretarial time, photographic services, use of recording studios, or specially purchased materials) in the development of the work, the work shall be considered to have been made with significant institutional support, and therefore the provisions of sec. 3.331 shall apply.

            1. Assigned time for special educational or research projects, or other institutional grants, fellowships, or scholarships shall be considered to be significant university resources when used in conjunction with the development of a copyrightable work. When such resources are accepted as part of a specific commission or assignment that might lead to a copyrightable work, the acceptance constitutes the type of commission or assignment referred to in sec. 3.312, and the terms of secs. 3.331–332 shall apply. When noncommissioned or otherwise unassigned copyrightable works (e.g., textbooks, creative artistic works) are developed in conjunction with the use of such resources awarded primarily for purposes of faculty professional development (including sabbatical leaves and difference-in-pay leaves), the university shall make no claim of copyright ownership or royalty distribution, and the terms of sections 3.331–332 shall otherwise apply.

            1. If a project that is likely to lead to the development of a copyrightable work entails partial institutional support as defined above, the author shall disclose the project to the university. A contractual agreement shall then be made by the institution and the author at the written request of either party. If at all possible, this contractual agreement should be drafted and signed before the author accepts institutional support. The contract should specify all terms having to do with the assignment of copyrights and granting of licenses and the distribution of royalties. These terms shall be negotiated and determined by mutual agreement of the author and the university or the San Diego State University Research Foundation.

            1. If no such agreement can be reached or no contract is made prior to the creation of the work, the issue shall be referred to the University Copyrights and Patents Committee (UCPC). The UCPC shall recommend how the Vice President for Research and Innovation might determine the relative ownership of copyrights and the division of royalties. In the absence of a prior contract stipulating otherwise or as otherwise provided in this policy, this recommendation shall reflect the following general principles:

                a. In compliance with existing university policy, the State shall be compensated for its part of the total institutional support.

                a. The remaining royalties shall be distributed between the author and the San Diego State University Research Foundation according to the relative values of the author’s contribution and the support contributed by the university and the Research Foundation. This calculation will be subject to the limitations of sec. 3.331.

                a. If the difference in the relative contributions of the author and the institution is not significant, net income derived from licensing, distribution, sale of the work shall be divided 50 percent to the author and 50 percent to the San Diego State University Research Foundation. The share distributed to the author shall be the personal income of the author.

                a. Copyright ownership may vest in whole or in part with either the author or the institution, depending on the relative values of the author’s contribution and the institution’s support.

            1. Each contractual agreement regarding ownership or assignment of rights to a copyrightable work having partial institutional support shall include the reserved right for the university to use the work for research or educational purposes free of royalties. Similarly, the author shall have a royalty-free right to use the work for personal, noncommercial purposes.

            1. Whenever persons or organizations other than university employees intend to use university resources or facilities in connection with the creation of a copyrightable work, exclusive of libraries, an agreement shall be executed in advance setting forth the understanding regarding the use of said resources and facilities, ownership rights, and financial arrangements.

            1. If intended or used for commercial purposes, otherwise noncommissioned or non-assigned fixed media reproductions (e.g., films, phonorecords, or magnetic and other electronic recordings) of “real time” performance events occurring in San Diego State University venues, including classroom lectures, laboratory demonstrations or related instructional activities shall be disclosed to the university, and all rights in the copyright to such works shall be determined in accordance with sec. 3.33. The university or its auxiliaries shall not make, distribute, or sell any such works without prior written agreement of the author involved.

        1. No Institutional Support

            1. A project shall be considered to have received no institutional support if the author has not caused the institution to incur any cost over and above the normal costs of supporting instructional activities.

            1. Lacking institutional support, the author of a copyrightable product shall hold all rights and shall receive all royalties. (Cf. sections 7.66–67.)

            1. Authors disclosing copyrightable works created without institutional support or independent of their employment at the university may refer their works to the University Copyrights and Patents Committee for copyright assignment or other disposition. If the University Copyrights and Patents Committee recommends such disposition upon disclosure by the author, the author shall, on the approval of the Vice President for Research, execute a Copyright Agreement and an Assignment of Rights with the San Diego State University Research Foundation. Royalties, less deduction for expenses, shall be shared by the author and the San Diego State University Research Foundation according to the terms specified in the Copyright Agreement as agreed to by both parties.

    1. Works of intellectual property created at San Diego State University that are both copyrightable and patentable shall be governed by the terms of the San Diego State University Patent Policy

    1. Intellectual property developed by students as a result of classwork is ordinarily owned by the students with following exceptions: (a) unless significant institutional resources have been used in the development of the work, in which case ownership shall be determined in accordance with sections 3.3.3 and 3.4; or (b) unless the student has entered an agreement with the instructor specifying alternative terms of copyright ownership; or (c) unless the work was completed under the terms of a contract with the university or its auxiliaries, in which case ownership shall be determined in accordance with sec. 3.3.1.

    1. Ordinarily the author of a thesis or dissertation completed at San Diego State University shall hold the copyright to the manuscript, but that right shall not automatically extend to the data used in developing the manuscript or to subsequent publications based on that data.

1. **Use of the Copyrighted Works of Others**

    1. The university shall protect and shall not infringe on the copyrights of others within or without the university community. Use of copyrighted works without permission of the owner may subject the user and the university to liability from an infringement action or other possible causes of action. Administration, faculty, staff, and students shall restrict their use of copyrighted materials according to university policies, university guidelines, applicable statutes, and relevant court decisions.

    1. Neither shall the rights of copyright owners be exclusive, nor shall permission be necessary for every use. Exceptions to the exclusive rights of copyright owners shall include inter alia (a) “Fair Use” of copyrighted works; (b) limited copying of computer programs; (c) certain “Library Exemptions”; (d) application of the “First-Sale Doctrine,” which shall allow the display and resale of purchased copyrighted work but shall not apply to sound recordings, computer programs, or distribution through a computer network.

    1. The university shall encourage use of copyrighted materials either through acquiring the permission of the copyright owner or under one of the legitimate exceptions outlined in sec. 4.2. (See also “Fair Use of Copyrighted Works: A Crucial Element in Educating America,” The Trustees of The California State University \[1995\].)

1. **San Diego State University Trademarks, Trade Names, and Service Marks**

    1. Trade or service marks relating to goods or services distributed by the university and its auxiliaries shall be owned by the university or the auxiliary. Examples include names, symbols, logos, seal, mascot, or other logos used with university activities and events.

    1. It shall be inappropriate to use without permission the name of the university or any of its auxiliaries with any activity not sponsored or authorized by the university.

    1. Requests to license university trademarks should be addressed to the Vice President for Business and Financial Affairs. Requests to license trademarks owned or affiliated with any of the university’s auxiliaries should be addressed to the General Manager’s office of the auxiliary.

1. **Trade Secrets:** Certain technologies may be licensable to industry as trade secrets. Use of trade secret protection may be approved by the university but should be used rarely. However, if public disclosure will inhibit a company’s willingness to invest the necessary funds for product development and commercialization, the university, in consultation with the employee, may license the subject intellectual property as a trade secret.

    1. Knowledge formalized as a trade secret cannot be disclosed in any open scientific forum as long as it maintains legal trade secret status.

    1. Intellectual property falling within this category shall be treated with regard to licensing and income sharing as are other patented technologies and copyrighted works.

1. **Administration of Policies and Procedures**

    1. Authorized Contracting Officer: The Vice President for Research and Innovation, acting for the President of the university, shall be designated the institutional officer responsible for matters involving intellectual property. The officer may designate other managers or directors of auxiliaries or units of the institution to act on his or her behalf. After consultation with the University Copyrights and Patents Committee and the college dean involved, the Vice President or designee may (a) approve agreements with respect to ownership and other rights related to intellectual property, (b) register copyrights and obtain patents, and (c) grant licenses in the name of the institution for all intellectual property.

    1. San Diego State University Research Foundation: Pursuant to the Operating Agreement between the Trustees of the California State University and the San Diego State University Research Foundation, the San Diego State University Research Foundation shall be designated as the university’s agent for securing and executing agreements with external entities on behalf of the university with respect to intellectual property, in matters other than the award of compensation for university (i.e., State) expenses. The San Diego State University Research Foundation shall also establish and maintain a Technology Transfer Office for the development, management, and commercialization of all intellectual property secured in the name of the university and of all licenses granted by or to the university. The President may designate persons to act as university agents and contracting officers responsible for securing and executing agreements about copyrightable works or trademarks owned by other designated auxiliaries.

    1. Copyrights and Patents Subcommittee: The Vice President for Research and Innovation shall appoint a Copyrights and Patents Subcommittee of the University Research Council.

    1. Intellectual Property Agreements

        1. Agreements Involving University-Commissioned or -Assigned Works (Works Made for Hire)

            1. When employees accept a commission or assignment from the university or one of its auxiliaries to produce a copyrightable work not specifically within the defined scope of their employment, an agreement shall be reached specifying the terms that apply to ownership of the work and to the distribution of royalties between the creator(s) and the San Diego State University Research Foundation. Unless otherwise specified in the agreement, the university shall be considered the author and owner of such specially assigned or commissioned works.

            1. Before commencing any such work on institutional matters involving the creation of intellectual property for or on behalf of the university, nonemployees, independent contractors, and outside consultants shall sign an agreement with the university setting forth the understanding of the use of university resources and facilities, ownership rights, and financial arrangements.

        1. Agreements Involving Works Developed with University Resources: Whenever significant institutional support in the form of either financial or physical resources is used in the creative process from which the intellectual property results, the institution shall have an interest in the work, and a contractual agreement shall be made between the institution and the creators of the work. The contractual agreement shall specify the terms applying to ownership of the work, assignment of copyrights, and the distribution of royalties between the creator(s) and the San Diego State University Research Foundation. These agreements shall be prepared and executed within a reasonable time, ordinarily not to exceed 60 days from the disclosure of the work to the university. If possible, especially wherein the use of university (i.e., State) resources is likely to be substantial, the agreement shall have been made before the use of these resources.

        1. Agreements on the Reimbursement of State Resources. Wherein considerable university (i.e., State) resources have been used in the development of intellectual property, agreements upon the reimbursement of State expenses shall be executed. The Vice President for Business and Financial Affairs shall prepare such agreements and shall represent the interests of the State in negotiating proper agreements with the San Diego State University Research Foundation and the author. These agreements shall be prepared and executed within a reasonable time ordinarily not to exceed 60 days from the disclosure of the work to the university. If possible, wherein the use of university (i.e., State) resources is likely to be substantial, the agreement on reimbursement shall have been made before the use of these resources.

        1. Agreements with Outside Sponsors

            1. If an outside agency provides support for an educational or research project that may result in the creation of intellectual property, the San Diego State University Research Foundation may enter into an agreement with that agency governing the ownership of property rights and the distribution of royalties. In such cases, the Research Foundation may require a written intellectual property agreement with the author on file in order to legally execute contractual agreements about the disposition of copyrightable works of the faculty.

            1. Faculty engaged in sponsored projects that stipulate assignment of intellectual property rights to the San Diego State University Research Foundation or to the sponsor shall (a) execute a written intellectual property agreement with the San Diego State University Research Foundation at the time the grant or contract is accepted by the San Diego State University Research Foundation, (b) execute an Assignment of rights either to the Research Foundation or to the sponsor as the circumstances may require, and (c) promptly disclose intellectual property to the University Copyrights and Patents Committee on an Intellectual Property Disclosure form. The San Diego State University Research Foundation shall notify the sponsor of any inventions and shall take necessary further action.

        1. Model or Property Releases: Model or property releases should be obtained before any videotaping, broadcasting, or other recording or transmission of classroom, laboratory, or other instruction. Those whose names, persons, or likenesses will be shown in whole or in part shall have signed a written release.

        1. Release of University Rights: Wherein the university has ownership rights to intellectual property and the San Diego State University Research Foundation determines that commercialization efforts are no longer justified, the university upon request of the author and for good cause may release copyright ownership to the author. Such releases shall generally be subject to a perpetual royalty-free license to the university to use the work for its own purposes. Requests for reassignment of rights to the author should be submitted to the Associate Vice for Research and Innovation.

    1. Appeals: An author may appeal a decision of the Vice President for Research and Innovation or the Vice President for Business and Financial Affairs regarding the disposition of property rights and royalties. All appeals shall be directed to the President of the university, who after examining necessary evidence may request additional review or modification of the intellectual property agreement.

    1. Use of the University Name

        1. Works Owned by the university. All works of authorship owned by the university shall be published as follows: “© \[year of publication or creation\], San Diego State University. All rights reserved.” Goods owned or distributed by the university or services rendered by the university shall show thereon the university’s trademarks and service marks in packaging and in advertising such goods and services.

        1. Works Owned by the Author or Creator

            1. An employee of the university not acting within the scope of employment may make a true and accurate statement of a relationship or connection with or employment by the university in the course of stating experience or qualifications as an author of the intellectual property.

            1. In those circumstances in which such identification might reasonably be construed as implying the support or endorsement of the work or the advancement or opposition of any political, religious, sociological, or economic movement, activity, or program by the university, the employee shall issue an appropriate disclaimer concurrent with the use of the university name, declaring in substance that the university has not endorsed the work or is not involved in the particular activity or program.

    1. Responsibilities of University Employees and Other Included Parties

        1. The University, its employees, faculty, students, staff, independent contractors, and any person or entity deriving any interest pursuant to this policy shall ensure adherence to this policy and any referenced agreement.

        1. In order to determine the rights of the author and the University, the author of works conceived or developed while employed or enrolled at San Diego State University shall promptly report to the University Copyright and Patent Officer all copyrightable works in which the University may have a right or interest. A written Disclosure of Copyrightable Work and a Declaration of Institutional Support shall be submitted as soon as possible but no later than 30 days from the date of the creation of the work.

        1. The author shall inform all other persons who may have rights to the copyrightable work (e.g., collaborators, research assistants, students) of the terms and obligations of this policy.

        1. The author shall assign to the San Diego State University Research Foundation any and all rights in and to a copyrightable work in which the University has an interest as determined by the University Patents and Copyrights Committee and in accordance with the provisions of this policy.

        1. The author shall cooperate with the San Diego State University Research Foundation in pursuing copyrights, obtaining licenses, or otherwise commercializing intellectual property assigned to the San Diego State University Research Foundation.

        1. The author shall not enter into any “exclusivity agreements” regarding the licensing of copyrightable works that would conflict with normal university work assignments or the satisfactory performance of all duties of the unit employee.

        1. Authors who enter independent copyright agreements with publishers should reserve rights with those publishers to reproduce their own materials for their own instructional and research purposes.

    1. General Advice and Assistance: The Division of Research and Innovation shall provide assistance to faculty, students, and other university employees in complying with this policy. The Technology Transfer Office of the San Diego State University Research Foundation shall provide assistance to faculty, students, and other university employees in recognizing, securing, and protecting intellectual property rights associated with the products of their research and other scholarly endeavors. The author of copyrightable works should contact the Technology Transfer Office or the Division of Research and Innovation for current information on intellectual property procedures and to ensure appropriate action in accordance with the San Diego State University Copyright, Trademark, and Trade Secret Policy.

    1. Income Sharing of Funds Received from Copyrightable Works: Any funds received by the San Diego State University Research Foundation through royalties or licenses or through other consideration for copyrightable works shall be distributed in accordance with the Distribution of Royalty Guidelines developed by the University Copyrights and Patents Committee, recommended by the Vice President for Research and Innovation on advice of the college deans and approved by the President. Such funds shall be used to support scholarly activities at San Diego State University with these exceptions:

        1. Funds generated by a unit of the university (e.g., an academic department) in a specific ongoing function may be used to defray the actual expenses of the function. Specific letters of agreement may be entered into between the university and units involved in such functions.

        1. Royalty income allocated to the author in accordance with a Copyright Agreement between the author and the San Diego State University Research Foundation shall be unconstrained by the stipulations of sec. 7.9.

        1. The disposition of funds accruing to the Associated Students shall be unconstrained by the stipulations of sec. 7.9.

        1. The disposition of funds accruing to certain other auxiliary organizations and formally organized campus groups may, on approval of the President, also be unconstrained by the stipulations of sec. 7.9.

1. Amendments: Any change in the Copyrights, Trademarks, and Trade Secrets policy shall be recommended by the University Research Council and the Vice President for Research and Innovation for approval by the Senate and the President.

:::

## Disabilities, Persons with {#disabilities-persons-with .unnumbered}

::: {.policy-numbering .policy-start-1}

(This policy shall apply to all university employees except those represented by the Academic Professionals of California (Unit 4).)

1. San Diego State University (a) shall provide an environment where faculty, staff and administrators respect disabled persons, (b) shall conform to federal and state legislation that provides equal access to all persons, and (c) shall promote and support full access to its telecommunication and information technology.

    1. The university shall implement the Americans with Disabilities Act; the Rehabilitation Act, sec. 504; California Government Code, secs. 12926, 12940, 12955.3, 12926.1, and 19231; and California Civil Code, secs. 51, 51.5, and 54.

    1. The university shall not discriminate against a qualified person due to a disability in employment application procedures, the hiring process, advancement or promotion, discharge, compensation, job training, or other employment terms, conditions, or privileges. Qualified applicants and employees with disabilities may request reasonable accommodation for their disability to participate in hiring and employment.

    1. The university shall provide disabled persons access to and participation in the university's programs, services, and activities, and it shall inform them of this policy.

    1. Responsibilities

        1. The university (a) shall provide reasonable accommodations when requested regarding the known disabilities of job applicants and employees and (b) shall provide reasonable accommodations for the known physical or mental disabilities of job applicants and employees when requested by them or by someone authorized in writing by the applicant or employee, unless to do so would impose undue hardship on the university. The university shall ensure that its programs, services, and activities are accessible to the general public, including disabled persons.

        1. Disabled job applicants shall request accommodation from the Center for Human Resources. Disabled employees shall request accommodation through their departments and shall provide timely documentation of disability in an interactive process.

1. An accommodation shall be (a) a change or adjustment to a job or learning environment that permits a qualified job applicant or employee with a disability to participate in the job application process, to perform the essential functions of a job, and to enjoy the employment benefits and privileges of employees without disabilities, and (b) a change or adjustment to any program or activity open to the public that permits equal participation by a disabled person.

1. **Compliance**

    1. The Center for Human Resources, in consultation with the University’s Disability Access and Compliance Committee shall develop and maintain procedures to implement and enforce this policy regarding job applicants and employees. The Office of Employee Relations and Compliance shall do likewise regarding the general public. Copies of these procedures shall be available in the Center for Human Resources and the Office of Employee Relations and Compliance.

    1. Complaints regarding application, violation, or enforcement of this policy shall be made to and coordinated by the Office of Employee Relations and Compliance.

    1. Retaliation is illegal. Retaliation against anyone reporting or thought to have reported prohibited discrimination or violation of this policy or who is a witness to or otherwise involved in an investigation of discrimination or policy violation shall be prohibited.

:::

## Faculty, Staff, and Student Conflict of Interest {#faculty-staff-and-student-conflict-of-interest .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Faculty must avoid academic supervisory, teaching, or evaluative relationships with students, staff, or other faculty that pose significant conflicts of interest from the standpoint of personal or professional connections. Such connections might include married couples, domestic partners or other affectional liaisons, supervisor/employee relationships, or parent/child relationships. The appearance of conflict of interest should be avoided; the department chair should be consulted if questions arise.Spouses, domestic partners, parents, or those involved in other affectional relationships must not direct or serve on committees that evaluate their partners, children, or other close relatives. Such committees include thesis, dissertation, or preliminary, comprehensive, or qualifying examination committees, periodic staff evaluations, or annual, three-year, or tenure evaluations.

    1. Students should not enroll in courses offered by their parents, spouses, domestic partners, or partners in affectional liaisons.

    1. An immediate supervisor in an employment relationship (except for a research or teaching assistantship or a situation in which a student serves as a grader for another course taught by a faculty member) should not direct a student’s research nor permit the enrollment of the supervisee in her/his courses or other organized instructional activity.

    1. Any exceptions should be approved and monitored by the chair or director of the faculty member’s unit, unless the chair is involved; in case of involvement, the chair must refer the decision to the dean. If the dean is involved, the exception decision must be referred to the Associate Vice President for Faculty Advancement and Student Success.

:::

## Faculty-Student Relations {#faculty-student-relations .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Governing Principles:** In all matters related to classes and grades, relations between faculty and students at San Diego State University shall be governed by the following principles:

    1. The instructor (i.e., professor, lecturer, or graduate teaching associate) shall be in charge of the class and shall be responsible for its discipline and grading. The instructor shall provide and follow a syllabus, shall maintain an atmosphere conducive to learning, and shall administer examinations and other exercises to determine the level of student attainment in a manner reasonably calculated to minimize the possibility of dishonest work. Grading practices shall meet the highest professional standards of objectivity, fairness, and accuracy, and testing procedures shall be designed to reasonably determine student attainments in the course’s subject matter.

    1. The student shall cooperate with the instructor and fellow students in maintaining an atmosphere conducive to learning. The student shall be courteous to faculty and fellow students and shall be scrupulously careful to adhere to the highest standards of academic honesty.

1. **Disciplinary Responsibilities:** In fulfilling responsibilities, the instructor may impose reasonable penalties for infractions of university and class rules and for instances of student dishonesty. In addition, the instructor shall report all incidents of academic dishonesty to the Vice President for Student Affairs and Campus Diversity or to the appropriate judicial body.

1. **Grade Changes:** The grade given to a student by an instructor shall not be changed by anyone other than the instructor except 1) as described in 9.0 Official Withdrawal, and 2) under the provisions in the Student Grievance Code. In controversies about grades, assigned grades shall be presumed to be correct.

1. For additional discussion of academic misconduct, see University Policies: Academics, Cheating and Plagiarism.

:::

## Nondiscrimination and Equal Opportunity {#nondiscrimination-and-equal-opportunity .unnumbered}

::: {.policy-numbering .policy-start-1}

1. San Diego State University shall maintain and promote a policy of nondiscrimination on the basis of race, religion, color, sex, age, disability, marital status, sexual orientation, gender identity and expression, national origin, pregnancy, medical condition, and covered veteran status. This policy incorporates by reference the requirements of Federal Executive Orders 11246 and 11375 as amended; Titles VI and VII of the Civil Rights Act of 1964 as amended; Title IX of the Educational Act of 1972; the Rehabilitation Act of 1973, secs. 503–504; the Americans with Disabilities Act; the Vietnam Era Veterans Readjustment Assistance Act of 1974, sec. 402; Equal Pay Act of 1963 as amended; Age Discrimination Acts of 1967 and 1978; and other applicable federal statutes as well as pertinent laws, regulations, and executive directives of the State of California, including regulatory procedures set forth in Title 5 of the California Code of Regulations. Persons covered by these regulations shall be considered members of protected groups.

1. The Affirmative Action Program, in compliance with federal and Executive Orders 1088 (2013) and 1026- Revised (2016), shall be revised annually by the Office of Employee Relations and Compliance and shall be disseminated to the campus community. The Nondiscrimination and Equal Opportunity policy shall apply at every level of decisions affecting faculty, staff, administration, and students who are employed by the university. It shall be subject to modification based upon experience and continuing interpretation of the laws of the United States and the State of California and of the policies of The California State University and San Diego State University; but it shall state the university’s commitment to the right of persons to equal employment opportunities without discrimination. The university as an employer shall ensure that employees are recruited, hired, placed, upgraded, promoted, awarded tenure, or terminated for job-related reasons and without prohibited discrimination. If any provision of the Nondiscrimination and Equal Opportunity policy is in conflict with the collective bargaining agreement, the collective bargaining agreement shall be controlling.

1. **Specific Objectives**

    1. To ensure equal employment opportunity for every applicant and employee, without regard to race, religion, color, sex, age, disability, marital status, sexual orientation, gender identity and expression, national origin, pregnancy, medical condition, or covered veteran status;

    1. To determine the appropriate talent and labor pools for each hiring unit for monitoring of placement actions and to ensure that each unit is provided this information at the initiation of a search;

    1. To assist every unit and department in reviewing and modifying its own practices to ensure fair personnel decisions that are objective, consistent with known requirements, and based on work-related rationale;

    1. To ensure that the university works conscientiously to seek applications for employment from the widest possible spectrum of available and qualified persons;

    1. To ensure that stated requirements for positions are essential to the effective performance of the duties of those positions;

    1. To encourage and assist employees in the professional and technical activities that qualify them for promotions;

    1. To ensure that employees have equal access to information that allows them to take advantage of opportunities for advancement;

    1. To ensure that the work environment for faculty, staff, and students is free from both prohibited discrimination and sexual harassment.

1. **Education and Awareness**

    1. The Office of Employee Relations and Compliance and the Center for Student Rights and Responsibilities shall educate employees and students about their rights to be free from prohibited discrimination and sexual harassment and about their obligations to refrain from prohibited discrimination and sexual harassment.

    1. When San Diego State University employees are featured in publications, the representative diversity of our employees should be pictured.

    1. Advertisements for position vacancies shall include the statement, “San Diego State University is an equal opportunity employer and does not discriminate against persons on the basis of race, religion, national origin, sexual orientation, gender, gender identity and expression, marital status, age, disability, pregnancy, medical condition, or covered veteran status.”

    1. The policy shall be published in staff and faculty handbooks, in the University Policy File, and in the University General Catalog, the Graduate Bulletin, and the IVC Bulletin.

    1. The policy shall be distributed to supervisors, and discussions of responsibilities for effective implementation shall be held during management, supervisory, and employee meetings.

    1. An equal opportunity clause shall be included in purchase orders, leases, and contracts.

1. **Office of Employee Relations and Compliance**

    1. The Director of the Office of Employee Relations and Compliance oversees legal compliance for nondiscrimination and nonharassment and coordinates the development and implementation of nondiscrimination and nonharassment policies and procedures. The Director acts as liaison to auxiliary organizations in these matters. The Director is appointed by and reports to the Associate Vice President of Administration in the Division of Business and Financial Affairs.

    1. Two Equal Opportunity Counselors from each college, SDSU Imperial Valley, the Library, Business and Financial Affairs, and University Relations and Development shall be recommended to the Director of the Office of Employee Relations and Compliance by the administrative heads of these units. Nominees for these positions shall be from among tenured faculty and permanent staff.

        1. The Equal Opportunity Counselors (a) shall serve as liaison between the Office of Employee Relations and Compliance and the members of the units, (b) shall offer informal advice and counseling to their peers regarding diversity and discrimination, and (c) shall direct concerned students and employees to the Office of Employee Relations and Compliance or to the Center for Student Rights and Responsibilities.

        1. The Office of Employee Relations and Compliance shall hold regular meetings of the Equal Opportunity Counselors to respond to their concerns and to inform them of recent developments in policy and law.

1. **Chief Diversity Officer**

    1. The Chief Diversity Officer promotes diversity initiatives and coordinates the development and implementation of campus and community outreach programs designed to improve the climate of the campus with respect to diversity. The Chief Diversity Officer acts as liaison to academic Deans; the Office of Faculty Advancement and Student Success; the Divisions of Research and Innovation, Business and Financial Affairs, University Relations and Development, Student Affairs and Campus Diversity, and Information Technology; and UniversityAuxiliaries in these matters. The Chief Diversity Officer is appointed by and reports to the President.

    1. The Chief Diversity Officer, in consultation with the Senate Committee for Diversity, Equity and Inclusion, will implement a process for every division, auxiliary, college, department/school and unit, including the SDSU University Senate, to create and/or revise plans for faculty and staff equity, diversity and inclusion. This will occur at least every five years. Plans should focus on diversity of representation, climate, and equitable success outcomes.

        1. The Chief Diversity Officer, in consultation with the Senate Committee for Diversity, Equity and Inclusion, and in accordance with state, and federal laws and CSU policy, will develop criteria for evaluation, strategies for implementation, a review and approval process, and deadlines for submissions of Equity, Diversity and Inclusion plans.

        1. In accordance with previous Senate resolutions, each Equity, Diversity and Inclusion plan shall provide specific recommendations on how to serve historically marginalized and disproportionately represented communities on campus.

        1. Units without an approved Equity, Diversity, and Inclusion plan shall not conduct faculty and staff searches until the criteria are satisfied, absent Presidential exception.

1. **Diversity Liaisons**

    1. The administrative heads of each college, SDSU Imperial Valley, the Library, Business and Financial Affairs, Student Affairs and Campus Diversity, Information Technology, Research and Innovation, and University Relations and Development in consultation with the Director of the Office of Employee Relations and Compliance shall recommend two Diversity Liaisons to the Chief Diversity Officer. Nominees for these positions shall be from among tenured faculty and permanent staff.

    1. The Diversity Liaisons (a) shall serve as liaison between the Chief Diversity Officer and the unit diversity councils as well as other members of the units, (b) shall offer informal advice and counseling to their peers regarding diversity and discrimination, (c) shall direct concerned students and employees to the Office of Employee Relations and Compliance, to the Chief Diversity Officer, or to the Center for Student Rights and Responsibility, and (d) shall report to the Chief Diversity Officer on existing and new diversity initiatives within their respective units.

    1. The Chief Diversity Officer, in consultation with the Office of Employee Relations and Compliance shall hold regular meetings of the Diversity Liaisons to respond to their concerns, to discuss diversity initiatives, and to inform them of recent developments in policy and law.

1. **Diversity Councils**

    1. To ensure effective shared governance, transparency and broad sharing of relevant information from all voices regarding diversity, inclusion and equity, each college, SDSU Imperial Valley, the Library, Global Campus, Business and Financial Affairs, Student Affairs and Campus Diversity, Information Technology, Research and Innovation, and University Relations and Development shall establish a standing Diversity Council.

    1. The Diversity Councils a) shall review, advise, and provide feedback to the unit’s leadership regarding matters related to students, staff and faculty diversity, equity, and inclusion; b) shall provide guidance and support for the development, implementation and on-going assessment of unit diversity plans; and c) may be involved in coordinating diversity, equity and inclusion initiatives within and across units and contributing to campus diversity, equity and inclusion initiatives.

    1. Each unit shall establish a process for ensuring that the composition of the Diversity Council includes broad representation of the unit’s employees and, as appropriate, students.

1. **Implementation**

    1. Recruitment, Appointment, and Development

        1. No offers of appointment shall be made to any candidate until appropriate steps have been taken to advertise to and reach out to the widest possible pool of talent in the discipline or field for as long and in as many ways as feasible. The processes leading to appointment shall be objective, fair, and rational to ensure genuinely equal opportunity for qualified persons.

        1. Vacancies shall be advertised locally, regionally, and nationally as appropriate. Such advertisements shall be placed strategically, for sufficient time, and on the World Wide Web to attract maximum attention from the widest spectrum of applicants.

        1. Standards and criteria for employment shall be clearly stated and relevant to job requirements and shall be accessible to employees and applicants.

        1. Selection panels, rather than individual interviewers, should be used whenever possible. Search committees and selection panels should be as diverse as possible, including gender.

        1. Specific steps shall be taken to provide guidance and assistance to employees in meeting the criteria for reappointment, tenure, permanent status, and promotion.

    1. Conditions of Work

        1. There shall be no discrimination in terms and conditions of employment including work assignments, classification, educational and training opportunities, benefits, research opportunities, use of facilities, and opportunities to serve on committees or decision- making bodies.

        1. Harassment of any employee on account of race, religion, color, sex, age, disability, marital status, sexual orientation, gender identity and expression, national origin, pregnancy, medical condition, or covered veteran status shall not be tolerated.

        1. Sexual harassment shall not be tolerated. Sexual harassment shall include such behavior as sexual advances, requests for sexual favors, and other verbal or physical conduct of a sexual nature directed toward an employee, student, or applicant as described in Executive Order 1081 (2012).

        1. Persons to be employed at San Diego State University shall be judged on their merits. Therefore, immediate family members of employees may be hired to fill vacancies.

            1. Employees neither shall initiate nor participate in institutional decisions involving a direct benefit (initial appointment, retention, promotion, salary, leave of absence, etc.) to immediate family members nor shall participate in discussions or votes designed to rank other employees in relationship to their immediate family members for the purpose of such decisions.

            1. For the purpose of this policy, “immediate family member” is defined as a close relative including: parent, child, grandparent, grandchild, sibling, uncle, aunt, nephew, niece, first cousin, spouse, registered domestic partner, step-parent, step-child, brother-in-law, sister-in-law, father-in-law, mother-in-law, son-in- law, daughter-in-law, and, by guardianship and/or adoption, a person residing in the immediate household. Relatives of domestic partners shall be treated as relatives of spouses.

        1. No personnel policies or practices shall arbitrarily exclude employees or applicants for advertised positions from employment opportunities because of pregnancy, childbirth, or related conditions. A request by any permanent, female employee for a leave of absence without pay for purposes related to pregnancy, childbirth, pregnancy-related conditions, or adoption shall be granted for up to one year. Additionally, a request by any employee for sick leave or leave of absence with or without pay for these purposes shall be handled in the same manner as requests for other reasons. No female employee shall be required to take a leave of absence before the anticipated delivery date so long as the employee is capable of performing her required duties.

        1. With regard to qualified individuals with a disability or medical condition, the university shall, upon request, provide reasonable accommodation so that they may perform the essential duties of their jobs, unless doing so would impose an undue hardship on the university. Reasonable accommodation is to be determined by the university following its receipt of an individual’s request for accommodation and engagement in an interactive process with the individual to identify the nature and extent of the individual’s restrictions and the appropriate reasonable accommodation.

        1. Any employee who believes that he or she has been treated in violation of nondiscrimination policy may seek redress through the discrimination complaint procedures available on the Website or at the Office of Employee Relations and Compliance. Use of this complaint procedure shall not prejudice access to formal university grievance procedures. The Office of Employee Relations and Compliance shall inform persons with discrimination complaints of other sources of redress outside the university.

        1. Retaliation against individuals, who have or are believed to have filed a discrimination complaint, opposed a discriminatory act or participated in a discrimination investigation or proceeding, is prohibited.

    1. Layoff, Termination, and Rejection or Non-reappointment during the Probationary Period

        1. Layoff for lack of funds or lack of work shall proceed according to campus and CSU policy developed in accordance with relevant sections of Title 5 of the California Code of Regulations and of the California Education Code, and without regard to race, religion, color, sex, age, disability, marital status, sexual orientation, gender identity and expression, national origin, pregnancy, medical condition, or covered veteran status.

        1. Rejection or non-reappointment during the probationary period and termination of employees shall similarly proceed in accordance with relevant policy and code and applicable sections of the Collective Bargaining Agreement, and without prohibited discrimination. The reasons for such action shall be fully documented.

    1. Documentation

        1. The Center for Human Resources and the Office of Employee Relations and Compliance shall jointly maintain statistical records for applicants for employment and for employees of the university. These records shall include by job classification sex, race, and other such characteristics as required by law. Summaries of these data shall be available for appointments to temporary positions, new hiring, promotions, and terminations (including rejection or non-reappointment during the probationary period). These records shall be available for two years.

        1. Departments or appropriate administrative units shall be able to provide records of the reasons for the following personnel actions: failure to appoint applicants, failure to reappoint or grant tenure to probationary faculty, failure to promote eligible faculty, and termination of tenured faculty. The Center for Human Resources shall maintain comparable information for staff. These records shall be retained for at least two years and shall be made available to the Director of the Office of Employee Relations and Compliance.

:::

## Patents {#patents .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Introduction: San Diego State University shall be committed to the development of ideas and to the broad dissemination of these ideas for the purpose of serving the public interest. The university shall also recognize and strive to protect the legitimate private interests of members of the university community who engage in research. Nothing in this policy shall restrict the rights of faculty or staff acting privately outside their capacities as university employees.

1. **Definitions**

    a. “auxiliaries”: official auxiliaries of San Diego State University, namely, Aztec Shops, San Diego State University Research Foundation, Campanile Foundation, and the Associated Students, and other auxiliaries that may be established by the university.

    a. “auxiliary funds”: funds, regardless of the sources, that are administered under the control, responsibility, or authority of the President of the university and the boards of directors of the designated auxiliaries.

    a. “contractual agreement”: an enforceable agreement between the university and other persons or parties.

    a. “inventor”: one or more persons, singly or as a group, who conceive or reduce to practice an invention.

    a. “invention”: (a) any new and useful process, machine, manufacture, or composition of matter, or any new and useful improvement thereof or (b) any patentable plant, for which United States patent rights may be obtained.

    a. “intramural research”: research conducted by a university employee without the aid of external funding by outside sponsors.

    a. “institution”: San Diego State University and its auxiliaries.

    a. “institutional support”: support provided by either San Diego State University or its auxiliaries for a project from which an invention results.

    a. “owner”: party or parties who own or control rights to an invention, whether patented or not.

    a. “patent”: a grant from the U.S. Patent Office or any foreign patent office entitling the patent owner to prevent others from making, using, or selling an invention for a term of years.

    a. “patent agreement”: formal written agreement to do all things necessary to comply with the Patent Policy of the university and to comply with the patent requirements of any grant or contract in which the signer participates. The patent agreement shall obligate the inventor (a) to disclose the details of any and all possible patentable inventions related to the project covered by the particular agreement, (b) to assist the SDSU Research Foundation or an assignee in the preparation and prosecution of any patent applications for inventions arising from the referenced project, and (c) to assign all rights to any such inventions to San Diego State University Research Foundation by means of a formal assignment document specifying the terms of the assignment including the royalty sharing amounts for all parties, including amounts for each inventor, if multiple inventors are disclosed.

    a. “SDSU resources”: funds and material resources, regardless of the source, administered under the control, responsibility, or authority of both the President of the university and the State of California.

1. **Ownership of and Rights Related to Inventions Developed through Intramural Research**

    1. If institutional support in the form of either financial or physical resources is used in the research process from which the invention results, the institution shall have ownership rights in said invention. Moreover, the institution as a public agency shall ensure that inventions are reduced to practice so as to serve the public interest. Discharging this responsibility may involve assisting employees in pursuing patents and marketing products, as well as securing licenses for the use of inventions of value to the institution.

    1. Institutional support shall refer to both State funds and auxiliary funds. For faculty research support, auxiliary funds shall be disbursed through the San Diego State University Research Foundation. Nothing herein should be construed as affecting the current legal relationship between San Diego State University and its auxiliaries.

    1. The assignment of property rights between the institution and its employees shall depend upon the degree of institutional support devoted to the conception, reduction to practice, and development of an invention and products or processes that utilize such an invention. Institutional support for an employee’s project that yields an invention shall be classified under one of two categories:

        1. Full Commission or Assignment

            1. An invention shall be commissioned or assigned when there exists between the university, acting through any of its agents or auxiliaries, and the inventor, a contractual agreement to develop that specific invention.

            1. For commission or assignment the contractual agreement shall specify the terms applying to ownership of the patent and the distribution of royalties between the inventor(s) and the university’s auxiliary.

            1. For commission or assignment by the university, the terms shall be in accordance with controlling university policy.

        1. Partial Institutional Support

            1. An invention shall be considered to have partial institutional support if the institution incurs resource costs associated with the invention. If an invention receives partial institutional support, a contractual agreement defining patent rights and royalty shares shall be made by the institution and the inventor. If State resources are used in the project, the agreement shall provide that the State will be reimbursed for said resource costs from the royalties associated with resulting patents.

            1. For institutional support, royalties from the product shall be divided according to the following formulation: First, in compliance with existing university policy, the State shall be compensated for its part of the total institutional cost. Second, remaining royalties will be distributed between the inventor(s) and the SDSU Research Foundation as specified in secs. 3.323–324.

            1. These relative shares of remaining royalties (sec. 3.322) shall be negotiated and determined by mutual agreement of the inventor and the university or the San Diego State University Research Foundation if such an agreement can be reached prior to the acceptance of partial institutional support by the inventor.

            1. If the parties have not reached an agreement prior to acceptance of institutional support, the issue shall be referred to the University Copyrights and Patents Committee (UCPC). The UCPC shall recommend to the Vice President for Research and Innovation a determination of the ownership of patent rights and the division of royalties. This recommendation shall reflect the following general principles:

                a. The royalty interests in the invention shall be divided in accord with the relative value of the inventor’s contribution and the State or non-State institutional support channeled through the university or the San Diego State University Research Foundation.

                a. In computing these values, the inventor’s contribution shall include direct costs incurred by the inventor (including patent application costs) and a reasonable value placed on the inventor’s time (unless compensated by the institution).

                a. Institutional support shall include only (1) those costs which would not have been incurred by the institution in the absence of the development of the invention (including patent application costs) and (2) those other costs associated with the significant use of institutional equipment, supplies, facilities, employee time, or other institutional resources.

                a. If the difference in the relative contributions of the inventor and the institution is not significant, net income derived from commercialization of the invention shall be divided 50 percent to the inventor and 50 percent to the San Diego State University Research Foundation. The share distributed to the inventor shall be the personal income of the inventor.

                a. Unless otherwise covered by a prior agreement with the inventor (sec. 3.323) or with an outside sponsor (sec. 4.0), or unless the UCPC determines that the contribution of the institution is not significant, ownership of rights to inventions, trademarks, and other tangible research property conceived, reduced to practice, or developed with partial institutional support shall be assigned to the San Diego State University Research Foundation even though the Research Foundation shall share some of the net royalties with the inventor, as specified above.

            1. If a patent management corporation is used to assist with the commercialization of an invention, the provisions of this section shall govern only that part of the royalties in excess of the portion retained by the management corporation.

            1. The UCPC, after consultation with the Vice President for Business and Financial Affairs, may recommend that pursuing a patent would not be in the best interest of the university. In this case, the Vice President for Research and Innovation may determine that patent rights associated with the invention shall belong to the inventor, and the inventor shall be so notified in writing.

            1. Each commercial license or assignment of an invention shall include the reserved right for the university to use the invention for research or educational purposes free of royalty.

    1. Wherein persons or organizations other than university employees intend to use university resources or facilities in connection with an invention, exclusive of libraries, an agreement shall be executed in advance setting forth the understanding regarding the use of said resources and facilities, ownership rights, and financial arrangements.

    1. Inventors disclosing inventions conceived, reduced to practice, or developed without institutional support or independent of their employment at the University may at their option refer their inventions to the University Copyrights and Patents Committee for patent prosecution or other disposition. If the UCPC recommends such disposition upon disclosure by the inventor, the inventor shall on the approval of the Vice President for Research and Innovation execute a Patent Agreement and an Assignment of Rights with the San Diego State University Research Foundation. Any royalties (after deduction for expenses, including the costs of a patent management corporation, if applicable) shall be shared by the inventor and the Research Foundation according to the terms specified in the Patent Agreement as agreed to by both parties.

1. **Ownership of Patent Rights on Sponsored Grants and Contracts**

    1. If an outside agency provides support for a scientific research project, which may result in the conception, reduction to practice, or development of an invention, it may be necessary for the San Diego State University Research Foundation to enter into an agreement with that agency governing the ownership of patent rights and the distribution of royalties. In such cases, the Research Foundation may have to have a written patent agreement with the inventor on file in order to legally execute contractual documents, which agree to dispose of inventions of the faculty.

    1. Faculty engaged in research on sponsored projects that stipulate assignment of patent rights to the San Diego State University Research Foundation or the sponsor shall (a) execute a written Assignment of Patent Rights with the San Diego State Research Foundation, on behalf of the University, encompassing all current and future contracts and grants, (b) promptly disclose any invention to the University Copyrights and Patents Committee by means of the invention disclosure process, and (c) execute a written Assignment Agreement in order to effectuate patent prosecution rights and authority.

    1. The San Diego State University Research Foundation shall notify the sponsor of any inventions and shall take the necessary further action.

1. **Copyrights and Patents Committee:** A University Copyrights and Patents Committee shall be established.

1. **Patent Agreements**

    1. The Vice President for Research and Innovation , acting for the President of the University, shall be designated as the institutional officer responsible for matters involving intellectual property. The Vice President may designate other managers or directors of auxiliaries or units of the institution to act on his or her behalf. After consultation with the University Copyrights and Patents Committee, the Vice President or designee may approve agreements with respect to (a) ownership and other rights related to inventions, (b) obtaining patents, and (c) granting licenses in the name of the institution for all inventions.

    1. Pursuant to the Operating Agreement between Trustees of The California State University and San Diego State University Research Foundation, the San Diego State University Research Foundation shall be designated as the University agent for securing and executing agreements for the University with respect to patents and inventions, in matters other than the award of compensation for University (i.e., State) expenses. The Research Foundation shall also establish a Technology Transfer Office for the development, management, and commercialization of University-owned technologies and shall maintain a central file for patents secured in the name of the University and licenses granted by or to the University.

    1. Wherein University (i.e., State) resources have been used in the development of an invention, agreements upon the reimbursement of State expenses shall be executed. The Vice President for Business and Financial Affairs shall prepare such agreements and shall represent the interests of the State in negotiating proper agreements with the Research Foundation and the inventor. These agreements shall be prepared and executed prior to the initiation of the patent search. If possible, wherein the use of university (i.e., State) resources is likely to be substantial, the agreement on reimbursement shall be made before the use of these resources.

1. **Appeals:** Inventors may appeal a decision of the Vice President for Research and Innovation or the Vice President for Business and Financial Affairs with respect to the disposition of patent rights and royalties. Appeals shall be directed to the President of the university, who may, after examining the required evidence, request additional review or modification of the patent agreement.

1. **Obligations of University Employees and Other Included Parties**

    1. San Diego State University faculty and staff, as a condition of their employment, shall comply with the terms of this policy. Students involved in research, as a condition of their education or employment at San Diego State University, shall also comply with the terms of this policy.

        1. To protect the inventor’s interests and to establish the inventor’s ownership rights to inventions conceived before employment at San Diego State University, each inventor shall disclose to the University Patent Officer at the time of employment, inventions conceived, reduced to practice, developed, or being developed by the inventor.

        1. In order to determine the rights of the inventor and the university, inventors shall promptly report to the University Patent Officer potentially patentable inventions conceived, reduced to practice, or developed while employed or enrolled at the university. Such disclosures shall be made in writing as soon as possible but no later than the 30 days before the date of first publication of the invention.

        1. Inventors shall inform other persons who may have rights to the invention (including co- inventors, collaborators, and research assistants) of the terms of this policy.

        1. Inventors shall assign to the Research Foundation the rights in and to an invention in which the university has an interest as determined by the University Patents and Copyrights Committee and in accordance with this policy.

        1. Inventors shall cooperate with the Research Foundation in pursuing patents or licenses or otherwise commercializing inventions assigned to the university.

    1. The foregoing obligations shall also apply to those who wish to refer inventions or discoveries developed independently of the institution for patent prosecution or other disposition by the university.

1. **Use of Funds Received from Inventions:** Funds received by the San Diego State University Research Foundation through royalties or licenses or other consideration for inventions shall be distributed in accordance with the Distribution of Royalties Guidelines developed by the University Copyrights and Patents Committee, recommended by the Vice President for Research and Innovation, and approved by the President. Such funds shall be used to support scholarly activities at the university with these exceptions:

    1. Funds generated by a unit of the university (e.g., an academic department) in the performance of a specific ongoing function may be used to defray the actual expenses of that function. Specific letters of agreement may be entered into between the university and units involved in such functions.

    1. Royalty income allocated to the inventor(s) in accordance with a Patent Agreement (sec. 6.0) between the inventor and the SDSU Research Foundation shall be unconstrained by the stipulations of this section.

    1. The disposition of funds accruing to the Associated Students shall be unconstrained by the stipulations of this section.

1. **Amendments:** Changes in or exceptions to this policy shall be recommended by the University Research Council and the Vice President for Research and Innovation for approval by the Senate and the President.

:::

## Research, Classified, Controlled Unclassified, Proprietary or Confidential {#research-classified-controlled-unclassified-proprietary-or-confidential .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Classified Research is defined as research, methods and/or results that are restricted to individuals who have U.S. government security clearances.

    1. San Diego State University (SDSU) and/or San Diego State Research Foundation (SDSURF) shall not engage in Classified Research unless all the criteria outlined below are met:

        1. The proposed research has been reviewed and approved by the Vice President of Research and Innovation, Vice President for Information Technology/Chief Information Officer, the appropriate Dean, and Facility Security Officer (FSO).

        1. SDSU and/or SDSURF has met all necessary requirements to obtain clearance to perform research and hold classified information/data as required by the contract and applicable regulations;

        1. All required personnel have obtained necessary security clearances to perform the research as required by the contract and applicable regulations;

        1. The project requires the use of unique specialized facilities or the participation of personnel unique to SDSU and/or SDSURF;

        1. Research does not involve participation by students for work related to fulfillment of degree requirements. Sponsoring faculty are obligated to explain and document this requirement to any students working on a classified project and discuss the fact that Classified Research may not be publishable without third party permission; and

        1. Adequate access to research facilities or instrumentation on-campus used by faculty or students for nonclassified research must be maintained. The sponsoring agency must finance any instrumentation, equipment, or space renovations on-campus designated solely for Classified Research.

    1. No thesis or dissertation shall be accepted as the basis for a degree if it is subject to restraints imposed by Classified Research.

1. Controlled Unclassified Information (CUI) is defined as information that requires safeguarding or dissemination controls pursuant to and consistent with applicable law, regulations, and government-wide policies but is not classified.

    1. SDSU and/or SDSURF may engage in research involving CUI provided all the following conditions are met:

        1. The research has been reviewed and approved by the Vice President of Research and Innovation, the Vice President for Information Technology, and appropriate Dean;

        1. All required personnel must complete CUI training;

        1. All required personnel must complete export control training and Technology Control Plan (TCP), if applicable;

        1. All required personnel must abide by SDSU CUI Policy;

        1. Protection of specifically identified CUI is essential for the conduct of the research that is disclosed to the SDSU investigator by an external sponsor under the terms of a confidentiality agreement or other applicable agreement between the investigator, SDSURF and the owner of the CUI; and

        1. CUI is appropriately identified by the providing agency.

    1. Principal Investigators are obligated to document that any students who will work or any research involving CUI have received training on the proper treatment of CUI in advance and understand that certain aspects of research involving CUI may not be publishable.

    1. A thesis or dissertation may be accepted as the basis for a degree on a case by case basis if it is subject to restraints imposed on research involving CUI. The Dean of the College of Graduate Studies may approve requests from students to withhold library shelving of a thesis or dissertation approved by the faculty for up to one year to protect the patent or other proprietary rights of students and faculty.

1. Proprietary or business confidential research refers to projects that involve requests from sponsors or others for the nondisclosure of the project.

    1. San Diego State University may engage in proprietary or business confidential research provided the following conditions are met:

        1. Brief delays in the publication of research for patenting or other proprietary purposes (one year maximum on approval of the Vice President for Research and Innovation) or for sponsor review and comment on manuscripts (not to exceed 120 days) provided that sponsor agrees that no changes in the manuscript be made without the consent of the author;

        1. Protection of specifically identified proprietary information essential for the conduct of the research that is disclosed to the SDSU investigator by an outside sponsor, person, or entity under the terms of a non-disclosure agreement between the investigator, SDSURF and the owner of the intellectual property;

        1. Maintenance of confidentiality in certain research-related activities primarily undertaken as a service wherein the project director certifies in advance that the activity is not primarily "research" and the results are not independently publishable (on approval of the Vice President of Research and Innovation or designee); or

        1. The research has been reviewed and approved by the Vice President of Research and Innovation, and appropriate Dean.

    1. A thesis or dissertation may be accepted as the basis for a degree on a case by case basis if it is subject to restraints imposed by proprietary or business confidential research. The Dean of the College of Graduate Studies may approve requests from students to withhold library shelving of a thesis or dissertation approved by the faculty for up to one year to protect the patent or other proprietary rights of students and faculty.

    1. Permissible delays

        1. The university may enter into nondisclosure agreements to allow for the exchange of proprietary information between partnering institutions during proposal development and submission.

        1. The university may agree to delay the submission of materials intended for publication for a maximum of 60 days to provide time for a sponsor to review such materials for confidential proprietary information that is protected under a sponsored agreement. In addition, because public disclosure of a patentable invention prior to filing a patent application precludes the availability of patent protection in most countries, the university may agree to delay the submission of materials intended for publication for a maximum of 90 days, not including the 60-day review period stated above, in order to seek patent protection.

        1. If an agreement proposes a restriction on publication, a Publication Waiver must be reviewed and approved by the Vice President of Research and Innovation, and appropriate Dean.

    1. Maintenance of confidentiality in research for protection of individual rights to privacy pursuant to the university's Guidelines on the Protection of Human Subjects, the Family Education Rights and Privacy Act, the San Diego State University Student Records Policy, and other applicable state and federal regulations shall not be construed as proprietary or business confidential research.

:::

## Research and Scholarship, Integrity in {#research-and-scholarship-integrity-in .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Members of the academic community engaged in research and scholarly activities are required to uphold the highest standards of ethical conduct. This policy applies to all individuals affiliated with San Diego State University, including those conducting research funded by the Public Health Service (PHS), as well as unfunded research, scholarship, or projects for which grant or contract applications have been submitted.

    The procedures outlined herein are designed to safeguard the rights and reputations of all parties involved in allegations of misconduct, including students employed on research grants or contracts. Allegations of academic dishonesty by students conducting research as part of their academic program shall be addressed in accordance with University academic policies, student disciplinary procedures, and the regulations of the Division of Research and Innovation.

    To maintain eligibility for federal funding, the University must comply fully with all applicable federal regulations. Adherence to this policy is a mandatory condition of funding and is not subject to negotiation. Failure to comply will result in suspension or termination of federal financial support. The Research Misconduct Policy is found here: [SDSU Research Misconduct Policy Jan. 2026 Final Approved Revised 1\_7\_2026.pdf](https://drive.google.com/file/d/1_CApJqq-rTXf3I0VPGok6qXBs80YwDfi/view)

:::

## Sexual Assault, Domestic Violence, and Stalking {#sexual-assault-domestic-violence-and-stalking .unnumbered}

::: {.policy-numbering .policy-start-1}

1. San Diego State University shall be committed to creating a community free from the crimes of sexual assault, domestic violence, and stalking. All members of the San Diego State University community shall uphold this policy.

1. The university shall cooperate fully in any criminal prosecution or civil litigation that may occur as a result of crimes of sexual assault, domestic violence, or stalking that are committed on the campus, at an off- campus facility, or at a university function.

1. A person who is convicted of committing these crimes on university property, at a university off-campus facility, or at a university function shall face maximum campus sanctions as prescribed by policies, codes, and collective bargaining agreements that govern the behavior of students, faculty, staff, and guests or visitors.

1. Members of the campus community and their guests or visitors should report crimes of sexual assault, domestic violence, and stalking to the appropriate university officials. A list of those appointed to receive these complaints and a summary of campus resources available to survivors of these crimes shall be made available.

    1. Those who have experienced or witnessed the crimes of sexual assault, domestic violence, and stalking should seek immediate assistance from the University Police and campus caregivers. Those seeking assistance shall be treated with respect and dignity, and their concerns shall be responded to in a timely and professional manner. To ensure a responsive environment to victim, the university shall provide support services to address the personal and academic needs of those surviving sexual assault, domestic violence, and stalking while these crimes are being investigated and prosecuted on and off the campus.

    1. University officials responding to charges of sexual assault, domestic violence, and stalking shall inform victims of their rights and the various options for relief, including the necessary steps and potential consequences of each option. These shall include but may not be limited to support in pursuing criminal prosecution, civil litigation, campus disciplinary action, and campus grievance procedures. Victims shall also be counseled about various options including mediation, alternative housing assignments, and academic scheduling assistance.

1. This policy has been enacted by San Diego State University in accordance with California State Law, Assembly Bill 3098, Postsecondary Education: Student Safety (July 1990).

:::

## Sexual Harassment {#sexual-harassment .unnumbered}

::: {.policy-numbering .policy-start-1}

1. San Diego State University shall be committed to preventing sexual harassment and to promptly addressing violations of this policy. The university shall create and maintain a positive learning and working environment for its students and employees and shall not tolerate sexual harassment. Nothing herein shall contravene rights guaranteed in the Constitution of the State of California or the Constitution of the United States.

1. Sexual harassment and its behaviors shall be prohibited by the university: Sexual harassment is demeaning and degrading and a form of prohibited discrimination on the basis of sex. As an affront to one’s dignity, sense of self, and self-esteem, it can negatively impact performance at work or in an academic setting.

1. Sexual harassment is illegal: It is a violation of state and federal laws including the California Education Code, sec. 212.5, Title VII of the Civil Rights Act of 1964, and Title IX of the Education Amendments of 1972. Sexual harassment is specifically prohibited in The California State University by Executive Order 1096 (2016).

1. **Scope**

    1. This policy shall apply to all persons at the university or attending university sponsored classes, events, and programs. Visitors to the campus and workers employed by private firms engaged in business on the campus shall comply with this policy.

    1. The SDSU Research Foundation, the Campanile Foundation, Aztec Shops, and the Associated Students, as auxiliaries of the university, also have policies that prohibit sexual harassment. These policies apply to programs and employees of the respective auxiliaries and each has a procedure and office designated for receiving reports of sexual harassment. Complaints related to auxiliaries may also be reported to the Office of Employee Relations and Compliance.

    1. The university and its auxiliaries shall promptly and reasonably investigate complaints of sexual harassment. If the alleged harasser is an employee of the university or of an auxiliary, the employer shall investigate and implement remedies and discipline as appropriate. Wherein the alleged harasser is not an employee or student, the university or auxiliary shall take action to minimize the recurrence of the harassing behavior. Although each auxiliary has a reporting procedure, complaints may be reported to the Office of Employee Relations and Compliance, which shall redirect the complainant to the appropriate auxiliary.

1. **Definitions**

    1. Sexual harassment shall be the unwelcome imposition of sexual attention often in the context of a relationship of unequal power. This policy shall apply to men and women equally with regard to both opposite sex and same sex harassment.

    1. Sexual harassment shall be any conduct, physical or verbal, that is sexual and has the effect of unreasonably interfering with a person’s or a group’s educational or work performance or that creates an intimidating, hostile, or abusive educational or work environment.

    1. Because academic freedom shall be safeguarded and the openness and integrity of the teaching process shall be protected, discussion of sexual topics and the discussion and display of sexually explicit materials and the touching of students in certain classroom settings may be professionally appropriate and shall not necessarily constitute “sexual harassment.”

    1. The California Education Code, sec. 212.5, states: “Sexual harassment means unwelcome sexual advances, requests for sexual favors, and other verbal, visual, or physical conduct of a sexual nature, made by someone from or in the work or educational setting, under any of the following conditions:

        1. “Submission to the conduct is explicitly or implicitly made a term or a condition of an individual's employment, academic status, or progress.

        1. “Submission to, or rejection of, the conduct by the individual is used as the basis of employment or academic decisions affecting the individual.

        1. “The conduct has the purpose or effect of having a negative impact upon the individual's work or academic performance, or of creating an intimidating, hostile, or offensive work or educational environment.

        1. “Submission to, or rejection of, the conduct by the individual is used as the basis for any decision affecting the individual regarding benefits and services, honors, programs, or activities available at or through the educational institution.”

    1. Examples of sexually harassing conduct may include but shall not be limited to the following: (a) sexual assault, (b) derogatory comments of a sexual nature, (c) displaying sexually suggestive pictures or objects, (d) graphic verbal commentaries about a person’s body, (e) impeding or blocking movements, (f) jokes of a sexual nature, (g) slurs of a sexual nature, (h) suggestive gestures, (i) unwelcome touching. Some of these examples may not, however, constitute sexual harassment if appropriate to reasonable academic purposes.

    1. Conduct may be found to be sexually harassing if it is pervasive or repetitive and sufficiently severe to alter the conditions of employment, education, or participation in university-sponsored activities or is a single incident sufficiently outrageous or harmful in and of itself that it substantially alters the conditions of the environment for the complainant or interferes with a person’s right to pursue an education or to perform a job-related responsibility.

1. **Intent of Sexually Harassing Behavior:** A claim by an alleged harasser that he or she did not intend to commit sexual harassment is not, as the law currently stands, a defense to a complaint of sexual harassment. Regardless of intent, the effect, characteristics, and context of the behavior shall determine whether the behavior constitutes sexual harassment.

1. **Sanctions for Sexual Harassment**

    1. Sanctions that San Diego State University may impose for sexually harassing behavior or other unprofessional conduct by a faculty or staff member shall include but not be limited to reprimand, mandatory attendance at sexual harassment training programs, suspension, demotion, and dismissal (loss of tenure).

    1. Sanctions imposed for sexually harassing behavior by a student shall include but are not limited to mandatory attendance at sexual harassment training program, probation, suspension, and expulsion.

    1. Sexually harassing behavior by nonstudents or nonemployees may result in restricting the harasser’s access to campus.

    1. In addition to university-imposed sanctions, persons who commit sexual harassment shall be subject to personal liability for damages suffered by the complainant.

1. **Consensual Relationships:** For purposes of this policy, a consensual relationship shall be any freely and mutually agreed-to dating, romantic, or sexual relationship between persons. The previous existence of a consensual relationship shall not be considered a defense in the context of a sexual harassment complaint.

1. **Administrative Office for Coordinating Complaints:** The Office of Employee Relations and Compliance shall coordinate the university response to complaints of sexual harassment and shall educate the university community about sexual harassment. It shall be a clearinghouse for university sexual harassment complaints and investigations, including those that arise in auxiliary corporations. It shall develop and disseminate sexual harassment complaint procedures to implement this policy and shall disseminate applicable state and federal regulations. Copies of these procedures shall be available at the Office of Employee Relations and Compliance and on its Website.

1. **Mandatory Reporting by University Officers:** Upon learning of allegations of sexual harassment from the alleged victim, deans, directors, department chairs, and other officers of the university shall report the allegations to the Office of Employee Relations and Compliance within five working days.

1. **Procedures for Reporting Sexual Harassment**

    1. A student, staff, or faculty member who believes that he or she has been sexually harassed may initiate a complaint with the Office of Employee Relations and Compliance or the designated office in the appropriate auxiliary. The Office of Employee Relations and Compliance or the auxiliary shall investigate complaints of sexual harassment and coordinate a formal investigation, a mediated intervention, or a formal mediation.

    1. A formal investigation shall be initiated by the complainant filing and submitting a Formal Complaint Form with the Office of Employee Relations and Compliance or by lodging a complaint with the appropriate auxiliary office. The procedures and time schedule for a formal investigation shall be available from the investigating office.

    1. Mediated interventions shall include but not be limited to steps to stop the harassing behavior or to remove the complainant or alleged harasser from the harassing environment.

    1. At any time from the initiation of a complaint to the conclusion of the campus investigation, either party or the university may suggest a confidential, nonbinding formal mediation of the dispute. Both parties and the University shall agree to any formal mediation and any resolution that arises therefrom.

    1. Without filing a formal complaint, a student, faculty member, or staff member may discuss with staff in the Office of Employee Relations and Compliance behaviors that could be sexual harassment. If a described behavior fits the definition of sexually harassing behavior, some intervention may be required.

    1. The university shall ensure that formal procedures appropriate to university complaints are followed. These procedures shall be governed by law, labor agreements, and university policy.

1. **Other Persons to Contact**

    The Office of Employee Relations and Compliance shall coordinate the university response to complaints of sexual harassment. A list of other personnel in the auxiliaries trained to receive complaints of sexual harassment shall be available at the Office of Employee Relations and Compliance and in informational material regarding the Sexual Harassment Prevention policy. Lists shall also be available in the auxiliaries

    1. Conversations with persons other than those designated shall not constitute notice to the university or its auxiliaries of allegations of sexual harassment.

1. **University Support:** Upon receiving a complaint of sexual harassment, the Office of Employee Relations and Compliance shall inform the complainant of the support services available at the university and in the community. At the university this may include the Chief Diversity Officer, Office of Counseling and Psychological Services, the Office of the Ombudsman, Student Health Services, Employee Assistance Programs, and Campus Police.

1. **Confidentiality**

    1. The Office of Employee Relations and Compliance and each designated auxiliary office shall maintain confidentiality for all parties to the extent permitted by law. The university or auxiliary shall take prompt action to correct sexually harassing behavior when it is reported. At the complainant’s request, the university or auxiliary shall attempt to intervene in a manner that shall maintain the complainant’s anonymity. However, complainants should be aware that in a formal investigation due process requires that the identity of the charging party and the substance of the complaint be revealed to persons charged with harassment.

    1. Students who wish complete confidentiality may obtain confidential counseling and advice about sexual harassment from counselors in the Office of Counseling and Psychological Services or Student Health Services. Faculty and staff may obtain confidential counseling and advice through employee assistance programs. Since university officials and auxiliary officials shall not be informed about such counseling, the university and its auxiliaries shall not be in a position to eliminate the alleged behavior that gave rise to the complaint.

    1. Nonparty witnesses participating in sexual harassment investigations shall not share with parties, other witnesses, or any others information revealed to them during the investigation.

1. **Record Keeping:** The Office of Employee Relations and Compliance and each designated auxiliary office shall keep the written records of mediated interventions, formal mediations, and formal complaints with final dispositions in a confidential, secure location with access to the records limited to those persons with a need to know. Records shall be kept for 10 years.

1. **Retaliation against Persons Reporting Sexually Harassing Behaviors**

    1. It is illegal to retaliate against anyone reporting or thought to have reported sexual harassment behaviors or who is a witness or otherwise is involved in a sexual harassment proceeding. Encouraging others to retaliate also is illegal. Examples include but are not limited to retaliatory grading, evaluation, assignment or ridicule, threats, and withholding information to which a person is entitled.

    1. Sanctions imposed for retaliatory behavior by a faculty or staff member shall include but not be limited to reprimand, suspension, demotion, and dismissal (loss of tenure). The sanctions imposed for retaliatory behavior by a student shall include but not be limited to probation, suspension, and expulsion.

1. **False Charges**

    1. To make false charges of sexual harassment shall be a serious offense. A false charge shall be one in which the charging party knowingly or recklessly alleges sexual harassment for which there is no basis.

    1. Sanctions imposed for false charges of sexual harassment by a faculty or staff member shall include but not be limited to mandatory attendance at a sexual harassment training program, reprimand, suspension, demotion, and dismissal (loss of tenure).

    1. The sanctions imposed for false charges of sexual harassment by a student shall include but not be limited to mandatory attendance at a sexual harassment training program, probation, suspension, and expulsion.

1. **Other Legal Remedies:** Complainants not satisfied with the disposition of their complaint at the university may contact the Fair Employment and Housing Office of the State of California, the United States Department of Education Office for Civil Rights, or the Equal Employment Opportunity Commission. Contact information shall be available at the Office of Employee Relations and Compliance.

1. **Policy Review, Evaluation, and Improvement:** This policy shall be evaluated every two years by the Office of Employee Relations and Compliance. Proposed changes shall be forwarded to the Senate.

1. **Information Distribution and Training:** The Office of Employee Relations and Compliance shall distribute this policy to the university community and shall provide educational opportunities appropriate to faculty, staff, and students.

:::

## Student Conduct Procedures {#student-conduct-procedures .unnumbered}

::: {.policy-numbering .policy-start-1}

The Student Conduct Procedures of The California State University are outlined in Executive Order 1098- Revised (2015). The Executive Order may be found at https://[www.calstate.edu/eo/EO-1098-rev-6-23-15.html](http://www.calstate.edu/eo/EO-1098-rev-6-23-15.html)[.](http://www.calstate.edu/eo/EO-1098-rev-6-23-15.html)

:::

## Student Grievance Code {#student-grievance-code .unnumbered}

::: {.policy-numbering .policy-start-1}

1. A grievance shall be a complaint arising out of any alleged unauthorized or unjustified act or decision by a member of the faculty, administration, or staff that in any way adversely affects the status, rights, or privileges of a member of the student body. The burden of proof shall lie with the complainant.

1. The Student Grievance Committee (SGC) shall hear complaints, investigate grievances and make final judgments regarding redress of student grievances concerning members of the faculty, administration, or staff. The Student Grievance Committee may make advisory recommendations regarding disciplinary action to appropriate administrators.

    1. The voting members of the Student Grievance Committee shall be:

        a. Five students and three alternates named by the Associated Students. Undergraduate students serving on this committee shall be regular students in good standing. Graduate students shall have been admitted to an authorized advanced degree or credential program;

        a. Three tenured and probationary faculty members and two alternates named by the Senate;

        a. Two full-time members of the administration and two alternates named by the President; and

        a. One full-time staff representative and one alternate named by the Senate.

    1. The Ombudsman shall be a non-voting ex officio member.

    1. Seven voting members shall constitute a quorum. Judgments shall be reached by a majority of those present and voting, except where otherwise indicated (see sec. 4.2.).

    1. Each student member shall be appointed for two years. Non-student members shall be appointed for three years. No member shall serve more than two terms consecutively.

    1. A nonvoting Chair shall be appointed for a two-year term by the President of the University. A nonvoting Vice Chair shall be selected by the Associated Students. No member shall serve as Chair more than two consecutive terms. The Chair shall be the Committee’s administrative officer whose duties shall include the following: (a) arranging for appropriate times and places for meetings and hearings, informing members of the times and places of meetings and hearings, informing in writing all interested parties of the times and places of meetings or hearings that they are requested to attend and supplying them with a statement of alleged grievances, and informing all other interested parties that a grievance is pending and of the final disposition of the grievance; (b) securing and distributing written material appropriate for its consideration; (c) arranging for the recording of proceedings; (d) maintaining records and informing in writing the appropriate administrator of the committee’s judgments regarding redress or recommendations regarding disciplinary action.

    1. Should any member of the Committee be unable to complete an appointed term, a replacement shall be appointed to fill the balance of the term by the original appointing officer or agency. Resignations shall be submitted in writing to the Chair of the Committee. The Chair shall inform in writing the appropriate officer or agency of the vacancy and shall request the prompt appointment of a replacement.

    1. Should a Committee member be unable to hear a case, an alternate shall be appointed for the course of the grievance.

    1. If a member of the Committee is granted an official leave for less time than remaining in a term, or if because of illness or other reasons a member is judged unwilling or unable to participate in the work of the Committee, the Chair shall inform the officer or agency of the appointee and shall request the prompt appointment of a temporary replacement. When the services of a temporary appointee are no longer required, the Chair shall promptly inform the temporary appointee and the appointing officer or agency.

        1. Should the Committee be involved in a specific case when an absent member returns, the replacement member shall continue as a member of the committee in all sessions dealing with that specific case until it is concluded. The returning member shall resume membership on the Committee for subsequent cases.

        1. When a member of the Committee has more than three consecutive absences, the Committee may vote to remove that member and may request a replacement from the appointing officer or agency.

    1. A member of the committee may be reappointed upon the expiration of term if duly recommended by the designated persons as specified in 2.1, but the member may be appointed for a third term only after a break in service of no less than one year. If the Committee is involved in a case when a member’s term expires, the member shall continue on the Committee only in its consideration of the case. A newly appointed member shall not be considered a member of the committee for a prior continuing case. The new Committee member shall, however, serve for all other matters.

    1. A member of the Committee may choose to be disqualified permanently from the Committee, in which event a replacement for the balance of the term shall be appointed by the original appointing officer or agency.

        1. A member of the Committee may choose to be disqualified from consideration of any case, in which event a replacement shall be appointed by the Chair of the Committee from the list of alternates of the member’s constituency.

        1. If a member is a principal in a preliminary investigation or hearing by the Committee, the member shall be excluded from considering that case.

        1. Upon the conclusion of a hearing in which a Committee member was a principal, the Committee shall determine the member’s fitness to continue on the Committee. The decision shall be conveyed by the Chair to the appointing officer or agency, either informing of the continuation of membership or requesting a replacement.

    1. Either party to a hearing may request of the Chair that a Committee member be excluded from considering the case. The request shall be for cause and shall be brought to the Chair’s attention as the first item in the hearing. If a member is disqualified by the Chair from consideration, a replacement shall be appointed by the Chair from the list of alternates of the member’s constituency.

1. **Steps toward Redress**

    1. Steps toward redress should begin with informal discussions and should be resolved at the lowest level possible. If a satisfactory solution is not reached, the grievance should then be taken to the Student Grievance Committee for hearing and appropriate action.

    1. Informal Discussion

        1. Informal discussion between persons directly involved in a grievance shall be essential in the early stages of the dispute and should be encouraged at all stages. An equitable solution to a problem should be sought before the persons directly involved in the case have assumed official or public positions that might polarize the dispute and render a solution more difficult. Neither persons directly involved in a case nor any other persons shall use the informal discussion, the filing of a grievance, or the character of the informal discussions to strengthen the case for or against persons directly involved in the dispute or for a purpose other than to settle the grievance.

        1. When a student feels aggrieved by a member of the faculty, administration, or staff, the student may consult with fellow students, non-involved faculty members, the counseling staff, the Ombudsman, the Assistant Dean of the College in which the course was taken, the Associate Vice President for Faculty Advancement and Student Success or the Dean of the College of Graduate Studies to evaluate the situation and to determine which of the following steps might best apply:

            a. The student should bring the complaint to the attention of one or more of the proper department, school, or college committees where such grievance provision exists or to the chair, director, dean, administrator, or staff supervisor; or

            a. The student should bring a complaint against an administrator or staff member to that person’s supervisor.

    1. Procedures for Hearings by the Committee

        1. No student grievance shall be filed with the Committee later than the last day of the semester (excluding summer session) after the semester during which the student was allegedly aggrieved.

        1. When informal recourse fails, the student may file in writing to the Committee an appeal accompanied by available documentary evidence. Simultaneously a copy of the complaint shall be given to the respondent.

        1. The Committee shall establish and publish its own procedures in accordance with provisions for academic due process and in accordance with the stipulations below. Present at these meetings shall be only Committee members, parties to the action and their representatives, and testifying witnesses.

        1. The Committee, before sitting as a whole to arrive at judgment, shall arrange for a swift and comprehensive investigation of the matter. From written statements presented by the complainant and from preliminary discussions with the complainant it shall decide whether there are sufficient grounds to hear a case and whether it will accept written statements in lieu of personal appearances by witnesses. The Committee shall review and consider documentary records of department, school, or college grievance organizations relating to the case. If the Committee closes the case, having decided that there are not sufficient grounds for a hearing, it shall notify in writing the complainant and respondent as to the reasons for its actions.

        1. If the Committee determines that the case merits further consideration, the parties involved (a) shall be informed in writing, (b) shall be consulted as to the possibility of correcting the situation, and (c) if a hearing is still required, shall be advised in writing of the scheduled time, place of the hearing, and the alleged grievance.

        1. At the hearing the complainant, the respondent, persons directly involved, and witnesses may testify and be questioned by either party and Committee members. Written evidence presented by either party may be subject to refutation and consideration by the opposite party and Committee members. Only evidence presented in the hearings shall be considered in the final judgment.

        1. A record of the hearing shall be presented for reference and review. A tape recording of the hearings shall be made and shall be retained for at least five years.

        1. Proceedings shall be conducted in accordance with the American Association of University Professors’ Joint Statement on Rights and Freedoms of Students (1967).

1. **Judgment**

    1. Committee members shall arrive at a judgment in consultation among themselves. Only those entitled to vote on the case, their alternates, the chair, the Ombudsman, and a clerk secretary shall be present during consultation and voting. Only members of the Committee who have heard all testimony during the hearing relating to the alleged grievance shall vote on the case.

    1. If informal attempts at redress fail, a judgment of the Student Grievance Committee relating to redress alone shall be forwarded to the appropriate administrator. When redress requires that a grade be changed, the Committee by vote of two-thirds of the members of the Committee who have heard the grievance shall forward their judgment to the Provost who shall affirm or deny the judgment of the Committee. If the Provost affirms the decision, the Provost will direct the appropriate administrator for recommended redress. When the decision whether to change a grade depends upon the quality of work in a course, the chair of the department involved in the grievance will be asked by the SGC to recommend faculty at SDSU or elsewhere competent in the subject matter of that course to evaluate the quality of the work. This expert consultation will be considered by the SGC before a judgment is reached.

    1. The Committee shall transmit its judgment regarding academic matters to the Provost who will direct final action. The committee shall transmit its judgments regarding redress for other matters to the appropriate administrator.

    1. When in the opinion of the Committee disciplinary action may be appropriate, the Committee may recommend further action to the appropriate administrator.

    1. The judgments reached by this Committee shall take precedence over decisions reached by student grievance committees within departments, schools, or colleges, and over decisions made by individual deans.

    1. If redress requires a policy change or if a policy change appears advisable or necessary, the Committee shall refer its recommendations to the Senate Executive Committee or to the President as appropriate.

    1. Should any person, whether or not directly involved in a complaint, allegedly suffer some disadvantage, discrimination, or reprisal as the result of a complaint, testimony, or statement in connection with Committee action, the Student Grievance Committee shall, upon request or upon its own motion, exercise original jurisdiction and take the necessary steps to verify the facts and remedy the injustice.

1. **Revisions in the Code**

    1. The Committee may recommend revisions in this code. Revisions shall be submitted for ratification by the Senate, the Associated Students, and the President.

    1. This code shall be reviewed by the parties concerned and shall be reconfirmed, amended, or terminated as necessary

:::

## Sustainability {#sustainability .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Sustainability Policy**

    1. San Diego State University (SDSU) shall create accessible paths for University shareholders to achieve sustainability goals and resilience planning which benefit social, environmental, and economic health.

    1. The Senate Sustainability Policy shall benefit the greater San Diego region and apply to all students, faculty, staff, and auxiliaries—and their respective areas—for the University’s Mesa, Imperial Valley, Mission Valley, Georgia, and all future SDSU campuses.

    1. SDSU shall comply with rules and regulations regarding sustainability issued by the city of San Diego, the California State University (CSU) , the State of California, and the Federal Government.

    1. SDSU shall strive to achieve the goals of the 2017 Climate Action Plan (CAP) and construct new goals that reflect contemporary needs such as full carbon neutrality by 2030 with a feasibility study in place.

    1. SDSU shall heed recommendations of both the United Nations Sustainable Development Goals and the Association for the Advancement of Sustainability in Higher Education (AASHE) while evaluating and updating our current CAP as appropriate.

    1. SDSU shall designate a central administrative role committed to the implementation and integration of sustainability across all SDSU campuses.

    1. SDSU shall strive towards developing and implementing a Zero Waste Policy which will prioritize the purchasing of recycled products whenever possible.

    1. Taken together, all of these rules, regulations, and recommendations shall constitute, and guide annual reporting on the actions and outcomes of, the SDSU Sustainability Policy.

:::
