---
title: "University Policies: Committees - Regular Senate"
---

## Campus Planning Committee {#campus-planning-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Purpose:** The campus President—acting with the advice and assistance of an administrative officer that he or she appoints—and a Campus Planning Committee that the President also appoints, initiates all planning, services, and capital outlay matters: (a) site development; (b) the construction of new buildings and modification of existing buildings; (c) roads, landscaping, and parking; (d) the naming of rooms and buildings; (e) the location of monuments, works of art, and signage; and (e) related matters.

1. **Membership (13):** seven faculty, including one senator; one staff member; Director of Physical Facilities, Vice President for Business and Financial Affairs or designee; SDSU Research Foundation Director of Facilities; two students, to include the President of Associated Students.

1. **Functions**

    1. The Committee recommends actions to the President on the campus’ long-range plan, physical development, all capital outlay related matters and other areas of study delegated by the President. The Committee shall be informed in a timely fashion of proposed major changes in campus development so that it may review these changes and report to the Senate.

:::

## Environment and Safety, Committee {#environment-and-safety-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. The campus environment shall include (a) sidewalks, walkways, and pedestrian malls; (b) classrooms, laboratories, and work areas; and (c) restrooms, stairwells, elevators, hallways.

1. **Membership (13):** five faculty, including one senator, one of whom shall chair; two staff members, Vice President for Business and Financial Affairs or Director of Administrative Services, Director of Health Services or designee, Director of Physical Plant or designee, a member of local Unit 3 collective bargaining agency, and two students.

1. **Functions**

    1. The Committee shall study, advise, and report to the Senate and administration on the safety, health, and learning conditions in the campus environment.

    1. The Committee shall investigate problems such as health, hazardous materials and waste, safety, emergency preparedness, matters of excessive noise or traffic, and other matters that detrimentally affect the campus environment and learning conditions.

    1. The Committee shall recommend policy and procedures on the health, safety, and learning conditions of the campus environment.

:::

## Expanded Senate Executive Committee {#expanded-senate-executive-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (43):** members of the Senate Executive Committee, members of the Academic Deans Council, members of the Presidential Budget Advisory Committee (PBAC). The Senate Chair shall chair.

1. **Function:** The Committee shall meet to consider crises of profound or wide-ranging impact on the university and shall report to the Senate Executive Committee.

:::

## Faculty Honors and Awards Committee {#faculty-honors-and-awards-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (4+):** four faculty, with one student selected by Associated Students joining the Committee for the Excellence in Teaching Award, two former recipients and one alumnus joining the Committee for the Chief Diversity Officer, and a past recipient of the award, all with full voting privileges.

1. **Functions:** The Committee shall nominate faculty to the following honors and awards: (a) Emeritus status, (b) SDSU Senate Excellence in Teaching Award, (c) Alumni Award for Outstanding Faculty Contribution to the University (d) San Diego State University Diversity Excellence Award, and (e) such other honors and awards as the Senate shall designate.

:::

## General Education Curriculum Committee {#general-education-curriculum-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (12):** nine faculty, one from the College of Arts and Letters, Sciences, Professional Studies and Fine Arts, Fowler College of Business, Health and Human Services, Education, and Engineering, one from SDSU Imperial Valley, and one from the Library; Associate Vice President for Curriculum, Assessment and Accreditation or designee; and two undergraduate students.

1. **Functions**

    1. The Committee shall review and evaluate current and proposed courses for General Education.

    1. The Committee shall provide informational reports to the Undergraduate Curriculum Committee.

    1. The Committee shall review and evaluate, in consultation with content experts, courses that fulfill the American institutions, cultural diversity, and writing graduation requirements.

:::

## Global Campus Advisory Council {#global-campus-advisory-council .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (17, one of whom must be a Senate member):** Eight faculty (one of whom shall serve as Council chair); specifically, one from each of the academic colleges and SDSU Imperial Valley, Academic Affairs representative, Student Affairs and Campus Diversity representative, Curriculum, Assessment and Accreditation representative, College of Graduate Studies representative, Library representative, Academic Affairs - Technology representative, Undergraduate Curriculum Committee representative, Global Campus staff representative (not eligible to serve as Committee Chair).

    Non-voting: Dean of Global Campus

1. **Functions:** The Council shall (a) assist in the development of policies, procedures, and directions for present and future self-support education programs, including special sessions; (b) review and recommend proposed self-support programs with the Dean of Global Campus and make recommendations to the appropriate university entity; (c) communicate the strategic purpose for and functions of self-support programs to faculty and the general community; and (d) assist in analyzing issues and opportunities regarding self-support and recommend actions to promote student success.

:::

## Honorary Degrees, Advisory Committee on {#honorary-degrees-advisory-committee-on .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (10):** Provost, who shall chair; Vice President for Research and Innovation; Dean of the College of Graduate Studies; Vice President for University Relations and Development, Associate Vice President for Faculty Advancement and Student Success; Chair, Vice Chair, and immediate past Chair of the Senate; President of the San Diego State University Alumni Association, President of the Associated Students.

1. **Functions**

    1. The Committee shall review nominations for honorary degrees forwarded from the President’s office that have been received from the campus community and the Chancellor’s office. It shall evaluate the specific contribution made to San Diego State University according to the general criteria established by the Board of Trustees.

    1. The Committee may include others to participate in its review. By Trustees’ policy, Committee business shall be held in confidence.

    1. Having assembled documentation, the Committee shall recommend to the President persons deemed worthy of this honor, and it shall identify a supporting college or academic unit. It may also defer consideration until it has additional information for evaluation. Its recommendations shall also be sent to the Senate Executive Committee for its executive session consideration and its separate recommendation to the President before candidates are proposed to the Trustees.

:::

## Instructional and Information Technology Committee {#instructional-and-information-technology-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (16):** nine faculty, one from each college, SDSU Imperial Valley and the Library; one staff member; one student; Director of Instructional Technology Services or Designee; Chief Information Officer or designee; Academic Affairs Information Technology Coordinator or Designee; Information Technology Security Office Designee appointed by the Associate Vice President for Financial Operations; representative selected by and from the Information Technology Managers Group.

1. **Functions**

    1. The Committee shall advise the administration and the Senate on instructional and information technologies.

    1. The Committee shall evaluate the specific contribution made to San Diego State University according to the general criteria established by the CSU Board of Trustees.[^fn12]

    1. The Committee shall assist the Directors of Instructional Technology Services, the Library, the Academic Affairs Information Technology Coordinator, and other campus Instructional / Information Technology offices, with developing long-range master plans and shall review and make recommendations on the mission and services of ITS, the Library and Academic Affairs on instructional and information technologies.

    1. The Committee shall consider any matter referred by the Senate or by the administration of the University (and may consider, at its own discretion, other matters relating to instructional and information technologies at the campus and CSU system-wide levels.) The committee shall review and provide feedback on campus information technology initiatives as related to instruction, research and operational needs.

[^fn12]: Such criteria can be found: [https://calstate.policystat.com/policy/12871063/latest/ ](https://calstate.policystat.com/policy/12871063/latest/)

:::

## International Affairs Council {#international-affairs-council .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (24):** fourteen faculty; seven administrators or staff to include the Associate Vice President for International Affairs, who shall serve as Chair; one staff member, one undergraduate and one graduate student who have studied in a foreign country.

1. **Functions:** The Council shall (a) recommend policies and procedures to enhance the university’s international activities, (b) shall identify existing involvement in international activities and related resource commitments, (c) report on funding programs and opportunities for external support of international activities, (d) shall identify needs for improvement and development, and (e) report annually to the Senate and administration.

1. **Campus ACIP Member**: The Council shall appoint the campus ACIP member for a three-year term; this initial term may be renewed for one additional three-year term. The appointed ACIP campus member may be a contingent faculty member, a staff, or MPP. It is the option of the ACIP member to continue service on ACIP during leave or FERP, if not contrary to campus policy.

:::

## Liberal Studies Committee {#liberal-studies-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (1****3****):** five faculty who have taught in the Program for Liberal Studies, one each from English and speech, mathematics and natural sciences, fine arts and humanities, social and behavioral sciences, and Imperial Valley; Director of Liberal Studies who shall chair; Dean of the College of Education (or designee); Director of the School of Teacher Education; Chair of Dual Language and English Learner Education; Chair of Special Education; a Liberal Studies advisor; and two students majoring in Liberal Studies, one of whom shall be from Imperial Valley.

1. **Functions**

    1. The Committee shall develop policy, program, and curricular proposals for recommendation to the Senate and shall review other policy and curriculum proposals that affect the Program in Liberal Studies.

    1. The Committee shall consult with deans of colleges and with other Senate committees and shall consider their recommendations in preparing its proposals.

    1. The Committee shall have primary responsibility for recommending policy and program changes in Liberal Studies and may request the assistance of external specialists.

:::

## Library Committee {#library-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership (20): sixteen faculty, two from each college and one from SDSU Imperial Valley; Dean of the Library, one classified Library staff member appointed thereby, two students.

1. Functions

    1. The Committee shall advise the administration and the Senate on the allocation of book and periodical funds and on Library policies and programs, and it may consider other matters relating to Library policy and planning.

    1. The Committee shall regularly report to the Senate and shall forward to the Senate requests from the Dean of the Library.

:::

## University Research Council {#university-research-council .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (20+):** At least sixteen faculty, one to three from each college, the Library, and SDSU Imperial Valley; Chair of the Institutional Review Board (IRB); Associate Vice President (and CEO) for San Diego State University Research Foundation (SDSURF) (or designee); Dean of the College of Graduate Studies (or designee); Vice President for Research and Innovation (or designee), who shall chair.

1. **Functions:** The Council shall provide advice on research related policies, as well as promote, encourage, and publicize the research, scholarship and creative activities necessary to carry out the research mission of the University. The Council shall carry out these responsibilities after appropriate deliberations and consultations with other interested segments of the university. These responsibilities shall include but not be limited to the following:

    1. To advise on the needs for research and creative activities resources,

    1. To advise on the policies and procedures pertaining to the creation of campus research centers and institutes,

    1. In consultation with the Copyrights and Patents Subcommittee, review and advise on patents and copyrights policy,

    1. To advise and consult on the development of faculty and student research programs, as well as the allocation of dedicated funds for these programs,

    1. To encourage the development of interdisciplinary research facilities and activities,

    1. To promote university-wide research lectureships on topics of general interest,

    1. To advise on best practices and institutional programs for faculty in obtaining fellowships and grants from appropriate sources,

    1. To review and assure information on policies to protect the rights of parties concerned in experiments involving human subjects, policies for the care and use of animals in research, and policies for research using recombinant DNA and biohazardous material is made widely available to the University community,

    1. To advise on the process and communication of the procedures for the administration of research proposals and grants, and

    1. To report annually to the Senate and the administration.

1. **Subcommittees**

    1. **Copyrights and Patents subcommittee**

        1. **Membership (9+):** at least four faculty: three faculty members of the University Research Council, one of whom shall chair; at least one other faculty member, one member-at-large, Chief Executive Officer of the SDSU Research Foundation or designee, Vice President for Research and Innovation or designee, Vice President for Business and Financial Affairs or designee, Director of the San Diego State University Research Foundation Technology Transfer Office (nonvoting). Members shall be appointed to one-year renewable terms by the Vice President for Research and Innovation.

        1. **Functions:** The Committee shall report to the University Research Council on the effectiveness of the Copyrights, Trademarks, and Trade Secrets policy and of the Patents policy. The Committee shall

            1. submit for approval to the Vice President for Research and Innovation and to the University Research Council (URC) guidelines for the implementation of the provisions of the Copyrights, Trademarks, and Trade Secrets policy,

            1. ascertain the extent of institutional support involved in the completion of intellectual properties and shall recommend to the Vice President for Research and Innovation assignment of ownership rights and division of royalties, and

            1. advise the Vice President for Research and Innovation on other matters of intellectual property.

:::

## Student Learning Outcomes and Program Assessment Committee (SLOPAC) {#student-learning-outcomes-and-program-assessment-committee-slopac .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (16):** nine (9) faculty, including one from each college, the Library, and SDSU Imperial Valley; Associate Vice President for Curriculum, Assessment and Accreditation (or designee); Associate Vice President for Student Affairs and Campus Diversity (or designee); Instructional Technology Services representative (ex officio); Center for Teaching and Learning representative (ex officio); the Assessment and Accreditation Specialist, and two undergraduate students.

1. **Functions**

    1. The Committee shall provide oversight for the program assessment of Degree Learning Outcomes, and shall evaluate assessment plans and progress for all degrees and programs, including those programs accredited by external agencies.

    1. The Committee shall assess reports for each degree on a regular basis and provide feedback to the respective programs.

    1. The Committee shall provide the Senate, and, when relevant, the Graduate Council, with an annual report on the state of program assessment across the university, including programs accredited by external agencies.

:::

## Tenure-Track Planning Committee {#tenure-track-planning-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (****10+****):** Chair of the Senate, Chair of Academic Policy and Planning, Chair of University Resources and Planning, Chair of Faculty Affairs, Chair of Diversity, Equity and Inclusion. For colleges not otherwise represented among these Senate positions, membership will be augmented with a tenured or probationary faculty representative from each missing college planning committee to ensure that each college has at least one representative on the Tenure-Track Planning Committee. Colleges represented shall be: Arts and Letters, Education, Engineering, Fowler College of Business, Health and Human Services, Professional Studies and Fine Arts, Sciences, Library and Imperial Valley.

    1. The Chair of the Tenure-Track Planning Committee will determine any gaps and coordinate with the Chair of the Committee on Committees and Elections (CCE). CCE will oversee the filling of vacancies within the relevant colleges.

    1. Members are not required to be current Senators.

    1. The Provost shall serve in an advisory capacity to the committee.

1. **Function and Process:** The Committee shall annually consider the Senate’s Tenure-Track Planning Policy and programming initiatives, review requests and supporting documentation, and recommend to the Provost the allocation of new and vacated tenured and probationary faculty positions.

    1. The Provost should provide to the Tenure-Track Planning Committee in the Spring semester the number of hires and search proposals for searches that will launch in the following academic year. If final budgetary information is unavailable, the number of vacated faculty lines, new hires, and search proposals will be shared with the Tenure-Track Planning Committee as soon as possible.

    1. Each committee member will solicit feedback from their respective college planning committee about the process of shared governance utilized in each college’s planning process. That information will be shared with the entire Tenure-Track Planning Committee as part of the committee’s overall recommendations.

    1. The Tenure-Track Planning Committee will make its preliminary recommendations by the end of the spring semester based on the guidelines of the Tenure-Track Planning Policy, Building on Inclusive Excellence faculty hiring program policy, and any other relevant policies or directives.

1. **Recommendation**: After appropriate consultation with the Tenure-Track Planning Committee, the Provost shall determine and communicate to the university a decision concerning allocation of the distribution of new faculty lines across academic affairs. The Provost shall report back to the Tenure-Track Planning Committee and the full Senate the final set of positions allocated in each hiring cycle, and shall justify decisions that deviate from the recommendations of the TTPC.

1. **Cluster Hires**: The Tenure-Track Planning Committee shall be involved in the establishment of University-wide cluster hires as described in section 6 of the University Policies: Faculty, Tenure-Track Planning.

:::
