---
title: "University Policies: Committees - Senate Affiliated"
---

## Bookstore Advisory Committee {#bookstore-advisory-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (14):** eight faculty, one from each college and SDSU Imperial Valley; one Aztec Shops Board representative, the Aztec Shops General Manager, the Book Department Manager, the Senate representative to Aztec Shops; one staff member; one student.

1. **Functions**

    1. The Committee shall improve the relationship between the faculty and Aztec Shops Bookstore by reviewing Bookstore policies, textbook requisitions, sales data, and custom course packets.

    1. The Committee shall be especially sensitive to specific problems and to written complaints.

    1. The Committee may recommend to the Aztec Shops Board changes in policy or procedures and shall report to the Aztec Shops Board and the Senate at least once a year, no later than the April meeting.

:::

## Fee Advisory Committee, Campus {#fee-advisory-committee-campus .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (17):** Senate Chair or designee; two Senate appointed faculty members; Provost or designee; Vice President for Student Affairs and Campus Diversity or designee: Vice President for Business and Financial Affairs or designee; Vice President for Research and Innovation or designee; one Senate appointed staff member; seven students from the San Diego campus, appointed by Associated Students, including the Associated Students President (San Diego campus) or designee; two students from SDSU Imperial Valley, appointed by Associated Students. Student members shall constitute a majority.

1. **Functions**

    1. The Committee shall ensure that campus fees are established or adjusted in accordance with Executive Order 1102 (2015) and Trustees’ policy.

    1. The Committee shall advise the President on the establishment and adjustment of Category II and III fees.

    1. The Committee shall advise the President on the reasonableness of Category II and III fee proposals, whether the deletion, adjustment, or reclassification of current fees or the creation of new fees.

:::

## Freedom of Expression, Committee on {#freedom-of-expression-committee-on .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (15-17):** Provost or designee, Vice President for Student Affairs and Campus Diversity or designee, Vice President for Business and Financial Affairs or designee, Dean of SDSU Imperial Valley or designee, Associated Students President or designee, five faculty, at least one of whom must be a Senator, four students, and one staff member. One of the faculty members of the committee shall function as chair and serve a single, non-renewable three-year term. If not appointed to a voting position, the coordinator for noncommercial speech and expressive activities and the coordinator for commercial activities shall serve as ex officio, non-voting, members.

1. **Functions:** The function of the Committee on Freedom of Expression is to provide advice regarding the regulation and management of campus activities that fall under the university’s freedom of expression policy and to receive, evaluate, and advise the President on complaints regarding freedom of expression activities.

    1. The Committee shall work with campus administrators and organizations to ensure that the Freedom of Expression Policy is being followed, both in campus regulations and in management practices. The Committee shall, on a biannual basis, review existing campus and auxiliary organization policies that might affect freedom of expression and make suggestions, as needed, for revision of those policies to reflect the intent of the SDSU policy on freedom of expression.

    1. The Committee shall review campus activities covered under the SDSU Freedom of Expression Policy and advise the President whether those activities were managed in a manner consistent with the principles expressed in the policy.

    1. The Committee shall serve as a forum for complaints regarding activities covered under the SDSU Freedom of Expression Policy and shall advise the President as it deems to be appropriate.

    1. The Committee shall serve as a forum for complaints regarding activities covered under the SDSU Freedom of Expression Policy and the Academic Freedom Policy and shall advise the President as it deems to be appropriate.

    1. The Committee may promote an understanding of free expression and academic freedom through forums, discussions, workshops, and other educational activities.

:::

## Intercollegiate Athletics Council {#intercollegiate-athletics-council .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Jurisdiction:** The Intercollegiate Athletics Council (IAC) shall be an all-university advisory body to the President on varsity intercollegiate athletics. The IAC shall be responsible for recommendations to the President about the entire intercollegiate athletic program as offered by the San Diego State University Department of Intercollegiate Athletics. The IAC shall represent the segments of the university community interested in athletics at San Diego State University. The Chair of the IAC shall make periodic reports to the Senate.

1. **Duration:** The IAC shall function with periodic review by the President.

1. **Membership (21 voting):**

    1. 21 Voting Members

        1. Five faculty appointed by the Senate

        1. Three faculty appointed by the President (which may include up to one college dean with faculty retreat rights)

        1. Faculty Athletics Representative

        1. Vice President for Business and Financial Affairs

        1. Vice President for Student Affairs and Campus Diversity or designee

        1. Vice President for University Relations and Development or designee

        1. Diversity Officer for Student Affairs and Campus Diversity, who shall sit on the Gender, Diversity, Equity and Well-Being Committee

        1. Two students, one appointed by the President of Associated Students and one appointed by the Student-Athlete Advisory Council

        1. Member of the Aztec Club

        1. One alumnus appointed by the Director of the Alumni Association

        1. One community member appointed by the President

        1. One staff member nominated by the Staff Affairs Committee and confirmed by the Senate

        1. One faculty emeritus appointed by the SDSU Retirement Association

        1. One staff emeritus appointed by the SDSU Retirement Association

    1. One of the five Senate-appointed faculty members will be appointed by the Senate to serve as the University representative to the Coalition on Intercollegiate Athletics (COIA).

    1. Chair or designee of the Committee on University Resources and Planning to sit on the IAC Budget Subcommittee.

    1. The President or the Chair of the IAC may invite others with special expertise to sit as non-voting ex officio members.

    1. The Chair of the IAC shall be named by the President from the faculty members selected to the IAC.

    1. Term Limits

        1. Faculty and staff members (including emeritus) appointed by the President, Senate, Staff Affairs Committee, and SDSU Retirement Association shall serve three- year terms (excluding the Faculty Athletics Representative and IAC Chairperson). These members shall serve no more than two consecutive terms. Service for a partial term shall not be included in this calculation. So far as feasible, member seats shall be arranged to serve staggered terms.

        1. Student members shall serve one-year terms.

        1. Alumni and community members shall serve three-year terms. These members shall serve no more than two consecutive terms. Service for a partial term shall not be included in this calculation.

    1. Membership as defined in section 3.0 for conducting committee business shall not include substitutes, absentees, or proxy representation.

    1. In the event of a vacancy, the jurisdiction represented by the position shall be responsible for filling that position.

    1. For conducting council business and votes, a quorum will be defined as a simple majority of voting members (not including vacant seats).

1. **Duties and Responsibilities**

    1. The IAC shall be the primary advisory body to the President on varsity intercollegiate athletics. Subject to approval by the President, it shall develop policies governing intercollegiate athletics that shall guide the administration of the intercollegiate athletics program by the Director of Intercollegiate Athletics. The IAC shall have no administrative or executive capacity.

    1. More specifically, the IAC shall consider and recommend to the President policy on such matters as (a) income and expenditures budgets, (b) the schedules for seasonal and postseason play in relation to the effect upon student-athlete welfare, (c) grants and other financial aid to student- athletes, (d) eligibility of student-athletes, (e) student-athlete grievance procedures on sportsmanship and other non-scholarship policies, (f) awards to student-athletes, (g) ticket distribution policies, and (h) public and campus relations of the athletics program. Issues of student-athlete welfare shall be within the purview of the IAC.

:::

## President’s Budget Advisory Committee (PBAC) {#president-s-budget-advisory-committee-pbac .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Membership:

    1. Voting Members (15)

        1. Administration-appointed members: Vice President for Business and Financial Affairs (co-chair), Senior Vice President for Academic Affairs (Provost; co-chair), Vice President of Student Affairs and Campus Diversity (Chief Diversity Officer), Vice President for Research and Information, Vice President for University Relations and Development, Vice President for Information Technology (Chief Information Officers), and the President’s Chief of Staff.

        1. Student-appointed members: President of Associated Students, and one additional student representative identified by Associated Students.

        1. Senate-appointed members: Senate Chair, or designee; Chair of the Committee for University Resources and Planning, three elected faculty members, and one elected non-MPP staff member.

            1. There shall be no more than one faculty representative from any of the following: College of Arts and Letters, College of Engineering, College of Professional Studies and Fine Arts, Fowler College of Business, College of Education, College of Health and Human Services, College of Sciences, SDSU Imperial Valley, Faculty Advancement and Student Success, and the Library.

    1. Non-Voting Members (10)

        1. Budget Area Representatives: Chief Financial Officer of the Campanile Foundation, AVP for Academic Affairs Financial Operations, AVP for Student Affairs and Campus Diversity Financial Operations, AVP for Business and Financial Affairs Financial Operations, Director of Information Technology Finance and Administration.

        1. Staff Attendees: Chief Financial Officer SDSU Research Foundation, Senior AVP for Administration, Director of Budget and Finance, Special Assistant to the Vice President of Business and Financial Affairs.

        1. Senate Attendees: Senate Treasurer.

    1. The committee co-chairs shall share the committee membership roster annually in September, or as changes occur, with Senate leaders. The Senate Secretary shall include the full membership of PBAC in the Senate’s committee roster and make this information available to the university community.

1. Procedure for Electing Senate Representatives to PBAC[^fn13]

    1. Nomination of Senate-appointed Members

        1. The Committee on Committees and Elections Chair shall announce vacancies and make a call for nominations. The Staff Affairs Committee Chair shall announce vacancies and make a call for nominations to all non-MPP staff.

        1. Calls for nominations shall go out no later than the second week of February for terms that begin the following academic year.

        1. The call for nominations shall include the following statement: “For these positions, it is desirable for nominees to have experience with and understanding of complex budgets. Elected representatives are expected to make decisions based on the overall academic mission of the university, and not to advocate for their respective academic or bargaining units.”

        1. Nominations shall be made by a faculty member or non-MPP staff member with the approval of the nominee. No self-nominations are allowed.

        1. Nominees shall write a short statement, no longer than 250 words, addressing their qualifications for the position. The statement shall be distributed to the Senate in advance of the election.

    1. Election of Senate-appointed Members

        1. Faculty representatives shall be elected by the full voting membership of the Senate in an election managed by the Committee on Committees and Elections, per the procedures outlined in the Bylaws, no later than the end of March for terms that begin the following academic year.

        1. The staff representative shall be elected by the Staff Affairs Committee no later than the end of March for terms that begin the following academic year.

        1. Elections may be completed during a Senate session, or via a secure electronic balloting process ahead of a Senate session as long as the Chair of the Committee for Committees and Election makes a formal announcement regarding the election results during the Senate meeting.

    1. Term for Senate-appointed Members

        1. The election shall be for a three-year term.

        1. Elected representatives who go on leave for any part of the academic year forfeit the remainder of their term, creating a vacancy that shall be filled by regular procedure outlined in 2.1. and 2.2.

        1. Upon the completion of their term, representatives may run for re-election, but shall serve no more than nine consecutive years.

1. Function: The President’s Budget Advisory Committee (PBAC) reviews the university budget periodically and makes recommendations to the President regarding budget proposals.

[^fn13]: Exceptional Procedure for Academic Year 2019-2020. All 2019-2020 interim appointments shall end at the conclusion of the academic year.The Chairs of the Senate and Staff Affairs Committee shall send out a call for nominations for all four vacancies no later than the second week of March 2020, and the election shall be held during the Senate/Staff Affairs Committee's April 2020 meeting. In order to stagger terms of the elected representatives, the length of terms beginning in the Fall of 2020 shall be determined by lot after the election. One of the elected representatives shall serve a one-year term, one shall serve a two-year term, and two shall serve three-year terms. Subsequently all terms shall be three years.

:::

## Press Editorial Board, San Diego State University {#press-editorial-board-san-diego-state-university .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (19):** six faculty, Director of the SDSU Press, one academic dean, Dean of the College of Graduate Studies, ten external members.

1. **Function:** The Editorial Board shall represent the interests of the university community for scholarly publication.

:::

## Student Grievance Committee {#student-grievance-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (10 + 6 alternates):** five students and three alternates; three faculty, at least one of whom is a tenured or probationary faculty member, and two alternates; one full-time staff representative and one alternate; Ombudsman (nonvoting).

    1. A Vice Chair shall be selected from among the voting student members appointed by the Associated Students. The role of the Vice Chair is to chair Student Grievance Committee meetings when the Chair cannot do so. The Vice Chair shall not vote when serving as the chair of a Student Grievance Committee meeting.

1. **Functions:** The Committee shall hear and seek redress of student grievances concerning members of the faculty, administration, or staff, and to recommend disciplinary actions. (See Codes: Student Grievance Procedure.)

1. The chair of the Student Grievance Committee shall present an annual written report to the President and the Senate Executive Committee of the number of grade appeal cases heard and the disposition of those cases.

:::

## Student Media Advisory Committee {#student-media-advisory-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (18):** Associated Students President or designee, Associated Students Vice President for Finance or designee, Associated Students Executive Director or designee (nonvoting), Daily Aztec Editor (nonvoting), Daily Aztec General Manager (nonvoting), KCR Radio General Manager (nonvoting), University President designee, Student Affairs and Campus Diversity designee, University Relations and Development designee, Business and Financial Affairs designee, three faculty members, one from the faculty in Journalism; one staff member; four students.

1. **Functions:** The Student Media Advisory Committee shall be an advisory body to the University President on student-run media.

:::

## Teacher Preparation Advisory Council {#teacher-preparation-advisory-council .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (16):** eight faculty, one from each college and SDSU Imperial Valley; Dean of College of Education, who shall chair, Provost, Dean of the College of Graduate Studies, Associate Vice President for Faculty Advancement and Student Success; three representatives from the San Diego area school districts;

1. **Functions:** The Council shall advise the Dean of Education on various programs for the preparation of teachers and other school personnel.

:::

## Transportation Advisory Committee {#transportation-advisory-committee .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Membership (11)**:

    1. Voting members (6): two faculty members; two students; and two staff members.

    1. Non-Voting members (5): Director of Parking & Transportation; Transportation Analyst; Director of Energy and Sustainability, or designee; a representative from the Chancellor's Office; and a representative from a San Diego transportation agency.

    1. The Director of Parking & Transportation shall chair the committee or designate a chair.

    1. Terms:

        1. Appointed faculty or staff members shall serve for a period of two (2) years.

        1. Student members shall be appointed annually.

    1. Eligibility:

        1. Senate-appointed members shall be appointed by the Senate in a manner outlined in the University Senate Policy File Bylaws: faculty members shall be appointed by the Committee on Committees and Elections; student members shall be appointed by Associated Students; and staff members shall be appointed by the Staff Affairs Committee. The Transportation Advisory Committee Chair shall consult with the Chair of the Committee on Committees and Elections in order to fill vacant senate-appointed seats on the committee.

        1. University Senate, Staff Affairs, Associated Students, and others putting forward nominees for appointed membership on this committee shall consider the backgrounds of potential nominees to ensure that members with varying abilities and from diverse communities are represented.

        1. Members should be representative of constituencies which use transit, micromobility, carpool, vanpool, and/or active transportation (e.g. bicycle/walking) as forms of commuting.

    1. The committee may invite guests as needed to participate in the activities of the committee, and who may contribute to discussions, provide information about or background on an issue, etc. Guest participants are not eligible to vote.

    1. Any committee vote of the regular voting member that results in a tie shall require that the Energy & Sustainability Director cast a vote to break the tie. If the Director of Energy & Sustainability is not present, the committee chair shall cast a vote to break the tie.

1. Function:

    1. The purpose of the Transportation Advisory Committee is to assist San Diego State University in identifying and prioritizing recommended opportunities to improve pedestrian, bicycling, transit and other non-single occupancy vehicle commute modes.

    1. The committee’s goal is to provide members of the campus community equitable access to mobility options and to help overcome barriers using sustainable transportation modes.

    1. The committee shall remain independent from existing campus parking committees.

    1. The committee shall report to the Vice President of Business & Financial Affairs.

    1. Regular meetings of the Transportation Advisory Committee shall occur at least once per semester, but may be called as needed by the chair.

:::
