---
title: "University Policies: Organization"
---

## Assistant Deans {#assistant-deans .unnumbered}

::: {.policy-numbering .policy-start-1}

1. An Assistant Dean shall be assigned to each academic college and to the Office of Faculty Advancement and Student Success, the College of Graduate Studies, and the Office of the Dean of Students. These positions (with the exception of those located in FASS, Graduate Studies, the Imperial Valley Campus, and the Office of the Dean of Students) are jointly supervised by the Dean of each respective College and the Division of Student Affairs and Campus Diversity. Assistant Deans in the academic colleges work in collaboration with the Dean of the College and with the Vice President for Student Affairs or designee to deliver and integrate student services for undergraduate students in the academic setting. Primary responsibilities shall include promoting a safe, equitable and inclusive learning environment, collaborating across campus to advance student success and retention work, and to aid in student persistence toward graduation. Additional responsibilities are assigned by the supervisor and may include (a) identifying and eliminating barriers to promote timely graduation processes; (b) overseeing the coordination of academic advising and student services; (c) leading outreach and retention initiatives; (d) leading new student and family orientation; (e) collaborating on co-curricular student involvement and engagement; and (f) making judgments on complex undergraduate student issues or petitions for reenrollment, reinstatement, withdrawals, and late schedule adjustments, many of which include deliberation with students. Graduate student issues are referred to the Assistant Dean in the College of Graduate Studies for action.

:::

## Auxiliaries, Review of {#auxiliaries-review-of .unnumbered}

::: {.policy-numbering .policy-start-1}

1. SDSU has four auxiliaries: Associated Students, Aztec Shops, The Campanile Foundation, and the SDSU Research Foundation. Normally, the President shall call for a review of each auxiliary on a five-year rotating basis. Taking into consideration both Title 5 Education Code policies and procedures for California State University Auxiliary Organizations and the San Diego State University Scope of Authority for Auxiliary Organizations, the review shall a) evaluate how well the auxiliary supports the mission and goals of the university, (b) examine how it manages its resources and its fiscal responsibilities, (c) assess the direction and appropriateness of growth, (d) elucidate and recommend change or need for further support, and (e) examine the overall functioning and day-to-day management of the organization.

1. **Review Panel**

    1. The review panel for the San Diego State University Research Foundation shall comprise seven members: one dean chosen by the Provost, one vice president of a major research institution chosen by the President, one chief operating officer of a nonacademic entity chosen by the Research Foundation’s Chief Executive Officer, two faculty members chosen by the President from four nominated by the Senate, one faculty member chosen by the President, one student chosen by Associated Students

    1. The review panel for Associated Students shall comprise nine members: the Vice President for Student Affairs and Campus Diversity, one vice president for student affairs from a similar academic institution chosen by the President, one student government officer from a similar academic institution chosen by Associated Students, two faculty members chosen by the President from four nominated by the Senate, one faculty member chosen by the President, one staff member chosen by the Staff Affairs Committee, two students not serving on the Associated Student Council but chosen by Associated Students.

    1. The review panel for Aztec Shops Ltd. shall comprise eight members: one dean chosen by the Provost, one vice president of business affairs of a similar academic institution chosen by the Vice President for Business and Financial Affairs, one chief operating officer of a similar entity at another academic institution chosen by Aztec Shops Manager, two faculty members selected by the President from four nominated by the Senate, one faculty member chosen by the President, one staff member chosen by the Staff Affairs Committee, one student chosen by Associated Students.

    1. The review panel for the Campanile Foundation shall comprise seven members: one dean chosen by the Provost, one vice president of development chosen by the President, one chief operating officer of a nonacademic entity chosen by the Vice President for University Relations and Development, two faculty members chosen by the President from four nominated by the Senate, one faculty member chosen by the President, one student chosen by Associated Students.

1. **Procedures**

    1. The President, in consultation with the Cabinet and the Senate Executive Committee, shall prepare a charge to the auxiliary outlining questions to be addressed in a self-study. In the course of the review, the panel may request more specific information from the auxiliary to answer questions related to the charge.

    1. The President shall appoint a chair who shall convene the organizational meeting of the panel. The President or designee shall appear at that meeting to review the charge.

    1. After the panel has been constituted, the auxiliary shall be notified and requested to send copies of the self-study to each panel reviewer. After review of the self-study, the panel shall meet to develop the review process which may include, but not be limited to: interviews with constituency groups or individuals who are knowledgeable about or affected by the auxiliary, interviews with individuals or groups employed by the auxiliary, and/or arrangements to visit the auxiliary at a mutually agreeable time or to request documents or information that will facilitate the review.

    1. Agendas and time lines shall be established by the chair of the review panel in consultation with appropriate administrators.

1. **Report and Follow-up**

    1. After the review, the panel shall submit a report or reports with recommendations for further action or review.

    1. The report shall first be presented to the auxiliary which may submit comments and responses to the panel, which shall include them in the full report presented to the President and the Senate.

    1. The President or the Senate may ask for further review should it be deemed necessary.

    1. The auxiliary will be requested to provide a follow-up report after one year to the Senate on its progress including changes developed as a result of the review or other campus policy changes.

:::

## Chairs of Departments or Programs and Directors of Schools {#chairs-of-departments-or-programs-and-directors-of-schools .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Department or program chairs and school directors shall serve at the pleasure of the President. They shall perform duties and carry out responsibilities assigned by the President. They shall be both academic administrators and faculty members. Most chairs or directors shall continue their faculty activities as time allows and eventually shall return to a full-time assignment of teaching, research, and service.

1. Collective bargaining unit chairs and directors shall normally be selected from tenured or probationary faculty employees recommended by the department, school, or program. A department, school, program may recommend that a person be concurrently appointed to its faculty and to the position of chair or director.

1. **Appointment**

    1. Not later than March of each year, a department, program, or school whose position of chair or director will be vacated at the end of the academic year shall recommend the name of one or more nominees to the dean of its college. When a vacancy occurs at another time, the appointment shall be implemented as rapidly as possible.

    1. The dean either shall inform the department, program, or school of his or her intention to recommend to the President one nominee or shall promptly return the name(s) to the unit stating why its recommendation is unacceptable. If the unit’s recommendation is rejected, it may either submit another recommendation or request reconsideration of the original recommendation. Ordinarily, the dean and the unit should reach agreement. However, if no agreement is reached, the dean, after deliberation and consultation with the personnel committee of the college, shall recommend to the President the appointment of a chair or director.

    1. In the event of a vacancy, the President may appoint an interim chair or director. The appointment shall last until the regular appointment of a chair or director.

1. Departments, programs, or schools shall develop procedures and schedules for periodic review of the chair or director. The review shall be completed by March of the third year and every two years thereafter and shall consist of at least a referendum by the tenured and probationary faculty. After the referendum or review, the unit shall recommend to the dean of the college that the appointment be continued or terminated.

1. During a term of office, a department, program, or school may request that the dean remove the chair or director, or the dean may determine to remove the chair or director. In either case, after deliberation and consultation with the unit and the personnel committee of the college, the dean may recommend to the President that the chair or director be removed and an interim chair or director be appointed and may request from the unit a nomination for a regularly appointed chair or director.

:::

## College Policy and Planning Committees {#college-policy-and-planning-committees .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Each college shall have an academic policy and planning committee that shall deliberate on and recommend academic policy and planning for the college. The committee shall conduct both long-range and short-range planning. Normally, the dean shall consult with this committee in advance of deadlines for decisions and shall make decisions only after this consultation. The committee shall have access to all budget and resource allocation information and to other information available to and from deans, departments or schools, and programs relevant to policy and planning.

1. This committee shall be charged with:

    a. Keeping policy and planning under continuous review and formulating and recommending the priorities among departments, schools, and programs in order to arrive at quality programs,

    a. Facilitating communication between university policy sources (e.g., Senate, administration, Chancellor’s Office) and faculty members of the college at large,

    a. Helping to coordinate departments’, schools’, and programs’ responses to policy actions taken by the Senate, the administration, the Chancellor’s Office,

    a. Cooperating with the Committee on Academic Policy and Planning, and

    a. By February 1 of each year, reporting its activities and problems to the Committee on Academic Policy and Planning.

1. The committee shall comprise elected members (the number determined by each college) and the dean or designee as an ex officio member. The elected members shall serve staggered three-year terms and shall be eligible for reelection. The members shall elect the chair of the committee.

:::

## Colleges {#colleges .unnumbered}

::: {.policy-numbering .policy-start-1}

1. A college within the university shall comprise faculty concerned with instruction and research in the liberal or applied arts and sciences that contribute to the total intellectual development of the students of the university. Through its colleges, the university shall offer baccalaureate and graduate degrees.

1. Departments, schools, and programs within the college shall be the fundamental instructional units and shall develop and offer majors in the various disciplines. Usually, a college shall be larger than an autonomous school, and the administrative structure may be more complex. Specific guidelines for efficient size and the number of degrees granted shall not be identified.

1. If the conditions are not met as outlined under 1.0 and 2.0, the term "college" may only be used as an honorary designation with the approval of the University Senate.

:::

## Departments and Schools {#departments-and-schools .unnumbered}

::: {.policy-numbering .policy-start-1}

1. The department or school shall initiate, operate, and administer academic programs (e.g., instruction, research, community services, and creative activities).

1. The department or school shall be a fundamental instructional unit within a college that shall deal with a discrete and specific body of knowledge or techniques. Specific guidelines for efficient size and the number of degrees granted shall not be identified.

    1. For undergraduate programs, the department or school shall contribute to the university’s baccalaureate curriculum by providing instruction in subject matter fields integrated into the total discipline leading to the baccalaureate degree.

    1. For master’s and doctoral programs, the department or school, as a faculty, shall be more autonomous and shall direct its own degree requirements and recommend its own candidates.

1. The department or school shall initiate recommendations concerning appointments, reappointments, tenure, and promotions. Except in the most extraordinary circumstances, department and school recommendations concerning appointments, reappointments, and tenure shall be accepted by the dean of the college; however, the faculty of any college may adopt a procedure requiring that final recommendations to the dean concerning any personnel matter be prepared by a designated college committee.

1. The department or school shall be administered by a chair or director who shall report to the dean of the college and who shall lead the unit’s faculty in developing curricula and in keeping current in the unit’s discipline(s). The chair or director shall institute programs for enlistment and motivation of students and shall conduct a strong advising program. The chair or director should not be immersed in fiscal or budgetary details except in an informal and advisory capacity with the dean.

:::

## Administrative Units: Establishment and Restructuring Establishment of Departments or Schools {#administrative-units-establishment-and-restructuring-establishment-of-departments-or-schools .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Proposals for the establishment of a department or school may be initiated by departments or schools, faculty members, or administrative officers of the university. The proposal shall address employment options, informed by the current Collective Bargaining Agreements, for the affected faculty and for permanent staff.

1. The proponent(s) shall distribute a written proposal to the Academic Planning Committee of the affected college, which shall invite faculty representatives from any affected academic units to serve on that Committee on an ad-hoc basis. The Committee shall transmit its recommendation to the dean(s). If the recommendation is negative, the proponents of the proposal shall have ten working days to offer additional arguments.

1. The proposal shall be reviewed by the dean(s) of the college(s) concerned.

    1. If the dean(s) judges that the proposal has no merit, this recommendation together with the original proposal shall be forwarded to the Provost. The Provost shall publicly announce to the faculty of the affected units the recommendation of the dean(s) not to pursue further action. The faculty shall have ten working days to offer additional arguments.

    1. If the dean(s) judges that the proposal has merit, the dean(s) shall then form an ad hoc committee that will give the matter full and serious consideration. The committee shall comprise at least five members, at least two of whom should be department chairs or school directors, one tenured faculty member drawn from an uninvolved college, and representatives from at least two affected academic units elected by tenured and probationary faculty from the affected academic units. The committee shall then report its recommendations to the dean(s) and the executive committee(s) (or equivalent) of the college(s) involved.

1. A final proposal shall be made available to all tenured and probationary faculty from affected academic units. These faculty members shall vote on the proposal. The results of the vote shall be transmitted to the dean(s) and all subsequent reviewing bodies.

1. The dean(s)’s recommendation shall be transmitted to the Provost, who shall convey the recommendation with comments to the Committees on Academic Policy and Planning and on University Resources and Planning. A complete report including the proposal and a record of the responses of the subsequent reviewing bodies will be sent forward to these committees.

1. The Senate Committees on Academic Policy and Planning and on University Resources and Planning shall present their recommendations to the Senate, which shall recommend action to the President.

1. **Criteria for Establishing Schools within an Administrative Unit (i.e., Protoschools)**

    1. The academic unit (a) shall offer a degree program subject to accreditation by a recognized external accrediting group or (b) shall contain within itself subunits that offer various and distinct professional degree programs and faculty members who do not necessarily have common professional qualifications.

1. **Criteria for Establishing Autonomous Schools**

    1. The academic unit shall meet the criteria of section 7.1 for the establishment of a school within an existing administrative unit.

    1. If a recognized external accrediting body exists, the academic unit shall meet the criteria for accreditation except autonomy.

    1. The academic unit shall demonstrate experience in the operation of a program as a major, department, or school within a college.

    1. The academic unit shall demonstrate both present capacity and future potential for a graduate program.

:::

## Colleges: Establishment {#colleges-establishment .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Proposals for the establishment of a college may be initiated by departments or schools, faculty members, or administrative officers of the university. The proposal shall address employment options, informed by the current Collective Bargaining Agreements, for the affected faculty and for permanent staff.

1. The proposal shall be reviewed by a committee of elected representatives from groups in relevant or related fields of study. If the committee affirms that the proposal has merit it shall be sent to the Provost.

    1. If the Provost judges that the proposal has merit, the Provost shall then form an ad hoc committee that will give the matter full and serious consideration. The committee shall comprise at least seven members: any dean(s) from the affected units, at least two department chairs or school directors, one tenured faculty member drawn from an uninvolved college, and at least three faculty from any affected academic units elected by tenured and probationary faculty from the affected academic units. The committee shall then report its recommendations to the dean(s) (if applicable) and the executive committee(s) (or equivalent) of the college(s) involved and to the Provost.

1. A final proposal shall be made available to all tenured and probationary faculty from affected academic units. These faculty members shall vote on the proposal. The results of the vote shall be transmitted to the dean(s) (if applicable) and all subsequent reviewing bodies.

1. The Provost shall convey the recommendation with comments to the Committees on Academic Policy and Planning and on University Resources and Planning. A complete report including the proposal and a record of the responses of the subsequent reviewing bodies will be sent forward to these committees.

1. The Senate Committees on Academic Policy and Planning and on University Resources and Planning shall present their recommendations to the Senate, which shall recommend action to the President.

:::

## Departments and Schools: Merger, Restructuring, Transfer, and Abolition {#departments-and-schools-merger-restructuring-transfer-and-abolition .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Proposals for merger, transfer, restructuring (including splitting) or abolition of existing departments or schools may be initiated by departments or schools, faculty members, or administrative officers of the university. The proponent(s) shall distribute a written proposal to the appropriate departments, schools and deans. The proposal shall address employment options, informed by the current Collective Bargaining Agreements, for the affected faculty and for permanent staff.

1. The proponent(s) shall distribute a written proposal to the Academic Planning Committee of the affected college(s), which shall invite faculty representatives from any affected academic units to serve on that Committee on an ad-hoc basis. The Committee shall transmit its recommendation to the dean(s). If the recommendation is negative, the proponents of the proposal shall have ten working days to offer additional arguments.

1. The proposal shall be reviewed by the dean(s) of the college(s) concerned.

    1. If the dean(s) judges that the proposal has no merit, this recommendation together with the original proposal shall be forwarded to the Provost. The Provost shall publicly announce to the faculty of the affected units the recommendation of the deans not to pursue further action. The faculty shall have ten working days to offer additional arguments.

    1. If the dean(s) judges that the proposal has merit, the dean(s) shall then form an ad hoc committee that will give the matter full and serious consideration. The committee shall comprise at least five members, at least two of whom should be department chairs or school directors, one tenured faculty member drawn from an uninvolved college, and representatives from at least two affected academic units elected by tenured and probationary faculty from the affected academic units. The committee shall then report its recommendations to the dean(s) and the executive committee(s) (or equivalent) of the college(s) involved.

1. A final proposal shall be made available to all tenured and probationary faculty from affected academic units. These faculty members shall vote on the proposal. The results of the vote shall be transmitted to the dean(s) and all subsequent reviewing bodies.

1. The dean(s) shall subsequently transmit final recommendations to the Provost, who shall convey the recommendation with comments to the Committees on Academic Policy and Planning and on University Resources and Planning. A complete report including the proposal and a record of the responses of the subsequent reviewing bodies will be sent forward to these committees.

1. The Senate Committees on Academic Policy and Planning and on University Resources and Planning shall present their recommendations to the Senate, which shall recommend action to the President.

:::

## Colleges: Merger and Abolition {#colleges-merger-and-abolition .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Proposals for the merger or abolition of existing colleges may be initiated by faculty members, or administrative officers of the university. The proponent(s) shall distribute a written proposal to the appropriate dean(s). The proposal shall address employment options, informed by the current Collective Bargaining Agreements, for the affected faculty and for permanent staff.

1. The proponent(s) shall distribute a written proposal to the Academic Planning Committee(s) of the affected college(s), which shall invite faculty representatives from any affected academic units to serve on the Committee(s) on an ad-hoc basis. The Committee(s) shall transmit its/ their recommendation(s) to the Dean(s) of the affected College(s). If the recommendation(s) is/ are negative, the proponents of the proposal shall have ten working days to offer additional arguments.

1. The proposal shall be reviewed by the dean(s) of the college(s) concerned.

    1. If the dean(s) judge(s) that the proposal has no merit, this recommendation together with the original proposal shall be forwarded to the Provost. The Provost shall publicly announce to the faculty of the affected units the recommendation of the dean(s) not to pursue further action. The faculty shall have ten working days to offer additional arguments.

    1. If the dean(s) judge(s) that the proposal has merit, the dean(s) shall then make recommendations to the Provost.

1. The Provost shall form an ad hoc committee that will give the matter full and serious consideration. The committee shall comprise at least seven members, dean(s) of the affected units, at least two department chairs or school directors, one tenured faculty member drawn from an uninvolved college, and at least three faculty from affected academic units elected by tenured and probationary faculty from the affected academic units. The committee shall then report its recommendations to the dean(s) and the executive committee(s) (or equivalent) of the college(s) involved and to the Provost.

1. A final proposal shall be made available to all tenured and probationary faculty from affected academic units. These faculty members shall vote on the proposal. The results of the vote shall be transmitted to the dean(s) and all subsequent reviewing bodies.

1. The Provost shall evaluate the report and submit a recommendation with comments to the Committees on Academic Policy and Planning and on University Resources and Planning. A complete report including the proposal and a record of the responses of the subsequent reviewing bodies will be sent forward to these committees.

1. The Senate Committees on Academic Policy and Planning and on University Resources and Planning shall present their recommendations to the Senate, which shall recommend action to the President.

:::

## SDSU Imperial Valley {#sdsu-imperial-valley .unnumbered}

::: {.policy-numbering .policy-start-1}

1. SDSU Imperial Valley, Calexico shall provide in a remote community setting genuine university experiences and degree curricula for those students at San Diego State University who cannot readily attend the San Diego campus.

1. SDSU Imperial Valley and relevant San Diego campus departments, schools, and colleges shall be responsive to the distinctive community, regional, and programmatic needs served by SDSU Imperial Valley.

1. SDSU Imperial Valley shall be integral to San Diego State University and shall for practical purposes function as a college.

    1. SDSU Imperial Valley faculty, staff, and administrators shall be employees of San Diego State University assigned to SDSU Imperial Valley.

    1. The chief administrative officer shall be the Dean. In consultation with the faculty, the Dean shall determine the needs and shall recommend to the President appointments of administrative, staff, and faculty personnel. The Dean shall request that relevant San Diego campus departments or schools initiate SDSU Imperial Valley faculty appointments and other faculty personnel actions in accordance with the resources allocated to SDSU Imperial Valley. For each faculty search, the SDSU Imperial Valley Dean shall request that the appropriate San Diego campus department or school elect a search committee to include at least one member from SDSU Imperial Valley.

    1. The SDSU Imperial Valley Dean and faculty shall propose and coordinate programs, review curricular assignments and scheduling, and review and recommend faculty personnel actions.

    1. SDSU Imperial Valley faculty shall serve on university committees and councils only by virtue of election or appointment as members of SDSU Imperial Valley. They shall be allotted proportional elective representation in the Senate. As members of SDSU Imperial Valley they shall not serve on San Diego campus college committees except as external members, nor shall they participate in San Diego campus college elections to the Senate.

:::

## Name Changes, Academic Unit {#name-changes-academic-unit .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Proposals for unit name changes shall be reviewed in order by the following:

    a. Originating department, school, or program

    a. Academic planning committees of the college(s) in question

    a. Relevant college dean(s)

    a. Provost

    a. Committee on Academic Policy and Planning

    a. Senate, which shall receive the recommendation of the Committee on Academic Policy and Planning as an information item.

:::

## Press, San Diego State University {#press-san-diego-state-university .unnumbered}

::: {.policy-numbering .policy-start-1}

1. The San Diego State University Press shall be established for the purpose of scholarly and creative publication and shall represent the interests of the university community.

1. The Director of the Press shall manage the Press and shall report to the Provost or designee. Contracts negotiated by the Press shall be executed by the San Diego State University Research Foundation.

1. **Editorial Board**

    1. The Board shall recommend works for publication.

    1. The Board shall comprise 14 scholars, six of whom shall be San Diego State University faculty members appointed by the Senate; Director of the Press, an academic dean designated by the Provost, and the Dean of the Graduate Division or designee; and eight external members nominated by the Director in consultation with the faculty Board members and appointed by the Provost.

        1. Board members shall be nominated because of their expertise in the areas of the Press’s specialization. No person shall be a member of the Board who has a position of conflict of interest with the operation of the Press (Political Reform Act of 1974, California Government Code, sec. 19251, or other legislation of regulation pertinent to The California State University).

        1. External members shall be invited to participate by recommending and reviewing manuscripts for consideration.

        1. Members shall serve three-year staggered terms to a maximum of three consecutive terms.

        1. The Director of the Press shall chair the Board.

    1. Functions

        1. The Board shall gather, screen, and recommend to the Director materials for publication by the Press.

        1. Board members shall participate actively in editing works scheduled for publication by the Press.

        1. The Director, in consultation with the Board, shall prepare an annual written report for the Provost and the Senate. The report shall include the activities of the preceding year and a compilation of works published, sales figures, a listing of unpublished acquired works, and a financial statement.

        1. The Director shall schedule for publication those works recommended by the Board that meet the Press standards of quality and marketability.

:::
