---
title: "University Policies: Staff"
---

## Awards {#awards .unnumbered}

::: {.policy-numbering .policy-start-1}

1. **Staff Excellence Awards**

    1. Awards and Eligibility

        1. Five merit awards (Community Service, Service to the University, Staff-to-Staff Mentoring, Innovation and Team Effort) are available to recognize formally those San Diego State University staff members who have made significant contributions in each of the respective areas based on criteria posted on the Staff Affairs Committee website.

            1. To be eligible, nominees must be permanent full-time staff employees of San Diego State University (San Diego and/or SDSU Imperial Valley) is in good standing with the University, and must be employed with the University at the time of the award, as verified through Human Resources. Members of the Staff Honors and Awards committee are ineligible to receive an award during any year they serve on the committee.

        1. Two non-staff awards (Auxiliary Support and Manager of the Year) are available to recognize formally one employee from auxiliaries of San Diego State University (San Diego State University Research Foundation, Associated Students, Aztec Shops) and one Management Personnel Plan (MPP) employee of San Diego State University who have made significant contributions to the university.

            1. To be eligible, nominees in the Auxiliary Support category must be a full-time employee of a recognized San Diego State University auxiliary (San Diego and/or SDSU Imperial Valley) in good standing with the auxiliary and be employed with the auxiliary at the time of the award, as verified through the auxiliary’s human resources department.

        1. The Staff Lifetime Achievement Award shall be awarded to staff members who make significant contributions to the mission of the university throughout their careers.

            1. To be eligible, nominees in the Staff Lifetime Achievement category must have served the university for a minimum of fifteen years. Represented staff and MPP staff of the university are eligible for this award and must be actively employed by the university at the time of the award (fall semester) in order to be considered. Staff members who serve as part-time lecturers are eligible for the award provided they are nominated in their role as a staff member.

        1. Staff members who serve as part-time lecturers are eligible for merit awards, provided they are nominated in their role as a staff member.

        1. Members of the Staff Honors and Awards Committee are ineligible to receive an award during any year they serve on the committee. Student employees and faculty members (bargaining unit 3 tenure/tenure track and lecturers) are also ineligible to receive the award.

    1. Procedure and Criteria for Nomination

        1. The Staff Honors and Awards Committee shall issue a campuswide call for nominations, utilizing a wide variety of methods, in order to collect nominations in each category. Nominations may be received from staff, students, faculty members, administrators, alumni, and other members of the community. Nominees will be considered for an award only in the category in which they are nominated, however, an individual may be nominated in more than one category. Separate nominations are required for each category.

        1. Each nomination shall include: (a) Nominator’s contact information (name, department, telephone, email, primary role (b) Name and contact information of nominee (c ), Award nomination category (d) Description of work or event that is deserving of award (e) Actions that set the nominee apart from other candidates, and (f) Unique qualities that make the nominee worthy of award.

            1. The Staff Lifetime Achievement Award additionally requires at least three letters of recommendation from current SDSU faculty, staff, or administrators.

        1. The Staff Honors and Awards Committee shall review all nominations, determine eligibility and select those nominations which best fit the criteria for each category. The committee will then forward all nominations in each category and highlight up to three unranked recommendations in each category to the President, who shall select the recipients. The President will determine how many awards, if any, will be given in each category.

        1. The staff honored with an award shall receive a monetary bonus from the San Diego Alumni Association.

:::

## Policies {#policies .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Faculty, staff, and administration shall complement each other in the mission of the university to provide the best possible education for its students. Accordingly, San Diego State University shall strive to provide an environment where people demonstrate mutual respect regardless of rank or role.

1. For employees covered under specific collective bargaining agreements, policies relating to wages, hours, work assignments, and working conditions shall be addressed in the Collective Bargaining Agreement (CBA) for each one of those employees’ specified units. A copy of the employee’s agreement shall be found in the Center for Human Resources and shall be made available to any staff member upon request.

1. Information on policies relating to employees of auxiliary organizations and other organizations as listed in the Office of the Chancellor pursuant to Title 5 of the California Code of Regulations, sec. 42406, and covered by sec. 42405, shall be located in the human resources department for each specific auxiliary organization.

1. Policies relating to employees under the Management Personnel Plan shall be covered by Title 5 of the California Code of Regulations, secs. 42720–42723.

1. **Academic Misconduct**

    1. Staff shall not provide students with unethical academic assistance, including but not limited to: providing or arranging for the provision of:

        a. copies of a test, an examination, or other course material to any student without the permission of the instructor;

        a. fraudulent academic credit or false transcripts regarding an individual’s academic record; and

        a. an academic exception that results in a grade change, academic credit, or fulfillment of a graduation requirement when such an exception is not available to all students.

    1. Any disciplinary action will be administered in accordance with the Education Code and applicable Collective Bargaining Agreement.

:::
