---
title: "University Policies: Students"
---

## Associated Students {#associated-students .unnumbered}

::: {.policy-numbering .policy-start-1}

By their student fees, students of San Diego State shall be members of the Associated Students and shall be represented by the Associated Students.

:::

## Employment {#employment .unnumbered}

::: {.policy-numbering .policy-start-1}

Student employees shall be accountable for the same standards of discretion, confidentiality, and honesty as other university employees. Like all other employees of the university, students shall be made aware of the general nature of their work environment, their duties and responsibilities, and the potential for violating the conditions of their employment. Students charged with abusing this trust shall be referred to the University Judicial Coordinator or the Center for Human Resources for appropriate disciplinary and legal action.

:::

## Theses and Projects, Ownership of and Rights to {#theses-and-projects-ownership-of-and-rights-to .unnumbered}

::: {.policy-numbering .policy-start-1}

1. Research or creative work shall be defined as including pictures, sculptures, special editions, laboratory devices, laboratory techniques, manuscripts as theses, musical compositions, mathematical or theoretical conclusions, data and/or research results and the product of the inquiry. In general, the product of an inquiry related to student work, study, or experimentation shall be deemed research.

1. A student’s thesis or dissertation used to fulfill the requirements of an advanced degree shall belong to the student author. Copyright of a thesis or dissertation is secured automatically when the work is created. The university shall be entitled to a copy or definable facsimile of the thesis or dissertation.

1. The university retains rights to data developed by a student and shall have access to use excerpts from any such thesis or dissertation, including data and graphical support of such data, to develop patent applications to which the University has an interest. Any inventions, trademarks, trade secrets or other intellectual property developed shall be owned in accordance with Senate policy addressing intellectual property including royalty sharing with the student as appropriate. The student will retain copyright ownership of his/her thesis separate from ownership of any intellectual property associated with the work.

    <br>

:::
