---
title: "Resolutions"
---

* November 3, 1987	
    - Supporting Gann Expenditure Limitations 
    - Components in the General Education Requirement		
    - Honorary Doctoral Degree Guidelines

* April 12, 1988	
    - General Education Transfer Curriculum
    - Allocation of Lottery Revenue Funds for Distinguished Visiting Scholars, Lecturers, and Artists

* May 17, 1988	
    - Professional Interaction at North County Campus
    - Research Space and Equipment, North County Campus 

* September 6, 1988	
    - Restoration of Library Funds

* October 4, 1988	
    - Supporting Proposition 78, Higher Education Facilities Bond Act of 1988
    - Opposing Proposition 102, AIDS Reporting Requirements	
    - Permanent Faculty for North County
    - Supporting the Recommendations of the Study of Child Care Services 

* May 9, 1989	
    - Opposing the Advertisement for Sale of Research Papers

* September 19, 1989	
    - Opposing the Retroactive Parking Fee Levy 

* November 28, 1989	
    - Opposing Term Paper Purchasing
    - Attracting Ethnically Diverse Applicants and Establishing a Recruitment Task Force
    - AAOAC Representation and Responsibilities
    - Recruitment and Retention of Ethnic Diversity, and Annual University Award to Recognize Academic Unit for Leadership in Promoting Equity

* April 17, 1990	
    - CSU Administration and Governance

* May 15, 1990	
    - CSU Systemwide Administration in Transition	
    - Clean Campus

* January 29, 1991
    - Honoring Lynn Peters

* May 14, 1991	
    - Library Addition

* April 9, 1991	
    - Contingent Faculty

* September 10, 1991	
    - Against Discrimination in ROTC 

* November 19, 1991	
    - Campus Security

* May 12, 1992	
    - Against Discriminatory Attacks
    - Against Athletics Reductions

* June 29, 1992	
    - Vote of No Confidence in the Leadership of President Day 
    - Requesting Rescission of the Restructuring Document  

* July 20, 1992	
    - Supporting the Student Vigil

* August 27, 1992	
    - Requesting New Leadership at SDSU 
    - Requesting Rescinding the Layoffs 
    - For a Sensible SDSU Transition 
    - Supporting the Student Vigil

* October 15, 1992	
    - Fair Share Alternative Motion

* December 15, 1992	
    - Endorsing the Martin Luther King Day Parade 

* February 9, 1993	
    - Addition to the Campus Budget Committee 

* March 9, 1993	
    - SDSU Administration and Teaching
    - New RTP Timeline

* May 11, 1993	
    - IRA Funding

* October 5, 1993	
    - Opposing Proposition 174, Parental Choice in Education Initiative
    - Supporting Proposition 172, Local Public Safety Protection and Improvement Act of 1993

* December 7, 1993	
    - Rescinding the Report of the Committee on University Restructuring
    - Commending the Offices of Environmental Health and Safety and Public Safety (Disaster Preparedness)
    - Urging the Administration to Allocate a Portion of Capital Funds for Seismic Upgrades 
    - Locked Ballot Box

* March 22, 1994	
    - Dissolution of the Industrial Technology Department 

* April 19, 1994	
    - Supporting the Equitable Treatment of Domestic Partners 

* May 17, 1994	
    - Dissolution of the Industrial Technology Department

* September 14, 1994	
    - Voter Registration

* November 1, 1994	
    - Opposing Proposition 187

* May 16, 1995	
    - Honoring Nancy Carmichael
    - Commending Dorothy Romano

* February 6, 1996	
    - Endorsing Proposition 203

* May 14, 1996	
    - Tenure Issues at the University of Minnesota 
    - Commending Chair Ray Boddy

* October 15, 1996	
    - California Rights Initiative (Proposition 209)
    - Reaffirming the Senate Position Concerning Procedures for Improving the CSU Presidential Search Process

* April 1, 1997	
    - Faculty Compensation

* May 6, 1997	
    - Supporting Library Subscription Journals 

* September 9, 1997	
    - Chancellor’s Search

* November 11, 1997	
    - CETI Postponement

* December 16, 1997	
    - Injunction Regarding CETI 

* March 10, 1998	
    - Faculty and Staff Salaries

* May 12, 1998	
    - Interim Distance (or Distributed) Learning Policy 

* May 14, 1998	
    - Role of Department Chairs in the CSU  

* September 15, 1998	
    - Supporting Starting a Master Plan
    - Supporting Faculty Needs during Collective Bargaining 
    - Master Plan Resolution
    - Supporting CFA Bargaining
* October 13, 1998	
    - Freeway Sign
* March 10, 1999	
    - Rebuke of Chancellor Reed
* April 13, 1999	
    - Supporting a Parking Fee Increase
* May 11, 1999	
    - Honoring David DuFault
    - Cornerstones and Campus Autonomy 
* October 12, 1999	
    - Review of Auxiliaries
* November 9, 1999	
    - Supporting President Weber on Impaction
* December 7, 1999	
    - Against Chancellor Reed’s Reversal of SDSU Enrollment Management Policy 
* February 8, 2000	
    - Supporting the SJSU “Out of Crisis” Paper on CSU Governance
* March 7, 2000	
    - Support of Associated Students Resolution on Program Commencement Ceremonies 
* November 7, 2000	
    - Representation of Aztec Culture on the SDSU Campus
    - Educational Presentations about Aztec Culture 
    - Year-Round Operations and Extended  Studies 
    - Urging Out-of-Contract Evaluation of Merit Pay Policies 
* February 6, 2001	
    - Request for Campus Coordination of Student Retention 
* May 1, 2001	
    - Honoring Senate Chair Patricia Huckle
    - Supporting an Independent EdD
    - No Confidence in Chancellor Reed 
* October 8, 2002	
    - Honoring Groundskeeping Staff
* November 5, 2002	
    - General Education
    - Free but Responsible Expression
* February 4, 2003	
    - Opposition to a Decrease in CSU Funding Tied to an Increase in Student-Faculty Ratio 
* March 4, 2003	
    - Task Force on Shared Governance
    - American Sign Language as Foreign Language Requirement 
    - Evaluation of Very Large Lecture Classroom Implementation 
* April 27, 2004	
    - Honoring Former Chair Raford D. Boddy
* October 5, 2004	
    - Honoring Senator Gordon Shackelford 
* December 7, 2005	
    - Supporting Independent Doctorates
* March 8, 2005	
    - Support of Environmental Impact Report and Campus Master Plan Revision 
* May 3, 2005	
    - Honoring Parliamentarian Richard Berry
    - Honoring Senator Thomas Warschauer
* October 11, 2005	
    - Opposing Proposition 76: State Spending and School Funding Limits 
* December 13, 2005	
    - Implementation of ACR 73 and closing the CPEC Faculty Salary Gap 
* February 7, 2006	
    - Request Aztec Shops Discontinue Tobacco Sales
* April 11, 2006	
    - Regarding Internationalization on Campus 
* May 6, 2006	
    - Honoring Former Chair Gene Lamke 
* October 10, 2006	
    - Supporting Proposition ID-Facilities Board
* November 7, 2006	
    - Supporting Freedom of International Academic Exchange 
* February 6, 2007	
    - Importance of Achieving a New Contract Between CSU and CFA 
* March 6, 2007	
    - Supporting Library Research Needs
* April 10, 2007	
    - Sustainability at SDSU
* September 4, 2007	
    - Supporting 2007 SDSU Master Plan
    - Honoring Janis F. Andersen
* April 8, 2008	
    - Response to CSU Budget Reductions
    - Against Homophobia and Transphobia at SDSU 
* May 6, 2008	
    - Honoring Henry Janssen
    - Honoring Michael Perkins
* November 3, 2009	
    - Supporting AB 656
* December 1, 2009	
    - Concerning Campus Layoff
    - Demands for the Statewide CSU Chancellor and Board of Trustees 
* May 4, 2010	
    - Honoring Fred Hornbeck
    - Honoring Bonnie Zimmerman
* October 5, 2010	
    - Supporting SDSU’s Institutional Membership in The Scholars at Risk Network
* February 1, 2011	
    - Supporting San Diego State University’s Plaza Linda Verde Project
* April 5, 2011	
    - Honoring President Stephen L. Weber
* May 3, 2011	
    - Resolution of Appreciation Honoring William Eadie 
* September 6, 2011	
    - Resolution on CSU President Searches
* February 7, 2012	
    - Resolution Urging the University Senate to Support the Creation of an Online Wait List System
    - Resolution in Support of Signing the American College and University Presidents’ Climate Commitment
* May 8, 2012	
    - Resolution of Appreciation Honoring William Snavely
* October 2, 2012	
    - Support of Proposition 30 on the November 2012 Ballot: Temporary Taxes to Fund Education. Guaranteed Local Public Safety Funding
* December 4, 2012	
    - Removing the Clause Recommending the Discontinuation of State University Grants for Graduate Students Pending ASCSU Resolution AS-3100-12/FGA
* May 7, 2013   
    - Resolution of Appreciation Honoring Vice President of Student Affairs James R. Kitchen 
    - Resolution of Appreciation Honoring Vice President of Business and Financial Affairs Sally Roush
    - Resolution on Signing the American College and University Presidents’ Climate Commitment
* October 1, 2013	
    - Resolution on the Appointment of a Faculty Trustee to the California State University Board of Trustees
* March 4, 2014	
    - Resolution Endorsing "Statement on the Principles of Scholarly Research and Public Records”

* May 6, 2014	
    - Resolution of Appreciation Honoring William Eadie
    - Resolution of Appreciation Honoring Provost Nancy Marlin 

* May 5, 2015	
    - Resolution of Appreciation Honoring Edith Joyce Benkov

* October 6, 2015	
    - Resolution to Support Calls for Open and Transparent Search Processes for Presidential Searches in 2015-16

* April 5, 2016	
    - Resolution (Sense of the Senate) regarding preferences for probationary faculty: 3-year initial and successor contracts; departmental period evaluations in years 1, 2, 4, and 5; and multilevel performance reviews in years 3 and 6

* May 3, 2016	
    - Resolution in Support of Open Educational Resources (OER) as a Means to Reduce Textbook Costs

* November 1, 2016	
    - Resolution in Support of (State of California) Proposition 55 

* March 7, 2017	
    - Resolution in Support of Undocumented Students

* May 2, 2017	
    - Resolution (Sense of the Senate) regarding the budget allocation process 

* May 31, 2017	
    - Resolution of Appreciation Honoring President Hirshman

* October 3, 2017	
    - Sense of the Senate Resolution Calling for the Immediate Reinstatement of Dr. Joanna Brooks as AVP of Faculty Advancement
    - Resolution: Development and Implementation of Executive Orders 1100 (Revised) and 1110
    
*  November 7, 2017 
    - Resolution to Eliminate the Mascot and Form a Task Force to Investigate the Aztec Identity

* February 6, 2018 
    - Resolution to Require SDSU and its Academic and Administrative Units To Have Diversity Plans (amended as part of the Senate’s approval) 

* April 3, 2018 
    - Resolution Honoring the Memory of Morteza (Monte) Mehrabadi, Dean of the College of Engineering (2014-2018), Passed March 13, 2018

* May 1, 2018 
    - Resolution Honoring SDSU President Sally Roush

* March 5, 2019 
    - Resolution of Concern for Pell Student Enrollment Decline

* April 9, 2019 
    - Principles of Shared Governance
    - Fostering a Welcoming and Safe Campus Climate for African American Students
    - Rejection of the Report of the California State University General Education Task Force

* September 9, 2019 
    - To Establish an Official SDSU Kumeyaay Land Acknowledgement
    - Fostering a Welcoming and Safe Campus for Lesbian, Gay, Bisexual, Transgender, Queer, Questioning, Intersex, and Asexual (LQBTQIA+) Students

* November 5, 2019 
    - Ethnic Studies Graduation Requirement

* February 4, 2020 
    - Resolution of Appreciation for Dr. Marcie Bober-Michel

* March 3, 2020
    - Establish an Official Campus Policy to Fly the Kumeyaay Nations Flag on the SDSU Campus
    - General Education Area B Waiver for Engineering

* April 7, 2020 
    - General Education Areas D and E Waiver for Engineering

* May 5 and 7, 2020
    - Creating a More Equitable and Welcoming Environment for Women Faculty of Color
    - Initiation of the Process of Establishment of Independent Doctoral Degree Programs within the CSU
    - Sustainability Leadership & Integration
    - Response to the Racial Violence Targeting Black People and Communities in the United States

* November 10, 2020
    - Resolution in Opposition to Title 5 Restructuring of General Education and in Acknowledgement of SDSU’s Ethnic Studies Requirement’s Alignment with AB 1460

* April 16, 2021
    - Resolution from SDSU African American Alumni - Building Naming Proposal (Shirley Weber, Ph.D, Professor Emerita of Africana Studies)
    - SDSU Resolution on Climate Conscious Business Travel 

* May 4 and May 6, 2021
    - Resolution to Propose an Alternative Mascot for SDSU
    - Resolution in Response to the Escalating Anti-Asian Hate in the United States
    - Resolution of the San Diego State University Senate to Allow Smudging On Campus
    - Senate Resolution of the University Senate in Support of Open Access Publishing for Faculty Publications

* July 9, 2021
    - SEC Resolution Condemning Anti-Semitism (Summer 2021)

* February 1, 2022
    - Commendation of Laura Shinn

* March 1, 2022
    - No Confidence in Chancellor Joseph Castro’s Leadership

* November 1, 2022
    - Increase Number of Awarded Sabbatical Applications
    - Adoption of the California General Education Transfer Curriculum (Cal-GETC) to Succeed GETC

* March 7, 2023
    - Condemning Gender-Based Violence and Supporting of the Rights of Women and Other Vulnerable People

* December 12, 2023
    - Reaffirming the Condemnation of Antisemitism on Campus

* March 5, 2024
    - Condemning anti-Palestinian, anti-Arab, and anti-Muslim Racism 
    - Separation of Cal-GETC and CSU GE Breadth

* May 7 and 9, 2024
    - Priorities for Collegiality, Inclusivity and Equity for IV Faculty in Home Departments at the San Diego Mesa Campus
    - Support of Students’ Right to Protest Acts of Terrorism, War Crimes, Crimes Against Humanity, and Genocide

* September 3 and 5, 2024
    - Condemning the Expansion of Administrative Policies Undermining the Right to Peaceful Campus Protest

* October 8, 2024
    - Supporting a Constitutional Referendum to Add Dedicated Lecturer Seats to the Academic Senate of the California State University System

